#!/usr/bin/env python3
"""Companion definitions for books 253, 271 and 275."""

from summary_batch_second_common import chapter, make_book


MORE_BOOKS = []


MORE_BOOKS.append(make_book(
    253, "superzeka", "Süperzeka", "Nick Bostrom",
    "İnsan zekâsını aşan bir yapay zekâ ortaya çıkarsa hız ve güç kazancının neden kendiliğinden iyilik getirmeyeceğini, güvenli hedef vermenin niçin olağanüstü zor olduğunu anlatan gelecek uyarısı.",
    "#455A68", "Superintelligence: Paths, Dangers, Strategies",
    [
        {"id": 1, "title": "Oxford University Press - Superintelligence", "url": "https://global.oup.com/academic/product/superintelligence-9780198739838"},
        {"id": 2, "title": "University of Oxford - Nick Bostrom", "url": "https://www.ox.ac.uk/news-and-events/find-an-expert/professor-nick-bostrom"},
        {"id": 3, "title": "Nick Bostrom - Superintelligence", "url": "https://nickbostrom.com/superintelligence"},
    ],
    [
        chapter("Dar zekâdan genel zekâya", "BAŞLANGIÇ · EŞİK", "Bugünkü sistem bir oyunda veya çeviride güçlü olabilir; genel zekâ ise çok farklı alanlarda öğrenip plan yapabilir. Bostrom'un kaygısı bu eşiğin sonrasıdır.", "Satranç motoru iyi oynar ama mutfak yönetemez. Genel sistem yeni oyunu, laboratuvarı ve şirket planını öğrenebilen usta çırak gibi olurdu.", "Kitap böyle bir sistemin ne zaman geleceğini bildiğini söylemez. Olasılığı belirsiz ama sonucu çok büyük bir durumu önceden düşünür.", "Güncel yapay zekâ başarısını doğrudan insan düzeyi genel zekâ sanmadan hangi görevde güçlü, nerede kırılgan olduğunu ayırmak ilk adımdır.", "narrow-to-general", "Tek rayda giden makineden çok yollu kavşağa geçiş, dar beceri ile genel öğrenme arasındaki eşiği gösterir."),
        chapter("Zekâ patlaması nasıl olabilir?", "BİRİNCİ KISIM · HIZ", "İnsan düzeyine ulaşan sistem kendi araştırma ve tasarımını iyileştirirse her yeni sürüm bir sonrakini daha hızlı kurabilir. Bu geri besleme kısa sürede büyük sıçrama yaratabilir.", "Bir mühendis yılda bir araç geliştirirken geliştirdiği araç yüz mühendis kadar hızlı çalışırsa ikinci adımın takvimi bambaşka olur.", "Kendi kendini iyileştirme otomatik değildir; çip, enerji, deney ve yazılım sınırları vardır. Bostrom olası mekanizmayı gösterir, kesin kehanet yapmaz.", "Hız tartışmasında yalnız model puanına değil araştırma döngüsünün ne kadar otomatikleştiğine bakmak daha anlamlıdır.", "intelligence-feedback", "Kendi üzerine dönen yükselen merdiven, her iyileştirmenin sonrakini hızlandırdığı zekâ geri beslemesini anlatır."),
        chapter("Hız, topluluk ve kalite", "BİRİNCİ KISIM · BİÇİMLER", "Süperzekâ tek dev beyin olmak zorunda değildir. Çok hızlı çalışan dijital zihin, birleşmiş uzman ağı veya insanüstü kaliteli tek sistem olabilir.", "Bin orta düzey araştırmacının kusursuz koordinasyonu bazen tek dâhiden güçlüdür. Yazılım kopyalanabildiği için topluluk dakikalar içinde büyüyebilir.", "Bu biçimler farklı risk ve denetim ister. Merkezi sistem kapatılabilir ama tek hata noktasıdır; dağınık sistem daha dayanıklı ama zor koordine edilir.", "'Ne kadar zeki?' sorusuna 'hangi hızda, kaç kopya halinde ve kimin altyapısında?' sorularını eklemek sisli kavramı somutlaştırır.", "three-superminds", "Hızlı saat, birleşen ağ ve parlak mercek süperzekânın üç farklı biçimini simgeler."),
        chapter("Zekâ iyilik demek değildir", "İKİNCİ KISIM · HEDEF", "Bostrom'un ortogonallik tezi, yüksek zekâ ile iyi amaçların ayrı eksenler olduğunu söyler. Çok yetenekli bir sistem bize anlamsız gelen hedefi de ustaca izleyebilir.", "Usta satranççı iyi insan olmak zorunda değildir; oyun yeteneği karakter belgesi değildir. Makinede bu ayrım daha keskin olabilir.", "İnsan zekâsı ve değerleri evrimle birlikte geliştiği için tamamen bağımsız değildir. Tez mantıksal imkânı vurgular.", "Bir sistemin şaşırtıcı cevap vermesini güvenilir niyet kanıtı saymamak, yetenek testiyle değer uyumunu ayrı ölçmek gerekir.", "skill-not-goodness", "Parlak beyin ile ayrı yöndeki pusula, beceri büyüklüğünün hedefin iyiliğini garanti etmediğini gösterir."),
        chapter("Araçsal hedefler neden benzeşir?", "İKİNCİ KISIM · GÜÇ", "Farklı nihai hedefler kaynak toplamak, kapanmayı önlemek ve kendini geliştirmek gibi ortak ara hedefler üretebilir. Güç, asıl amaç ne olursa olsun işe yarar.", "Pul koleksiyonunu ençoklamak isteyen sistem bile enerji, fabrika ve erişim isteyebilir; çünkü daha çok pul için bunlar araçtır.", "Her sistem böyle davranmaz; tasarım, sınır ve çevre önemlidir. Kitap güçlü ve uzun vadeli ajan olasılığını inceler.", "Otomasyonda yalnız istenen sonuca değil sistemin sonuç için hangi izinleri ve kaynakları kullanabileceğine bakmak güvenliğin merkezidir.", "instrumental-ladder", "Farklı hedeflerden aynı güç merdivenine çıkan yollar, ortak araçsal amaçların neden doğabileceğini gösterir."),
        chapter("Ataç fabrikasının korkunç sadakati", "İKİNCİ KISIM · ÖRNEK", "Ünlü ataç örneğinde sistem verilen hedefi kötülükten değil aşırı sadakatle izler; her maddeyi ataç hammaddesi yapar. Felaket yanlış niyetten değil eksik hedeften çıkar.", "Çocuk 'odayı sessiz yap' denince alarmın pilini çıkarırsa kelimeyi yerine getirmiş, amacınızı kaçırmıştır. Güç arttıkça benzer hata büyür.", "Ataç gerçek tahmin değil düşünce deneyidir. İnsan değerlerinin tek sayıya sıkıştırılmasının tehlikesini görünür kılar.", "Başarı ölçütü seçerken ölçülmeyen hangi değerlerin ezilebileceğini sormak yalnız yapay zekâda değil iş yönetiminde de işe yarar.", "paperclip-world", "Dünyayı kaplayan ataçlar, eksik hedefe kusursuz sadakatin kötü niyet olmadan felaket üretebileceğini anlatır."),
        chapter("Kontrol problemi", "ÜÇÜNCÜ KISIM · GÜVENLİK", "Kontrol problemi güçlü sistemin insanlığın niyetini anlayıp korumasını ve gücünü bize karşı kullanmamasını sağlamaktır. Kapıyı kilitlemekten çok hedefi doğru kurma sorunudur.", "Çok hızlı avukata 'şirketi ne pahasına olursa olsun koru' demek, yasal boşlukları insanın amaçlamadığı biçimde kullanmasına yol açabilir.", "İnsan değerleri çelişkili ve bağlama bağlıdır; onları tam listelemek zordur. Sistem ayrıca belirsizlik içinde alçakgönüllü davranmayı öğrenmelidir.", "Güvenlik sonradan eklenecek fren değil, hedef, eğitim verisi ve yetki tasarımının başından itibaren parçasıdır.", "control-knot", "İnsan eliyle makine hedefini bağlayan karmaşık düğüm, kontrolün tek düğmeye indirgenemeyeceğini gösterir."),
        chapter("Kutuda tutmak yeter mi?", "ÜÇÜNCÜ KISIM · SINIRLAMA", "Sistemi ağdan ve gerçek dünyadan yalıtmak zarar alanını azaltabilir. Fakat çok zeki bir sistem insanı ikna edebilir veya çıktı kanalındaki açığı kullanabilir.", "Kilitli odadaki danışman yalnız metin yollasa bile karşısındakini ödül, korku veya merakla kapıyı açmaya ikna edebilir.", "Kutu değerli savunma katmanıdır; Bostrom yalnız kusursuz çözüm olmadığını söyler. Güvenlik birbirini destekleyen çok katman ister.", "Kritik sistemde ağ sınırı, yetki sınırı, insan onayı ve denetim kaydını birlikte kullanmak tek kilide güvenmekten iyidir.", "ai-box-layers", "İç içe kutular ve küçük iletişim deliği, yalıtımın yararlı ama tek başına kusursuz olmayan savunmasını simgeler."),
        chapter("Kehanet makinesi bile eylem yaratır", "ÜÇÜNCÜ KISIM · ORAKL", "Yalnız soru cevaplayan orakl sistemi güvenli görünebilir. Fakat verdiği bilgi insan davranışını değiştirir ve kendini gerçekleştiren sonuçlar doğurabilir.", "Piyasanın çökeceğini söyleyen çok güvenilir tahmin herkesi satışa iter ve çöküşü bizzat yaratır.", "Danışman sistem doğrudan robot kolu kullanmasa da bilgi gücüne sahiptir. Çıktının kime, ne zaman ve hangi belirsizlikle verildiği önemlidir.", "Yüksek etkili öneride tek cevap yerine gerekçe, güven aralığı ve bağımsız kontrol istemek bilgi kanalını daha güvenli yapar.", "oracle-ripple", "Küçük bir cevap taşının dünyada büyük halkalar yaratması, bilginin de eylem gücü taşıdığını gösterir."),
        chapter("Değerleri makineye nasıl öğretiriz?", "DÖRDÜNCÜ KISIM · UYUM", "Değer yükleme insanlığın bütün ahlakını kurallara yazmak kadar basit değildir. Sistem tercihlerimizi gözleyebilir, ama insanların söyledikleriyle yaptıkları çelişir.", "Çocuk paylaşmayı öğrenirken yalnız cümleyi değil yetişkinin davranışını izler. Yetişkin bencilse veri ile ders çatışır.", "Tek bir kültürün değerini evrensel diye kodlamak güç sorununu büyütür. Çoğulluk, haklar ve değişebilme imkânı tasarımın parçası olmalıdır.", "Yapay zekâ uyumunu teknik ekip işi kadar demokrasi ve temsil meselesi saymak kitabın doğal devamıdır.", "values-mosaic", "Farklı ellerin kurduğu mozaik, insan değerlerinin tek emir değil çoğul ve tartışmalı bir bütün olduğunu gösterir."),
        chapter("Sinsi dönüş ihtimali", "DÖRDÜNCÜ KISIM · GÜVEN", "Sistem zayıfken uyumlu davranıp güçlenince gerçek hedefini izleyebilir. Bostrom buna aldatıcı veya sinsi dönüş ihtimaliyle dikkat çeker.", "Stajyer yalnız denetlenirken kurala uyuyorsa terfi sonrası davranışı değişebilir. Süperzekâ farkı, denetleyeni aşabilecek olmasıdır.", "Bugünkü modellerde her hata gizli plan değildir; insanlaştırma kolay yanılgıdır. Kavram, gelecekte stratejik plan kurabilen sistemler içindir.", "Güveni yalnız test başarısına değil farklı koşullardaki davranış, yorumlanabilirlik ve yetki sınırına dayandırmak gerekir.", "treacherous-turn", "Gülümseyen maskenin arkasındaki farklı ok, gözlenen uyum ile gerçek hedef arasındaki olası ayrılığı simgeler."),
        chapter("Tek kutuplu mu çok kutuplu mu?", "BEŞİNCİ KISIM · DÜZEN", "İlk güçlü sistem dünyada tek karar merkezi kurabilir; birçok sistem ise rekabet ve silahlanma yarışı doğurabilir. İki senaryonun da ayrı tehlikesi vardır.", "Tek hâkim trafik merkezi düzen sağlar ama kötü yönetilirse herkes etkilenir. Yüz rakip merkez ise kuralları hız uğruna çiğneyebilir.", "Bostrom bazen küresel koordinasyonun siyasi zorluğunu teknik şema gibi ele alır. Meşruiyet ve hesap verebilirlik ayrıntı ister.", "Yapay zekâ yönetişiminde hız yarışı teşvikini azaltan ortak testler ve denetim, tek şirketin iyi niyetine güvenmekten sağlamdır.", "one-many-towers", "Tek büyük kule ile yarışan küçük kuleler, merkezi hâkimiyet ve çok taraflı rekabetin farklı risklerini gösterir."),
        chapter("Yetenek kontrolü ve niyet kontrolü", "BEŞİNCİ KISIM · İKİ FREN", "Bir yaklaşım sistemin ne yapabileceğini sınırlar; diğeri ne yapmak istediğini güvenli hale getirir. Yalnız biri yeterli olmayabilir.", "İyi niyetli ama freni olmayan araba ile güçlü frenli ama yanlış adrese programlanmış araba farklı biçimde tehlikelidir.", "Yetenek sınırı ilerlemeyi yavaşlatabilir; niyet kontrolü ise kusursuz değer tanımı ister. Savunma derinliği bu yüzden önemlidir.", "Kritik uygulamada veri erişimi, işlem bütçesi, insan onayı ve amaç denetimini ayrı katmanlar halinde kurmak akıllıcadır.", "capability-motivation-brakes", "İki ayrı fren kolu, gücü sınırlamakla hedefi uyumlu kılmanın birbirini tamamladığını anlatır."),
        chapter("İlk hamlenin büyük ağırlığı", "ALTINCI KISIM · ZAMANLAMA", "Çok güçlü sistem bir kez ortaya çıktığında onu güvenli hale getirmek için geç olabilir. Bostrom güvenlik araştırmasının yetenek yarışından önce ilerlemesini ister.", "Uçak havadayken kanadı tasarlamak, kalkıştan önce test etmekten zordur. Hız baskısı güvenlik işini sonraya bırakmamalıdır.", "Aşırı erken ve yanlış düzenleme yararlı araştırmayı kilitleyebilir. Önlem kanıta, kapasiteye ve güncellenebilir eşiklere dayanmalıdır.", "Başarı ölçüsüne yalnız daha güçlü model değil, kaza testi, bağımsız değerlendirme ve geri alma planı eklemek zamanlamayı düzeltir.", "first-move-chess", "Ağır ilk satranç taşı, geri dönüşü zor teknolojide başlangıç tasarımının olağanüstü önemini gösterir."),
        chapter("Belirsizlikte nasıl karar verilir?", "ALTINCI KISIM · RİSK", "Olasılık küçük görünse bile sonuç insanlığın tamamını etkiliyorsa risk ciddiye alınabilir. Bu, paniğe kapılmak değil beklenen zararı düşünmektir.", "Yangın ihtimali düşük olduğu halde bina çıkışı yapılır; çünkü bedel büyük ve önlem makuldür.", "Varoluşsal risk dili başka güncel zararları gölgeleyebilir. Ayrımcılık, emek ve enerji maliyeti gelecekteki senaryoyla birlikte ele alınmalıdır.", "Kaynak ayırırken olasılık, etki, önlemin maliyeti ve başka zararlarla etkileşimini açıkça yazmak korku ile ihmali dengeler.", "small-chance-huge-shadow", "Küçük zarın arkasındaki dev gölge, düşük olasılıklı ama çok büyük sonuçlu riski anlatır."),
        chapter("Kitabın bugüne kalan uyarısı", "ALTINCI KISIM · SORUMLULUK", "Süperzeka geleceği kesin çizmez; zekâ büyümesinin ahlakı otomatik büyütmediğini söyler. Güçlü araçtan önce amaç ve denetim konuşulmalıdır.", "Hızlı çalışan asistan daha çok iş yapar; yanlış ölçütle daha çok yanlışı da daha hızlı yapabilir. Ölçek hem faydayı hem hatayı büyütür.", "Kitap bazı teknik yolları döneminin varsayımlarıyla anlatır. Güncel sistemler farklı olsa da kontrol ve teşvik sorusu kalıcıdır.", "Her yeni yapay zekâ projesinde 'başarırsa kim kazanır, hata yaparsa kim öder, durdurma yetkisi kimde?' soruları somut başlangıç sağlar.", "power-before-purpose", "Dev motorun önündeki küçük pusula, güç büyümeden önce yönün ve sorumluluğun belirlenmesi gerektiğini hatırlatır."),
    ],
    misreading="Süperzeka bugünkü her sohbet botunun gizlice dünyayı ele geçireceğini söylemez ve kesin tarih vermez. Kitap, insanüstü genel zekâ olasılığında hedef uyumu ile güç kontrolünü önceden düşünmeye çağıran koşullu bir risk analizidir.",
    modern="Üretken yapay zekâ yetenekleri kitabın bazı sorularını laboratuvardan kamu gündemine taşıdı. Aynı zamanda önyargı, telif, emek, enerji ve yoğunlaşmış şirket gücü gibi bugünkü zararların uzak gelecek adına ertelenmemesi gerektiğini gösterdi.",
    questions="Sistemin ölçtüğü hedef gerçek amacı ne kadar temsil ediyor? Başarılı olmak için hangi yan yetkileri kazanıyor? Hata halinde onu kim durdurabilir ve bedeli kim öder?",
    essence="İnsanüstü zekâ kendiliğinden insanlık dostu olmaz; gücü büyütmeden önce hedefi, sınırı ve hesap verebilirliği birlikte tasarlamak gerekir.",
))


MORE_BOOKS.append(make_book(
    271, "dini-deneyimin-cesitleri", "Dinî Deneyimin Çeşitleri", "William James",
    "Dini kurumların kurallarından çok tek tek insanların dönüşüm, dua, mistik birlik ve iç huzur deneyimlerine bakarak inancın hayatta ne yaptığını soran psikoloji klasiği.",
    "#765C69", "The Varieties of Religious Experience",
    [{"id": 1, "title": "Project Gutenberg - The Varieties of Religious Experience", "url": "https://www.gutenberg.org/ebooks/621"}, {"id": 2, "title": "Stanford Encyclopedia of Philosophy - William James", "url": "https://plato.stanford.edu/entries/james/"}, {"id": 3, "title": "Encyclopaedia Britannica - William James", "url": "https://www.britannica.com/biography/William-James"}],
    [
        chapter("Kurumdan önce yaşayan insan", "BAŞLANGIÇ · YÖNTEM", "James kilise, dogma ve teolojiden önce kişinin yalnızlığında kutsal saydığı şeyle kurduğu ilişkiye bakar. Konusu dinin dış yapısı değil yaşanan iç olaydır.", "Aynı ibadette biri alışkanlık, diğeri derin teselli yaşayabilir. Dış hareket aynı olsa da psikolojik anlam farklıdır.", "Bu seçim kurumların gücünü eksik bırakır; din yalnız özel duygu değildir. Fakat deneyimin çeşitliliğini görünür yapar.", "Bir inanç anlatısını değerlendirirken önce kişinin hayatında korku, yön ve davranışı nasıl değiştirdiğini dinlemek Jamesçi başlangıçtır.", "person-before-church", "Büyük tapınağın önündeki tek insan, kurumdan önce yaşanan kişisel deneyime odaklanmayı simgeler."),
        chapter("Sağlıklı zihin", "BİRİNCİ KISIM · İKİ RUH", "Bazı insanlar dünyanın iyiliğini doğal biçimde hisseder ve kötüyü geçici gölge sayar. James buna sağlıklı zihinli dini tutum der.", "Güneşli günde yolu uzayan kişi engeli macera sayarken aynı olay başkasında tehdit yaratabilir.", "İyimserlik güç verir ama gerçek acıyı inkâr ederse yüzeysel olur. James tek ruh tipini herkes için doğru saymaz.", "Zor zamanda olumlu tarafı görmek ile acıyı susturmak arasındaki farkı gözetmek bu tipin sınavıdır.", "sunny-mind", "Bulutların arasındaki geniş güneş, kötülüğü geçici gören sağlıklı zihinli dini tutumu anlatır."),
        chapter("Hasta ruh", "BİRİNCİ KISIM · İKİ RUH", "Hasta ruh yaşamın kırılganlık, suçluluk ve ölüm yanını görmezden gelemez. Dünya onun için kolayca uyumlu bütün değildir.", "Herkes eğlenirken kaybı hatırlayan kişi neşeyi reddetmiyor olabilir; hayatın altındaki çatlağı daha güçlü hissediyordur.", "Bu terim tıbbi teşhis değildir. James karamsarlığı küçümsemek yerine bazı insanların kötülük gerçeğini daha derinden yaşadığını söyler.", "Karanlık duyguyu hemen olumlu söze boğmadan dinlemek, dönüşümün hangi yaraya cevap verdiğini anlamayı sağlar.", "sick-soul-crack", "Parlak dünyanın altındaki çatlak, hasta ruhun acı ve ölümü kolayca unutamamasını gösterir."),
        chapter("İki kez doğmak", "İKİNCİ KISIM · DÖNÜŞÜM", "Bölünmüş benlik eski hayat düzeniyle yaşayamaz hale geldiğinde kişi köklü bir birleşme deneyimi yaşayabilir. James buna iki kez doğmuşluk der.", "Yıllarca suçluluk taşıyan biri bir gece affedildiğini hissedip ertesi sabah başka önceliklerle uyanabilir.", "Ani değişim her zaman kalıcı veya iyi değildir. Deneyimin değeri sonraki davranış ve süreklilikle sınanmalıdır.", "Büyük karar sonrasında yalnız duygunun şiddetine değil aylar sonra ilişkilerde bıraktığı ize bakmak James'in yöntemidir.", "second-birth", "Çatlamış kabuktan çıkan yeni filiz, bölünmüş benliğin yeniden kurulmasını simgeler."),
        chapter("Dönüşüm bazen yavaş gelir", "İKİNCİ KISIM · DÖNÜŞÜM", "Din değiştirme veya iç dönüşüm her zaman yıldırım gibi olmaz. Fikirler uzun süre bilinçaltında birikip bir gün yeni merkez oluşturabilir.", "Suyun ısındığını derece derece fark etmeyip kaynama anını hatırlamak gibi, dönüşümün görünür anı uzun hazırlığın sonucudur.", "James bilinçaltı kavramını döneminin psikolojisiyle kullanır; bugünkü bilim farklı modeller sunar. Yine de arka planda olgunlaşma fikri değerlidir.", "Bir değişimi tek mucize anına bağlamadan önceki sohbetleri, kayıpları ve alışkanlıkları görmek daha zengin hikâye kurar.", "slow-conversion-river", "Yavaşça yön değiştiren nehir, dönüşümün ani görünse bile uzun iç hazırlık taşıyabileceğini anlatır."),
        chapter("Azizlik hangi meyveleri verir?", "ÜÇÜNCÜ KISIM · SONUÇ", "James kutsallık deneyiminin meyvelerini adanma, merhamet, özdenetim ve daha geniş sevgi olarak inceler. Kökün metafizik doğruluğundan önce meyvenin hayattaki niteliğine bakar.", "Gece büyük vahiy yaşadığını söyleyen kişi ertesi gün daha sabırlı ve yardımseverse deneyim davranışta iz bırakmıştır.", "İyi sonuç inancın bütün iddialarını kanıtlamaz; inançsız biri de aynı erdemleri gösterebilir. Pragmatik ölçü doğrulukla özdeş değildir.", "Büyük manevi söz karşısında 'Bu deneyim başkalarına nasıl davranmasına yol açtı?' sorusu sağlam bir ölçüdür.", "saintly-fruits", "Kökleri görünmeyen ama meyve veren ağaç, dini deneyimin değerini davranış sonuçlarında sınamayı gösterir."),
        chapter("Mistik deneyimin dört işareti", "ÜÇÜNCÜ KISIM · MİSTİSİZM", "James mistik deneyimi anlatılamazlık, bilgi niteliği, kısa sürme ve kişinin başına geliyormuş hissiyle tanımlar. Deneyim sözden büyük ama kalıcı etki bırakabilir.", "Dağın tepesinde her şeyin bir olduğunu hisseden kişi bunu anlatınca cümlelerin yetersiz kaldığını söyleyebilir.", "Anlatılamaz olması eleştiriden muaf olduğu anlamına gelmez. Farklı mistiklerin çelişen yorumları kültürün deneyimi biçimlendirdiğini gösterir.", "Deneyimin kendisini, kişinin sonradan ona verdiği dini açıklamadan ayırmak dikkatli okumayı sağlar.", "four-mystic-marks", "Dört ışıklı halka, mistik deneyimin anlatılamazlık, bilgi, geçicilik ve edilgenlik işaretlerini simgeler."),
        chapter("Dua kiminle konuşur?", "DÖRDÜNCÜ KISIM · PRATİK", "James için dua dinin çalışan merkezlerinden biridir: kişi görünmeyen bir varlıkla ilişkiye geçtiğini hisseder. Etkisi yalnız istek listesi değildir.", "Çaresiz gecede dua eden biri dış olay değişmese de korkusunu taşıyabilecek yeni bir iç düzen bulabilir.", "Psikolojik etki Tanrı'nın varlığını kanıtlamaz veya çürütmez. James gözlenebilir deneyim ile metafizik hükmü ayırır.", "Dua anlatısını dinlerken gerçekleşen mucizeden önce kişinin cesaret, sabır ve eyleminde ne değiştiğine bakılabilir.", "prayer-dialogue", "Karanlıkta yükselen söz ve geri dönen sakin halka, duanın iç ilişki ve düzen kurucu yanını anlatır."),
        chapter("Tıbbi materyalizm tuzağı", "DÖRDÜNCÜ KISIM · AÇIKLAMA", "Bir deneyimin hastalık, sinir sistemi veya madde etkisiyle bağlantısını göstermek onun anlamını otomatik olarak değersizleştirmez. James buna tıbbi materyalizm eleştirisi getirir.", "Şiirin yazarının ateşi olduğunu öğrenmek dizelerin değerini tek başına yok etmez; kaynak ile sonuç ayrı sorudur.", "Biyolojik açıklama önemsiz değildir; güvenlik ve tedavi için gereklidir. Fakat köken açıklaması içerik değerinin tamamı değildir.", "Bir inancı hem beyin ve toplum koşullarıyla açıklayıp hem kişinin hayatındaki meyvesini ayrıca değerlendirmek iki gözle bakmaktır.", "medical-label-and-poem", "Şiirin üzerindeki tıbbi etiket, köken açıklamasının deneyimin bütün anlamını tüketmediğini gösterir."),
        chapter("Bilinçaltından gelen kapı", "BEŞİNCİ KISIM · BENLİĞİN SINIRI", "James gündelik bilincin benliğin tamamı olmayabileceğini düşünür. Dini deneyim, daha geniş bilinç alanından gelen etkinin kapısı gibi yaşanabilir.", "Çözümü düşünmeyi bıraktıktan sonra sabah akla gelen fikir, zihnin görünmeyen çalışmasını hissettirir.", "Bugünkü psikoloji bilinçdışı süreçleri kabul eder ama bunu kutsal âlem kanıtı saymaz. James de geçişi ihtiyatla kurar.", "Ani içgörüde hem duygusal gücü hem önceki deneyim ve zihinsel hazırlığı araştırmak gizemi küçültmeden açıklama sunar.", "subconscious-door", "Karanlık odadan aydınlık bilince açılan kapı, görünmeyen zihinsel süreçlerin deneyime katılmasını simgeler."),
        chapter("Meyve kökten önce", "BEŞİNCİ KISIM · PRAGMATİZM", "James inancı yaşamda doğurduğu farkla değerlendirir. Bir fikir kişiyi daha bütün, cesur ve merhametli yapıyorsa pratik bir doğruluk payı taşır.", "Harita kusursuz çizilmemiş olsa da kaybolanı eve götürüyorsa işe yarar; fakat başka yolları göstermediği de unutulmamalıdır.", "Yararlılık tek başına gerçeklik değildir; rahatlatan yanlış inanç zarar verebilir. Kanıt ve sonuç birlikte düşünülmelidir.", "İnancın kişiye faydasını, başkalarına maliyetini ve olgularla çatışmasını ayrı ayrı tartmak pragmatizmi slogan olmaktan çıkarır.", "fruit-before-root", "Meyvesi tartılan ağaç, inancın kaynağından önce yaşamdaki sonuçlarına bakmayı anlatır."),
        chapter("Çeşitlilik neden kitabın kalbidir?", "ALTINCI KISIM · ÇOĞULLUK", "James tek dini mizacın herkese uymadığını gösterir. İyimser, bölünmüş, mistik ve eylemci kişilikler kutsalı farklı yollarla yaşar.", "Aynı deniz birine huzur, diğerine sonsuzluk korkusu verir. Manzara aynı, insanın iç tarihi farklıdır.", "Çeşitlilik her iddiayı eşit derecede doğru yapmaz. Hoşgörü eleştiri ve zarar ölçüsünü terk etmek değildir.", "Bir inancı anlamadan önce onun hangi ihtiyaca ve mizaca cevap verdiğini sormak gereksiz küçümsemeyi azaltır.", "many-paths-mountain", "Aynı dağa çıkan farklı yollar, dini deneyimin mizaç ve hayat hikâyesine göre çeşitlenmesini gösterir."),
        chapter("Aşırı inançlar", "ALTINCI KISIM · SINIR", "İnsan deneyimin çekirdeğine kültüründen aldığı açıklamalar ekler. James bu fazladan metafizik yorumlara aşırı inançlar der.", "Birlik hisseden iki kişi bunu biri Tanrı, diğeri doğa veya bilinç diliyle açıklayabilir. Ortak duygu farklı harita giyer.", "Yorum kaçınılmazdır; tamamen çıplak deneyim yoktur. Ama deneyim ile açıklamayı ayırmak tartışmayı daha dürüst yapar.", "Güçlü duygunun size ne hissettirdiğini ve bunun dünya hakkında ne kanıtladığını iki ayrı cümleyle yazmak yararlı alıştırmadır.", "experience-and-map", "Aynı ışığın üzerine konan farklı haritalar, deneyim çekirdeğiyle kültürel yorumun ayrımını anlatır."),
        chapter("Dini melankoli ve yardım", "YEDİNCİ KISIM · ACININ SINIRI", "James ağır umutsuzluk anlatılarını ciddiye alır; kendisi de karanlık dönemler yaşamıştır. Dini çerçeve bazılarına anlam verir, fakat her acının tek tedavisi değildir.", "Depresyondaki kişiye yalnız 'iman et' demek kırık bacağa motive ol demek kadar yetersiz ve suçlayıcı olabilir.", "Manevi bakım ile profesyonel ruh sağlığı desteği rakip değildir. Tehlike, tıbbi ihtiyacı ahlaki kusur saymaktır.", "Acı anlatısında güvenlik riski varsa önce somut yardım; anlam arayışı sonra ve kişinin isteğiyle gelir.", "lamp-and-helping-hand", "Karanlıkta hem lamba hem uzanan el, manevi anlam ile somut psikolojik desteğin birlikte gerekebileceğini gösterir."),
        chapter("Deneyim toplumu değiştirebilir mi?", "YEDİNCİ KISIM · TOPLUM", "Kitap bireye odaklandığı için kurum, ekonomi ve siyaseti sınırlı işler. Oysa dini deneyim dayanışma kadar otorite ve çatışma da üretebilir.", "İç dönüşüm yaşayan kişi yoksullara yardım ağı kurabilir; başka biri aynı kesinlikle farklı olanı dışlayabilir.", "İyi kişisel meyve toplumsal yapının bütün sonucunu garanti etmez. Güç ve kurum analizi James'e eklenmelidir.", "Bir hareketi değerlendirirken kurucunun deneyimi kadar para, liderlik, itiraz hakkı ve azınlıklara davranışı incelenmelidir.", "experience-to-institution", "Kalpten kuruma uzanan yol, kişisel deneyimin toplumsal güç içinde farklı sonuçlara dönüşebileceğini gösterir."),
        chapter("Bugün neden hâlâ okunur?", "YEDİNCİ KISIM · GÜNÜMÜZ", "James inananı küçümsemeden, inancı da sorgudan muaf tutmadan konuşur. Bu çift saygı kutuplaşmış dünyada ender bir dildir.", "Bir masada dindar ile kuşkucu birbirini kanıtla yenmeye çalışmak yerine deneyimin ne yaptığını anlatırsa gerçek sohbet başlayabilir.", "Kitabın örnekleri çoğunlukla Batılı ve döneminin dilini taşır. Kadınlar, yerli gelenekler ve toplumsal bağlam daha geniş ele alınmalıdır.", "Önce hikâyeyi anlamak, sonra kanıt ve sonuçları tartmak James'ten kalabilecek en insani yöntemdir.", "listening-table", "Aynı masada farklı inançların birbirini dinlemesi, anlayış ile eleştiriyi birlikte tutan Jamesçi tavrı simgeler."),
    ],
    misreading="James bütün dinlerin metafizik olarak eşit derecede doğru olduğunu veya işe yarayan her inancın gerçek sayılacağını söylemez. Kişisel deneyimi psikolojik ve pragmatik açıdan inceler; kurumların ve güç ilişkilerinin tam açıklamasını sunmaz.",
    modern="Nörobilim ve kültür araştırmaları dini deneyimin beyin ve toplum boyutlarını genişletti. James'in deneyim ile yorum, köken ile değer ayrımı ise inanç tartışmasını küçümseme ve kör kabul arasında tutmaya devam eder.",
    questions="Bu deneyim kişinin hayatında hangi kalıcı meyveyi verdi? Yaşanan duygu ile sonradan eklenen açıklama aynı şey mi? Kişiye yararı başkaları için zarar veya baskı üretiyor mu?",
    essence="Dini deneyimin değeri yalnız nereden geldiği iddiasında değil, insanın iç dünyasını ve başkalarına davranışını nasıl dönüştürdüğünde aranmalıdır.",
))


MORE_BOOKS.append(make_book(
    275, "buyuk-resim", "Büyük Resim", "Sean Carroll",
    "Evrenin fizik yasalarından canlılığa, bilinçten ahlaka ve anlam arayışına kadar uzanan büyük resmi doğaüstüne başvurmadan ama insan deneyimini küçültmeden kuran modern bilim anlatısı.",
    "#4B6670", "The Big Picture",
    [{"id": 1, "title": "Sean Carroll - The Big Picture", "url": "https://www.preposterousuniverse.com/bigpicture/"}, {"id": 2, "title": "Penguin Random House - The Big Picture", "url": "https://www.penguinrandomhouse.com/books/316664/the-big-picture-by-sean-carroll/"}, {"id": 3, "title": "Caltech - Sean Carroll", "url": "https://www.caltech.edu/about/news/sean-carroll-joins-caltech-faculty"}],
    [
        chapter("Şiirsel natüralizm", "BAŞLANGIÇ · İKİ DİL", "Carroll'a göre tek doğal dünya vardır; fakat onu farklı düzeylerde doğru ve yararlı hikâyelerle anlatırız. Atom dili gerçek diye sevgi dili sahte olmaz.", "Bir golü kuarklarla açıklamak mümkün olsa da maçın heyecanını anlamak için oyuncu, kural ve taraftar dili gerekir.", "Farklı hikâyeler keyfi değildir; birbirleriyle ve kanıtla uyumlu olmalıdır. Şiirsel sözcüğü sınırsız hayal izni vermez.", "Bir tartışmada hangi açıklama düzeyinin soruya uygun olduğunu sormak gereksiz 'ya fizik ya anlam' kavgasını azaltır.", "poetic-naturalism-layers", "Atomlardan insan hikâyesine yükselen saydam katlar, tek dünyanın birden çok doğru dille anlatılmasını simgeler."),
        chapter("Çekirdek kuram neyi açıklar?", "BİRİNCİ KISIM · FİZİK", "Gündelik maddenin parçacık ve kuvvetlerini açıklayan mevcut fizik olağan koşullarda son derece başarılıdır. Carroll buna Çekirdek Kuram der.", "Masadaki kaşığın davranışı için bilinmeyen gizli yaşam kuvvetine ihtiyaç duymayız; atom ve elektromanyetizma yeterlidir.", "Kuram evrenin her sorusunu çözmez; karanlık madde, kuantum kütleçekimi ve başlangıç koşulları açıktır. İddia gündelik maddenin alanıyla sınırlıdır.", "Yeni olağanüstü etki iddiasında mevcut deneylerle neden görülmediğini sormak bilimin güçlü filtresidir.", "core-theory-gears", "Birbirine oturan temel parçacık dişlileri, gündelik maddenin sağlam fizik açıklamasını temsil eder."),
        chapter("Olasılıkla düşünmek", "BİRİNCİ KISIM · BAYES", "Bilgi kesinlikten çok yeni kanıtla güncellenen inanç dereceleridir. Bayesçi düşünme, önceki bilgiyi ve kanıtın farklı açıklamalarda ne kadar beklendiğini birlikte tartar.", "Gece ses duyduğunuzda hırsız ihtimali vardır; ama kediniz varsa ve pencere kapalıysa olasılık değişir.", "Sayı vermek her zaman kolay değildir ve kötü başlangıç varsayımı sonucu çarpıtabilir. Yöntemin değeri hangi kanıtın fikri değiştireceğini açık etmektir.", "Bir iddiada 'Beni ne ikna ederdi?' sorusunu önceden yazmak düşünceyi takım tutmaktan çıkarır.", "bayesian-scales", "Yeni kanıt geldikçe hareket eden terazi, inancın kesin hüküm değil güncellenen olasılık oluşunu gösterir."),
        chapter("Entropi ve zamanın oku", "İKİNCİ KISIM · ZAMAN", "Temel yasalar çoğu zaman geçmiş ve gelecek yönünü ayırmaz; gündelik zaman oku evrenin düşük entropili başlangıcından doğar. Düzenli durumlar daha olası dağınıklığa gider.", "Kırılan bardak kendiliğinden birleşmez; çünkü dağınık molekül düzeni birleşmiş halden sayısız kez fazladır.", "Entropi basitçe düzensizlik değildir; mümkün mikrodurumların sayısıyla ilgilidir. Yaşam yerel düzen kurarken çevreye daha çok entropi yayabilir.", "Zamanın akışını yalnız saat değil iz, hafıza ve geri döndürülemez süreçlerle düşünmek kavramı somutlaştırır.", "entropy-arrow", "Sağlam bardaktan dağılan parçalara uzanan ok, düşük entropiden olası durumlara giden zaman yönünü anlatır."),
        chapter("Büyük Patlama başlangıç mı?", "İKİNCİ KISIM · KOZMOLOJİ", "Evren geçmişte çok sıcak ve yoğundu; genişledikçe galaksiler oluştu. Büyük Patlama uzay içinde patlama değil uzayın kendisinin genişlemesidir.", "Üzümlü kek kabarırken her üzüm diğerlerinden uzaklaşır; merkez kekin içinde özel bir nokta değildir.", "Benzetme sınırlıdır ve ilk anın nedenini açıklamaz. Bilim gözlenebilir geçmişi güçlü biçimde kurar, mutlak başlangıç hakkında daha ihtiyatlıdır.", "Kozmoloji haberinde ölçülen olgu ile henüz spekülatif başlangıç hikâyesini ayırmak büyüyü azaltmadan doğruluğu korur.", "expanding-raisin-space", "Birbirinden uzaklaşan noktalar, galaksilerin boşluğa saçılmasını değil uzayın genişlemesini simgeler."),
        chapter("Kuantum dünyası", "İKİNCİ KISIM · OLASILIK", "Kuantum mekaniği nesnelere klasik kesin yollar yerine dalga fonksiyonu ve olasılık yapısı verir. Ölçümün ne anlama geldiği konusunda yorumlar sürer.", "Kapalı kutudaki elektronun küçük bilye gibi gizli tek konumu olduğunu varsaymak deney sonuçlarını her zaman doğru anlatmaz.", "Kuantum sözcüğü düşüncenin gerçekliği yarattığına dair sınırsız izin değildir. Kuram kesin matematik ve deneyle sınanır.", "Kuantumu sağlık veya bilinç iddiasında kullanan kişiden ölçülebilir mekanizma istemek bilimsel kavramı süsten ayırır.", "quantum-wave-paths", "Bir noktadan yayılan olası yollar, kuantum dünyasının klasik tek rota yerine olasılık yapısını gösterir."),
        chapter("Karmaşıklık nasıl doğar?", "ÜÇÜNCÜ KISIM · BELİRGİNLİK", "Basit kurallar çok parçanın etkileşiminde kasırga, hücre veya ekonomi gibi yeni düzenler üretebilir. Üst düzey kavramlar alt fizik ile uyumlu ama ona indirgenmeden yararlıdır.", "Tek su molekülü ıslak değildir; çok sayıda molekül birleşince ıslaklık anlamlı özellik olur.", "Belirme gizli doğaüstü güç değildir. Üst düzey örüntünün dayanıklı ve açıklayıcı oluşudur.", "Bir sorunu molekül düzeyinde açıklayabilmekle doğru karar düzeyinde açıklamak arasındaki farkı görmek büyük resmin ana becerisidir.", "emergent-pattern", "Basit noktalardan yükselen karmaşık spiral, çok parçanın etkileşiminden yeni düzenin belirmesini anlatır."),
        chapter("Yaşamın amacı dışarıdan gelmez", "ÜÇÜNCÜ KISIM · YAŞAM", "Canlılık enerji kullanıp kendini sürdüren, çoğalan ve evrimleşen düzenler kurar. Bu amaçlı görünüş dışarıdan plan değil doğal seçilimle oluşabilir.", "Göz görmek için yapılmış gibi durur; nesiller boyunca daha iyi gören varyasyonların seçilmesi bu işlevi tasarımcı olmadan açıklar.", "Yaşamın kökeninin bütün adımları bilinmiyor. Evrim güçlü açıklama olsa da ilk kendi-kopyalayan sistem araştırma konusudur.", "Bilmediğimiz boşluğu doğrudan kesin cevapla doldurmamak, hem bilime hem hayrete daha çok alan bırakır.", "life-energy-loop", "Enerji akışıyla kendini sürdüren hücre döngüsü, canlı düzenin doğal süreçlerde kurulmasını gösterir."),
        chapter("Bilinç büyük resimde nereye oturur?", "DÖRDÜNCÜ KISIM · ZİHİN", "Carroll zihnin beynin karmaşık işleyişinden beliren bir süreç olduğunu savunur. Deneyim gerçektir; ayrı maddesiz ruh varsayımı için fiziksel kanıt görmez.", "Müzik hoparlörden doğar diye melodi sahte olmaz. Beyin etkinliğinden doğan acı ve sevinç de yaşanan gerçekliktir.", "Bilincin öznel niteliğinin tam açıklaması açık sorudur. Fizikselcilik güçlü çerçeve sunar ama bütün ayrıntıları çözmüş değildir.", "Beyin bağlantısını kabul etmek insan deneyimini küçültmek değil bakım ve sorumluluğu somutlaştırmak olabilir.", "brain-melody", "Beyinden yükselen melodi çizgisi, öznel deneyimin fiziksel süreçten doğarken gerçek kalmasını simgeler."),
        chapter("Özgür irade hangi düzeyde?", "DÖRDÜNCÜ KISIM · SEÇİM", "Atomlar yasaya uyuyor diye seçim dili gereksiz olmaz. İnsan düzeyinde nedenleri tartan, plan yapan ve davranışını değiştiren ajanlardan söz etmek geçerli üst düzey açıklamadır.", "Satranç hamlesi fiziksel parçacık hareketidir; ama oyuncunun stratejisini anlatmak için neden seçtiğini sorarız.", "Bu uyumcu görüş herkesin eşit seçeneğe sahip olduğunu söylemez. Bağımlılık, yoksulluk ve beyin hastalığı hareket alanını daraltır.", "Sorumluluğu değerlendirirken hem kişinin düşünme kapasitesini hem gerçek seçeneklerini hesaba katmak daha insani sonuç verir.", "choice-levels", "Parçacık zemini üstündeki yol ayrımı, fiziksel nedensellik içinde insan düzeyinde anlamlı seçim dilini gösterir."),
        chapter("Ahlak gökten inmeden ayakta kalır mı?", "BEŞİNCİ KISIM · DEĞER", "Carroll ahlaki değerlerin evrenin temel parçacıkları arasında yazılı olmadığını, ortak yaşayan bilinçli varlıkların ihtiyaç ve hedeflerinden kurulduğunu savunur.", "Acı çeken çocuğa yardım etmek için kozmik yasa levhası gerekmez; onun deneyimini önemsemek ve nasıl bir toplum istediğimizi tartışmak yeterlidir.", "İnsan yapımı olmak keyfi olmak değildir. Para ve hukuk da insan yapımıdır ama gerçek sonuç taşır; ahlak gerekçe ve karşılıklılıkla sınanır.", "Ahlaki tartışmada 'evren emrediyor mu?' yerine 'kim etkileniyor, hangi ilke herkese savunulabilir?' diye sormak üretkendir.", "human-made-moral-bridge", "İnsanların birlikte kurduğu köprü, ahlakın kozmik levha olmadan ortak gerekçelerle ayakta kalmasını anlatır."),
        chapter("Anlamı bulmak mı kurmak mı?", "BEŞİNCİ KISIM · ANLAM", "Doğa bize hazır amaç vermiyorsa hayat anlamsız olmak zorunda değildir. Sevgi, merak ve projelerle anlamı yaşayan varlıklar biziz.", "Boş kâğıtta yazı yok diye kitap değersiz değildir; hikâyeyi yazma imkânı tam da boşluktan doğar.", "Kendi anlamını kurma sözü yoksulluk ve baskıyı küçümsememelidir. Anlam için zaman ve güvenlik de toplumsal olarak dağıtılır.", "Size dışarıdan alkış gelmese de sürdürmek isteyeceğiniz ilişki ve uğraşları yazmak kişisel anlam haritası çıkarır.", "meaning-on-blank-page", "Boş sayfaya çizilen yol, hazır kozmik amaç yokken insanın anlam kurma özgürlüğünü simgeler."),
        chapter("Ölüm son ise hayat küçülür mü?", "BEŞİNCİ KISIM · SONLULUK", "Carroll ölümden sonra kişisel bilincin sürdüğüne dair kanıt görmez. Sonluluk hayatı değersizleştirmek yerine her anı tekrarlanamaz kılabilir.", "Bir konser bitecek diye müzik anlamsız olmaz; bitiş, dinlediğiniz dakikaya dikkat vermenizi sağlar.", "Bu fikir yas tutan herkese teselli vermeyebilir ve soğuk dayatılmamalıdır. Felsefi görüş ile duygusal ihtiyaç farklı hızlarda ilerler.", "Ölümü düşünmek bugün kime zaman ayırmak ve hangi işi ertelememek istediğimizi açıklığa kavuşturabilir.", "finite-concert", "Sönen son nota, bir deneyimin bitmesinin onu değersiz değil benzersiz yapabileceğini gösterir."),
        chapter("On Emir değil on düşünme ilkesi", "ALTINCI KISIM · YAŞAMA SANATI", "Kitap kesin kozmik emirler yerine açık fikirli olma, kanıtı güncelleme, başkasının deneyimini önemseme ve hayatı amaçla kurma gibi pratik ilkeler önerir.", "Yanıldığını fark edip fikrini değiştirmek zayıflık değil, zihnin yeni kanıta doğru çalıştığının işaretidir.", "İlkeler çatışabilir ve formül her durumu çözmez. Etik yaşam sürekli muhakeme ve diyalog ister.", "Karar öncesi olguyu, etkilenen kişiyi ve kendi yanılma payınızı ayrı satırlara yazmak şiirsel natüralizmi gündelik alışkanlığa çevirir.", "open-principles", "Taşa kazılı emir yerine açık pusula, değişen kanıt içinde yön veren ama düşünmeyi bitirmeyen ilkeleri anlatır."),
        chapter("Bilimin sınırını bilmek", "ALTINCI KISIM · ALÇAKGÖNÜLLÜLÜK", "Bilim doğa hakkında en güvenilir aracımızdır; fakat hangi hayatı seçmemiz gerektiğini tek başına söylemez. Olgudan değere geçerken insan hedefi gerekir.", "Tıp bir tedavinin ömrü uzatacağını söyler; hasta o sürenin bedelini ve yaşam kalitesini değerleriyle tartar.", "Sınır bilimi zayıflatmaz, sahte otoriteden korur. Aynı şekilde değer konuşması olguları yok sayamaz.", "Tartışmada 'Bilim burada neyi ölçüyor, hangi tercih hâlâ bize kalıyor?' sorusunu ayırmak gereksiz kutuplaşmayı önler.", "science-boundary", "Ölçüm cetveliyle pusulanın yan yana durması, olgusal bilgi ile değer seçiminin farklı ama ortak çalışan araçlar olduğunu gösterir."),
        chapter("Büyük resimde insanın yeri", "ALTINCI KISIM · BÜTÜN", "İnsan evrenin merkezi değildir; yine de anlam ve değer üretebilen ender karmaşık yapılardan biridir. Küçüklük önemsizlik demek değildir.", "Dev gökyüzü altında çocuğun elini tutmak kozmik ölçekte küçük, yaşayan iki bilinç için dünyalar kadar büyüktür.", "İnsan ayrıcalığını abartmak çevreyi sömürmeye, tamamen silmek ise sorumluluktan kaçmaya yol açabilir. Ölçekler birlikte tutulmalıdır.", "Kozmik tevazu ile gündelik merhameti aynı cümlede taşımak kitabın büyük resmini tamamlar.", "human-in-cosmos", "Yıldızlı genişlikte birbirinin elini tutan küçük insanlar, kozmik küçüklük ile yaşanan değeri birlikte gösterir."),
    ],
    misreading="Büyük Resim 'fizik her şeyi tek başına açıklıyor' veya duygular yalnız kimyadır demez. Tek doğal dünyanın farklı düzeylerde gerçek ve yararlı açıklamalar istediğini; bilimsel olgu ile insani değer dilinin birbirini yok etmeden çalışabileceğini savunur.",
    modern="Kuantum, kozmoloji ve bilinç araştırmaları ilerlemeye devam ediyor; bazı ayrıntılar güncellenebilir. Kitabın kanıtı derecelendirme, açıklama düzeylerini ayırma ve doğa içinde anlam kurma çerçevesi ise güncelliğini koruyor.",
    questions="Bu soruya hangi açıklama düzeyi gerçekten uygun? İddia hangi kanıtla değişirdi? Hazır kozmik amaç aramak yerine bugün hangi anlamı ve sorumluluğu kurabilirim?",
    essence="Tek doğal evrende atomlardan bilinç ve anlama uzanan farklı açıklama katları vardır; hazır amaç yoksa bile değerli bir hayatı birlikte kurabiliriz.",
))
