#!/usr/bin/env python3
"""Build books 72, 93, 103, 122 and 124."""

from summary_batch_second_common import chapter, make_book, write_books


BOOKS = []


BOOKS.append(make_book(
    72, "savas-sanati", "Savaş Sanatı", "Sun Tzu",
    "Zaferi yalnız çarpışma anında değil; bilgi, hazırlık, hız, aldatma, arazi ve maliyet hesabında arayan, en iyi savaşın düşmanı dövmeden etkisizleştirmek olduğunu söyleyen kısa ama katmanlı strateji klasiği.",
    "#58614D", "The Art of War / Sunzi Bingfa",
    [
        {"id": 1, "title": "Chinese Text Project - The Art of War", "url": "https://ctext.org/art-of-war"},
        {"id": 2, "title": "MIT Classics - The Art of War", "url": "https://classics.mit.edu/Tzu/artwar.html"},
        {"id": 3, "title": "Encyclopaedia Britannica - Sun Tzu", "url": "https://www.britannica.com/biography/Sunzi"},
    ],
    [
        chapter("Savaş başlamadan yapılan hesap", "BİRİNCİ BÖLÜM · PLANLAMA",
            "Sun Tzu savaşı cesaret gösterisi değil, devletin yaşamını belirleyen ağır bir hesap sayar. İlk adım kılıç çekmek değil koşulları karşılaştırmaktır: Kim daha uyumlu, hazırlıklı, disiplinli ve esnektir?",
            "İki işletmenin büyük ihaleye girdiğini düşünün. Biri rakamları, ekibini ve teslim süresini ölçmüş; diğeri yalnız kendine güveniyor. Sahadaki sürpriz çoğu zaman masadaki ihmalin sonucudur.",
            "Planlama geleceği kusursuz bilmek değildir. Sun Tzu değişen bilgiye göre planı yenilemeyi ister. Katı plan, harita doğru olsa bile hareket eden dünyaya yetişemez.",
            "Gündelik kararda da önce maliyet, zaman, insan ve çıkış yolu sorulur. Hazırlık korkaklık değil, gereksiz cesaret ihtiyacını azaltan akıldır.",
            "war-table-calculation", "Zaferin ilk sahnesi savaş alanı değil, koşulların soğukkanlı biçimde karşılaştırıldığı plan masasıdır."),
        chapter("Yol, gök, yer, komutan ve düzen", "BİRİNCİ BÖLÜM · BEŞ ETKEN",
            "Kitap beş temel etken sayar: Halkla yönetimi aynı yönde tutan yol; mevsim ve zaman olan gök; mesafe ve arazi olan yer; komutanın karakteri; ordunun örgüt ve lojistiği.",
            "İyi kaptan tek başına yetmez. Fırtına, rota, mürettebatın güveni ve geminin bakımı aynı yolculuğa girer. Lideri kahramanlaştırmak sistemin kalanını görünmez yapar.",
            "Bu beşli sihirli kontrol listesi değildir; birbirine bağlı alanları hatırlatır. Ahlaki bağlılık lojistik açığı kapatmaz, iyi erzak da kötü komutanı otomatik düzeltmez.",
            "Bir proje tıkandığında 'kim suçlu?' yerine amaç, zaman, çevre, liderlik ve süreç başlıklarını ayrı ayrı görmek sorunu daha doğru yere taşır.",
            "five-factors", "Amaç birliği, zaman, arazi, liderlik ve düzen aynı stratejik sistemin beş ayağıdır."),
        chapter("Bütün savaş aldatmaya dayanır", "BİRİNCİ BÖLÜM · ALDATMA",
            "Sun Tzu güçlü olduğunda zayıf, yakınken uzak görünmeyi; düşmana yanlış beklenti verip kararını bozmayı önerir. Aldatma kaba yalan değil, karşı tarafın bilgi modelini yönetmektir.",
            "Futbol takımı serbest vuruşta topu bir oyuncunun kullanacağını gösterip başka oyuncuya bırakır. Hareket rakibi kandırır ama oyunun amacı içindedir. Stratejik sürpriz, gücü doğru anda yoğunlaştırır.",
            "Bu fikir gündelik ilişkide sınırsız manipülasyon ruhsatı değildir. Savaş metninin aracını dostluk ve aileye taşırsanız güveni yok edersiniz. Bağlam ahlaki sınırı değiştirir.",
            "Rekabette asıl ders, kendi planınızı gereksiz yere açık etmemek ve rakibin gösterdiği görüntüyü doğrudan gerçek sanmamaktır.",
            "false-banner", "Aldatma rakibin gözünü kapatmak değil, ona yanlış harita gösterip gücünü yanlış yere taşıtmaktır."),
        chapter("Dövüşmeden kazanmanın üstünlüğü", "ÜÇÜNCÜ BÖLÜM · STRATEJİ",
            "En yüksek başarı yüz savaş kazanmak değil, düşmanın direncini çarpışmadan kırmaktır. İttifakı bozmak, planı engellemek ve çıkış yolu bırakmak, şehir kuşatmaktan daha az yıkıcıdır.",
            "Mahkemeye yıllarca gitmek yerine iyi arabuluculukla iki tarafın kabul edeceği çözüm bulmak düşünün. Kimse büyük zafer töreni yapmaz ama para, zaman ve ilişki korunur.",
            "Çarpışmasız zafer her zaman barışçıl değildir; tehdit, baskı ve psikolojik üstünlük içerebilir. Sonucun az kanlı olması yöntemi otomatik adil yapmaz.",
            "Yine de liderlik için önemli ölçüdür: Başarıyı görünür çatışma sayısıyla değil, kaç çatışmayı gereksiz hale getirdiğinizle de değerlendirin.",
            "unbroken-city", "En üstün komutan şehri yıkıp almaktan çok, onu savaşmadan teslim edecek koşulu kurar."),
        chapter("Uzayan savaşın görünmeyen faturası", "İKİNCİ BÖLÜM · MALİYET",
            "Uzun savaş silahı köreltir, morali tüketir ve hazineyi boşaltır. Sun Tzu yalnız cephedeki kaybı değil, taşıma, vergi, fiyat ve çiftçinin eksilen emeğini de hesabın içine alır.",
            "Ev tadilatının iki hafta yerine iki yıl sürmesi gibi, gecikme yalnız ilk bütçeyi aşmaz; yaşamın diğer alanlarını da sürekli bozar. Savaşın süresi maliyeti katlayarak büyütür.",
            "Hız tutkusu da kör olmamalıdır. Acele yanlış hedefe saldırmayı doğurabilir. Kitabın istediği, amaç açık olduğunda gereksiz uzamayı önleyen hazırlıklı hızdır.",
            "Kurumsal projelerde batık maliyet tuzağına dikkat edin: Çok harcadık diye kötü yolu sürdürmek, kaybı kurtarmak yerine büyütebilir.",
            "long-war-ledger", "Savaş uzadıkça cephe dışındaki vergi, üretim, moral ve fırsat kayıpları görünmeyen faturayı büyütür."),
        chapter("Kendini ve düşmanı bilmek", "ÜÇÜNCÜ BÖLÜM · BİLGİ",
            "Ünlü öğüt, yalnız düşmanı tanımayı değil kendi gücünü, korkusunu ve sınırını da bilmeyi ister. Tek taraflı bilgi tehlikelidir: Rakibi biliyor ama kendinizi abartıyorsanız hesap yine bozulur.",
            "Satranç oyuncusu rakibin açılışlarını ezberlese de kendi zaman baskısında yaptığı hatayı bilmiyorsa kaybedebilir. İç kör nokta dış istihbaratı değersizleştirir.",
            "Bilmek tek rapora sahip olmak değildir; yanlış bilgiyi ayıklamak ve değişimi izlemek gerekir. Dünkü düşman profili bugünkü davranışı garanti etmez.",
            "Bir tartışmada karşı tarafın zayıf noktasını aramadan önce kendi öfke eşiğinizi tanımak, stratejiyi daha insanî ve daha etkili yapabilir.",
            "two-mirrors", "Stratejist bir aynayı rakibe, diğerini kendi sınır ve zaaflarına tutar."),
        chapter("Biçimsiz olmanın gücü", "DÖRDÜNCÜ BÖLÜM · KONUMLANMA",
            "Rakibin sizi kolay okuyamaması için sabit kalıba hapsolmamak gerekir. Sun Tzu savunmayı görünmez, saldırıyı beklenmedik yapar; biçimsizlik seçenekleri açık tutar.",
            "Her maçta aynı köşeye servis atan tenisçi güçlü olsa bile çözülebilir. Vuruşlarını koşula göre değiştiren oyuncu rakibi sürekli tahmine zorlar.",
            "Biçimsizlik kimliksiz ve plansız olmak değildir. Omurga hedefte, esneklik yöntemdedir. Her gün fikir değiştiren lider ile koşula uyarlanan lider aynı değildir.",
            "Kariyerde tek beceriye kapanmak yerine temel yeteneği farklı araçlarla kullanabilmek, değişen piyasada stratejik biçimsizlik sağlar.",
            "formless-water", "Biçimsiz strateji hedefsiz değil; hedefe giderken rakibin okuyamayacağı kadar esnek olmaktır."),
        chapter("Shi: yokuş aşağı yuvarlanan taş", "BEŞİNCİ BÖLÜM · MOMENTUM",
            "Sun Tzu zaferi yalnız askerin bireysel cesaretinde değil, doğru kurulan durumda arar. 'Shi' diye çevrilen stratejik güç, yokuşun tepesindeki taşın konumundan gelen birikmiş etkidir.",
            "Ağır taşı düz yolda itmek zordur; yokuşta küçük dokunuş yeter. İyi lider insanları sürekli kahramanlığa zorlamak yerine sonucun doğal akacağı düzeni kurar.",
            "Momentum kendiliğinden iyi değildir. Yanlış bilgiyle büyüyen kalabalık da aynı hızla felakete gidebilir. Enerjinin yönü ve durdurma mekanizması önemlidir.",
            "İş akışında doğru şablon, otomasyon ve yetki dağılımı bireysel çabayı büyütür. Sistem iyi kurulunca insanlar daha az yorularak daha iyi sonuç alır.",
            "rolling-stone", "Stratejik momentum, doğru konuma yerleştirilmiş taşın küçük itmeyle büyük güç üretmesine benzer."),
        chapter("Boşluk ve doluluk", "ALTINCI BÖLÜM · ZAYIF NOKTA",
            "Rakibin güçlü olduğu dolu yere çarpmak yerine savunmasız boşluğa yönelmek gerekir. Kendi niyetinizi gizleyip rakibi birçok noktaya bölmek, yerel üstünlük yaratır.",
            "Kalabalık ana caddede aynı dükkânı açmak yerine kimsenin hizmet vermediği mahalleyi seçmek gibi. Başarı bazen daha güçlü olmaktan değil, karşılaştırmanın olmadığı alanı bulmaktan gelir.",
            "Zayıf nokta aramak etik sınır ister. Hastalık, yas ve güven ilişkisini sömürmek stratejik olabilir ama ahlaken kabul edilemez. Etkinlik ile doğruluk aynı ölçü değildir.",
            "Sorun çözerken enerjiyi en sert dirence değil, sistemi açacak küçük kaldıraç noktasına vermek kitabın barışçıl kullanım alanıdır.",
            "empty-full", "Güçlü duvara tekrar tekrar vurmak yerine savunmanın boş bıraktığı kapıyı görmek gerekir."),
        chapter("Su araziye göre şekil alır", "ALTINCI BÖLÜM · UYUM",
            "Su yüksekten kaçar, alçağa akar ve kabın biçimini alır. Ordu da tek yöntemle değil, düşmanın ve arazinin durumuna göre hareket etmelidir. Değişmeyen zafer tarifi yoktur.",
            "Yağmur suyu kayayı bir anda yenmez; yol bulur, birikir ve zamanla aşındırır. Esneklik zayıflık değil, gereksiz çarpışmayı reddeden sürekliliktir.",
            "Her koşula uyum sağlamak değerlerden vazgeçmek demek değildir. Su benzetmesi yöntem içindir; amaç ve etik sınırın da su gibi kaybolması gerekmez.",
            "Yönetimde aynı toplantı biçimini her ekibe dayatmak yerine insanların deneyimi, işin aciliyeti ve iletişim ortamına göre süreç seçmek daha etkilidir.",
            "water-terrain", "Su nasıl kabın ve arazinin biçimini alıyorsa strateji de yöntemi koşula göre değiştirir."),
        chapter("Arazi yalnız toprak değildir", "DOKUZUNCU VE ONUNCU BÖLÜM · ARAZİ",
            "Dar geçit, bataklık, yüksek zemin ve uzak mesafe kararları değiştirir. Arazi, kimi yerde savaşmayı, kimi yerde beklemeyi ve kimi yerde hiç girmemeyi gerektirir.",
            "İyi koşucu buzlu zeminde aynı hızla dönemez. Yeteneği kaybolmamıştır; zemin davranışın maliyetini değiştirmiştir. Strateji kişiyi çevreden ayrı değerlendirmez.",
            "Modern kullanımda arazi pazar, hukuk, teknoloji platformu ve kurum kültürü olabilir. Fakat her şeyi savaş alanı görmek insan ilişkilerini gereksiz düşmanlaştırır.",
            "Bir karar öncesi 'hangi zeminde oynuyoruz ve bu zemin kimin hareketini kolaylaştırıyor?' sorusu görünmeyen avantajı ortaya çıkarır.",
            "terrain-map", "Aynı kuvvet, dar geçitte, açık ovada ve bataklıkta bambaşka değere sahiptir."),
        chapter("Dokuz zemin ve bağlılık", "ON BİRİNCİ BÖLÜM · DURUM",
            "Sun Tzu ordunun kendi toprağından ölümcül çıkmazlara kadar dokuz farklı durumda farklı davranacağını söyler. İnsanlar kaçış yolu kalmadığında daha sıkı birleşebilir.",
            "Sınava daha aylar varken dağılan öğrenci son gece olağanüstü odaklanabilir. Baskı enerjiyi toplar, fakat bedeli yüksektir ve sürekli kullanılırsa tükenme getirir.",
            "Komutanın insanları bilerek çaresizliğe sürmesi modern gözle ciddi etik sorundur. Korku kısa vadeli bağlılık yaratırken güveni ve ruh sağlığını yıkar.",
            "İyi lider ölüm zemini üretmek yerine önceliği berraklaştırır, dağınık çabayı ortak hedefe toplar ve gerçek çıkış yollarını korur.",
            "nine-grounds", "Durumun kaçış ve risk yapısı aynı insanlarda farklı bağlılık ve cesaret düzeyleri üretebilir."),
        chapter("Ateş saldırısından önce hava", "ON İKİNCİ BÖLÜM · ZAMANLAMA",
            "Ateşle saldırı rüzgâr, kuruluk ve doğru zaman ister. Araç ne kadar güçlü olursa olsun çevre uygun değilse geri dönüp kendi ordunu yakabilir.",
            "Kuru otları yakmak için rüzgârlı günde kibrit atmak kontrol edilemeyen yangın doğurur. Güçlü araç, etkisinin yönünü garanti etmez.",
            "Sun Tzu öfke yüzünden saldırmamayı vurgular. Duygu geçer, yıkılan ülke ve ölen insan geri gelmez. Liderin iç durumu stratejik riskin parçasıdır.",
            "E-posta, sosyal medya ve hukuki tehdit gibi modern 'ateşler' de gönderilmeden önce zaman, geri tepme ve kalıcı kayıt açısından düşünülmelidir.",
            "fire-and-wind", "Güçlü ateş yanlış rüzgârda düşmandan önce onu yakan kişiye dönebilir."),
        chapter("Casus bilgiye neden bedel kazandırır?", "ON ÜÇÜNCÜ BÖLÜM · İSTİHBARAT",
            "Savaşın sonucu binlerce kişinin hayatını etkilerken bilgiye para kıymak aptallıktır. Sun Tzu yerli, iç, çift taraflı, ölüme gönderilen ve geri dönen casus türlerini ayırır.",
            "Bir şirket milyonluk yatırım yaparken müşteriyle konuşmaya bütçe ayırmıyorsa karanlıkta ilerler. Küçük bilgi maliyeti büyük yanlış yönün önüne geçebilir.",
            "İstihbarat da hatalı, taraflı veya kasıtlı yanıltıcı olabilir. Kaynağın amacı, çapraz doğrulama ve bilginin güncelliği önemlidir. Casusa sahip olmak gerçeğe sahip olmak değildir.",
            "Gündelik hayatta casusluk değil, karar öncesi sahadan güvenilir bilgi toplamak gerekir. Varsayımın ucuzluğu bazen yanlış kararın pahalı faturasını gizler.",
            "five-spies", "Bilgiye yapılan küçük yatırım, kör bir savaşın dev maliyetini önleyebilir; fakat kaynak mutlaka doğrulanmalıdır."),
        chapter("Bayrak, davul ve ortak dikkat", "YEDİNCİ BÖLÜM · DİSİPLİN",
            "Kalabalık orduda tek kişinin sesi yetmez; gündüz bayrak, gece davul ortak hareket sağlar. İletişim, büyük gücü bir anda aynı yöne çevirecek kadar açık olmalıdır.",
            "Yangın tahliye planında herkes farklı talimat duysa kapı tıkanır. Basit işaretler paniği azaltıp hareketi koordine eder. Disiplin yalnız ceza değil ortak dil kurmaktır.",
            "Aşırı merkezi komut yerel bilgiyi öldürebilir. İşaret hedefi ve sınırı vermeli, sahadaki kişinin değişen koşula uyum payını korumalıdır.",
            "Ekiplerde iletişim kanalı, karar sahibi ve acil durum işaretleri önceden belirlenirse kriz anında uzun açıklama ihtiyacı azalır.",
            "flags-and-drums", "Ortak işaretler kalabalığın dikkatini birleştirerek dağınık gücü eşzamanlı harekete çevirir."),
        chapter("Öfkeli komutanın kör noktası", "SON BÖLÜMLER · LİDERLİK",
            "Komutan askerlerini çocukları gibi gözetmeli ama disiplini de korumalıdır. Ne yalnız sevgi ne yalnız ceza yeterlidir. En büyük tehlikelerden biri kişisel öfkeyi devlet kararı sanmaktır.",
            "Bir yöneticinin eleştiriye kızıp bütün projeyi iptal etmesi, kurumu kendi duygusunun uzantısına çevirir. Duygu gerçek olabilir; sonuç onunla aynı ölçekte olmamalıdır.",
            "Sun Tzu'nun hiyerarşik dünyası modern katılımcı liderlikten farklıdır. Yine de karar sahibi kişinin kendini denetlemesi, başka herkesten daha çok önem taşır.",
            "Büyük karar öncesi bekleme süresi, karşı görüş ve geri dönüş planı koymak komutanın anlık öfkesine karşı kurumsal fren oluşturur.",
            "angry-general", "Liderin anlık öfkesi ordunun kalıcı kaderine dönüşmemeli; büyük güç daha güçlü özdenetim ister."),
    ],
    misreading="Savaş Sanatı'nı her ilişkiyi kandırma ve rakibi ezme kılavuzu gibi okumak kitabı sığlaştırır. Metnin en güçlü çizgisi gereksiz çatışmayı önlemek, maliyeti görmek ve koşula göre hareket etmektir; aldatma savaş bağlamından çıkarıldığında güveni yok edebilir.",
    modern="Metnin tarihi ve yazarlığı üzerine tartışmalar vardır; yüzyıllar boyunca derlenmiş bir strateji geleneği olarak okunabilir. İş ve kişisel gelişim dünyası kavramları sıkça aşırı genişletir. En sağlam güncel kullanım hazırlık, bilgi, sistem tasarımı ve çatışma maliyetidir.",
    questions="Bu çatışmaya gerçekten girmek gerekiyor mu? Gücümü en sert duvara mı, en etkili kaldıraç noktasına mı yöneltiyorum? Kararım bilgiye mi dayanıyor, yoksa öfke ve gösteriş beni savaşa mı sürüklüyor?",
    essence="En iyi strateji kahramanca çatışma aramak değil; bilgi, hazırlık, arazi ve zamanlamayla sonucu öyle kurmaktır ki büyük savaş gereksiz hale gelsin.",
))


BOOKS.append(make_book(
    93, "leviathan", "Leviathan", "Thomas Hobbes",
    "İnsanların korku, rekabet ve güvensizlik içinde birbirine zarar verebildiği bir dünyadan yola çıkıp barışı sağlayacak ortak gücün neden gerekli olduğunu savunan; güvenlik uğruna iktidara ne kadar yetki verilebileceğini hâlâ tartıştıran siyaset klasiği.",
    "#4E5963", "Leviathan",
    [
        {"id": 1, "title": "Project Gutenberg - Leviathan", "url": "https://www.gutenberg.org/ebooks/3207"},
        {"id": 2, "title": "Stanford Encyclopedia of Philosophy - Hobbes's Moral and Political Philosophy", "url": "https://plato.stanford.edu/entries/hobbes-moral/"},
        {"id": 3, "title": "Internet Encyclopedia of Philosophy - Thomas Hobbes", "url": "https://iep.utm.edu/hobmoral/"},
    ],
    [
        chapter("Yapay insanın dev gövdesi", "GİRİŞ · LEVİATHAN",
            "Kapaktaki dev hükümdarın bedeni binlerce küçük yurttaştan oluşur. Devlet doğal bir yaratık değil, insanların güvenlik için kurduğu yapay insandır; egemen onun ruhu, memurlar eklemleri, yasalar aklıdır.",
            "Bir şirket logosu tek görünür figürdür ama arkasında binlerce çalışan vardır. Leviathan da tek taç gibi görünse de gücünü onu yetkilendiren insanların birleşiminden alır.",
            "Benzetme devleti kutsal ve değişmez olmaktan çıkarır; fakat yapay insanın başını aşırı büyütüp yurttaş bedenini sessizleştirme tehlikesi taşır.",
            "Bugün devletin veri, polis ve hukuk gücünü tartışırken aynı soruya döneriz: Ortak beden bizi korurken başı nasıl denetleyeceğiz?",
            "leviathan-body", "Dev devlet gövdesi tek hükümdardan değil, güvenlik için birleşmiş küçük yurttaş bedenlerinden oluşur."),
        chapter("İnsan makinesi nasıl işler?", "BİRİNCİ KISIM · İNSAN",
            "Hobbes düşünce, arzu ve korkuyu bedensel hareketlerle açıklar. İnsan kendine iyi gelen şeye yönelir, zarar verecek olandan kaçar; akıl amaç seçen kraldan çok sonuç hesabı yapan araçtır.",
            "Market rafında eliniz bir ürüne uzanırken tat beklentisi, fiyat, sağlık kaygısı ve alışkanlık aynı bedende yarışır. Karar saf düşünceden değil hareket eden eğilimlerin bileşiminden çıkar.",
            "Bu mekanik insan tasviri sevgi ve özveriyi bütünüyle dışlamaz; insanlar başkasının iyiliğini de isteyebilir. Fakat Hobbes siyaseti en kötü ihtimale dayanacak kadar sağlam kurmak ister.",
            "Kurum tasarımında insanların her zaman iyi niyetli olacağını varsaymamak karamsarlık değil, hata payı bırakmaktır. Yine de insanı yalnız çıkar makinesine indirgemek işbirliğinin zenginliğini kaçırır.",
            "human-machine", "Hobbes insan davranışını bedende çarpışan arzu, korku ve sonuç hesaplarının hareketi olarak görür."),
        chapter("Eşitlik neden huzur değil tehlike getirir?", "BİRİNCİ KISIM · DOĞA DURUMU",
            "İnsanlar güç ve yetenek bakımından tam eşit değildir; fakat en zayıf kişi bile plan ve ittifakla en güçlüyü öldürebilir. Bu karşılıklı incinebilirlik herkesin birbirinden korkmasına yol açar.",
            "Aynı odada herkesin birbirinin kasasını açabilecek anahtarı olduğunu düşünün. Kimse mutlak üstün değildir; bu yüzden herkes gece önce davranmayı düşünebilir.",
            "Hobbes'un eşitliği demokratik saygıdan değil, zarar verme kapasitesinden doğar. Karanlık ama önemli nokta, güç farkı olsa bile hiç kimsenin tamamen güvende olmadığıdır.",
            "Silah ve siber saldırı çağında küçük aktörlerin büyük sisteme zarar verebilmesi bu karşılıklı kırılganlığı yeni biçimde hatırlatır.",
            "equal-vulnerability", "İnsanların eşitliği aynı yetenekte olmalarından çok, birbirine ciddi zarar verebilecek kadar kırılgan olmalarından doğar."),
        chapter("Rekabet, güvensizlik ve şan", "BİRİNCİ KISIM · ÇATIŞMA",
            "Hobbes çatışmanın üç kaynağını sayar: Kazanç için rekabet, güvenlik için güvensizlik ve itibar için şan. İnsan yalnız istediği şeyi almak için değil, saldırıya uğramadan önce saldırmak ve küçümsenmemek için de savaşabilir.",
            "İki komşu birbirinin çit büyüttüğünü görünce savunma için daha yüksek çit yapar. Her biri güvenlik ararken sokak kaleye döner. Niyet savunma, ortak sonuç güvensizliktir.",
            "Şan boyutu maddi çıkarın yetmediğini gösterir. Küçük bir hakaret büyük kavgayı tetikleyebilir; insanın başkasının gözündeki yeri gerçek kaynak kadar önemlidir.",
            "Çatışma çözümünde yalnız para paylaşımını değil, güvence ve saygınlık ihtiyacını da görmek bu üçlüden kalan pratik derstir.",
            "three-causes-war", "Kazanç, güvenlik korkusu ve itibar arzusu aynı çatışmayı farklı kapılardan besleyebilir."),
        chapter("Savaş yalnız çatışma anı değildir", "BİRİNCİ KISIM · DOĞA DURUMU",
            "Doğa durumunda savaş sürekli kılıç sallamak değil, saldırı ihtimalinin herkesin hesabını belirlediği dönemdir. Fırtınalı hava tek tek yağmur damlaları değil, uzun süren tehdit koşuludur.",
            "Gece açık bir otoparkta hiç saldırı olmasa bile sürekli tetikte yürüyorsanız güvenlik yoktur. Barış yalnız kavga olmaması değil, kavga beklememek için makul güven taşımaktır.",
            "Hobbes tarih öncesi bütün insanların gerçekten böyle yaşadığını kanıtlamaz; doğa durumu siyasi otorite kalktığında neyin mümkün olduğunu gösteren düşünce deneyidir.",
            "Kırılgan devletlerde yol, ticaret ve eğitim yalnız gerçekleşen şiddetten değil, şiddet beklentisinden de çöker. Güven ekonomik altyapıdır.",
            "storm-of-war", "Savaş tek tek çatışmalardan önce, herkesin saldırı ihtimaline göre yaşadığı sürekli fırtına havasıdır."),
        chapter("Kötü, kısa ve yalnız hayat", "BİRİNCİ KISIM · GÜVENSİZLİK",
            "Ortak güvence olmadığında tarım, denizcilik, sanat ve bilgi birikimi zayıflar; çünkü kimse emeğinin ürününü yarın koruyacağından emin değildir. Hobbes'un ünlü karanlık hayat tasviri buradan çıkar.",
            "Her gece dükkânınızın yağmalanabileceği yerde yeni makineye yatırım yapmazsınız. Üretim isteksizlikten değil, geleceğe güven eksikliğinden durur.",
            "Bu tablo devlet öncesi toplumları haksız biçimde kaba gösterebilir. Antropoloji, merkezi devlet olmadan norm ve işbirliği kuran birçok topluluk gösterir.",
            "Yine de mülkiyet, sözleşme ve gelecek planının güvenlik kurumlarına bağlı olduğu açıktır. Barış, kültür ve ekonomi için görünmez zemin sağlar.",
            "abandoned-workshop", "Gelecekte emeğini koruyamayan insan üretim ve işbirliğine yatırım yapmaktan vazgeçebilir."),
        chapter("Doğa yasalarının barış yolu", "BİRİNCİ KISIM · AKIL",
            "İnsan yalnız korkan varlık değildir; akıl barış için kurallar bulur. Barışı ara, gerektiğinde kendini savun, başkaları da razıysa sınırsız haklarının bir bölümünden vazgeç ve sözleşmeye uy.",
            "Dar kapıdan herkes aynı anda geçmeye çalışırsa kimse geçemez. Sıraya girmek küçük özgürlükten vazgeçip daha büyük hareket imkânı kazanmaktır.",
            "Doğa yasaları ahlaki yön verir ama zorlayıcı güç yoksa kırılgandır. Ben sözümü tutarken başkasının tutmayacağından korkarsam ilk adımı atmak istemem.",
            "İklim, trafik ve dijital mahremiyet gibi ortak sorunlarda kuralın yararı açıktır; güvenilir uygulama ve karşılıklılık olmadan iyi niyet dağılır.",
            "narrow-door-contract", "Herkes küçük hareket özgürlüğünden vazgeçince dar kapıdan güvenli biçimde geçebileceği ortak düzen doğar."),
        chapter("Kılıçsız sözleşme neden yalnız sözdür?", "İKİNCİ KISIM · DEVLET",
            "Hobbes'a göre sözleşmeleri uygulayacak ortak güç yoksa vaatler güven vermez. Ceza ihtimali, sözün yalnız bugünkü niyete değil yarınki çıkar değişimine karşı da dayanmasını sağlar.",
            "Hakemsiz maçta iki takım kurala uyacağına söz verse bile kritik anda faul tartışması çıkar. Hakem oyunu yaratmaz ama ortak kuralı uygulanabilir kılar.",
            "Yalnız korkuya dayalı uyum uzun vadede yetersizdir. Meşruiyet, adalet ve içselleşmiş normlar da kurumun dayanıklılığını artırır. Hobbes yaptırımın ağırlığını öne çıkarır.",
            "Sözleşme tasarımında ceza kadar açık süreç, tarafsız denetim ve itiraz yolu bulunmalıdır. Kılıç kimin elindeyse onun da kurala bağlanması modern eklemedir.",
            "contract-and-sword", "Sözü ortak kural yapan, yalnız imza değil ihlal karşısında işleyecek güvenilir ve denetlenebilir yaptırımdır."),
        chapter("Herkesin herkesi temsil eden kişi", "İKİNCİ KISIM · EGEMEN",
            "Toplum sözleşmesi bireylerin egemenle değil birbirleriyle yaptığı yetkilendirmedir. Herkes ortak temsilcinin kararını kendi eylemi saymayı kabul eder; çokluk tek siyasi kişiye dönüşür.",
            "Apartman sakinleri yöneticiyi seçip bakım bütçesi için imza yetkisi verir. Yönetici tek başına bina değildir ama dağınık kararları ortak eyleme çevirir.",
            "Hobbes egemen sözleşmenin tarafı olmadığı için ona karşı ihlal iddiasını çok dar tutar. Bu, temsilcinin hesap vermeden temsil edilenlerin üstüne çıkmasına yol açar.",
            "Modern temsil anlayışı yetkilendirmeyi süreli, sınırlı ve geri alınabilir yapar. Temsil, boş çek değil belirlenmiş görevdir.",
            "many-to-one", "Dağınık kalabalık ortak temsilciyi yetkilendirerek tek siyasi eylem kapasitesi kazanır."),
        chapter("Bölünmez egemenlik iddiası", "İKİNCİ KISIM · GÜÇ",
            "Hobbes yasama, yargı, savaş, vergi ve öğretim gücünün bölünmesini iç savaş daveti sayar. Son sözü kimin söylediği belirsizse rakip otoriteler yeniden doğa durumuna döner.",
            "Aynı gemide iki kaptan zıt yönde dümen çevirirse fırtınada karar felç olur. Hobbes tek komuta hattını barışın koşulu görür.",
            "Fakat bütün gücü bir elde toplamak yanlış kararı ve zulmü büyütebilir. Modern güçler ayrılığı çatışmayı yok etmek yerine kurallı ve denetimli hale getirir.",
            "Kurum tasarımındaki gerçek soru birlik mi bölünme mi değil; karar hızını kötüye kullanımı önleyen frenlerle nasıl dengeleyeceğimizdir.",
            "two-captains", "Tek gemide iki mutlak kaptan karar felci yaratabilir, ama tek kaptanın da denetlenmesi gerekir."),
        chapter("Özgürlük yasanın sustuğu yerde mi?", "İKİNCİ KISIM · ÖZGÜRLÜK",
            "Hobbes özgürlüğü dış engelin yokluğu olarak tanımlar. Yasanın düzenlemediği alanda kişi istediğini yapabilir; yasa ile özgürlük suyun kıyıları gibi birbirini sınırlar.",
            "Şehirde yol kuralı hızınızı kısıtlar ama herkesin hareket edebilmesini sağlar. Kuralın varlığı her özgürlüğü yok etmez; bazı özgürlükleri mümkün kılar.",
            "Hobbes düşünce alanını geniş bıraksa da kamusal itaatsizliği daraltır. Yasal olanın adil olduğu varsayımı baskıcı yönetimde sorun çıkarır.",
            "Modern özgürlük yalnız engel yokluğu değil, hak, fırsat ve keyfî güce karşı korunma anlamı da taşır. Hobbes başlangıç noktası verir, son söz değil.",
            "law-riverbanks", "Yasa hareketi sınırlayan kıyı olabilir; aynı zamanda ortak akışın güvenle sürmesini sağlar."),
        chapter("Canını koruma hakkının sınırı", "İKİNCİ KISIM · İTAAT",
            "Birey güvenlik için haklarını devreder, fakat kendi yaşamını doğrudan yok etmeye zorlandığında direnme hakkını bütünüyle kaybetmez. Kimse kendini öldürme emrine gönüllü sözleşmeyle bağlayamaz.",
            "Devlet sizi korumak için vardır; doğrudan uçurumdan atlamanızı emrettiğinde sözleşmenin amacı tersine döner. Bedenin kendini koruma dürtüsü devrin son sınırıdır.",
            "Bu sınır Hobbes'un mutlak egemenliğinde küçük ama önemli çatlak açar. Güvenlik egemeni kuruyorsa egemenin güvenliği yok eden eylemi meşruiyeti sorgulatır.",
            "Vicdani ret, ölüm cezası ve olağanüstü hâl tartışmalarında kişisel korunma ile ortak güvenlik arasındaki düğüm sürer.",
            "cliff-command", "Güvenlik için kurulan iktidar kişiye doğrudan yok oluş emrettiğinde sözleşmenin temel amacı çatlar."),
        chapter("Din ile devlet aynı kürsüde", "ÜÇÜNCÜ VE DÖRDÜNCÜ KISIM · DİN",
            "Hobbes rakip dini otoritelerin yurttaşın sadakatini bölerek iç savaşı körüklemesinden korkar. Kutsal metnin kamusal yorumunu egemenin denetimine vermek ister.",
            "Aynı okulda iki müdür birbirine zıt emir verirse öğretmen kime uyacağını bilemez. Hobbes kilise ile devletin çatışmasını böyle bir çift komuta sorunu görür.",
            "Çözümü din özgürlüğünü ciddi biçimde daraltabilir ve siyasi gücü hakikat hakemi yapabilir. Barış adına inancı devletleştirmek vicdanı baskılar.",
            "Modern laiklik farklı bir yol arar: Devlet tek mezhebin aracı olmaz, inanç da kamusal şiddet yetkisini ele geçirmez. Ayrım, tekleştirmeden barış kurmayı amaçlar.",
            "two-pulpits", "Rakip kutsal ve siyasi otoriteler yurttaşı iki zıt emre bölebilir; çözüm tek inancı dayatmak olmak zorunda değildir."),
        chapter("Mülkiyet egemenden önce var mı?", "İKİNCİ KISIM · MÜLKİYET",
            "Hobbes'a göre güvenilir mülkiyet devletin yasasıyla oluşur. Ortak güç yoksa 'benim' dediğiniz şeyi koruyacak kesin hak da yoktur; sahiplik toplumsal düzenin ürünüdür.",
            "Issız yerde toprağa tabela dikmek başkalarını bağlamaz. Tapu, sınır, mahkeme ve kayıt sistemi tabelayı mülkiyete çevirir.",
            "Bu görüş devletin mülkiyete keyfî el koymasını haklı çıkarabilir. Modern hukuk mülkiyeti devletçe tanırken devleti de anayasa ve haklarla sınırlar.",
            "Dijital varlık ve veri sahipliği tartışmalarında aynı ders görülür: Teknik kontrol tek başına hak değildir; ortak tanım ve uyuşmazlık çözümü gerekir.",
            "property-deed", "Eşya üzerindeki fiilî kontrol, ortak kayıt ve yargı sistemi olmadan güvenilir mülkiyet hakkına dönüşmez."),
        chapter("İç savaşın gölgesinde yazılan kitap", "TARİHSEL BAĞLAM · KORKU",
            "Leviathan İngiliz İç Savaşı'nın idam, bölünme ve rejim değişikliği ortamında yazıldı. Hobbes için anarşi soyut korku değil yaşanmış siyasi çöküştü.",
            "Yangından yeni çıkmış kişinin bina yönetmeliğinde güvenliği her şeyin önüne koyması anlaşılırdır. Kişisel tarih hangi riski en büyük gördüğümüzü etkiler.",
            "Bağlam fikri açıklar ama zorunlu kılmaz. Aynı iç savaşı yaşayan biri özgürlüğü, diğeri düzeni öne çıkarabilir. Tarih yazarın sorusunu biçimlendirir, cevabı tek başına üretmez.",
            "Kriz dönemlerinde toplumların güçlü lidere yönelmesi Hobbesçu refleksi canlandırır. Asıl sınav, olağanüstü yetkinin kriz bitince geri dönüp dönmediğidir.",
            "civil-war-window", "İç savaş deneyimi Hobbes'un penceresinde anarşiyi en büyük siyasi kötülük haline getirdi."),
        chapter("Güvenlik için ne kadar özgürlük?", "ELEŞTİRİ · MUTLAKLIK",
            "Hobbes barışın değerini berrak biçimde gösterir, fakat egemene verdiği geniş yetki güvenliği iktidarın tanımına bırakır. Susturulan yurttaşın sessizliği barış gibi görünebilir.",
            "Evde kavga çıkmasın diye tek kişinin konuştuğu düzen sakin olabilir ama adil değildir. Çatışmanın yokluğu ile özgür barış aynı değildir.",
            "Mutlak güç doğru karar garantisi vermez; bilgi hatası, çıkar ve korku yöneticiyi de etkiler. Denetimsiz Leviathan, koruyacağı bedeni ezebilir.",
            "Hobbes'un kalıcı katkısını mutlak egemenlik değil, güvenliğin ortak kurum gerektirdiği sorusu olarak almak daha verimlidir. Modern cevap güvenlik ile hakları birlikte kurmalıdır.",
            "peace-or-silence", "Sessizlik her zaman barış değildir; denetlenmeyen güvenlik gücü koruduğu yurttaşı susturabilir."),
    ],
    misreading="Hobbes 'insan doğası yalnız kötüdür' demekten daha inceliklidir. Sorun insanların sürekli saldırgan olması değil, ortak güvence yokken saldırı ihtimalinin herkesi önleyici davranmaya zorlamasıdır. Kitap mutlak devleti savunsa da korkunun nedenini anlamak savunuyu kabul etmeyi gerektirmez.",
    modern="Anayasal hukuk, güçler ayrılığı ve insan hakları Hobbes'un bölünmez egemenliğine güçlü alternatifler kurdu. Yine de çöken devletlerde güvenlik, dijital alanlarda ortak yaptırım ve kriz döneminde yetki soruları Leviathan'ın temel düğümünü güncel tutuyor.",
    questions="Kuralı uygulayacak güvenilir ortak güç var mı? Güvenlik için verdiğim yetki nasıl denetleniyor ve geri alınabiliyor? Ortadaki sessizlik gerçek barış mı, yoksa korkudan konuşamayan insanların sessizliği mi?",
    essence="İnsanları ortak kurala bağlayan güvenilir güç olmadan barış kırılgandır; fakat güvenliği sağlayan Leviathan denetlenmezse koruyucu olmaktan çıkıp yeni tehdide dönüşebilir.",
))


from build_twenty_more_summaries_batch_2b import MORE_BOOKS  # noqa: E402

BOOKS.extend(MORE_BOOKS)


if __name__ == "__main__":
    write_books(BOOKS)
