#!/usr/bin/env python3
"""Build summary data for books 222, 241, 253, 271 and 275."""

from summary_batch_second_common import chapter, make_book, write_books
from build_twenty_more_summaries_batch_4b import MORE_BOOKS


BOOKS = []


BOOKS.append(make_book(
    222, "feminizm-herkes-icindir", "Feminizm Herkes İçindir", "bell hooks",
    "Feminizmi kadınlarla erkekler arasındaki bir kavga değil, cinsiyetçiliği ve onun ürettiği baskıyı sona erdirme hareketi olarak anlatan sıcak, açık ve gündelik bir rehber.",
    "#8A4E62", "Feminism Is for Everybody",
    [
        {"id": 1, "title": "bell hooks Books - Feminism Is for Everybody", "url": "https://bellhooksbooks.com/product/feminism-is-for-everybody/"},
        {"id": 2, "title": "Encyclopaedia Britannica - bell hooks", "url": "https://www.britannica.com/biography/bell-hooks"},
        {"id": 3, "title": "Routledge - Feminism Is for Everybody", "url": "https://www.routledge.com/Feminism-Is-for-Everybody-Passionate-Politics/hooks/p/book/9781138821620"},
    ],
    [
        chapter("Feminizmin kısa ve açık tanımı", "BAŞLANGIÇ · KAPIYI AÇMAK",
            "bell hooks feminizmi cinsiyetçiliği, cinsiyetçi sömürüyü ve baskıyı sona erdirme hareketi diye tanımlar. Bu tanım suçlanacak bir cins aramaz; değiştirilecek bir düzeni gösterir.",
            "Bir evde kız çocuğuna sofra, oğlana dinlenme düşüyorsa sorun tek bir kötü baba değildir. Aynı kuralı anne, dede ve televizyon da öğretebilir.",
            "Tanımın gücü erkeklerin de cinsiyetçi düzen içinde incinebileceğini kabul etmesidir. Fakat güç eşit dağılmadığı için kadınların yaşadığı sistemli kayıp görünmez kılınmamalıdır.",
            "Bir davranışı tartışırken 'Bunu kim yaptı?' sorusunun yanına 'Bu davranışı normal gösteren kural ne?' sorusunu eklemek kitabın kapısını açar.",
            "open-feminism-door", "Açık kapı, feminizmi bir cinsin kalesi değil cinsiyetçi kuralı birlikte değiştirme çağrısı olarak gösterir."),
        chapter("Sorun erkekler değil cinsiyetçiliktir", "BİRİNCİ KISIM · YANLIŞ KORKU",
            "Kitap, feminizmin erkek düşmanlığı olduğu korkusunu dağıtır. Erkekler cinsiyetçilikten yararlanabilir; ama cinsiyetçi düşünceyi kadınlar da öğrenip yeniden üretebilir.",
            "Oğluna 'erkek ağlamaz' diyen bir anne onu sertlik kafesine iter. Burada cümlenin sahibi kadın olsa da taşıdığı kural erkek egemen kültürdür.",
            "Bu yaklaşım erkeklerin sorumluluğunu silmez. Avantajı olan kişinin yalnız niyetine değil, davranışının sonucuna ve vazgeçmesi gereken ayrıcalığa bakılır.",
            "Tartışmayı 'kadınlar mı erkekler mi haklı?' maçından çıkarıp hangi söz ve kurumun eşitsizlik ürettiğine çevirmek çözüm alanını büyütür.",
            "sexism-not-men", "Hedef tahtasındaki tek tek erkekler değil, herkese öğretilen ve eşitsizliği sürdüren cinsiyetçi kuraldır."),
        chapter("Bilinç yükseltme odaları", "BİRİNCİ KISIM · DENEYİMİ ADLANDIRMAK",
            "İlk feminist bilinç yükseltme gruplarında kadınlar özel sandıkları deneyimleri birbirine anlattı. Aynı korku ve engelin tekrarlandığını görünce kişisel sorun siyasi bir örüntüye dönüştü.",
            "İş yerinde sözü sürekli kesilen biri kendini beceriksiz sanabilir. Beş kadının aynı sahneyi anlatması, aynanın kişide değil toplantı düzeninde olduğunu gösterir.",
            "Paylaşım tek başına dönüşüm değildir; grup yalnız öfke boşaltan kapalı çevreye dönüşebilir. Deneyim, araştırma ve ortak eylemle bağlanmalıdır.",
            "Bugün güvenli çevrim içi topluluklar aynı işi yapabilir; fakat yanlış bilgi ve yankı odası riskine karşı farklı deneyimleri dinlemek gerekir.",
            "consciousness-circle", "Bir çemberde birleşen kişisel hikâyeler, tek tek utançları ortak ve değiştirilebilir bir düzene dönüştürür."),
        chapter("Kız kardeşlik neden kolay değildir?", "İKİNCİ KISIM · FARKLAR",
            "Kadın olmak herkesi otomatik olarak eşit ortak yapmaz. Irk, sınıf, milliyet ve cinsel yönelim bazı kadınlara başkaları üzerinde güç verebilir.",
            "Varlıklı bir kadın yönetici cam tavanı kırarken düşük ücretli kadın çalışanın omzuna basıyorsa, yalnız temsil artmış ama düzen bütünüyle değişmemiştir.",
            "hooks eski 'hepimiz aynıyız' kız kardeşliğinin farkları örttüğünü söyler. Dayanışma benzerlikten değil, eşitsizlikle yüzleşme ve sorumluluk alma iradesinden doğar.",
            "Bir grupta en çok konuşanın değil en çok bedel ödeyenin deneyimine yer açmak, romantik kardeşliği gerçek siyasi ortaklığa çevirir.",
            "unequal-sisterhood", "Aynı köprüde yürüyen kadınlar farklı yükler taşır; dayanışma bu yük farkını görerek kurulur."),
        chapter("Sınıf kapıdan içeri girince", "İKİNCİ KISIM · EMEK",
            "Ana akım feminizm bazen ücretli işe çıkmayı bütün kadınların özgürlüğü gibi sundu. Oysa yoksul kadınlar zaten çalışıyor, üstelik evdeki ücretsiz emeği de taşıyordu.",
            "Ofise giden orta sınıf kadının çocuğuna daha düşük ücretli başka bir kadın bakıyorsa özgürlük birinden diğerine aktarılmış olabilir.",
            "Ücretli iş ekonomik bağımsızlık sağlayabilir ama kötü ücret, taciz ve bakım yükü varsa tek başına kurtuluş değildir. Çalışmanın koşulları belirleyicidir.",
            "Eşit ücret kadar kreş, bakım paylaşımı, sendika ve güvenli çalışma konuşmak sınıfı feminist gündemin merkezine getirir.",
            "work-care-scales", "Terazinin bir kefesindeki ücretli iş, diğerindeki görünmez bakım emeği hesaba katılmadan özgürlük ölçülemez."),
        chapter("Beden üzerinde söz sahibi olmak", "ÜÇÜNCÜ KISIM · BEDEN",
            "Üreme özgürlüğü yalnız kürtaj hakkı değildir; güvenli doğum kontrolü, doğru bilgi, sağlık hizmeti ve çocuk sahibi olabilme koşullarını da kapsar.",
            "Bir kadın yasal hakkı olduğu halde kliniğe ulaşamıyor veya parasını ödeyemiyorsa kâğıttaki özgürlük gündelik hayatta kapalı kapıdır.",
            "hooks seçim dilinin sınıf farkını gizleyebileceğini hatırlatır. Gerçek seçim, seçeneklerin maddi olarak ulaşılabilir olmasını ister.",
            "Beden tartışmasında 'izin var mı?' kadar 'güvenli hizmete kim ulaşabiliyor?' diye sormak hak ile imkân arasındaki boşluğu gösterir.",
            "body-choice-paths", "Beden özgürlüğü yalnız açık bir kapı değil, herkesin yürüyebileceği güvenli ve erişilebilir yollar gerektirir."),
        chapter("Güzellik aynasının arkasındaki güç", "ÜÇÜNCÜ KISIM · GÖRÜNÜŞ",
            "Cinsiyetçi kültür kadının değerini görünüşe bağlar; piyasa da bu kaygıyı ürün satarak büyütür. Özgürlük yalnız istediğini giymek değil, giymediğinde cezalandırılmamaktır.",
            "İş görüşmesinde aynı yetenekte iki kişinin saçına veya yaşına farklı anlam yüklenmesi, aynanın aslında toplumsal bir değerlendirme aracı olduğunu gösterir.",
            "Makyaj yapan kadını bilinçsiz, yapmayanı üstün saymak yeni bir denetim kurar. Önemli olan seçimin korku, zorunluluk ve ceza içindeki yeridir.",
            "Bir reklamı izlerken hangi eksikliği icat edip sonra çözüm sattığını sormak güzellik baskısının ekonomik motorunu görünür kılar.",
            "mirror-price-tag", "Aynanın arkasındaki fiyat etiketi, beden kaygısının kültür kadar pazar tarafından da üretildiğini gösterir."),
        chapter("Şiddetin evi yoktur", "DÖRDÜNCÜ KISIM · GÜVENLİK",
            "Aile içi şiddet özel alan bahanesiyle saklandığında ev güvenli liman değil kapalı bir tuzağa dönüşür. Feminist hareket bu sessizliği kamusal mesele yaptı.",
            "Komşunun duyduğu çığlığı 'aile işidir' diye görmezden gelmesi tarafsızlık değildir; güçlü olanın duvarını kalınlaştırır.",
            "hooks şiddeti yalnız erkeklerin kadınlara uyguladığı biçime indirgemez; çocuklara ve aynı cins ilişkilerdeki şiddeti de ciddiye alır. Yine de oran ve güç farkları unutulmamalıdır.",
            "Koruma hattı, sığınak ve hukuk gereklidir; uzun vadede ise çocuklara sevgi ile kontrolün aynı şey olmadığını öğretmek gerekir.",
            "house-with-open-window", "Kapalı evin açılan penceresi, özel sayılan şiddetin toplumun görebileceği ve durdurabileceği bir mesele oluşunu anlatır."),
        chapter("Çocuk yetiştirmek de feminist iştir", "DÖRDÜNCÜ KISIM · AİLE",
            "Cinsiyetçilik çocukken öğrenilir. Kıza uyum, oğlana hâkimiyet öğreten ev gelecekteki eşitsiz ilişkinin küçük okuludur.",
            "Oğlan düşüp ağladığında sarılmak, kıza bozulan oyuncağı tamir ettirmek basit görünür; ama duygu ve beceriyi cinsiyetten ayırır.",
            "Aile yalnız baskı yeri değildir; bakım, direnç ve aidiyet de üretir. Feminist eleştiri aileyi yok etmekten çok tahakkümsüz hale getirmeyi amaçlar.",
            "Ev işlerini yaşa göre paylaştırmak ve çocuğun beden sınırına saygı göstermek büyük kavramları günlük davranışa çevirir.",
            "equal-childhood-tools", "Aynı oyuncak ve bakım araçlarına uzanan çocuklar, beceri ile duygunun cinsiyete ait olmadığını öğrenir."),
        chapter("Erkekler de özgürleşebilir", "BEŞİNCİ KISIM · ERKEKLİK",
            "Ataerkil düzen erkeğe güç verirken sevgi, kırılganlık ve yardım isteme alanını daraltır. Feminist değişim erkeklere insanlıklarının budanan yanlarını geri verebilir.",
            "İşini kaybeden adam üzüntüsünü söyleyemeyip öfkeye çeviriyorsa, 'geçindiren sert erkek' rolü hem ona hem evdekilere zarar verir.",
            "Erkeklerin acı çekmesi kadınların maruz kaldığı baskıyla aynı değildir. Acıyı görmek ayrıcalığı inkâr etmek değil, dönüşüm için neden çoğaltmaktır.",
            "Erkeklerin çocuk bakımına, dostluğa ve duygusal dile katılması iyilik jesti değil daha özgür bir yaşam pratiğidir.",
            "man-removing-armor", "Zırhını çıkaran erkek güç kaybetmez; duygu, bakım ve yakınlık için hareket alanı kazanır."),
        chapter("Aşk tahakkümle yaşayamaz", "BEŞİNCİ KISIM · SEVGİ",
            "hooks sevginin bakım, saygı, güven ve sorumluluk içerdiğini; kontrol ile şiddetin sevgi sayılamayacağını söyler. Feminist siyaset bu nedenle aşkın karşıtı değildir.",
            "Telefonu sürekli kontrol eden eş kıskançlığını 'çok seviyorum' diye adlandırabilir. Ad değişince denetim sevgi olmaz.",
            "Romantik ilişkiyi yalnız kişisel uyumla açıklamak ekonomik bağımlılık ve öğrenilmiş rolleri kaçırır. Sevgi için eşit pazarlık alanı gerekir.",
            "İlişkide 'Beni seviyor mu?' sorusunun yanına 'Sınırıma ve gelişmeme saygı duyuyor mu?' sorusunu koymak kitabın pratik dersidir.",
            "love-without-cage", "Açık duran kafes, sevginin sahip olmak değil karşıdakinin özgür gelişimine alan açmak olduğunu hatırlatır."),
        chapter("Eğitim özgürlüğün dili olabilir", "ALTINCI KISIM · ÖĞRENME",
            "Feminist eğitim öğrenciye hazır doğruyu ezberletmek yerine kendi deneyimini güç ilişkileriyle birlikte okuma imkânı verir. Sınıf, konuşma hakkının da paylaşıldığı yerdir.",
            "Öğretmen yalnız erkek yazarlardan örnek verirse öğrenci dünyanın yarısını otorite koltuğunda görür. Müfredat sessizce kimin bilgi üretebileceğini öğretir.",
            "Kadın yazar eklemek yetmez; ırk, sınıf ve sömürge soruları da tartışılmalıdır. Temsil, eğitim yönteminin demokratikleşmesiyle tamamlanır.",
            "Toplantı veya sınıfta kimin sözünün kesildiğini saymak bile görünmez hiyerarşiyi tartışılabilir veriye dönüştürür.",
            "shared-classroom-voice", "Açık kitap çevresinde eşit söz alan öğrenciler, bilginin tek kürsüden inmediği bir eğitim alanı kurar."),
        chapter("Popüler kültür hem öğretir hem direnebilir", "ALTINCI KISIM · MEDYA",
            "Film, şarkı ve reklam aşkın, güzelliğin ve gücün nasıl görünmesi gerektiğini tekrarlar. Medya eğlence sunarken cinsiyet dersini de sessizce verir.",
            "Dizide kıskanç erkeğin büyük âşık diye ödüllendirilmesi, denetimi romantik jest gibi paketler. Aynı dizi güçlü bir kadın karakterle kalıbı da kırabilir.",
            "İzleyici boş kap değildir; parodi yapar ve karşı okuma üretir. Fakat tekrarın ve büyük platformların dağıtım gücü hâlâ önemlidir.",
            "Ailece izlenen sahnede 'Burada kimin isteği önemli sayıldı?' diye sormak medya eleştirisini sıkıcı dersten canlı sohbete çevirir.",
            "screen-role-shadows", "Ekrandan düşen rol gölgeleri davranışı biçimlendirir; izleyici ışığı çevirerek gölgeyi de değiştirebilir."),
        chapter("Irk ve cinsiyet aynı kavşakta", "YEDİNCİ KISIM · KESİŞİM",
            "Siyah kadınların deneyimi yalnız ırkçılık ile cinsiyetçiliğin yan yana toplamı değildir; iki yolun kesişiminde farklı bir engel oluşur.",
            "İşveren beyaz kadını kadın kotasında, siyah erkeği ırk kotasında işe alıp siyah kadını yine dışarıda bırakabilir. Ayrı cetveller kavşağı ölçmez.",
            "hooks kesişimsellik kelimesini icat etmedi ama siyah feminist geleneğin bu uyarısını popüler ve açık biçimde taşır.",
            "Politika tasarlarken ortalama kadını değil, gelir, engellilik, göç ve ırk nedeniyle en çok kapı kapanan kişiyi düşünmek çözümü güçlendirir.",
            "intersection-crossroads", "Kesişen yollar tek tek engellerin toplamından farklı, özellikle bazı kadınları sıkıştıran yeni bir kavşak yaratır."),
        chapter("Herkes için hareket ne demektir?", "YEDİNCİ KISIM · KATILIM",
            "Başlıktaki 'herkes' feminizmin sulandırılması değil, cinsiyetçiliğin herkesi ilgilendirdiği çağrısıdır. Hareket uzmanların özel kulübü olursa gündelik hayatı değiştiremez.",
            "Ev işini paylaşan baba, ayrımcı şakaya itiraz eden arkadaş ve adil kreş isteyen işçi aynı büyük değişimin farklı kapılarından girer.",
            "Katılım merkezdeki kadınların liderliğini silmemeli; erkekler sahneyi devralmadan sorumluluk ve dayanışma üstlenmelidir.",
            "Kendinize 'Bugün hangi küçük kuralı yeniden üretmedim?' diye sormak kimliği eyleme bağlar.",
            "everyone-joins-path", "Farklı insanların aynı yola katılması, feminizmi etiket değil gündelik cinsiyetçiliği azaltan ortak hareket yapar."),
        chapter("Devrim gündelik alışkanlıkta başlar", "SON KISIM · EYLEM",
            "hooks yasal eşitliğin gerekli ama yetersiz olduğunu söyler. Cinsiyetçilik evde, dilde, aşkta ve tüketimde yaşamaya devam ediyorsa değişim kâğıtta kalır.",
            "Şirket yönetmeliği eşitlik yazarken toplantıda kadınların fikirleri erkek meslektaş üzerinden duyuluyorsa eski alışkanlık yeni tabelanın altında sürer.",
            "Küçük davranışları değiştirmek kurum siyasetinin yerini tutmaz. Maaş, hukuk ve güvenlik dönüşümü kişisel farkındalıkla birlikte yürümelidir.",
            "Büyük sloganı ertesi sabah kimin bulaşığı yıkadığı, kimin konuştuğu ve kimin güvende olduğu sorularına indirmek kitabı canlı tutar.",
            "everyday-revolution", "Büyük pankarttan eve uzanan yol, feminist değişimin yasa kadar sofra ve konuşma düzeninde de kurulacağını gösterir."),
    ],
    misreading="Kitap kadınların erkeklerden üstün olması gerektiğini savunmaz; feminizmi yalnız bireysel başarı veya yaşam tarzı seçimi de saymaz. Temel hedef, cinsiyetçi tahakkümün sınıf ve ırkla birleşen bütün biçimlerini değiştirmektir.",
    modern="Sosyal medya feminist sözü yaygınlaştırdı, fakat görünürlük yarışını ve çevrim içi şiddeti de büyüttü. hooks'un sade tanımı bugün temsil ile gerçek güç değişimini, etiket ile gündelik davranışı birbirinden ayırmak için hâlâ işe yarar.",
    questions="Bu durumda kimin sözü ve bedeni daha az değerli sayılıyor? Görünürdeki seçim herkes için maddi olarak mümkün mü? Kendi rahatlığımı korurken başkasının yükünü görünmez mi yapıyorum?",
    essence="Feminizm kadınlarla erkeklerin savaşı değil, sevgiye, emeğe ve özgürlüğe zarar veren cinsiyetçi tahakkümü herkes için sona erdirme hareketidir.",
))


BOOKS.append(make_book(
    241, "akiskan-modernite", "Akışkan Modernite", "Zygmunt Bauman",
    "İş, kimlik, ilişki ve güvenlik gibi eskiden katı görünen kurumların hızla şekil değiştirdiği dünyada neden daha özgür ama aynı zamanda daha yalnız ve kaygılı hissettiğimizi anlatan güçlü bir toplum okuması.",
    "#536A73", "Liquid Modernity",
    [
        {"id": 1, "title": "Polity - Liquid Modernity", "url": "https://www.politybooks.com/bookdetail?book_slug=liquid-modernity--9780745624105"},
        {"id": 2, "title": "Encyclopaedia Britannica - Zygmunt Bauman", "url": "https://www.britannica.com/biography/Zygmunt-Bauman"},
        {"id": 3, "title": "University of Leeds - Bauman Institute", "url": "https://baumaninstitute.leeds.ac.uk/"},
    ],
    [
        chapter("Katı dünya nasıl sıvılaştı?", "BAŞLANGIÇ · ANA BENZETME",
            "Katı bir kap biçimini korur, sıvı ise girdiği kabın şeklini alır. Bauman modern hayatın kurumlarının uzun ömürlü kalıp olmaktan çıkıp hızla değişen düzenlemelere dönüştüğünü söyler.",
            "Bir insan dedesinin yaptığı gibi aynı fabrikada kırk yıl çalışmayı planlayamaz; meslek, şehir ve beceri birkaç kez değişebilir.",
            "Geçmiş hiçbir zaman tamamen sabit değildi. 'Katı' ve 'akışkan' tarih fotoğrafı değil, değişimin hızını ve güvence kaybını gösteren mercektir.",
            "Bugün bir karar verirken yalnız iyi seçimi değil, seçimin ne kadar süre geçerli kalacağını da hesaplamamız bu akışkanlığın gündelik izidir.",
            "solid-melts-liquid", "Eriyen katı blok, uzun ömürlü kurumların hızla biçim değiştiren geçici düzenlere dönüşmesini simgeler."),
        chapter("Özgürlük neden yük gibi gelir?", "BİRİNCİ KISIM · BİREYLEŞME",
            "Modern insan daha çok seçim yapar ama sonuçların sorumluluğu da onun omzuna bırakılır. Toplumsal sorunlar kişisel başarısızlık hikâyesine çevrilebilir.",
            "İş piyasası daralırken işsiz kalan kişiye yalnız 'kendini geliştir' denirse ekonomik düzen kişisel motivasyon eksikliği gibi görünür.",
            "Bireysel çaba gerçektir; Bauman bunu reddetmez. Sorun, herkesin farklı başlangıç koşullarını görünmez kılan sınırsız seçim masalıdır.",
            "Kendinizi suçlamadan önce aynı sorunu kaç kişinin yaşadığını ve hangi kurum kararlarının etkili olduğunu sormak özel kaygıyı toplumsal haritaya yerleştirir.",
            "choice-backpack", "Seçimlerle dolu ağır sırt çantası, özgürlüğün kurumsal destek olmadan kişisel yük haline gelebileceğini anlatır."),
        chapter("İş yerinde uzun vade kaybolunca", "BİRİNCİ KISIM · EMEK",
            "Esnek çalışma işletmeye hız kazandırırken çalışanın geleceği planlama gücünü azaltabilir. Sadakat istenir ama karşılığında kalıcı güvence verilmez.",
            "Üç aylık sözleşmeli çalışan ev kredisi, çocuk planı ve şehir seçimini sis içinde yapar. Takvim kısa olunca hayatın geri kalanı da geçici hissedilir.",
            "Esneklik bazı insanlara bağımsızlık verir; uzaktan çalışma veya proje işi özgürleştirici olabilir. Aynı kelimenin kim için fırsat, kim için mecburiyet olduğuna bakılmalıdır.",
            "İş teklifinde maaş kadar öngörülebilir zaman, öğrenme imkânı ve riskin kimin üzerine bırakıldığını sormak akışkan emeğin gerçek fiyatını gösterir.",
            "short-contract-calendar", "Yaprakları hızla kopan sözleşme takvimi, kısa vadeli işin bütün yaşam planını belirsizleştirmesini gösterir."),
        chapter("Tüketici kimliğini sepetten seçer", "İKİNCİ KISIM · TÜKETİM",
            "Üretici toplumda kimlik yapılan işle, tüketici toplumda ise seçilen ürün ve deneyimlerle anlatılır. İnsan kendini sürekli güncellenmesi gereken projeye dönüştürür.",
            "Yeni telefon yalnız araç değil 'geri kalmadım' işaretidir. Bir sezon sonra aynı nesne kimliği taşımakta yetersiz görülür.",
            "İnsanlar reklama tamamen teslim değildir; ürünü yaratıcı biçimde kullanır. Fakat pazar, huzursuzluğu yeni satın alma ihtiyacına çevirmekte ustadır.",
            "Bir istek doğduğunda ihtiyacın kendisini, başkalarına göstermek istediğiniz kişiden ayırmak tüketim döngüsüne küçük bir fren koyar.",
            "identity-shopping-cart", "Alışveriş sepetindeki değişen maskeler, kimliğin satın alınıp hızla yenilenmesi beklenen bir projeye dönüşmesini anlatır."),
        chapter("Bağlantı çok, bağ zayıf", "İKİNCİ KISIM · İLİŞKİLER",
            "Akışkan ilişkiler yakınlık isteği ile kaçış kapısını açık tutma arzusunu birlikte taşır. Bağlanmak güven verir; aynı zamanda gelecekteki seçenekleri sınırlayabilir.",
            "Mesaj uygulamasında konuşmayı tek dokunuşla silmek kolaydır; yüz yüze komşulukta ertesi gün aynı kişiye yeniden rastlanır. Araç ilişkinin bedelini değiştirir.",
            "Bauman bazen eski ilişkileri fazla sıcak gösterebilir; geçmiş aile ve mahalleleri de baskı üretebilirdi. Kalıcılık her zaman iyilik değildir.",
            "Sağlıklı bağ, kaçışın imkânsızlığı değil, sorun çıktığında hemen değiştirmek yerine konuşmayı deneme iradesi olabilir.",
            "many-links-thin-rope", "Çok sayıdaki ince bağlantı, kalabalık görünürken ağırlık taşımakta zorlanan akışkan ilişki ağını simgeler."),
        chapter("Şehirde yabancıyla yan yana", "ÜÇÜNCÜ KISIM · MEKÂN",
            "Büyük şehir farklı insanların yakın mesafede yaşadığı yerdir. Yabancı hem yenilik imkânı hem belirsizlik kaynağıdır; kent tasarımı bu karşılaşmayı artırabilir veya kapatabilir.",
            "Güvenlikli site ile yoksul mahalle arasındaki duvar korkuyu azaltıyor görünür, fakat iki grubun birbirini tanıma imkânını da yok eder.",
            "Açık meydan otomatik eşitlik yaratmaz; erişim, ulaşım ve polis uygulaması kimin rahatça durabileceğini belirler.",
            "Bir şehirde kamusal bank, kütüphane ve pazarın niteliği, farklıların yalnız geçip gitmesini mi yoksa karşılaşmasını mı istediğimizi gösterir.",
            "city-strangers-bridge", "Duvar yerine köprüyle kesişen yabancılar, şehirde korku ile karşılaşma imkânının aynı mekânda kurulmasını anlatır."),
        chapter("Güç hareketli, siyaset yerinde", "ÜÇÜNCÜ KISIM · İKTİDAR",
            "Sermaye ve şirketler sınırları hızla aşabilirken yurttaşın siyasi kurumu çoğunlukla ulusal sınırda kalır. Güç kararın sonucundan kaçabilir, siyaset bedeli yerelde taşır.",
            "Fabrika bir gecede başka ülkeye taşınabilir; işini kaybeden kasabanın belediyesi ise insanları ve boş binaları geride bırakamaz.",
            "Devlet tamamen güçsüz değildir; vergi, hukuk ve uluslararası işbirliğiyle hareket alanı kurabilir. Bauman dengesizliği vurgular, kaçınılmaz kaderi değil.",
            "Bir ekonomik haberde karar vericinin nerede, bedeli ödeyenin nerede olduğunu işaretlemek güç ile sorumluluk arasındaki mesafeyi görünür kılar.",
            "mobile-power-fixed-town", "Uçan şirket merkezi ile yerde kalan kasaba, hareketli güç ve yerel siyasi sorumluluk arasındaki açığı gösterir."),
        chapter("Zamanın uzun yolu kısa ana döner", "DÖRDÜNCÜ KISIM · HIZ",
            "Akışkan modernite beklemeyi kusur sayar; değer hızla ve anlık erişimle ölçülür. Uzun emek isteyen ilişki ve beceri bu ritimde zorlanır.",
            "Yemeğin gelmesini on dakika beklerken huzursuz olan kişi, bir dostluğu on yılda kurmanın yavaşlığını da verimsizlik gibi hissedebilir.",
            "Hız acil sağlık ve bilgi erişiminde büyük kazançtır. Sorun her alanın aynı hız cetveliyle ölçülmesidir.",
            "Günde bir işi bilerek yavaş yapmak, örneğin telefonsuz yürümek veya uzun metin okumak, zamanın yalnız teslim süresi olmadığını hatırlatır.",
            "hourglass-to-instant", "Uzun kum saatinin anlık parıltıya sıkışması, farklı yaşam ritimlerinin hız ölçüsüne indirgenmesini simgeler."),
        chapter("Gözetim özgürlüğün gölgesinde", "DÖRDÜNCÜ KISIM · GÖRÜNÜRLÜK",
            "Akışkan dünyada hareket etmek için dijital iz bırakırız. Kolaylık sağlayan sistem aynı anda davranışı ölçüp sınıflandırabilir.",
            "Harita uygulaması yolu buldurur, konum geçmişinizi de biriktirir. Hareket özgürlüğü ile izlenebilirlik aynı cebin içinde taşınır.",
            "Bauman'ın bu kitabı bugünkü platform gözetimini bütünüyle anlatmaz; sonraki çalışmaları konuyu genişletir. Yine de hareket ve kontrol gerilimi temel kalır.",
            "Ücretsiz hizmette paranın yerine hangi veri ve davranışın verildiğini sormak kolaylığın görünmez sözleşmesini okumaktır.",
            "footprints-under-lens", "Hızla yürüyen kişinin büyüteç altındaki dijital izleri, hareket kolaylığının gözetimle birleşmesini gösterir."),
        chapter("Korku neden her yere yayılır?", "BEŞİNCİ KISIM · GÜVENLİK",
            "Belirsiz ve uzak tehditler nedenleri bulunamadığında yakındaki yabancıya, göçmene veya yoksula yapışabilir. Yönetilemeyen kaygı somut hedef arar.",
            "İş güvencesi azalan kişi öfkesini şirket kararına değil otobüsteki yabancı dile yöneltebilir; çünkü yakındaki hedef daha görünürdür.",
            "Her güvenlik kaygısı uydurma değildir. Bauman'ın uyarısı tehlikeyi inkâr etmek değil, korkunun hangi nedene bağlandığını sınamaktır.",
            "Bir korku haberi gördüğünüzde olasılığı, kaynağı ve önerilen çözümden kimin güç kazandığını sormak sisin içindeki yolu açar.",
            "fear-finds-target", "Biçimsiz korku bulutu yakındaki yabancının üzerine çökerken asıl uzak neden görünmez kalabilir."),
        chapter("Topluluk özlemi ve kapalı kapı", "BEŞİNCİ KISIM · AİDİYET",
            "Belirsizlik arttıkça insanlar sıcak, güvenli topluluk özler. Fakat tamamen benzerlerden kurulan güvenlik, farklı olanı dışarıda bırakma pahasına sağlanabilir.",
            "Mahalle grubunun yalnız aynı görüştekileri kabul etmesi huzur verir; ilk anlaşmazlıkta bu huzurun konuşma değil sessizlik olduğu anlaşılır.",
            "Topluluk ile özgürlük arasında basit seçim yoktur. İyi aidiyet üyeye destek sunarken ayrılma ve eleştirme hakkını da korur.",
            "Bir grubun sıcaklığını ölçerken içeri girmenin, farklı kalmanın ve çıkmanın bedeline birlikte bakmak gerekir.",
            "warm-circle-closed-gate", "Sıcak çemberin kapalı kapısı, aidiyetin destek kadar dışlama ihtimali de taşıdığını anlatır."),
        chapter("Atık yalnız eşya değildir", "ALTINCI KISIM · DIŞARIDA KALANLAR",
            "Tüketim düzeni ürünleri hızla eskittiği gibi insanları da 'gereksiz' ilan edebilir. İş bulamayan, göç eden veya sisteme uymayan kişi ekonomik atık diliyle görülür.",
            "Yeni yazılıma geçildiğinde yılların çalışanına eğitim vermek yerine onu eski model saymak, ürün mantığının insana uygulanmasıdır.",
            "İnsan ile nesne aynı değildir; benzetmenin sarsıcı amacı tam da bu ahlaki skandalı göstermektir.",
            "Bir politika maliyeti azaltırken kimi görünmez ve terk edilmiş bıraktığını sormak verimlilik tablosunun dışındaki insanı geri getirir.",
            "discarded-person-shadow", "Atılmış eşya yığınının yanında duran insan gölgesi, tüketim mantığının kişileri de kullanılmış ve gereksiz sayma tehlikesini gösterir."),
        chapter("Kesinlik satan uzmanlar", "YEDİNCİ KISIM · REHBERLER",
            "Kurumların uzun vadeli yönü zayıflayınca birey hayat koçu, liste ve algoritmadan kesin cevap arar. Rehber çoğalır çünkü dünya daha anlaşılır değil, daha belirsizdir.",
            "Her hafta tersini söyleyen beslenme önerileri arasında kişi doğru hayatı bulmak yerine yanlış seçim yapma korkusu yaşar.",
            "Uzmanlık gereksiz değildir; tıp ve mühendislik güvenilir bilgi üretir. Sorun, değer çatışmasını teknik reçete gibi satmaktır.",
            "Bir tavsiyede kanıtı, çıkarı ve başarısızlık halinde sorumluluğun kime yüklendiğini ayırmak kesinlik pazarına karşı koruma sağlar.",
            "many-compasses", "Farklı yönleri gösteren pusulalar, belirsizlik arttıkça kesin cevap satan rehberlerin çoğalmasını anlatır."),
        chapter("Akışkanlık herkes için aynı değildir", "YEDİNCİ KISIM · EŞİTSİZLİK",
            "Hareketli dünya güçlü kişiye seyahat ve seçenek, yoksula zorunlu göç ve güvencesizlik getirebilir. Aynı akışta kimi sörf yapar, kimi sürüklenir.",
            "Pasaport ve birikimi olan çalışan ülke değiştirmeyi macera sayar; savaştan kaçan göçmen aynı sınırda aylarca bekler.",
            "Bu fark kitabın en önemli ahlaki uyarılarındandır: Esneklik kelimesi sınıf ve vatandaşlıkla birlikte okunmalıdır.",
            "Yeni bir özgürlüğü överken kimin riskini başkasına devrettiğini sormak parlak akışın altındaki eşitsiz zemini gösterir.",
            "surfer-and-drifter", "Aynı dalgada sörf yapan ile sürüklenen kişi, akışkanlığın güç ve kaynaklara göre bambaşka yaşandığını gösterir."),
        chapter("Nostalji çözüm müdür?", "SEKİZİNCİ KISIM · GERİ DÖNÜŞ",
            "Belirsizlik eski sağlam dünyaya dönme arzusunu güçlendirir. Fakat geçmişin güvenliği bazıları için itaat, dışlanma ve sessizlik demekti.",
            "Kapanan fabrikanın düzenli işi özlenebilir; aynı fabrikanın kadınlara kapalı veya sağlıksız oluşu nostalji fotoğrafında görünmeyebilir.",
            "Bauman eski katıları geri getirmeyi önermez. Soru, kalıcılığı özgürlüğü boğmadan ve güvenceyi dışlama üretmeden nasıl kuracağımızdır.",
            "Geçmişi anarken kimin güvende, kimin suskun olduğunu ayrı ayrı sormak hatırayı çözüm sanma tuzağını azaltır.",
            "nostalgia-house-cracks", "Uzaktan sağlam görünen eski evin çatlakları, nostaljik güvenliğin sakladığı baskı ve dışlamayı hatırlatır."),
        chapter("Akışta küçük sağlam adalar", "SEKİZİNCİ KISIM · ORTAK ÇÖZÜM",
            "Kitap hazır program sunmaz; fakat bireysel sorunları yeniden ortak meseleye çevirmemizi ister. Güvence, yalnız kişisel tasarruf değil birlikte kurulan kurum işidir.",
            "Mahalle kreşi, sendika, kütüphane ve dayanışma ağı değişimi durdurmaz; insanlara değişim içinde tutunacak zemin verir.",
            "Her katı kurum iyi değildir. Sağlam ada eleştiriye açık, erişilebilir ve gerektiğinde değişebilir olmalıdır.",
            "Hayatta kalıcı kılmak istediğiniz üç ilişki ve kurumu seçip onlara düzenli zaman vermek, akışkanlığa karşı küçük ama gerçek bir başlangıçtır.",
            "islands-in-current", "Hızlı akıntıdaki dayanışma adaları, değişimi dondurmadan insanlara ortak ve güvenli zemin sağlayabilir."),
    ],
    misreading="Akışkan Modernite 'eskiden her şey güzeldi' veya bütün değişim kötüdür demez. Benzetme, esneklik ve özgürlüğün riskini kurumlardan bireyin omzuna aktarabildiğini gösterir; teknoloji ya da tüketim tek başına şeytan ilan edilmez.",
    modern="Uzaktan çalışma, platform ekonomisi, çevrim içi ilişki ve yapay zekâ Bauman'ın anlattığı geçiciliği daha görünür yaptı. Yine de iklim krizi ve pandemi, ortak kurumlara duyulan ihtiyacın ortadan kalkmadığını güçlü biçimde gösterdi.",
    questions="Bu özgürlüğün riskini kim taşıyor? Geçici çözüm hangi uzun vadeli bağı zayıflatıyor? Kişisel başarısızlık sandığım sorun kaç kişinin ortak deneyimi?",
    essence="Akışkan dünyada seçenekler çoğalırken güvence ve sorumluluk bireyin omzuna kayar; özgür kalmak için yeni ortak dayanaklar kurmak gerekir.",
))


if __name__ == "__main__":
    write_books(BOOKS + MORE_BOOKS)
