#!/usr/bin/env python3
"""Companion definitions for books 32, 41 and 66."""

from summary_batch_second_common import chapter, make_book


MORE_BOOKS = []


MORE_BOOKS.append(make_book(
    32, "behave-davranis", "Behave (Davranış)", "Robert Sapolsky",
    "Bir insanın iyilik ya da şiddet anını tek bir nedene bağlamayı reddeden; davranıştan bir saniye önceki beyin faaliyetinden çocukluğa, hormonlardan kültüre ve evrime doğru zamanı geriye saran büyük biyoloji hikâyesi.",
    "#53645B", "Behave: The Biology of Humans at Our Best and Worst",
    [
        {"id": 1, "title": "Penguin Random House - Behave", "url": "https://www.penguinrandomhouse.com/books/311787/behave-by-robert-m-sapolsky/"},
        {"id": 2, "title": "Stanford - Robert Sapolsky", "url": "https://profiles.stanford.edu/robert-sapolsky"},
        {"id": 3, "title": "Nature Reviews Neuroscience - Stress and the brain", "url": "https://www.nature.com/articles/nrn2639"},
    ],
    [
        chapter("Bir saniye önce", "BAŞLANGIÇ · ZAMAN MAKİNESİ",
            "Sapolsky bir davranışın nedenini sormak için zamanı geriye sarar. Bir tetiğe basılmadan, bir yabancıya yardım edilmeden ya da kırıcı söz söylenmeden hemen önce hangi sinir hücreleri ateşlendi? İlk durak beynin o anki elektrik ve kimyasal durumudur.",
            "Gece karanlığında çalıdan ses geldiğinde beyniniz daha ne olduğunu anlamadan bedeniniz gerilir. Bir saniye sonra bunun kedi olduğunu görüp rahatlarsınız. Davranış, bilinçli hikâyemizden önce başlayan hızlı değerlendirmeler taşır.",
            "Bu yaklaşım kişiyi robota çevirmez; tek açıklamalı ahlak masalını zorlar. Niyet önemlidir ama niyet de algı, hafıza, beden ve durum içinden oluşur.",
            "Bir tartışmada 'nasıl böyle yaptı?' demeden önce o saniyede ne gördüğünü, neyi tehdit saydığını ve hangi seçeneği fark edebildiğini sormak daha açıklayıcıdır.",
            "one-second-before", "Davranışın görünen anından hemen önce beyin, çevreyi çoktan tehdit ya da fırsat olarak değerlendirmeye başlamıştır."),
        chapter("Amigdala: korku düğmesi değil", "BİRİNCİ KISIM · BEYİN",
            "Amigdala çoğu popüler anlatıda yalnız korku merkezi diye geçer. Sapolsky onu daha geniş görür: Tehdit, belirsizlik, toplumsal işaret ve duygusal önem değerlendirmesinde rol alan bir ağ parçasıdır.",
            "Kalabalıkta tanımadığınız birinin hızla yaklaşması aynı hareket olmasına rağmen karanlık sokakta tehdit, havaalanında kavuşma olabilir. Amigdala görüntüyü bağlamdan kopuk bir alarm gibi okumaz.",
            "Beyinde hiçbir bölge tek başına ahlak, şiddet ya da sevgi üretmez. Amigdala prefrontal korteks, hafıza ve beden sinyalleriyle konuşur. Bölge adını neden sanmak, orkestradaki tek çalgıyı besteci saymaktır.",
            "Güncel beyin haberlerinde 'şu bölge yandı, demek ki...' cümlesine temkinli yaklaşmak gerekir. Aktivite ilişki gösterir; tek başına niyet ve kader göstermez.",
            "amygdala-context", "Amigdala tek bir korku düğmesi değil, bağlama göre önem ve tehdit işaretlerini değerlendiren ağın parçasıdır."),
        chapter("Prefrontal korteksin zor freni", "BİRİNCİ KISIM · BEYİN",
            "Alnın arkasındaki prefrontal bölgeler planlama, dürtü denetimi ve sonuçları tartmada önemlidir. Yavaş olgunlaşır, yorgunluk ve stres altında verimi düşer; bu yüzden doğruyu bilmek her zaman doğruyu yapmak değildir.",
            "Diyet yaptığınızı sabah hatırlamak kolaydır; gece uykusuz ve açken pastanın önünde aynı karar zorlaşır. Fren sistemi bozulmuş değildir, kaynakları ve rakip dürtüler değişmiştir.",
            "Prefrontal korteksi saf iyilik merkezi saymak da yanlıştır. Aynı planlama becerisi yardım kampanyası düzenlemek için de soğukkanlı dolandırıcılık yapmak için de kullanılabilir.",
            "İş yerinde hata yapan kişiye yalnız karakter dersi vermek yerine uyku, zaman baskısı ve karar ortamını düzeltmek davranışı daha kalıcı biçimde değiştirebilir.",
            "prefrontal-brake", "Prefrontal denetim güçlü bir fren olabilir ama yorgunluk, stres ve bağlama göre gücü değişir."),
        chapter("Dopamin: haz değil beklenti", "BİRİNCİ KISIM · ÖDÜL",
            "Dopamin çoğu zaman mutluluk kimyasalı diye tanıtılır. Sapolsky'nin anlattığı araştırmalar, onun özellikle ödül beklentisi, öğrenme ve beklenenle gerçekleşen arasındaki farkta rol oynadığını gösterir.",
            "Telefon bildirimi geldiğinde henüz iyi haber okumadan ekrana uzanırsınız. Heyecan ödülün kendisinden çok gelebilecek şeydedir. Belirsiz aralıklarla gelen küçük ödüller davranışı güçlü biçimde bağlayabilir.",
            "Dopamin kötü değildir; hedefe yönelme ve öğrenme için gereklidir. Sorun, sistemin kumar, sosyal medya ya da sürekli alışveriş gibi çevrelerce bitmeyen beklentiye kilitlenebilmesidir.",
            "Kendimizi 'iradesiz' diye suçlamak yerine hangi ipuçlarının beklenti döngüsü kurduğunu görmek, ortamı değiştirmek için somut başlangıç verir.",
            "dopamine-slot-machine", "Dopamin çoğu zaman ödülün tadından çok, birazdan gelebilecek ödülün beklentisini güçlendirir."),
        chapter("Hormonlar davranışı emretmez", "İKİNCİ KISIM · BEDEN",
            "Testosteron saldırganlığı açıp kapatan bir düğme değildir. Var olan toplumsal rekabeti, statü arayışını ve öğrenilmiş davranışı bağlama göre güçlendirebilir. Statü cömertlikle kazanılıyorsa cömert davranış da artabilir.",
            "Bir spor takımında alkış sert müdahaleye gidiyorsa oyuncu sertleşir; aynı hormon düzeyi saygınlığın centilmenlikten geldiği ortamda farklı davranabilir. Hormon melodiyi tek başına yazmaz, sesini yükseltir.",
            "Oksitosin de evrensel sevgi sıvısı değildir. Yakın gruba güveni artırırken yabancıya kuşkuyu büyütebilir. Biyoloji 'biz' duygusunu güçlendirir ama o bizin sınırını kültür çizer.",
            "Hormon etiketleri cinsiyet ve şiddet hakkında kolay mazeret üretmemeli. Beden etkiler; sosyal kural, öğrenme ve hesap verebilirlik bu etkinin yönünü değiştirir.",
            "hormone-volume-knob", "Hormonlar davranışın tek bestecisi değil, bağlamda çalan eğilimlerin sesini değiştiren düğmeler gibidir."),
        chapter("Stres altında daralan dünya", "İKİNCİ KISIM · STRES",
            "Kısa süreli stres kaçmak, odaklanmak ve enerji toplamak için yararlıdır. Kronik stres ise dikkat, bağışıklık, metabolizma ve karar verme sistemlerini yıpratır; dünya daha tehdit dolu görünmeye başlar.",
            "Yangın alarmı beş dakika çalarsa hayat kurtarır, aylarca susmazsa binada kimse düşünemez. Yoksulluk, ayrımcılık ve güvencesizlik bedeni böyle uzun bir alarmda tutabilir.",
            "Sapolsky stresi yalnız kişisel zayıflık saymaz. Denetim duygusu, öngörülebilirlik, sosyal destek ve hiyerarşideki yer biyolojik yükü değiştirir.",
            "Bu nedenle nefes egzersizi yararlı olsa da kötü çalışma koşullarının yerine geçmez. Sağlık, bireysel başa çıkma ile toplumsal düzenin birlikte ele alınmasını ister.",
            "chronic-alarm", "Kısa alarm korur; hiç susmayan stres alarmı bedenin ve kararların ufkunu daraltır."),
        chapter("Çocukluk beyne nasıl yazılır?", "ÜÇÜNCÜ KISIM · GELİŞİM",
            "Erken bakım, tehdit, beslenme ve güven deneyimleri beynin gelişim yollarını etkiler. Çocukluk geçmişte kalmış bir anı değil, stres sisteminin hangi eşiğe ayarlanacağını belirleyen uzun bir hazırlıktır.",
            "Sürekli bağırılan evde çocuk en küçük yüz hareketini tehlike işareti olarak öğrenebilir. Yıllar sonra nötr bir bakışı küçümseme sanması mantıksız karakter değil, geçmişte işe yarayan hassas alarmın yeni yerde çalışması olabilir.",
            "Erken deneyim kader değildir. Beyin yaşam boyunca değişir; güvenli ilişkiler, eğitim ve tedavi yeni yollar kurabilir. Olasılık yükselir, sonuç mühürlenmez.",
            "Çocuk politikası bu yüzden yalnız ahlaki iyilik değil uzun dönemli halk sağlığıdır. Güvenli bakım gelecekteki karar sistemlerinin altyapısına yatırım yapar.",
            "childhood-alarm-setting", "Çocukluk deneyimleri beynin tehdit ve güven eşiğini ayarlar ama geleceği değişmez biçimde mühürlemez."),
        chapter("Ergen beyninin gazı ve freni", "ÜÇÜNCÜ KISIM · ERGENLİK",
            "Ergenlikte ödül ve toplumsal kabul sistemleri güçlü çalışırken prefrontal denetim daha geç olgunlaşır. Risk, özellikle akranların yanında daha çekici olabilir.",
            "Genç sürücü yalnızken sakin, arkadaşları arabadayken hızlı sürebilir. Motor aynı, yol aynı; fakat sosyal ödül hesabı değişir. Ergenlik davranışını yalnız bilgisizlik açıklamaz.",
            "Bu dönem aynı zamanda yaratıcılık, cesaret ve adalet duyarlılığı taşır. Risk alma yalnız sorun değil, eski düzeni sorgulama ve yeni bağlar kurma gücüdür.",
            "Yetişkinlerin görevi yalnız yasak koymak değil, güvenli risk alanları ve ait olunacak olumlu gruplar yaratmaktır. Çevre, gaz ile fren arasındaki dengeyi etkiler.",
            "teen-gas-brake", "Ergenlikte toplumsal ödülün gazı erken güçlenirken uzun vadeli denetimin freni daha yavaş olgunlaşır."),
        chapter("Biz ve onlar bir anda değişebilir", "DÖRDÜNCÜ KISIM · GRUPLAR",
            "Beyin insanları hızla biz ve onlar diye ayırır. Bu ayrım ırk, takım, din ya da geçici bir işaret üzerinden kurulabilir; sabit değildir. Aynı yabancı bir dakika içinde ortak amaç sayesinde 'bizden' olabilir.",
            "Derbi günü farklı forma giyen komşu rakiptir; deprem olduğunda aynı enkazın gönüllüsüdür. Kategori değişince yüz aynı kalsa da duygu ve yardım davranışı değişir.",
            "Hızlı grupçuluk biyolojik yatkınlık taşısa da sınırları kültür ve siyaset çizer. Liderler tehdidi büyüterek kategoriyi sertleştirebilir, kurumlar ortak kimliği genişletebilir.",
            "Önyargıyla mücadele yalnız 'iyi insan ol' çağrısı değil, işbirliği gerektiren temas ve ortak hedef tasarımıdır. Biz sözcüğünün çapı büyütülebilir.",
            "changing-us-them", "Grup sınırı yüzlerden daha hızlı değişebilir; ortak amaç dünün yabancısını bugünün ortağı yapabilir."),
        chapter("Ahlaki tiksinmenin tehlikeli yolu", "DÖRDÜNCÜ KISIM · AHLAK",
            "Tiksinme başlangıçta bozuk yiyecek ve hastalıktan kaçınmaya yardım eder. İnsan toplumu bu bedensel duyguyu ahlaki ve siyasi alanlara taşır; bir grubu kirli diye görmek dışlamayı kolaylaştırır.",
            "Çürük kokusuna verdiğimiz yüz ifadesinin bir insan topluluğunu anlatan konuşmada tekrarlandığını düşünün. Dil, biyolojik kaçınma sistemini toplumsal nefrete bağlayabilir.",
            "Ahlaki yargı yalnız tiksinmeden oluşmaz; empati, zarar, adalet ve gelenek de rol oynar. Fakat tiksinme güçlü olduğunda kanıt ve bireysel farklılık görünmez hale gelebilir.",
            "Bir söylem insanları haşere, mikrop ya da pislik benzetmeleriyle anlatıyorsa bu yalnız kaba söz değildir; şiddetin duygusal zeminini hazırlayabilir.",
            "moral-disgust", "Bedensel tiksinme dili toplumsal gruplara yöneldiğinde dışlama ve şiddeti kolaylaştırabilir."),
        chapter("Empatinin spot ışığı", "DÖRDÜNCÜ KISIM · YARDIM",
            "Empati güçlüdür ama tarafsız değildir. Tanıdığımız tek kişinin acısı milyonlarca yabancının istatistiğinden daha çok etkileyebilir. Spot ışığı bir yüzü aydınlatırken geniş karanlığı görünmez bırakır.",
            "Haberlerde adı ve fotoğrafı olan bir çocuğa yardım etmek kolaydır; aynı bütçeyle yüzlerce görünmeyen çocuğun aşısını düşünmek daha soyuttur. Duygunun şiddeti her zaman toplam yararla aynı yönde değildir.",
            "Sapolsky empatiyi değersizleştirmez; merhameti ilke ve kurumlarla tamamlamayı ister. Yalnız hissettiğimiz kişiye değil, görmediğimiz kişiye de adil davranacak düzen gerekir.",
            "Bağış ve kamu politikalarında hikâye ile veri birlikte kullanılabilir. Kalp kapıyı açar, hesap yardımın nereye ulaşacağını düzeltir.",
            "empathy-spotlight", "Empati bir yüzü güçlü biçimde aydınlatırken istatistik içindeki görünmeyen kalabalığı karanlıkta bırakabilir."),
        chapter("Şiddet tek bir canavar değildir", "BEŞİNCİ KISIM · SALDIRGANLIK",
            "Şiddet soğukkanlı plan, korku patlaması, grup sadakati, statü kavgası ya da sadistik haz gibi farklı yollarla ortaya çıkabilir. Aynı sonuç, farklı beyin ve toplum süreçlerinden doğar.",
            "Aynı kırık cam bir hırsızın planı, çocuğun kazası ya da öfkeli kalabalığın eylemi olabilir. Camı görmek nedeni söylemez. Müdahale de nedene göre değişmelidir.",
            "'Şiddet geni' ya da 'kötü beyin' açıklaması bu çeşitliliği siler. Genetik, erken yaşam, hormon, anlık tehdit, propaganda ve cezasızlık birbirine eklenebilir.",
            "Önleme politikası yalnız cezayı artırmakla yetinemez; silaha erişim, çocukluk stresi, grup dili ve adil kurumlar gibi farklı zaman ölçeklerine dokunmalıdır.",
            "many-roads-to-violence", "Aynı şiddet görüntüsüne korku, plan, statü ve grup sadakati gibi farklı yollar ulaşabilir."),
        chapter("Hiyerarşinin bedene girişi", "BEŞİNCİ KISIM · EŞİTSİZLİK",
            "Hiyerarşide düşük konum, özellikle denetimin az ve aşağılanmanın yüksek olduğu yapılarda kronik stres yaratır. Sorun yalnız az para değil, sürekli belirsizlik ve söz hakkı eksikliğidir.",
            "Aynı yoğun işi yapan iki kişiden biri vardiyasını seçebiliyor, diğeri her an çağrılmayı bekliyorsa beden yükü farklı olur. Kontrol duygusu stres tepkisini değiştirir.",
            "Primat türleri ve insan toplumları aynı değildir; Sapolsky hayvan bulgusunu doğrudan siyasi reçeteye çevirmemeye dikkat eder. Yine de toplumsal sıralamanın biyolojik iz bırakabildiği açıktır.",
            "İş sağlığı maaşın yanında öngörülebilir program, saygı ve karar payını da hesaba katmalıdır. Adalet hissi bedensel bir meseledir.",
            "hierarchy-in-body", "Söz hakkı olmayan ve aşağılanmaya açık hiyerarşi, toplumsal konumu kronik bedensel strese çevirebilir."),
        chapter("Genler olasılık yazar, emir değil", "ALTINCI KISIM · GENETİK",
            "Genler sinir sistemi ve davranış eğilimlerini etkiler, fakat etkileri çevreye bağlıdır. Aynı genetik fark güvenli ve tehdit dolu ortamlarda farklı sonuçlar verebilir.",
            "Bir tohumun boyu genetik özellik taşır ama su, ışık ve toprak olmadan sonuç bilinmez. Davranış genetiği de tohum paketindeki etiketten ibaret değildir.",
            "Kalıtsallık bir toplumdaki farkların oranını anlatabilir; değiştirilemezlik söylemez. Göz bozukluğu yüksek ölçüde kalıtsal olsa da gözlük sonucu dramatik biçimde değiştirir.",
            "Gen haberi okurken 'hangi çevrede, ne kadar etki, hangi nüfusta?' sorularını sormak gerekir. Biyoloji kader cümlesinden daha koşulludur.",
            "genes-and-weather", "Genetik eğilim, çevrenin ışığı ve suyu içinde büyüyen bir olasılıktır; değişmez emir değildir."),
        chapter("Evrim her davranışa masal yazmaz", "ALTINCI KISIM · EVRİM",
            "İşbirliği, akraba yardımı, statü ve eş seçimi evrimsel geçmiş taşır. Fakat bugünkü her davranışa kolay bir Taş Devri hikâyesi uydurmak bilim değildir; alternatif açıklama ve kanıt gerekir.",
            "İnsanların tatlı sevmesini kıtlık geçmişiyle ilişkilendirmek makul olabilir; belirli bir ofis modasını aynı rahatlıkla atalara bağlamak zorlama olur. Güzel hikâye test yerine geçmez.",
            "Kültür evrimsel eğilimlerin üstüne yalnız boya sürmez; yeni seçenekler, kurumlar ve geri beslemeler kurar. İnsanlar biyolojik geçmişlerinden öğrenip ona karşı düzen tasarlayabilir.",
            "Sapolsky'nin güçlü yanı düzeyleri yan yana getirmesidir. Evrim uzak zemin, çocukluk ayar, hormon bağlam ve bir saniye önceki sinyal birlikte davranışa yaklaşır.",
            "evolution-story-test", "Evrimsel açıklama çekici bir masal değil, alternatiflere karşı sınanması gereken uzak zamanlı bir hipotezdir."),
        chapter("Özgür irade ve sorumluluk düğümü", "YEDİNCİ KISIM · ADALET",
            "Davranışın nedenlerini ayrıntılı gördükçe tamamen bağımsız bir irade fikri zorlaşır. Sapolsky mazeret dağıtmak yerine, suçlamadan korumaya ve değiştirmeye odaklanan bir sorumluluk anlayışına yaklaşır.",
            "Freni arızalı araç kazaya neden olduğunda sürücüyü alkışlamayız ama çözüm yalnız öfke değildir; aracı durdurur ve sistemi onarırız. İnsan daha karmaşıktır, fakat güvenlik ile intikam ayrımı düşündürücüdür.",
            "Nedenleri anlamak tehlikeli kişiyi serbest bırakmayı gerektirmez. Toplum korunabilir; soru, acı çektirmeyi ahlaki amaç sayıp saymadığımızdır.",
            "Ceza tartışmasında 'hak etti' cümlesinin yanına 'hangi müdahale tekrarını azaltır?' sorusunu koymak kitabın en zor ama verimli mirasıdır.",
            "justice-repair", "Nedenleri görmek güvenliği kaldırmaz; intikam yerine koruma, onarım ve tekrarın azaltılmasını öne çıkarır."),
    ],
    misreading="Behave, 'beyin yaptı, kişinin sorumluluğu yok' diye okunmamalıdır. Kitap davranışı tek bölgeye, hormona ya da gene indirmez; tam tersine saniyelerden evrime uzanan birçok nedenin nasıl birleştiğini gösterir.",
    modern="Davranış bilimi hızla değişiyor ve bazı popüler nörobilim sonuçları daha büyük örneklerle yeniden değerlendiriliyor. Kitabın kalıcı gücü tek tek bulgulardan çok, nedenleri zaman katmanlarına ayıran ve biyoloji ile toplumu birbirine düşman etmeyen yöntemidir.",
    questions="Bir davranıştan hemen önce ne oldu? O kişinin bedeni ve geçmişi hangi eşiği hazırladı? Hangi toplumsal düzen bu davranışı ödüllendiriyor, kolaylaştırıyor ya da zorlaştırıyordu?",
    essence="İyi ve kötü davranış tek bir karakter düğmesinden çıkmaz; beyin, beden, çocukluk, kültür ve evrimin farklı zamanlarda kurduğu koşullar aynı anda sahneye gelir.",
))


MORE_BOOKS.append(make_book(
    41, "beyindeki-hayaletler", "Beyindeki Hayaletler", "V. S. Ramachandran & Sandra Blakeslee",
    "Kayıp kolu hâlâ ağrıyanlardan kendi felcini inkâr edenlere kadar sıra dışı hastaları izleyerek beynin beden, benlik ve gerçeklik duygusunu nasıl kurduğunu anlatan nörolojik dedektiflik kitabı.",
    "#554D63", "Phantoms in the Brain",
    [
        {"id": 1, "title": "HarperCollins - Phantoms in the Brain", "url": "https://www.harpercollins.com/products/phantoms-in-the-brain-v-s-ramachandran-sandra-blakeslee"},
        {"id": 2, "title": "UC San Diego - V. S. Ramachandran", "url": "https://psychology.ucsd.edu/people/profiles/vsramachandran.html"},
        {"id": 3, "title": "Brain - Phantom limbs review", "url": "https://academic.oup.com/brain/article/121/9/1603/283360"},
    ],
    [
        chapter("Nörolojinin dedektif odası", "BAŞLANGIÇ · YÖNTEM",
            "Ramachandran pahalı cihazdan önce dikkatli soruya, basit deneye ve hastanın anlattığı tuhaf ayrıntıya güvenir. Nadir vakalar, sağlam beyinde görünmeyen düzeni hasar yoluyla açığa çıkarır.",
            "Elektrik panosundaki tek sigorta kapanınca yalnız mutfak kararıyorsa kablonun yolunu anlarsınız. Beyin hasarı da hangi işlevlerin birlikte, hangilerinin ayrı çalıştığına dair doğal deney sunar.",
            "Tek vaka bütün insanlık için kesin kanıt değildir. İlginç gözlem yeni hipotez üretir; sonra daha çok kişi ve kontrollü deney gerekir. Kitabın heyecanı ile kanıtın sınırı birlikte tutulmalıdır.",
            "Gündelik yaşamda da şaşırtıcı hatayı hemen saçmalık diye atmak yerine hangi görünmez kuralı ortaya çıkardığını sormak güçlü bir öğrenme yöntemidir.",
            "neurology-detective", "Sıra dışı hasta, beynin gizli kablolarını gösteren doğal bir dedektiflik vakasına dönüşür."),
        chapter("Olmayan kol neden ağrır?", "BİRİNCİ KISIM · HAYALET UZUV",
            "Kolunu kaybeden kişi parmaklarını, kaşıntıyı ve hatta şiddetli ağrıyı hissedebilir. Çünkü beden haritası yalnız etten oluşmaz; beyin kayıp uzuvdan sonra da eski temsilini taşır.",
            "Eviniz yıkılsa bile navigasyon uygulamasında eski sokak bir süre görünür. Beynin haritası da beden değiştiği anda silinmez. Harita ile fiziksel arazi ayrışınca hayalet deneyim doğar.",
            "Bu, ağrının hayal ürünü olduğu anlamına gelmez. Kaynağı bedendeki doku değil sinir sistemindeki temsil olsa da acı gerçektir. 'Kafanda' sözü küçümseme değilse bile yetersizdir; bütün deneyimler beyinde işlenir.",
            "Kronik ağrı tedavisinde yalnız dokuyu değil beynin öğrenmiş olduğu koruma ve beden modellerini de hesaba katmak bu yüzden önemlidir.",
            "phantom-map", "Fiziksel kol kaybolsa da beynin beden haritası yaşamaya devam ederek gerçek bir hayalet uzuv deneyimi üretebilir."),
        chapter("Yüzde hissedilen parmaklar", "BİRİNCİ KISIM · HARİTA",
            "Bazı hayalet kol hastalarının yüzüne dokunulduğunda kayıp parmaklarında his oluşur. Beyin korteksinde yüz ve el bölgeleri komşudur; elden sinyal gelmeyince yüz girdisi boşalan alana yayılabilir.",
            "Yan daire boşalınca komşunun eşyalarını duvarın ötesine taşırması gibi, sinir haritası da kullanılmayan alana yeniden örgütlenebilir. Beyin sabit kablo panosu değil, canlı mahalledir.",
            "Bu bulgu yetişkin beynin değişebilirliğine güçlü örnektir. Ancak yeniden örgütlenme her zaman yararlı değildir; bazı değişimler ağrıyı veya rahatsız edici duyumu sürdürebilir.",
            "Rehabilitasyonun amacı yalnız kası çalıştırmak değil, beynin haritayı güvenli ve işlevli biçimde yeniden öğrenmesine fırsat vermektir.",
            "face-hand-map", "Yüz ile el haritalarının komşuluğu, yüz dokunuşunun kayıp parmakta hissedilmesine yol açabilir."),
        chapter("Ayna kutusundaki kurtuluş", "BİRİNCİ KISIM · TEDAVİ",
            "Hayalet el yumruk şeklinde kilitlenip ağrıdığında kişi onu açamadığını hissedebilir. Ayna kutusu sağlam elin yansımasını kayıp el yerindeymiş gibi gösterir; görsel geri bildirim beynin donmuş komutunu çözebilir.",
            "Sıkışmış bir bilgisayar programına doğru ekran bilgisi göndermek gibi, ayna beyne 'el açılıyor' görüntüsü verir. Bazı hastalarda ağrı şaşırtıcı hızla azalır.",
            "Ayna tedavisi herkeste aynı sonucu vermez ve mucize diye sunulmamalıdır. Fakat basit aracın güçlü olması, tedavinin mutlaka pahalı cihaz gerektirmediğini gösterir.",
            "Bugün ayna terapisi ve sanal gerçeklik farklı ağrı ve felç rehabilitasyonlarında araştırılır. Ana fikir, beynin beden modelini güvenli geri bildirimle güncellemektir.",
            "mirror-box", "Ayna, kayıp elin hareket ettiği görüntüsünü vererek beynin donmuş beden modelini yeniden öğrenmesine yardım edebilir."),
        chapter("Görmeyen gözün bildiği", "İKİNCİ KISIM · GÖRME",
            "Bazı kortikal körlük hastaları gördüklerini bilinçli olarak söyleyemez ama nesnenin yönünü tahmin edebilir. Körgörü, görsel bilginin bilinçli görme dışında da davranışı yönlendirebildiğini gösterir.",
            "Perdenin arkasındaki kişi topun geldiğini görmediğini söyler ama doğru anda eğilir. Bilgi sisteme girmiş, yalnız 'ben gördüm' raporuna ulaşmamıştır.",
            "Görme tek kamera akışı değildir. Nesne tanıma, hareket, yönelim ve bilinçli farkındalık kısmen farklı yollar kullanır. Bir yol hasar gördüğünde diğerinin izi kalabilir.",
            "Bu durum sezgimize meydan okur: Beynin bildiği şey ile kişinin bildiğini bildiği şey aynı olmayabilir. Bilinç, tüm işlemenin ekranı değil seçilmiş bölümüdür.",
            "blindsight-paths", "Görsel bilgi bilinçli görüntüye dönüşmeden de bedenin doğru yöne tepki vermesini sağlayabilir."),
        chapter("Kendi felcini inkâr eden zihin", "İKİNCİ KISIM · İNKÂR",
            "Anosognozi yaşayan bazı hastalar felçli kollarını hareket ettirebildiklerini söyler. Kanıt gözlerinin önünde olsa da beyin beden durumunu güncellemez; inkâr bilinçli yalan değildir.",
            "Arabanın yakıt göstergesi bozulmuşken sürücü motorun durduğuna rağmen deponun dolu olduğuna inanabilir. Sorun isteksizlik değil, iç model ile düzeltme sinyalinin kopmasıdır.",
            "Ramachandran sağ ve sol yarıkürelerin yenilikle başa çıkma biçimleri üzerine cesur yorumlar yapar; bu açıklamaların bir kısmı daha sonra fazla basit bulunmuştur. Vakanın kendisi ise benlik bilgisinin kırılabilirliğini güçlü biçimde gösterir.",
            "Hastaya 'gerçeği kabul et' demek yetmeyebilir. Rehabilitasyon, beynin hatayı güvenli biçimde fark etmesini sağlayacak yöntemler ister.",
            "denied-paralysis", "Felç inkârı, benlik bilgisinin doğrudan gerçeklik değil beynin sürekli güncellemesi gereken bir model olduğunu gösterir."),
        chapter("Beden bana mı ait?", "İKİNCİ KISIM · BEDEN SAHİPLİĞİ",
            "Beyin görme, dokunma, eklem duyusu ve hareket komutlarını birleştirerek 'bu beden benim' hissini kurar. Bu kaynaklar çatıştığında bir uzuv yabancı gelebilir veya sahte bir el bedenin parçası sanılabilir.",
            "Masanın üstündeki lastik el ile gizli gerçek el aynı anda fırçalanırsa bir süre sonra lastik ele vurulunca irkilebilirsiniz. Zihin sahipliği yalnız etiketle değil eşzamanlı sinyallerle hesaplar.",
            "Benlik duygusunun kuruluyor olması onun sahte olduğu anlamına gelmez. Köprü de parçalarla kurulur ama gerçektir. Önemli olan deneyimin değişmez bir çekirdek değil, çalışan bütünleştirme olduğudur.",
            "Sanal gerçeklik, protez tasarımı ve beden algısı bozukluklarında bu birleştirme kuralları doğrudan kullanılmaktadır.",
            "rubber-hand", "Eşzamanlı görme ve dokunma, sahte bir eli geçici olarak bedenin parçası gibi hissettirebilir."),
        chapter("Yarım dünyanın kaybolması", "ÜÇÜNCÜ KISIM · DİKKAT",
            "İhmal sendromunda kişi görme alanının sol tarafını gözleri sağlam olsa bile fark etmeyebilir. Tabağın yalnız sağ yarısını yer, saatin rakamlarını sağa yığar; sorun gözde değil dikkatin dünya haritasındadır.",
            "Bir sahnenin sol yarısının görünmez perdeyle örtülmesi gibi düşünmeyin; hasta çoğu zaman eksikliği de fark etmez. Onun deneyiminde dünya yarım görünmüyor, dünya zaten o kadardır.",
            "Bu durum algının yalnız gelen ışık olmadığını gösterir. Dikkat hangi bilginin zihinsel sahneye gireceğini seçer; seçilmeyen parça yokmuş gibi davranılabilir.",
            "Gündelik dikkatsizlik aynı hastalık değildir ama ortak dersi taşır: Görüş alanımızda bulunmak, gerçekten fark ettiğimiz anlamına gelmez.",
            "half-world-clock", "İhmal sendromunda göz değil, dikkatin dünya haritası yarım çalışır; eksiklik çoğu zaman fark edilmez."),
        chapter("Capgras: tanıdık yüz, yabancı duygu", "ÜÇÜNCÜ KISIM · TANIMA",
            "Capgras sanrısında kişi annesinin yüzünü tanır ama onun sahtekâr bir kopya olduğuna inanır. Yüz tanıma yolu çalışırken tanıdıklığa eşlik eden duygusal tepki kopmuş olabilir.",
            "Telefonunuzda annenizin fotoğrafı açılıyor ama normalde gelen sıcaklık hissi yok. Zihin bu tuhaf boşluğu 'demek ki bu gerçek annem değil' hikâyesiyle açıklamaya çalışabilir.",
            "Ramachandran'ın bağlantı kopması modeli etkileyicidir; her Capgras vakasını tek mekanizma açıklamayabilir. Sanrılar daha geniş psikiyatrik ve nörolojik etkenler taşır.",
            "Yine de tanımanın iki katmanını gösterir: Bir yüzün kim olduğunu bilmek ile o yüzün tanıdık geldiğini hissetmek aynı işlem değildir.",
            "capgras-double", "Yüz tanıma ile tanıdıklık duygusu ayrıldığında zihin, sevilen kişinin kopyayla değiştirildiği hikâyesini kurabilir."),
        chapter("Telefon neden sanrıyı değiştirebilir?", "ÜÇÜNCÜ KISIM · TANIMA",
            "Bazı Capgras hastaları kişiyi yüz yüze sahte sayarken telefondaki sesini gerçek kabul eder. Görsel tanıma ile duygusal bağlantı bozuk, işitsel yol sağlam olabilir.",
            "Aynı eve iki ayrı kapıdan girdiğinizi düşünün. Ön kapının zil hattı kopuk, arka kapı çalışıyor. Kişi aynı kişi olsa da beynin giriş yolu farklı duygu sonucu üretir.",
            "Bu küçük ayrıntı genel teoriyi sınamak için değerlidir. Bilimsel açıklama yalnız vakanın tuhaflığını anlatmamalı, hangi durumda değişeceğini de öngörmelidir.",
            "Bugün çoklu duyulu kimlik ve deepfake tartışmalarında aynı soru büyür: Birine gerçeklik hissi veren yalnız görüntü değil, ses, bağlam ve geçmiş uyumudur.",
            "two-doors-identity", "Görsel ve işitsel tanıma yolları farklı çalışınca aynı kişi yüz yüze sahte, telefonda gerçek hissedilebilir."),
        chapter("Gülmenin sinirsel bilmecesi", "DÖRDÜNCÜ KISIM · DUYGU",
            "Gülme yalnız neşe değildir; belirsizlik çözülünce, tehdit sahte çıkınca veya toplumsal gerginlik boşalınca ortaya çıkabilir. Ramachandran mizahı ani model düzeltmesiyle ilişkilendirir.",
            "Karanlıkta yılan sandığınız şeyin hortum çıkmasıyla gülmeniz, bedenin 'tehlike yok' işareti vermesidir. Şaka da ciddi görünen yolun beklenmedik biçimde güvenli çıkmasıyla benzer rahatlama yaratabilir.",
            "Her mizah bu tek formüle sığmaz; kültür, dil ve güç ilişkileri önemlidir. Açıklama ilginç bir mercek, evrensel yasa değildir.",
            "Yine de gülmenin düşünceden ayrı süs olmadığını gösterir. Mizah, beynin beklentiyi kurup bozma biçimine açılan küçük penceredir.",
            "snake-to-hose", "Tehdit sandığımız görüntünün zararsız çıkması, gülmeyi bir güvenlik ve model düzeltme işaretine dönüştürebilir."),
        chapter("Sanatın abartı düğmesi", "DÖRDÜNCÜ KISIM · SANAT",
            "Ramachandran sanatın bazı etkilerini 'tepe kaydırma' ile açıklar: Beyin önemli özelliğe tepki veriyorsa sanatçı o özelliği abartarak daha güçlü etki yaratabilir.",
            "Karikatüristin burnu biraz büyütmesi, fotoğraftan daha tanınır bir yüz üretebilir. Çünkü çizim kimlik için ayırt edici işareti yoğunlaştırır.",
            "Sanatı birkaç sinir kuralına indirgemek eleştirilmiştir. Tarih, anlam, teknik ve toplumsal bağlam olmadan estetik deneyim eksik kalır. Beyin ilkesi resmin bütün hikâyesi değildir.",
            "Yine de reklam, ikon ve arayüz tasarımında belirgin özelliği büyütmenin neden işe yaradığını anlamaya yarayan sezgisel bir araç sunar.",
            "caricature-peak", "Sanatçı ayırt edici özelliği abartarak beynin tanıma ve dikkat tepkisini gerçek görüntüden daha güçlü tetikleyebilir."),
        chapter("Ayna nöronların cazibesi", "DÖRDÜNCÜ KISIM · BAŞKALARI",
            "Bir başkasının eylemini izlerken kendi hareket sistemimizin bazı bölümleri etkinleşir. Ayna nöronlar taklit, niyet ve empati için heyecan verici bir araştırma alanı doğurdu.",
            "Birinin limon ısırdığını görünce ağzınızın sulanması veya esneyeni görünce esnemeniz, başkasının bedenini kendi sisteminizle yankılamanın gündelik izleri gibidir.",
            "Popüler anlatı ayna nöronları medeniyetin tek sırrı ilan etti. Bilimsel tablo daha temkinlidir; empati ve dil geniş ağlar, gelişim ve kültür gerektirir. Tek hücre sınıfı insanlığı açıklamaz.",
            "Kalıcı ders şudur: Başkasını anlamak yalnız dışarıdan hesap yapmak değil, kendi beden sistemlerimizi kullanarak içten bir benzetim kurmak da olabilir.",
            "mirror-neuron-echo", "Başkalarının eylemi, kendi hareket sistemimizde sessiz bir yankı yaratarak anlamaya katkı verebilir."),
        chapter("Beyin haritası sabit değil", "BEŞİNCİ KISIM · PLASTİKLİK",
            "Hayalet uzuv, yüz-el yeniden örgütlenmesi ve rehabilitasyon örnekleri beynin yetişkinlikte de değişebildiğini gösterir. Kullanım, hasar ve eğitim sinir haritalarını yeniden biçimlendirir.",
            "Şehirde kapanan yol trafiği yan sokaklara taşır; zamanla yeni ana güzergâh oluşur. Beyin de hasardan sonra alternatif yolları güçlendirebilir, fakat trafik her zaman sorunsuz akmaz.",
            "Plastiklik sınırsız mucize değildir. Hasarın yeri, yaşı, eğitim yoğunluğu ve sağlık koşulları sonucu belirler. 'İstersen beynini tamamen değiştirirsin' sloganı hastaya haksız yük bindirir.",
            "En iyi yaklaşım umut ile sınırı birlikte taşır: Sinir sistemi değişebilir, bu değişim hedefli pratik ve uygun destek ister.",
            "brain-detour", "Beyin kapanan yolun çevresinde yeni güzergâhlar kurabilir; plastiklik gerçek ama sınırsız değildir."),
        chapter("Benlik tek bir merkez mi?", "BEŞİNCİ KISIM · BENLİK",
            "Kitaptaki vakalar benliği beynin ortasında oturan tek yönetici olmaktan çıkarır. Beden sahipliği, hafıza, tanıma, duygu ve farkındalık farklı süreçlerin uyumundan doğar.",
            "Bir şirketin tek patron fotoğrafı olsa da işleyiş muhasebe, üretim, iletişim ve arşivin birlikte çalışmasına bağlıdır. Benlik de tek odadan değil koordinasyondan doğan bütünlük olabilir.",
            "Parçalardan oluşmak değersiz veya sahte olmak demek değildir. Müzik ayrı notaların uyumuyla gerçektir. Benliğin kırılabilirliği de yaşamın önemini azaltmaz.",
            "Bu düşünce tartışmalarda alçakgönüllülük sağlar: Kendi algımızı doğrudan gerçeklik sanmak yerine, beynin yararlı ama düzeltilebilir modeli sayabiliriz.",
            "self-orchestra", "Benlik tek bir kumanda odası değil, beden ve dünya hakkındaki birçok sürecin uyumundan doğan orkestradır."),
        chapter("Basit deney, büyük fikir", "BEŞİNCİ KISIM · BİLİM",
            "Kitabın ruhu pahalı teknolojiye karşı olmak değil, doğru sorunun değerini hatırlatmaktır. Pamuklu çubuk, ayna ve birkaç dikkatli karşılaştırma beynin büyük kuramlarına kapı açabilir.",
            "Evdeki su kaçağını bulmak için önce hangi musluk açılınca damlanın arttığına bakarsınız. Ölçü aleti sonra gelir. İyi deney, seçenekleri birbirinden ayıran küçük düzenektir.",
            "Vaka anlatılarının tiyatral çekiciliği bazen aşırı genellemeye yol açabilir. Tek hastadan evrensel sonuç çıkarmadan, gözlemi yeniden üretmek gerekir.",
            "Bilim okuryazarlığı için güzel ölçü şudur: İddia yalnız şaşırtıcı mı, yoksa yanlış çıkabileceği açık bir test de öneriyor mu?",
            "mirror-and-swab", "Ayna ve pamuklu çubuk gibi basit araçlar, doğru karşılaştırmayla beynin büyük sorularını sınayabilir."),
    ],
    misreading="Hastaların deneyimleri 'hayal' değildir. Hayalet ağrı, Capgras duygusu veya ihmal, beynin bozulmuş ama gerçek işleyişinden doğar. Bir başka yanlış okuma da tek vakanın bütün insan zihnini kanıtladığını sanmaktır.",
    modern="Beyin görüntüleme, ağ analizi ve daha büyük hasta çalışmalarının ilerlemesi kitaptaki bazı cesur açıklamaları düzeltti. Ayna nöronlara yüklenen büyük iddialar özellikle sınırlandı; ayna kutusu ve beden haritası fikirleri ise rehabilitasyon araştırmalarında yaşamayı sürdürüyor.",
    questions="Gördüğüm şey ile fark ettiğim şey aynı mı? Bedenime ve yakınlarıma aitlik hissi hangi duyusal işaretlerle kuruluyor? Tuhaf bir hatayı küçümsemek yerine, sistemin normalde nasıl çalıştığını ondan öğrenebilir miyim?",
    essence="Beyin gerçekliği pasifçe kaydetmez; beden, tanıdıklık ve benlik için sürekli bir model kurar, sıra dışı nörolojik vakalar da bu modelin gizli dikişlerini görünür kılar.",
))


MORE_BOOKS.append(make_book(
    66, "devlet", "Devlet", "Platon",
    "Adalet nedir sorusunu bir insanın ruhundan ideal şehrin sınıflarına, eğitimden iktidara ve mağaranın gölgelerinden filozofun dönüşüne taşıyan; büyüleyici olduğu kadar tehlikeli siyasi sonuçlar da barındıran klasik diyalog.",
    "#5F5547", "Politeia / Republic",
    [
        {"id": 1, "title": "Perseus Digital Library - Plato, Republic", "url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.01.0168"},
        {"id": 2, "title": "Stanford Encyclopedia of Philosophy - Plato's Ethics and Politics", "url": "https://plato.stanford.edu/entries/plato-ethics-politics/"},
        {"id": 3, "title": "Internet Encyclopedia of Philosophy - Plato's Republic", "url": "https://iep.utm.edu/republic/"},
    ],
    [
        chapter("Bir yaşlı adamın sakin hesabı", "BİRİNCİ KİTAP · ADALET",
            "Diyalog yaşlı Kephalos'un evinde başlar. Yaşlılık ona göre arzuların gürültüsünün azaldığı, fakat yapılan haksızlıkların hesabının daha çok düşünüldüğü dönemdir. Para, iyi insanın borcunu ödeyip huzur bulmasına yardım edebilir.",
            "Gece uyumadan önce kime ne borçlu olduğunuzu düşündüğünüzü hayal edin. Maddi rahatlık kaygıyı azaltabilir, ama dürüstlük yoksa para yalnız daha büyük hata imkânı verir.",
            "Sokrates 'adalet doğruyu söylemek ve borcu ödemek midir?' diye sorar. Silahını delirmiş arkadaşına geri vermek sözleşmeye uygun, sonuç bakımından tehlikelidir. Kural bağlamdan bağımsız yetmez.",
            "İlk bölüm kitabın yöntemini kurar: Tanıdık tanımı küçük karşı örnekle sınamak. Adalet slogan değil, zor durumda çalışması gereken ölçüdür.",
            "old-man-debt", "Adaletin basit borç ödeme kuralı, silahını isteyen tehlikeli arkadaş örneğinde çatlar."),
        chapter("Dosta iyilik, düşmana kötülük mü?", "BİRİNCİ KİTAP · ADALET",
            "Polemarchos adaleti dosta iyilik, düşmana zarar vermek diye tanımlar. Sokrates dost sandığımız kişinin kötü, düşman sandığımızın iyi olabileceğini; ayrıca zarar vermenin insanı daha kötü yaptığını söyler.",
            "Mahalle kavgasında kendi grubunun her davranışını savunup karşı tarafa her cezayı uygun görmek kolaydır. Fakat yanlış kişiyi dost seçtiyseniz adalet sadakatin arkasında kaybolur.",
            "Sokrates'in savı tartışmalıdır; tehlikeli kişiyi durdurmakla onu ahlaken bozmak aynı şey değildir. Yine de adaleti grup çıkarına indirgemeye güçlü itirazdır.",
            "Bugünün kutuplaşmasında soru canlıdır: Bir eylemi yapan kişiye göre mi, herkese uygulanabilir ölçüye göre mi değerlendiriyoruz?",
            "friend-enemy-scale", "Dostluk etiketi adalet ölçüsü olursa yanlış dost korunur, doğru düşman haksız yere cezalandırılabilir."),
        chapter("Thrasymakhos masaya vuruyor", "BİRİNCİ KİTAP · GÜÇ",
            "Thrasymakhos adaletin güçlünün çıkarından başka bir şey olmadığını savunur. Yasayı iktidar yapar ve kendi yararına uymayı adalet diye adlandırır. Diyalog bir anda ahlak dersinden iktidar analizine döner.",
            "Oyunun kurallarını aynı zamanda kazanan takım yazıyorsa, faul tanımı onun işine yarayabilir. Thrasymakhos'un kuşkusu, düzenin tarafsız görünümünün arkasındaki çıkarı arar.",
            "Sokrates yöneticinin gerçek sanatının yönetilenin iyiliğini gözetmesi gerektiğini söyler. Doktorluk doktorun değil hastanın yararına çalışır. Fakat kötü yöneticinin niçin gerçek yönetici sayılmayacağı tartışmalı bir kaçıştır.",
            "Bu çatışma bugün de sürer: Hukuk yalnız güç dengesi midir, yoksa gücü yargılayacak bağımsız bir adalet ölçüsü kurulabilir mi?",
            "thrasymachus-table", "Thrasymakhos adalet perdesinin arkasında yasayı yazan gücün çıkarını görür."),
        chapter("Gyges'in görünmez yüzüğü", "İKİNCİ KİTAP · SINAV",
            "Glaukon görünmezlik sağlayan Gyges yüzüğünü anlatır. Yakalanmayacağından emin olan kişi yine de adil kalır mı? Çoğu insanın adaleti sevdiği için değil ceza korkusuyla uyguladığını öne sürer.",
            "İnternette kimliğiniz tamamen gizli ve hiçbir kayıt yoksa aynı dili kullanır mıydınız? Görünmezlik, dış denetim kalkınca karakterin ne yaptığını sınayan modern bir soruya dönüşür.",
            "Sokrates adaletin yalnız itibar değil ruhun düzeni olduğunu kanıtlamaya çalışacaktır. Haksızlık yapan kişi yakalanmasa bile kendi iç yapısını bozar.",
            "Yine de kurum tasarımı için yüzüğün dersi açıktır: İyi niyete güvenmek yetmez; güç kullananı görünür ve hesap verebilir kılmak gerekir.",
            "ring-of-gyges", "Görünmezlik yüzüğü, ceza ve itibar kalktığında adaletin insan için hâlâ değerli olup olmadığını sınar."),
        chapter("Şehir neden büyüyor?", "İKİNCİ KİTAP · ŞEHRİN DOĞUŞU",
            "Sokrates adaleti büyük harflerle görmek için şehir kurar. İnsan tek başına bütün ihtiyaçlarını karşılayamadığı için iş bölümü doğar; çiftçi, dokumacı ve marangoz birbirine bağımlı hale gelir.",
            "Bir apartmanda herkes ekmek, elektrik ve tamiri tek başına üretmeye çalışsa hayat durur. Uzmanlık verimi artırır ama karşılıklı bağımlılığı da büyütür.",
            "Glaukon sade şehri domuzlar şehri diye küçümseyip lüks ister. Lüks ihtiyaçları, toprak talebini ve savaşı getirir. Arzu büyüdükçe siyasi düzen karmaşıklaşır.",
            "Platon'un sahnesi tüketim ile güç arasında bağ kurar: İhtiyaç listesi sonsuz genişlediğinde yalnız bireysel bütçe değil, ortak kaynak ve dış politika da değişir.",
            "city-needs", "İş bölümü şehri kurar; sınırsız lüks arzusu ise toprağı, rekabeti ve savaşı çağırır."),
        chapter("Koruyucuların iki eğitimi", "ÜÇÜNCÜ KİTAP · EĞİTİM",
            "Şehrin koruyucuları hem sert hem yumuşak olmalıdır: Düşmana cesur, yurttaşa ölçülü. Platon bu denge için müzik ve beden eğitimini birlikte düşünür.",
            "Yalnız kas çalıştıran bekçi kaba güce, yalnız şiir dinleyen bekçi eylemsiz duyarlılığa kayabilir. İyi eğitim ritim, hikâye, beden ve alışkanlığı aynı karakterde birleştirir.",
            "Platon eğitimin yalnız bilgi aktarmadığını, duygunun neye sevgi ve tiksinti duyacağını biçimlendirdiğini görür. Bu güçlü sezgi sansür fikrine de kapı açar.",
            "Bugün çocukların izlediği hikâyeler hakkında konuşurken aynı gerilim vardır: Kültür karakteri etkiler, ama tek otoritenin hangi hikâyenin güvenli olduğuna karar vermesi de tehlikelidir.",
            "music-gymnastics", "Platon koruyucunun karakterini müzikle yumuşatıp beden eğitimiyle güçlendirmeyi amaçlar."),
        chapter("Şair neden kapıda kalıyor?", "ÜÇÜNCÜ VE ONUNCU KİTAP · SANAT",
            "Platon taklit sanatının duyguları büyütüp aklı zayıflatabileceğinden korkar. Tanrıları kötü, kahramanları ölçüsüz gösteren şiirler koruyucuların ruhunu yanlış örneklerle eğitebilir.",
            "Sürekli öfke ve intikam hikâyesi izleyen çocuğun dünyayı öyle okumaya başlaması mümkündür. Platon bu etkiden hareketle anlatıyı sıkı denetlemek ister.",
            "Sorun, sanatın yalnız kötü örnek değil empati, eleştiri ve hayal gücü de üretmesidir. Şairi kovmak, iktidarı rahatsız eden sesi susturmanın kolay aracına dönüşebilir.",
            "Medya düzenlemesinde aynı soru sürer: Zarar veren içeriği sınırlarken kimin zevkini ve siyasetini evrensel ölçü diye dayatıyoruz?",
            "poet-at-gate", "Sanatın karakteri etkileyen gücü Platon'u büyüler, fakat bu kaygı şairi şehirden kovacak kadar sertleşir."),
        chapter("Ruhun üç sesi", "DÖRDÜNCÜ KİTAP · RUH",
            "Platon ruhu akıl, öfke-onur ve arzu olmak üzere üç eğilimle düşünür. Adalet, her parçanın uygun işini yapması ve aklın bütünü yönetmesidir.",
            "Sabah koşmak isteyen akıl, yatakta kalmak isteyen arzu ve kendine verdiği sözü tutmak isteyen gurur aynı kişide çekişebilir. İç çatışma, ruhun tek sesli olmadığını düşündürür.",
            "Model modern psikoloji değildir ve aklı her zaman tarafsız kral saymak sorunludur. Akıl arzunun avukatı gibi de çalışabilir. Yine de iç düzen fikri karakter eğitimine güçlü dil verir.",
            "Adil olmak Platon'da yalnız başkasına kural uygulamak değil, insanın kendi güçleri arasında sürdürülebilir denge kurmasıdır.",
            "three-part-soul", "Akıl, onur ve arzu aynı ruhta farklı yönlere çeker; adalet bu güçlerin düzenli uyumudur."),
        chapter("Şehrin üç sınıfı", "DÖRDÜNCÜ KİTAP · DÜZEN",
            "Ruhun üç parçası şehirde yöneticiler, koruyucular ve üreticiler olarak yansıtılır. Adalet herkesin kendi işini yapması ve diğer sınıfın görevine karışmamasıdır.",
            "Orkestrada kemancı davulu, davulcu şefliği aynı anda yapmaya kalkarsa düzen bozulur. Platon toplumsal uyumu uzmanlaşmış rollerin koordinasyonu gibi görür.",
            "Fakat insanı doğuştan tek role yerleştirmek özgürlüğü ve toplumsal hareketliliği kısıtlar. 'Kendi işini yap' sözü iktidarın ayrıcalığını koruyan emre dönüşebilir.",
            "Modern demokratik toplum, uzmanlık ihtiyacı ile herkesin yönetim hakkında söz hakkı arasındaki gerilimi Platon'dan farklı çözer.",
            "city-three-classes", "Platon adaleti sınıfların uyumunda bulur, fakat bu düzen bireyi kalıcı role hapsetme tehlikesi taşır."),
        chapter("Asil yalan ve metal masalı", "ÜÇÜNCÜ KİTAP · KURUCU HİKÂYE",
            "Platon yurttaşlara aynı toprağın çocukları olduklarını ve ruhlarında altın, gümüş ya da tunç bulunduğunu anlatan kurucu bir masal önerir. Amaç sınıfları ortak şehre bağlamaktır.",
            "Bir ülkenin ders kitaplarında herkesin tek büyük ailenin parçası olarak anlatılması dayanışma yaratabilir. Fakat aile hikâyesi eşitsiz görevleri doğal gösteriyorsa sorgulama zorlaşır.",
            "Platon yetenekli çocuğun sınıf değiştirebileceğini söylese de masal yönetilenlere bilinçli yanlış anlatmayı meşrulaştırır. İyi amaçla propaganda arasındaki sınır kırılgandır.",
            "Bugün siyasi mitleri değerlendirirken yalnız birleştirici güce değil, kimin çıkarını görünmez kıldığına da bakmak gerekir.",
            "myth-of-metals", "Metal masalı ortaklık üretirken toplumsal hiyerarşiyi doğanın emri gibi gösterebilir."),
        chapter("Kadın koruyucuların şaşırtıcı kapısı", "BEŞİNCİ KİTAP · KADINLAR",
            "Platon kadınların da uygun yetenekleri varsa koruyucu ve yönetici olabileceğini söyler. Bedensel farklar, aynı işi yapma kapasitesini bütünüyle belirlemez; bu fikir antik bağlamda sarsıcıdır.",
            "Kel erkek ile uzun saçlı erkeğin ayakkabıcılık yapabilmesi gibi, cinsiyet farkı da iş için ilgili yetenek değilse engel sayılmamalıdır. Platon işlevsel ölçü arar.",
            "Yine de kadınları çoğu yerde daha zayıf diye geneller ve özgürlüğü bireysel hak olarak değil devletin iyi koruyucu ihtiyacı için savunur. Eşitlik araçsaldır.",
            "Bölüm klasik metinlerin aynı anda hem zamanının ötesine geçip hem kendi çağının sınırını taşıyabileceğini gösterir.",
            "women-guardians", "Platon kadınlara koruyuculuk kapısını açar, ancak eşitliği bireysel özgürlükten çok devletin ihtiyacıyla savunur."),
        chapter("Aileyi kaldırmak neyi çözer?", "BEŞİNCİ KİTAP · ORTAKLIK",
            "Koruyucu sınıfta özel aile ve mülkiyet kaldırılır. Platon, yöneticilerin çocuk ve servet çıkarı peşinde koşmasını önleyip bütün şehri aile gibi görmesini ister.",
            "Hakemin maçta kendi çocuğu oynuyorsa tarafsızlığı zorlaşır. Platon çıkar çatışmasını kökten kesmek için hakemin aile bağını bile ortadan kaldırır.",
            "Çözüm insan ilişkilerini devlet planına teslim eder; eş seçimi ve çocuk yetiştirme üzerinde ağır denetim kurar. Yolsuzluğu önleme amacı totaliter bir özel hayat müdahalesine dönüşür.",
            "Bugünün dersi aileyi kaldırmak değil, kamu görevlilerinde çıkar çatışmasını şeffaf kurallarla sınırlamaktır. Amaç ile araç arasındaki oran sürekli sınanmalıdır.",
            "common-family", "Özel çıkarı önlemek için aileyi kaldırmak, yolsuzluğa karşı aşırı ve baskıcı bir devlet çözümü üretir."),
        chapter("Filozof kral neden istenir?", "BEŞİNCİ VE ALTINCI KİTAP · YÖNETİM",
            "Platon'a göre şehirler filozoflar yönetmedikçe ya da yöneticiler gerçekten felsefe öğrenmedikçe kötülük bitmez. Çünkü iktidar isteyen kişi çoğu zaman kendi çıkarını, hakikati seven filozof ise bütünün iyiliğini arar.",
            "Gemide yolcular dümeni ele geçirmek için kavga ederken yıldızları ve rüzgârı bilen kaptanı işe yaramaz sayabilir. Devlet gemisi benzetmesi uzmanlık ile popüler çekişme arasındaki farkı anlatır.",
            "Sorun, kimin gerçek filozof olduğuna kimin karar vereceğidir. Bilgili yönetici denetlenmezse kendi yanılmazlığına inanabilir. Uzmanlık, hesap verebilirliğin yerine geçmez.",
            "Modern çözüm tek bilge kral değil; uzman bilgiyi seçim, hukuk, özgür basın ve güçler ayrılığıyla dengeleyen kurumlar kurmaktır.",
            "ship-and-philosopher", "Devlet gemisi bilgiye ihtiyaç duyar, fakat kaptanın bilgisini denetleyecek ortak kurallar da gerekir."),
        chapter("İyi ideasının güneşi", "ALTINCI KİTAP · BİLGİ",
            "Platon güneşi görünen şeyleri aydınlatan kaynak, İyi ideasını ise bilginin ve varlığın anlaşılmasını sağlayan en yüksek ilke olarak düşünür. İyi yalnız bir nesne değil, diğer değerleri ölçen ışıktır.",
            "Karanlık odada eşyalar vardır ama seçilemez; ışık gelince biçimler görünür. Platon'a göre zihin de tek tek doğruların ötesinde neyin neden değerli olduğunu görecek ölçüye ihtiyaç duyar.",
            "Kavram yücedir ama belirsizdir. İyiyi bildiğini söyleyen yönetici, eleştiriyi karanlıkta kalmakla suçlayabilir. Metafizik ölçü siyasi güvence sağlamaz.",
            "Gündelik hayatta ise yararlı soru bırakır: Başarı, hız ve kazancı hangi daha yüksek ölçüyle değerlendiriyoruz? Ölçüsüz veri karar vermez.",
            "sun-of-good", "Güneş göz için neyse İyi ideası da zihin için odur: Şeyleri ve değerlerini görünür kılan ölçü."),
        chapter("Mağaranın gölgeleri", "YEDİNCİ KİTAP · MAĞARA",
            "Mahkûmlar çocukluktan beri mağarada zincirlenmiş, duvardaki gölgeleri gerçek sanmıştır. Biri çözülüp dışarı çıktığında ışık önce acı verir; sonra gölgelerin kaynağını ve güneşi görür.",
            "Yalnız kısa videolarla dünyayı tanıyan birinin kameranın arkasındaki seçimi, kesmeyi ve çıkarı hiç görmediğini düşünün. Ekrandaki akış mağara duvarı olabilir.",
            "Aydınlanan kişinin geri dönmesi gerekir; bilgi kişisel kaçış değil ortak sorumluluktur. Fakat mahkûmlar alıştıkları gerçekliği bozan kişiye öfkelenebilir.",
            "Benzetme güçlüdür ama tehlikesi vardır: Kendini dışarı çıkmış sayan kişi herkesi cahil görebilir. Gerçek aydınlanma, eleştiriden muafiyet değil daha fazla alçakgönüllülük istemelidir.",
            "cave-shadows", "Mağara gölgeleri, alışkanlık ve düzen tarafından gerçek sanılan sınırlı görüntüleri temsil eder."),
        chapter("Rejimlerin aşağı doğru merdiveni", "SEKİZİNCİ KİTAP · REJİMLER",
            "Platon ideal yönetimden timokrasiye, oligarşiye, demokrasiye ve tiranlığa doğru bozulma sırası çizer. Her rejim ruhun bir arzusunu büyütür: onur, para, sınırsız özgürlük ve sonunda tek kişinin tutkusu.",
            "Evde hiçbir kuralı kabul etmeyen özgürlük, en güçlü kişinin diğerlerini susturduğu düzene dönebilir. Platon demokrasinin sınır tanımaz arzularından tiranın doğduğunu düşünür.",
            "Demokrasi eleştirisi elitist ve tek yanlıdır; eşit yurttaşlık, barışçıl iktidar değişimi ve denetim imkânlarını küçümser. Antik Atina deneyimi modern anayasal demokrasiyle aynı değildir.",
            "Yine de demagogun özgürlük diliyle yükselip kurumları içeriden yıkması konusunda rahatsız edici bir uyarı taşır. Demokrasi yalnız seçim değil, kural ve özdenetim ister.",
            "regime-staircase", "Platon sınırsız arzunun demagogu, demagogun da tiranı besleyebileceğini anlatan karanlık bir rejim merdiveni çizer."),
    ],
    misreading="Devlet yalnız uygulanacak ideal anayasa değildir; adalet, ruh ve eğitim üzerine kurulmuş bir düşünce deneyidir. Fakat baskıcı sonuçları 'sadece mecaz' diyerek silmek de yanlıştır: Sansür, seçkin yönetim ve özel hayat denetimi metinde gerçek siyasi öneriler olarak bulunur.",
    modern="Modern demokrasi, bireysel haklar ve çoğulculuk Platon'un şehrinden farklı ilkeler kurdu. Yine de propaganda, uzmanlık, çıkar çatışması, eğitim ve demagog soruları güncelliğini koruyor. Kitap hem güçlü soru kaynağı hem otoriter çözüm tehlikesi olarak okunmalıdır.",
    questions="Bir kural herkes için mi, yalnız benim grubum için mi adil? Beni yöneten uzman hangi denetime tabi? Gördüğüm şey gerçekliğin kendisi mi, yoksa biri tarafından seçilip duvara yansıtılmış bir gölge mi?",
    essence="Adalet yalnız dışarıdaki yasa değil insanın ve şehrin iç düzenidir; fakat düzeni tek bir bilge sınıfa teslim etmek, iyilik arayışını özgürlüğü boğan bir iktidara çevirebilir.",
))
