#!/usr/bin/env python3
"""Build books 12, 17, 32, 41 and 66 for the second twenty-book series."""

from summary_batch_second_common import chapter, make_book, write_books


BOOKS = []


BOOKS.append(make_book(
    12, "tufek-mikrop-ve-celik", "Tüfek, Mikrop ve Çelik", "Jared Diamond",
    "Bazı toplumların başka toplumları fethetmesini insanların zekâsına ya da değerine değil; coğrafya, evcilleştirilebilir canlılar, hastalıklar ve kıtalar boyunca yayılan bilgi zincirlerine bağlayan büyük tarih anlatısı.",
    "#5E5947", "Guns, Germs, and Steel",
    [
        {"id": 1, "title": "Jared Diamond - Guns, Germs, and Steel", "url": "https://www.jareddiamond.org/guns-germs-and-steel"},
        {"id": 2, "title": "W. W. Norton - Guns, Germs, and Steel", "url": "https://wwnorton.com/books/Guns-Germs-and-Steel/"},
        {"id": 3, "title": "Encyclopaedia Britannica - Neolithic Revolution", "url": "https://www.britannica.com/event/Neolithic-Revolution"},
        {"id": 4, "title": "Our World in Data - Crop yields and agriculture", "url": "https://ourworldindata.org/crop-yields"},
    ],
    [
        chapter("Yali'nin tek cümlelik büyük sorusu", "BAŞLANGIÇ · SORU",
            "Diamond'ın yolculuğu Yeni Gine'de siyasetçi Yali'nin sorduğu sade ama sarsıcı soruyla başlar: Neden Avrupalıların bu kadar çok eşyası vardı da Yeni Ginelilerin yoktu? Kitap, bu farkı insanların doğuştan yetenekleriyle açıklamayı reddeder.",
            "Aynı sınıftaki iki çocuğu düşünün. Birinin kütüphanesi, bilgisayarı ve sakin çalışma odası; diğerinin ise sürekli kesilen elektriği olsun. Sonuç farkını yalnız çocuğun zekâsına bağlamak nasıl haksızsa, kıtaların tarihini de yalnız halkların karakteriyle açıklamak öyledir.",
            "Soru fetih yapanları aklamak için sorulmaz. Amaç güç farkının nasıl biriktiğini anlamaktır. Ahlaki sorumluluk ile tarihsel neden aynı şey değildir; bir olayın nedenini açıklamak onun adil olduğunu söylemez.",
            "Bugün ülkeler arasındaki uçurumu konuşurken kitap ilk freni koyar: İnsan topluluklarını tembel, çalışkan, üstün ya da geri diye etiketlemeden önce başlangıç koşullarını ve yüzyıllar boyunca büyüyen avantajları incele.",
            "yali-question", "Yali'nin sorusu insan değerini değil, tarih boyunca biriken maddi farkların kaynağını araştırır."),
        chapter("Avcı toplayıcının yanlış portresi", "BİRİNCİ KISIM · BAŞLANGIÇ ÇİZGİSİ",
            "Tarım öncesi toplumlar boş boş dolaşan ilkel kalabalıklar değildi. Bitkileri, hayvanları, mevsimleri ve arazinin küçük işaretlerini ayrıntılı biçimde biliyorlardı. Fakat yiyecek üretmeyen yaşam, aynı yerde çok büyük nüfusları beslemeyi zorlaştırıyordu.",
            "Bir manavdan yüzlerce çeşit ürünü bir saatte almakla ormanda aynı kaloriyi tek tek bulmak arasındaki farkı düşünün. Avcı toplayıcının bilgisi derindir; ancak depolama, nüfus yoğunluğu ve sürekli uzmanlaşma için gereken fazla ürün daha sınırlıdır.",
            "Diamond tarımı otomatik mutluluk gibi sunmaz. Yerleşik hayat salgın, eşitsizlik ve daha ağır emek getirebilir. Tarihsel avantaj ile bireysel refah aynı değildir; çiftçi devlet kurmaya daha elverişli olabilir ama daha sağlıklı yaşamayabilir.",
            "Bu ayrım ilerleme kelimesine dikkat etmeyi öğretir. Bir düzenin daha çok asker ve yönetici beslemesi, o düzende yaşayan herkesin daha iyi yaşadığı anlamına gelmez.",
            "forager-landscape", "Avcı toplayıcı yaşam bilgisiz değil; düşük nüfus ve sınırlı artı ürünle çalışan farklı bir düzendir."),
        chapter("Bereketli Hilal neden erken başladı?", "BİRİNCİ KISIM · YİYECEK ÜRETİMİ",
            "Bereketli Hilal'de yabani buğday, arpa ve baklagiller gibi toplanması, saklanması ve seçilmesi görece kolay bitkiler bir aradaydı. Mevsimsel iklim, büyük taneli yıllık bitkileri destekledi; erken tarım için hazır bir malzeme kutusu oluştu.",
            "Bir marangozun önüne kuru, düz ve kolay kesilen tahtalar; diğerinin önüne ise eğri, ıslak dallar koyun. İkisi de becerikli olabilir ama ilk dolabı aynı hızda yapamaz. Diamond'ın coğrafya vurgusu böyle bir malzeme farkına dayanır.",
            "Tarım tek kişinin bir sabah aldığı karar değildi. İnsanlar önce yabani türleri topladı, sonra en iri tohumları çevrelerine taşıdı; fark etmeden bitkilerin genetik yapısını değiştiren uzun bir seçim süreci başladı.",
            "Bugünün marketindeki tek tip ürünler bu eski seçimin devamıdır. Kitap, sofradaki ekmeği insan emeği kadar bitkinin biyolojik özellikleri ve bölgenin iklimiyle birlikte görmemizi sağlar.",
            "fertile-crescent", "Bereketli Hilal'in erken tarımı, uygun yabani bitkiler ile mevsimsel iklimin aynı yerde buluşmasından güç aldı."),
        chapter("Evcilleştirilemeyen zebranın dersi", "BİRİNCİ KISIM · HAYVANLAR",
            "Büyük memelilerin hepsi evcilleştirilemez. Hızlı büyüme, esaret altında üreme, uygun beslenme, sürü hiyerarşisi ve paniğe kapılmama gibi özelliklerin aynı hayvanda buluşması gerekir. At oldu; zebra olmadı.",
            "Bir şirketin parlak ama kimseyle çalışamayan yıldızı ile uyumlu ekip oyuncusunu düşünün. Tek özellik yetmez. Zebra güçlüdür ama ısırır, ürker ve kontrol edilmesi zordur; sığır ise insan düzenine uyabilen toplumsal bir yapıya sahiptir.",
            "Diamond Avrasya'nın bu bakımdan şanslı olduğunu savunur. Koyun, keçi, sığır, domuz ve at; et, süt, gübre, taşıma ve savaş gücü sağladı. Bu paket başka kıtalarda aynı zenginlikte bulunmadı.",
            "Buradaki sonuç insanların denemediği değildir. Bir türün binlerce yıl evcilleştirilmemiş olması çoğu zaman yerli halkın bilgisizliğini değil, hayvanın uygun olmayan biyolojisini gösterir.",
            "zebra-horse", "At ile zebra arasındaki fark insan zekâsından çok, hayvanların davranış ve üreme özelliklerinde yatar."),
        chapter("Artı ürünün kurduğu görünmez merdiven", "İKİNCİ KISIM · FAZLALIKTAN DEVLETE",
            "Tarım her ailenin yiyeceğini üretirken bir miktar fazlalık yaratınca, herkesin tarlada çalışması gerekmedi. Asker, zanaatkâr, kâtip, yönetici ve rahip gibi uzmanlaşmış gruplar beslenebilir hale geldi.",
            "On kişinin yalnız kendine yetecek kadar yemek yaptığı sofrada tam zamanlı bir demirci yaşayamaz. Herkes bir tabak fazla üretirse bir kişi bütün gün alet yapabilir. Küçük fazlalıklar, toplum ölçeğinde büyük iş bölümüne dönüşür.",
            "Fazlalık aynı zamanda eşitsizlik için kapı açar. Depoyu kimin yönettiği, verginin kimden toplandığı ve askerlerin kime bağlı olduğu güç ilişkilerini belirler. Devlet yalnız ortak ihtiyaç değil, kaynak denetimi de demektir.",
            "Bugün uzmanlık doğal görünür; fakat arkasında milyonlarca insanın yiyecek, enerji ve lojistik üretimi vardır. Kitap bir yazılımcının masasını bile tarladaki verim zincirine bağlar.",
            "surplus-stair", "Depolanabilir artı ürün, uzmanlaşmayı mümkün kılarken yönetim ve eşitsizlik merdivenini de kurdu."),
        chapter("Mikroplar ordudan önce yürüdü", "İKİNCİ KISIM · HASTALIK",
            "Yoğun nüfus, yerleşik yaşam ve evcil hayvanlarla yakın temas yeni salgınlara zemin hazırladı. Çiçek ve kızamık gibi hastalıklar büyük topluluklarda dolaşarak kalıcı hale geldi; hayatta kalan nüfuslarda kısmi bağışıklık birikti.",
            "Kalabalık bir okulda yayılan gribi düşünün. Hastalık her yıl yeni öğrencilere ulaşabilir. On kişilik izole bir adada ise herkesi hasta ettikten sonra taşıyıcı bulamayarak kaybolur. Salgının sürekliliği için nüfus büyüklüğü gerekir.",
            "Avrupalılar Amerika'ya ulaştığında mikroplar çoğu zaman silahlardan daha yıkıcı oldu. Yerli toplumların daha az değerli bedenleri yoktu; yalnızca bu özel hastalık geçmişine sahip değillerdi.",
            "Salgın deneyimi bize bağışıklığı kişisel kahramanlık gibi görmemeyi öğretir. Hastalık riski, uzun tarih, nüfus yapısı, hayvan teması ve sağlık kurumlarıyla birlikte oluşur.",
            "germs-before-army", "Fetih gemilerinden çıkan mikroplar, bağışıklığı olmayan toplumlarda ordulardan daha hızlı ilerledi."),
        chapter("Yazının hafıza deposu", "İKİNCİ KISIM · BİLGİ",
            "Yazı vergi, ürün, yasa ve askeri emirlerin insan hafızasından bağımsız saklanmasını sağladı. Büyük devletler, yüz yüze tanışmayan binlerce kişiyi kayıtlar üzerinden yönetebildi.",
            "Küçük bir bakkal on müşterinin borcunu aklında tutabilir; yüz şubeli market zinciri tutamaz. Defter yalnız hatırlatma değildir, ölçeği değiştiren bir teknolojidir. Yazı da devletin uzak mesafeye uzanan sinir sistemi oldu.",
            "Yazı her yerde aynı anda doğmadı ve bir kez doğunca hemen yayılmadı. Toplumun kayıt ihtiyacı, malzeme, uzman kâtipler ve komşulardan alınan örnekler önemliydi. Bilgi teknolojisi kurumlarla birlikte yaşar.",
            "Bugünün veri tabanları aynı ilkeyi büyütür. Kimin kayda geçtiği, hangi bilginin ölçüldüğü ve arşive kimin eriştiği yönetim gücünün merkezindedir.",
            "writing-ledger", "Yazı, devletin ürünleri ve insanları uzak mesafeden izlemesine yarayan büyük bir hafıza deposuydu."),
        chapter("Çelik neden tek başına doğmadı?", "İKİNCİ KISIM · TEKNOLOJİ",
            "Teknolojik icatlar çoğu zaman yalnız dâhinin zihninden çıkmaz. Kalabalık nüfus, uzman ustalar, deneme birikimi, kullanım ihtiyacı ve komşu toplumlarla temas küçük yenilikleri üst üste koyar.",
            "Modern telefonun içinde cam, pil, yazılım, anten ve onlarca ülkenin üretim bilgisi vardır. Tek mucit telefonu sıfırdan yapmadığı gibi, eski çağın kılıcı da maden, fırın, ticaret ve savaş talebinden ayrı düşünülemez.",
            "Diamond teknolojinin zorunlu bir sıra izlemediğini vurgular. Bazen oyuncak gibi görünen icat yüzyıllar sonra işe yarar; bazen güçlü bir toplum verimli yeniliği siyasi nedenlerle reddeder.",
            "Bu bakış yaratıcı bireyi küçültmez, onu besleyen ağı görünür kılar. İnovasyon politikası yalnız parlak fikir aramak değil, fikirlerin denenip paylaşılacağı kurumları kurmaktır.",
            "technology-network", "Çelik ve diğer teknolojiler, tek bir dâhiden çok uzmanlık ve bilgi alışverişi ağında olgunlaştı."),
        chapter("Avrasya'nın yatay otoyolu", "ÜÇÜNCÜ KISIM · KITALAR",
            "Avrasya doğu-batı yönünde uzanır. Aynı enlem boyunca gün uzunluğu ve iklim daha benzer olduğu için bitkiler, hayvanlar ve teknikler geniş mesafelere görece kolay yayıldı. Amerika ve Afrika'nın kuzey-güney ekseni ise sert iklim kuşaklarıyla kesildi.",
            "Aynı katta uzanan uzun bir koridorda eşyayı taşımak kolaydır; merdiven, dar kapı ve farklı sıcaklıktaki odalardan geçirmek zordur. Kıta eksenleri Diamond'ın gözünde böyle bir yayılma koridorudur.",
            "Bu bir mutlak yasa değildir. Dağlar, çöller, denizler ve toplumların kararları doğu-batı yayılmasını da durdurabilir. Coğrafya olasılığı etkiler; her adımı otomatik yazmaz.",
            "Küresel ağlar mesafeyi küçültse de tarım kuşakları, enerji yolları ve limanlar hâlâ önemlidir. Kitabın harita bakışı bugünün tedarik zincirlerinde yaşamaya devam eder.",
            "eurasia-axis", "Avrasya'nın doğu-batı ekseni benzer iklimler arasında ürün ve fikirlerin yayılmasını kolaylaştırdı."),
        chapter("Çin neden birleşti, Avrupa neden parçalı kaldı?", "ÜÇÜNCÜ KISIM · SİYASİ COĞRAFYA",
            "Diamond Çin'in büyük nehir ovaları ve daha az kesintili coğrafyasının siyasi birleşmeyi kolaylaştırdığını; Avrupa'nın dağ, yarımada ve adalarının kalıcı rekabetçi devletlere alan açtığını ileri sürer.",
            "Tek bir büyük şirkette patron kötü bir kararla bütün araştırmayı durdurabilir. Birbirine rakip on şirkette ise biri vazgeçse diğeri deneyebilir. Avrupa'nın parçalanmışlığı bazı yeniliklerin kaçacak başka kapı bulmasına yardım etmiş olabilir.",
            "Aynı parçalanmışlık savaşları da çoğalttı; Çin'in birliği ise büyük sulama ve yönetim kapasitesi sağladı. Coğrafi yapı iyi ya da kötü değildir, farklı risk ve imkânlar üretir.",
            "Bu tez tarihçiler arasında tartışmalıdır; kültür, kurum ve belirli lider kararları haritanın açıklayamadığı çok şeyi belirler. Yine de siyasi sınırların yalnız fikirlerden değil, araziden de beslendiğini hatırlatır.",
            "china-europe-map", "Kesintisiz ovalar birleşmeye, yarımada ve dağlarla bölünmüş coğrafya ise çok sayıda rakip devlete alan açabilir."),
        chapter("İspanyol ile İnka karşılaştığında", "DÖRDÜNCÜ KISIM · FETİH SAHNESİ",
            "Pizarro'nun küçük kuvveti Atahualpa'nın büyük ordusunu şaşırtıcı biçimde yenebildi. Atlar, çelik silahlar, yazılı bilgi, siyasi bölünme ve daha önce yayılan salgınlar aynı anda İspanyolların lehine çalıştı.",
            "Bir futbol maçında rakibin yalnız daha iyi ayakkabısı değil; hakem kurallarını bilmesi, telsiz kullanması ve sizin takımın yarısının hasta olması gibi düşünün. Sonuç tek bir üstünlükten değil, birleşen farklardan çıkar.",
            "Bu açıklama yerli direnişini görünmez yapmamalıdır. Fetih uzun, kanlı ve belirsizdi; Avrupalılar yerli müttefikler olmadan birçok yerde ilerleyemezdi. Kitabın geniş kamerası yerel karmaşıklığı bazen fazla küçültür.",
            "Bugün güçlü görünen bir kurumun başarısını tek özelliğe bağlamamak gerekir. Teknoloji, bilgi, sağlık, ittifak ve zamanlama çoğu kez aynı tabloda birleşir.",
            "pizarro-atahualpa", "Cajamarca'daki güç farkı at, çelik, salgın, yazı ve siyasi koşulların tek sahnede birleşmesiydi."),
        chapter("Afrika'nın tek hikâyesi yok", "DÖRDÜNCÜ KISIM · BÖLGESEL TARİHLER",
            "Afrika kıtası iklim, dil ve toplum bakımından olağanüstü çeşitlidir. Bantu dillerinin ve tarımın yayılması, yerel avcı toplayıcılarla karşılaşmalar ve hayvancılığın hastalık kuşaklarına göre değişmesi tek çizgili bir anlatıyı bozar.",
            "Kuzeyde işe yarayan bir tarım paketini ekvator ormanına, oradan Güney Afrika'nın iklimine taşımak aynı tohumu farklı seralara sokmak gibidir. Kıtanın kuzey-güney uzanışı her geçişte yeni bir engel çıkarır.",
            "Diamond bazı genellemeleri nedeniyle eleştirilir; sömürgecilik öncesi Afrika devletlerinin yaratıcılığı ve bölgesel ayrıntılar daha geniş anlatılabilir. Coğrafi çerçeve yerel tarihlerin yerine geçmemelidir.",
            "En iyi ders, Afrika'yı tek ülke gibi konuşmaktan vazgeçmektir. Harita üzerinde aynı renk görünen alanın içinde yüzlerce farklı tarihsel yol bulunur.",
            "africa-climate-bands", "Afrika'nın iklim kuşakları, bitki ve hayvanların kuzeyden güneye yayılmasını defalarca kesti."),
        chapter("Avustralya ve yalnızlığın bedeli", "DÖRDÜNCÜ KISIM · BÖLGESEL TARİHLER",
            "Avustralya uzun süre diğer büyük nüfus merkezlerinden yalıtıldı. Evcilleştirilebilir büyük hayvanların azlığı, değişken iklim ve küçük nüfus; yoğun tarım devletlerinin gelişmesini zorlaştırdı.",
            "On kişilik bir atölye ile on bin kişilik sanayi şehrinin icat havuzu aynı değildir. Küçük topluluk çok yaratıcı olabilir ama daha az uzman ve daha kırılgan bilgi zinciri taşır; bir ustanın ölümü tekniği bütünüyle kaybettirebilir.",
            "Bu anlatı Aborjin toplumlarını durağan saymamalıdır. Ateşle arazi yönetimi, geniş ticaret ağları ve karmaşık akrabalık sistemleri çevreye uyarlanmış yüksek bilgi biçimleridir.",
            "Teknoloji sayısını insan değerinin ölçüsü yapmak kitabın ruhuna aykırıdır. Farklı çevreler farklı becerileri ödüllendirir; metal alet eksikliği zihinsel eksiklik değildir.",
            "australia-isolation", "Yalıtılmış ve küçük nüfuslu Avustralya, farklı bir bilgi ve geçim düzeni geliştirdi."),
        chapter("Polinezya doğal deney gibi", "DÖRDÜNCÜ KISIM · ADALAR",
            "Polinezya adalarına benzer kökenden gelen insanlar yerleşti; fakat ada büyüklüğü, yağış, toprak ve kaynak farkları yüzünden küçük eşitlikçi topluluklardan katmanlı krallıklara kadar çok farklı düzenler kuruldu.",
            "Aynı tohum paketini yirmi farklı bahçeye ekin. Toprağı derin ve suyu bol bahçede yoğun ürün; kayalık ve kuru bahçede seyrek bitki çıkar. İnsan başlangıcı benzerken çevre sonucu ayrıştırabilir.",
            "Adalar kusursuz laboratuvar değildir; yolculuk tarihleri, kültürel tercihler ve rastlantılar da değişir. Yine de çevrenin toplum ölçeği üzerindeki etkisini karşılaştırmak için güçlü bir sahne sunar.",
            "Bugün şehirleri kıyaslarken de yalnız kültürü değil, liman, su, arazi, afet riski ve komşuluk ağlarını görmek gerekir. Yer maddi bir oyuncudur.",
            "polynesian-islands", "Benzer kökenden gelen Polinezyalılar, farklı ada koşullarında çok farklı siyasi yapılar kurdu."),
        chapter("Coğrafya kader mi?", "BEŞİNCİ KISIM · SINIRLAR",
            "Kitabın en büyük itirazı coğrafi determinizm suçlamasıdır. Diamond coğrafyanın her olayı zorunlu kıldığını söylemediğini belirtir; yine de geniş anlatısı bazen insan kararlarını ve kurumları arka plana iter.",
            "Eğimli bir yolda bisiklet sürmek yönü etkiler ama gidonu elinizden almaz. Yokuş bazı seçenekleri pahalı, bazılarını kolay yapar. Coğrafyayı böyle bir eğim olarak görmek kader sözünden daha doğrudur.",
            "Aynı çevrede farklı toplumların farklı kurumlar kurması, haritanın tek başına yetmediğini gösterir. Sömürgecilik, ticaret politikası, sınıf çatışması ve liderlik uzun dönemli eşitsizlikleri yeniden üretir.",
            "Kitap en güçlü olduğunda başlangıç avantajlarını gösterir; en zayıf olduğunda bu avantajların sonraki yüzyıllardaki bütün kararların yerine geçtiği izlenimini verir. İyi okur iki düzeyi birlikte tutar.",
            "sloped-road", "Coğrafya yolun eğimini belirleyebilir; fakat toplumsal kararların gidonunu tamamen elinden almaz."),
        chapter("Fetih açıklaması fetih savunusu değildir", "BEŞİNCİ KISIM · AHLAK",
            "Avrupa'nın avantajlarını çevreyle açıklamak, sömürge şiddetini doğallaştırmak için kullanılabilir; buna karşı dikkat gerekir. Nedensel açıklama, mağdurun acısını azaltmaz ve failin kararlarını masumlaştırmaz.",
            "Bir yangının kuru hava yüzünden hızla yayıldığını söylemek, kibriti atan kişiyi aklamaz. Kuru hava koşulu; kibrit ise eylemdir. Tarihte de yapısal avantaj ile bilinçli şiddet aynı tabloda bulunabilir.",
            "Diamond'ın temel hedefi ırkçı biyolojik açıklamayı yıkmaktır. Yine de yerli halkları yalnız başına gelen felaketlerin alıcısı gibi göstermemek, onların siyaseti ve direnişini anlatmak gerekir.",
            "Bu ayrım güncel eşitsizlik tartışmalarında da işe yarar: Yapının etkisini görmek bireysel sorumluluğu silmez; yalnız sorumluluğun hangi koşullarda kullanıldığını açıklar.",
            "fire-and-match", "Kuru hava yangını açıklar, kibriti atan kişiyi aklamaz; yapı ile sorumluluk birlikte düşünülmelidir."),
    ],
    misreading="Kitap 'Avrupalılar daha zekiydi' demez; tam tersine bu açıklamayı reddeder. Bir başka yanlış okuma da coğrafyanın her sonucu otomatik yazdığıdır. Diamond'ın savı, bazı bölgelerin yiyecek, hayvan, mikrop ve yayılma bakımından daha avantajlı başlangıç koşullarına sahip olduğudur.",
    modern="Arkeogenetik, iklim tarihi ve sömürgecilik araştırmaları kitabın bazı ayrıntılarını genişletti. Bugün kurumların, yerli ittifakların ve bölgesel tarihin ağırlığını daha fazla biliyoruz; yine de çevresel başlangıç farklarının uzun vadeli etkisi temel bir araştırma sorusu olmayı sürdürüyor.",
    questions="Bir güç farkı gördüğünüzde şunları sorun: Başlangıçta hangi kaynak farkı vardı? Avantaj zamanla hangi geri besleme yoluyla büyüdü? Sonucu açıklarken insanların seçimini ve ahlaki sorumluluğunu nerede yeniden tabloya koymalıyım?",
    essence="İnsan toplulukları arasındaki tarihsel güç farklarını doğuştan değer farkıyla değil; coğrafyanın sunduğu canlılar, hastalık geçmişi, bilgi dolaşımı ve yüzyıllarca biriken avantajlarla açıklamak gerekir.",
))


BOOKS.append(make_book(
    17, "evrenin-yapisi", "Evrenin Yapısı", "Lucretius",
    "Doğayı tanrıların kaprisinden kurtarıp atomların, boşluğun ve değişimin dünyasına yerleştiren; ölüm korkusunu evrenin işleyişini anlayarak hafifletmeye çalışan iki bin yıllık şiirsel düşünce yolculuğu.",
    "#6B594D", "De Rerum Natura",
    [
        {"id": 1, "title": "Perseus Digital Library - Lucretius, De Rerum Natura", "url": "https://www.perseus.tufts.edu/hopper/text?doc=Perseus:text:1999.02.0130"},
        {"id": 2, "title": "Stanford Encyclopedia of Philosophy - Epicurus", "url": "https://plato.stanford.edu/entries/epicurus/"},
        {"id": 3, "title": "Internet Encyclopedia of Philosophy - Lucretius", "url": "https://iep.utm.edu/lucretius/"},
    ],
    [
        chapter("Şiirle açılan laboratuvar", "BAŞLANGIÇ · ŞİİR VE DOĞA",
            "Lucretius felsefi düşüncelerini kuru ders biçiminde değil, uzun bir şiir halinde anlatır. Bal sürülmüş ilaç benzetmesi gibi, ritim ve görüntü zor düşünceyi içilebilir kılar; okur atomları yalnız hesapla değil hayal gücüyle de görür.",
            "Bir çocuğa acı şurubu meyve tadıyla vermek, şurubun etkisini değiştirmez ama kabulünü kolaylaştırır. Lucretius için şiirin güzelliği de Epikurosçu doğa görüşünü zihne taşıyan tatlı kenardır.",
            "Bu seçim bilimi süslemekten fazlasıdır. Görünmeyen atomlar, sonsuz boşluk ve çağlar boyunca oluşan dünya ancak güçlü imgelerle düşünülür. Şiir, görünmeyeni canlandıran bir model görevi görür.",
            "Bugünün belgeselleri ve iyi popüler bilim yazıları aynı işi yapar: Karmaşık fikri basitleştirirken ciddiyetini kaybetmeden merak uyandırır.",
            "poetic-laboratory", "Lucretius görünmeyen atomları şiirin ışığıyla görünür kılmaya çalışır."),
        chapter("Hiçten hiçbir şey çıkmaz", "BİRİNCİ KİTAP · MADDE",
            "Şiirin temel ilkesi, hiçbir şeyin hiçten doğmadığı ve hiçbir şeyin bütünüyle yokluğa gitmediğidir. Görünen biçimler çözülür; onları kuran maddi parçalar yeni birleşimlere katılır.",
            "Yanan odun kaybolmuş gibi görünür ama ısıya, dumana, küle ve gazlara dönüşür. Lucretius modern kimyayı bilmiyordu; yine de değişimin arkasında kalıcı maddi öğeler araması doğaüstü açıklamaya güçlü bir alternatiftir.",
            "Atom sözcüğü onun dünyasında deneyle ölçülen modern atomla aynı değildir. Bölünmez, görünmez ilk parçalar felsefi varsayımdır. Yine de korunma ve dönüşüm fikri bilimsel düşünceye benzeyen bir yön taşır.",
            "Gündelik hayatta kayboluş sandığımız birçok şeyin biçim değiştirdiğini fark etmek, hem doğaya hem atığa başka gözle bakmamızı sağlar.",
            "nothing-from-nothing", "Biçimler yok olurken madde yeni düzenlere geçer; doğa boşluktan sihirle kurulmaz."),
        chapter("Boşluk olmadan hareket olmaz", "BİRİNCİ KİTAP · BOŞLUK",
            "Atomların hareket edebilmesi için boşluk gerekir. Eğer evren bütünüyle dolu ve sıkışık olsaydı hiçbir parça yer değiştiremez, birleşme ve ayrışma gerçekleşemezdi.",
            "Kalabalık bir asansörde herkes omuz omuzaysa kimse yer değiştiremez. Bir kişinin çıkması küçük bir boşluk yaratınca diğerleri kayabilir. Lucretius evrensel hareketi de madde ile boşluğun ortaklığıyla düşünür.",
            "Boşluk onun için yoklukla aynı değildir; doğanın işleyen bir koşuludur. Bu fikir Aristotelesçi dolu evren anlayışına karşı cesur bir savdı.",
            "Bugün atomların büyük bölümünün boşluk olduğu söylenirken kavram farklı fizik içinde kullanılır. Yine de Lucretius'un sezgisi, görünmeyen aralığın görünen düzen kadar önemli olabileceğini hatırlatır.",
            "crowded-elevator", "Madde parçalarının yer değiştirebilmesi için aralarında hareket alanı, yani boşluk bulunmalıdır."),
        chapter("Atomların biçimleri", "İKİNCİ KİTAP · BİRLEŞİMLER",
            "Lucretius atomların büyüklük ve biçim bakımından çeşitlendiğini, maddelerin özelliklerinin de bu parçaların düzeninden doğduğunu düşünür. Tatlı, sert ya da akışkan olan şeyler farklı birleşim örüntüleridir.",
            "Aynı harflerle farklı kelimeler yazılır. A, R ve T harflerinin sırası değişince anlam değişir; harflerin kendisi kalır. Şair, sınırlı ilk parçaların sayısız nesneyi böyle kurabileceğini anlatır.",
            "Modern kimyada özellik yalnız şekle indirgenmez; elektrik yükü, bağlar ve kuantum davranışı vardır. Lucretius'un modeli yanlış ayrıntılar taşısa da karmaşıklığı temel birimlerin düzeninden açıklama fikri güçlüdür.",
            "Bu bakış insan yapımı nesnelerde de işe yarar: Aynı malzeme, farklı düzenlenince köprü, bıçak ya da müzik aleti olabilir. Yapı, parçaların toplamından fazlasını üretir.",
            "letters-and-atoms", "Sınırlı sayıdaki harflerden sayısız kelime çıktığı gibi, atom düzenleri de farklı maddeler kurar."),
        chapter("Düşüşteki küçük sapma", "İKİNCİ KİTAP · SAPMA",
            "Atomlar yalnız düz çizgide düşseydi birbirine hiç çarpmayabilir ve yeni düzenler kuramazdı. Lucretius çok küçük, öngörülemez bir sapma düşünür; bu sapma karşılaşmayı ve oluşu mümkün kılar.",
            "Düz şeritlerde aynı hızla giden arabalar sonsuza dek yan yana kalır. Bir araç hafifçe yön değiştirirse yollar kesişir. Sapma, evrenin donuk paralelliğini kıran küçük dönemeçtir.",
            "Bazı yorumcular bu fikri özgür iradenin kapısı sayar, fakat şiirde ilişki tam sistemli değildir. Rastlantı tek başına bilinçli seçim üretmez. Yine de sıkı zorunluluk ile hareket alanı arasındaki gerilimi açar.",
            "Bugünün kuantum belirsizliğiyle doğrudan aynı sayılmamalıdır. Benzerlik çekici olsa da iki kavram farklı bilgi dünyalarına aittir.",
            "atomic-swerve", "Küçük atom sapması, paralel düşüşü bozup karşılaşma ve yeni düzen olasılığı yaratır."),
        chapter("Fırtınaya kıyıdan bakmak", "İKİNCİ KİTAP · HUZUR",
            "Şiirin ünlü görüntüsünde insan kıyıdan denizdeki fırtınayı seyreder. Haz, başkasının acısından değil; kendisinin güvenli yerde olduğunu ve tutkuların karmaşasından uzaklaşabildiğini görmekten doğar.",
            "Yoğun trafikte korna sesleri arasında sıkışmışken evde sessizce çay içtiğiniz anı düşünün. Sakinlik lüks eşya değil, gereksiz yarıştan çekilmenin verdiği ferahlıktır.",
            "Epikurosçu haz ölçüsüz eğlence değildir. Bedensel acının ve zihinsel korkunun azalması, dostluk ve sade ihtiyaçlarla yetinme daha kalıcı bir mutluluk sağlar.",
            "Tüketim kültürü sürekli yeni eksik üretirken bu eski kıyı görüntüsü günceldir: Daha fazlasına yetişmek yerine hangi fırtınanın aslında bize ait olmadığını sorabiliriz.",
            "shore-storm", "Kıyıdaki sakinlik başkasının felaketinden değil, gereksiz tutkuların fırtınasından uzaklaşmaktan gelir."),
        chapter("Ruh da maddeden yapılmışsa", "ÜÇÜNCÜ KİTAP · RUH",
            "Lucretius ruhu bedenden ayrı, ölümsüz bir misafir saymaz. Zihin ve canlılık çok ince atomların bedensel düzenidir; beden dağıldığında bu düzen de çözülür.",
            "Bir müzik grubu üyeleri ve aletleri dağıldığında şarkı ayrı bir odada yaşamaya devam etmez. Şarkı, belirli bir düzenin gerçekleşmesidir. Lucretius ruhu da bedensel orkestranın etkinliği gibi düşünür.",
            "Bu görüş modern sinirbilim değildir ama zihni doğa içine yerleştiren cesur bir adımdır. Bilincin ayrıntılı mekanizmasını açıklamaz; yalnız doğaüstü tözü gereksiz görür.",
            "Bugün beyin hasarının kişilik ve hafızayı değiştirmesi, zihin ile beden bağını güçlü biçimde gösterir. Yine de bilincin nasıl ortaya çıktığı hâlâ açık bir sorudur.",
            "body-orchestra", "Ruh ayrı bir yolcu değil, bedensel parçaların canlı düzeninde ortaya çıkan etkinliktir."),
        chapter("Ölüm geldiğinde biz yokuz", "ÜÇÜNCÜ KİTAP · ÖLÜM KORKUSU",
            "Lucretius ölüm korkusunu mantıksal bir düğümle gevşetir: Biz varken ölüm yoktur; ölüm geldiğinde ise deneyimleyecek biz kalmayız. Korkulan sonsuz karanlık, hissedilen bir durum değildir.",
            "Doğmadan önceki milyarlarca yılı acı çekerek beklemedik. Şair gelecekteki yokluğu, geçmişteki yokluğun aynasıyla karşılaştırır. İki sessizlik arasındaki hayat neden yalnız ikinci sessizlik yüzünden zehirlensin?",
            "Bu argüman yas tutan kişinin özlemini kolayca silmez. Ölüm korkusu yalnız acı beklentisi değil, ilişkilerin ve imkânların kaybıdır. Felsefi sakinlik duygusal sürecin yerine geçmez.",
            "Yine de ölüm düşüncesinin hayatı sürekli ertelemesine karşı güçlüdür. Sınırlılık, zamanı değersiz değil daha seçilebilir hale getirebilir.",
            "mirror-of-nonexistence", "Doğumdan önceki yokluk nasıl acı vermediyse, ölümden sonraki yokluk da deneyimlenen bir karanlık değildir."),
        chapter("Duyular kapı, akıl düzenleyici", "DÖRDÜNCÜ KİTAP · ALGI",
            "Lucretius nesnelerden ince görüntü tabakalarının yayıldığını ve duyulara ulaştığını düşünür. Bu fiziksel model yanlış olsa da algıyı ruhun sihirli dokunuşu değil, dış dünya ile beden arasındaki temas olarak kurar.",
            "Karanlıkta düz sandığımız çubuğun suya girince kırık görünmesini düşünün. Duyu bize görünüşü dürüstçe verir; hata, görünüşün nedenini acele yorumlayan yargıda doğabilir.",
            "Şair duyulara güven olmadan bilginin hiçbir ölçüsü kalmayacağını savunur. Fakat duyular tek başına yeterli değildir; farklı gözlemleri akıl ve karşılaştırma düzenlemelidir.",
            "Bugünün yanlış bilgi çağında aynı denge gerekir: Gözlem olmadan fikir havada kalır, yorum denetimi olmadan görüntü bizi kolayca yanıltır.",
            "bent-stick", "Duyu görünüşü taşır; yanılgı çoğu zaman görünüşün nedenini aceleyle yorumlayan zihinde oluşur."),
        chapter("Rüya, arzu ve zihnin filmi", "DÖRDÜNCÜ KİTAP · ZİHİN",
            "Rüyalar ve arzular, zihnin gün içinde aldığı görüntüleri yeniden düzenlemesiyle açıklanır. İnsan uykuda koşar, konuşur ve korkar; beden yatakta olsa da zihinsel film sürer.",
            "Gün boyu oynanan bir oyunun gece rüyaya karışması tanıdık bir örnektir. Zihin sıfırdan sahne kurmak yerine yakın deneyimin parçalarını birleştirir.",
            "Lucretius cinsel arzuyu da doğallaştırır fakat kimi bölümleri kadınlara dair dönemin önyargılarını taşır. Bedeni doğanın parçası görmek özgürleştirici olabilir; insan ilişkisini yalnız mekanik boşalmaya indirgemek yetersizdir.",
            "Modern psikoloji rüyalar konusunda daha temkinlidir. Yine de görünmeyen ruhların mesajı yerine hafıza, duygu ve beden süreçlerini araştırmak Lucretiusçu bir mirastır.",
            "dream-film", "Rüya, günün görüntülerinin uykuda yeniden kurgulandığı bedensel bir zihin filmi gibi işler."),
        chapter("Dünya insan için yapılmadı", "BEŞİNCİ KİTAP · KOZMOS",
            "Evrenin insan için özel olarak tasarlandığı düşüncesine karşı Lucretius, dünyanın kusurlarını gösterir: sert iklimler, hastalıklar, yırtıcılar ve yaşamak için gereken ağır emek. Doğa bize göre kurulmuş bir ev değildir.",
            "Bir otel odası misafir için tasarlanır; yatak, ışık ve banyo kolaylık sağlar. Dünya ise depremi, çölü ve zehirli bitkisiyle böyle bir konfor planı göstermez. İnsan uygun köşelerde yaşamayı öğrenir.",
            "Bu sav tanrıların varlığını bütünüyle kanıtlama ya da çürütme meselesinden çok, doğal olayları amaçla açıklamaya karşıdır. Yağmur tarlamız için değil, fiziksel süreçler yüzünden yağar.",
            "İklim krizi çağında insan merkezcilik eleştirisi daha da önemlidir. Gezegen bize ait bir makine değil; içinde geçici ve bağımlı bir tür olduğumuz sistemdir.",
            "not-made-for-us", "Dünya insan konforuna göre döşenmiş bir oda değil; yaşamın uyum sağladığı kayıtsız bir doğadır."),
        chapter("Dünyaların doğuşu ve ölümü", "BEŞİNCİ KİTAP · KOZMOS",
            "Lucretius evrenin sonsuz atom ve boşluk içinde birçok dünya kurabileceğini düşünür. Dünyamız benzersiz ve sonsuz değildir; birleşen her düzen gibi doğar, yaşlanır ve çözülür.",
            "Sahilde dalgaların sürekli kumdan şekiller kurup bozmasını düşünün. Hiçbir kale sonsuza dek kalmaz ama kum bitmediği için yeni biçimler ortaya çıkar. Kozmik düzenler de geçici yapılardır.",
            "Modern çoklu evren fikirleriyle bunu aynı saymak anakronizm olur. Lucretius deneysel kozmoloji yapmıyordu; insan merkezli tek dünya fikrine felsefi alternatif kuruyordu.",
            "Gezegenin geçiciliğini düşünmek umutsuzluk değil ölçek duygusu verebilir. Kısa ömrümüz, evrensel düzenin içinde daha dikkatli yaşama çağrısına dönüşür.",
            "many-worlds-sand", "Sonsuz madde denizinde dünyalar kumdan kaleler gibi kurulabilir ve yeniden çözülebilir."),
        chapter("Canlılar deneme yanılmayla kaldı", "BEŞİNCİ KİTAP · YAŞAM",
            "Şair, erken dünyanın çeşitli canlı biçimleri ürettiğini; yaşamaya ve çoğalmaya uygun olmayanların kaybolduğunu söyler. Bu, Darwinci doğal seçilim değildir ama canlı çeşitliliğini tek tek tasarımla açıklamayan dikkat çekici bir düşüncedir.",
            "Bir atölyede yüz farklı anahtar yapıldığını düşünün. Kilide uymayanlar kullanılmaz, uyanlar kopyalanır. Ortada geleceği gören plan değil, sonuçların ayıklanması vardır.",
            "Lucretius kalıtım, nüfus değişimi ve ortak ata mekanizmasını bilmiyordu. Bu nedenle onu gizli Darwin ilan etmek doğru değildir. Sezgi ile bilimsel teori arasındaki fark kanıt ve mekanizmadır.",
            "Yine de doğadaki uyumu yalnız amaçla değil, başarısız biçimlerin elenmesiyle açıklamaya çalışması düşünce tarihinde önemlidir.",
            "failed-creatures", "Yaşamaya uygun olmayan biçimlerin kaybolması, doğadaki düzeni önceden çizilmiş plandan bağımsız düşünmeye yardım eder."),
        chapter("Uygarlığın yavaş icatları", "BEŞİNCİ KİTAP · İNSAN TARİHİ",
            "İnsanlar ateş, dil, aile, tarım, metal ve şehirleri bir anda tanrılardan almadı. İhtiyaç, taklit, tesadüf ve kuşaklar boyunca biriken denemeler kültürü kurdu.",
            "Bir mutfak tarifinin büyükanneden toruna geçerken küçük değişikliklerle gelişmesi gibi, teknikler de tek sahibin eseri olmadan olgunlaşır. Toplumsal bilgi ortak ve katmanlıdır.",
            "Lucretius erken insanı bazen fazla kaba bir çizgiyle anlatır; modern arkeoloji avcı toplayıcıların karmaşık kültürünü daha iyi gösterir. Yine de uygarlığı mucize değil birikim olarak düşünmesi kalıcıdır.",
            "Bugünkü teknolojiyi de gökten düşmüş saymamak gerekir. Her cihazın içinde unutulmuş ustaların, kamu yatırımlarının ve uzun deneme zincirlerinin emeği vardır.",
            "slow-inventions", "Dil, ateş ve şehir tek armağan değil, kuşakların küçük denemelerinden biriken ortak icatlardır."),
        chapter("Gök gürültüsünün içindeki korku", "ALTINCI KİTAP · DOĞA OLAYLARI",
            "Şimşek, deprem, volkan ve salgınlar tanrıların öfkesi sayıldığında korku büyür. Lucretius her olay için doğal mekanizma arar; doğru açıklamayı her zaman bulamasa da soru yönünü değiştirir.",
            "Gece evde bir ses duyunca hayalet düşünmek korkuyu çoğaltır; borunun genleştiğini öğrenmek bedeni sakinleştirir. Mekanizma bilgisi yalnız merak değil, duygusal özgürlük sağlar.",
            "Şair bazen birden fazla olası açıklama sıralar. Görmediğimiz uzak olaylarda tek öyküye yapışmak yerine doğayla uyumlu seçenekleri açık tutar. Bu tutum bilimsel alçakgönüllülüğe yakındır.",
            "Bugün komplo teorileri belirsizliği niyetli güçlerle doldurur. Lucretius'un panzehiri hâlâ geçerli: Önce olağan mekanizmaları araştır, bilmediğin yerde korkuyu kanıt sanma.",
            "thunder-without-gods", "Gök gürültüsünü öfkeli iradeye değil doğal işleyişe bağlamak, korkunun büyüsünü azaltır."),
        chapter("Atina vebasıyla biten şiir", "ALTINCI KİTAP · SALGIN",
            "Eser Atina vebasının sarsıcı tasviriyle sona erer. Bedenler çöker, cenaze düzeni bozulur ve toplumun alışılmış kuralları korku altında dağılır. Şiirin sonu sakin bahçe değil, çıplak kırılganlıktır.",
            "Salgın sırasında hastanenin dolması yalnız tıbbi değil toplumsal krizdir. İnsanlar vedalaşamaz, ritüeller aksar, güven çatlar. Lucretius hastalığın çevresinde kurumların da ateşlendiğini gösterir.",
            "Metin eksik kalmış olabilir veya bu karanlık bilinçli sondur. Her iki durumda da doğayı anlamak acıyı tamamen ortadan kaldırmaz; yalnız acıya doğaüstü dehşet eklememeyi sağlar.",
            "Yakın dönem salgın deneyimi bu sayfaları ürpertici biçimde güncel kılar. Bilgi, bakım ve ortak düzen olmadan bireysel sakinlik tek başına yetmez.",
            "athens-plague", "Atina vebası, doğa karşısındaki bedensel ve toplumsal kırılganlığı şiirin sonuna taşır."),
    ],
    misreading="Lucretius'u modern fiziği iki bin yıl önceden eksiksiz bilen bir bilim insanı saymak yanlıştır. Atomları, ruhu ve görüntüleri konusunda pek çok ayrıntı bugünkü bilgiyle uyuşmaz. Kalıcı olan, doğa olaylarını amaç ve öfkeli iradeler yerine maddi nedenlerle açıklama cesaretidir.",
    modern="Modern atom, evrim ve sinirbilim Lucretius'un modellerinden çok farklıdır. Fakat ölüm korkusu, tüketim tutkusu, insan merkezcilik ve belirsizliği doğaüstü hikâyelerle doldurma eğilimi değişmedi; şiir bu alanlarda hâlâ canlı bir düşünce ortağıdır.",
    questions="Bir olay beni korkuttuğunda doğal mekanizma hakkında ne biliyorum? İhtiyaç sandığım şey gerçek bir gereksinim mi, yoksa kıyasın ürettiği huzursuzluk mu? Ölümün kaçınılmazlığı bugün seçtiğim hayatı nasıl daha açık hale getirebilir?",
    essence="Doğayı maddi nedenlerle anlamak, insanı evrenin efendisi yapmaz; fakat tanrısal ceza, ölüm ve bitmeyen arzu korkusundan daha sade ve özgür bir hayata yaklaştırabilir.",
))


# The remaining three books are imported from a compact companion module to keep
# this file reviewable while preserving five-book execution batches.
from build_twenty_more_summaries_batch_1b import MORE_BOOKS  # noqa: E402

BOOKS.extend(MORE_BOOKS)


if __name__ == "__main__":
    write_books(BOOKS)
