#!/usr/bin/env python3
"""Companion definitions for books 189, 194 and 214."""

from summary_batch_second_common import chapter, make_book


MORE_BOOKS = []


MORE_BOOKS.append(make_book(
    189, "mitolojiler", "Mitolojiler", "Roland Barthes",
    "Güreşten bifteğe, deterjandan otomobile kadar sıradan kültür nesnelerinin nasıl masum görünüş altında sınıf, ulus, cinsiyet ve tüketim fikirlerini doğal gerçekmiş gibi sunduğunu çözen kısa, keskin göstergebilim yazıları.",
    "#62554F", "Mythologies",
    [
        {"id": 1, "title": "Éditions du Seuil - Mythologies", "url": "https://www.seuil.com/ouvrage/mythologies-roland-barthes/9782757841846"},
        {"id": 2, "title": "Encyclopaedia Britannica - Roland Barthes", "url": "https://www.britannica.com/biography/Roland-Gerard-Barthes"},
        {"id": 3, "title": "Internet Encyclopedia of Philosophy - Roland Barthes", "url": "https://iep.utm.edu/barthes/"},
    ],
    [
        chapter("Mit gündelik sözün ikinci katı", "BAŞLANGIÇ · MİT NEDİR?",
            "Barthes için mit eski tanrı hikâyesi olmak zorunda değildir. Bir fotoğraf, reklam, yemek ya da spor gösterisi ikinci bir anlam taşıyıp tarihsel fikri doğal gerçek gibi sunabilir.",
            "Takım elbiseli yöneticinin fotoğrafı yalnız bir insanı gösterir; aynı anda ciddiyet, hak etme ve otorite fikrini de taşır. İlk anlamın üstüne kültürel ikinci kat çıkar.",
            "Her anlam mit değildir. Mit, kendi yapılmışlığını gizleyip 'zaten böyledir' etkisi yarattığında güç kazanır.",
            "Gündelik görüntüye bakarken 'burada açıkça ne görüyorum ve bunun doğal saymam istenen ikinci mesajı ne?' sorusu kitabın ana aracıdır.",
            "second-story-sign", "Sıradan görüntünün üstüne kurulan ikinci anlam katı, tarihsel fikri doğanın kendisi gibi gösterebilir."),
        chapter("Güreşte gerçek değil okunabilir adalet", "BİRİNCİ KISIM · GÖSTERİ",
            "Profesyonel güreşte seyirci teknik sonuçtan çok açık işaretler ister. Kötü karakter yüzünde kötülüğü taşır, ceza büyütülür ve adalet sahnede görünür hale gelir.",
            "Çizgi filmde kötü adamın karanlık pelerini gibi, güreşçi bedeni rolün altyazısıdır. Seyirci kimin haklı olduğunu anında okur.",
            "Gösterinin yapay olması etkisiz olduğu anlamına gelmez. İnsan belirsiz gerçek hayattan farklı olarak kötünün açıkça cezalandırıldığı kısa ahlaki tiyatro yaşar.",
            "Reality show ve siyasi mitinglerde de karakterler karmaşık kişiden okunabilir role dönüştürülebilir. Netlik arttıkça gerçekliğin gri alanı kaybolur.",
            "wrestling-justice", "Güreş ringi gerçekçi dövüşten çok iyinin ve kötünün bedenlerle okunabildiği ahlaki tiyatrodur."),
        chapter("Bifteğin ulusal kanı", "BİRİNCİ KISIM · YEMEK",
            "Biftek Barthes'ın Fransa'sında yalnız yiyecek değil güç, doğallık ve ulusal kimlik işaretidir. Az pişmiş kırmızı et, kültürel tercihi bedensel zorunluluk gibi gösterir.",
            "Bayram yemeğinin 'bizden biri' olmanın ölçüsüne dönüşmesi gibi, tat toplumsal aidiyet taşır. Yemeği sevmemek yalnız damak değil kimlik sapması sayılabilir.",
            "Barthes kısa denemede sınıf ve sömürge boyutunu her zaman derinleştirmez. Sofranın anlamı üretim ve emek zinciriyle tamamlanmalıdır.",
            "Bugün kahve, veganlık veya yerel ürün tercihleri de benzer biçimde ahlaki ve siyasi kimlik işareti olabilir.",
            "steak-nation", "Biftek tabakta yalnız protein değil, güç ve ulusal aidiyet fikrini taşıyan kültürel işarettir."),
        chapter("Patates kızartmasının masum bayrağı", "BİRİNCİ KISIM · YEMEK",
            "Patates kızartması sıradan eşlikçi görünürken Fransızlık, ev rahatlığı ve ortak tat hissi taşır. Günlük yiyecek ulusal kimliği sessizce yeniden kurar.",
            "Stadyumda aynı yiyeceği paylaşan binlerce kişi, bayrak sallamadan da ortak ritüel yaşar. Tat hafızası siyasi sembolden daha derin çalışabilir.",
            "Ulusal mutfak sabit değildir; göç, ticaret ve sömürgeyle sürekli değişir. Mit bu karışık tarihi saf köken gibi sunar.",
            "Bir yemeğin 'gerçek sahibi' tartışıldığında tarifin yolculuğunu ve görünmez emeği araştırmak miti tarihe geri bağlar.",
            "fries-flag", "Gündelik yiyecek sessiz bir bayrak gibi ortak ulusal tat ve aidiyet hissi kurabilir."),
        chapter("Yeni Citroën: gökten inen nesne", "BİRİNCİ KISIM · TÜKETİM",
            "Yeni otomobil sergilendiğinde makine olmaktan çıkıp kusursuz yüzeyli büyülü nesneye dönüşür. Üretim emeği ve mekanik karmaşa görünmez, tasarım neredeyse kutsal görünür.",
            "Telefon tanıtımında cihazın fabrikası değil ışık altında kayan pürüzsüz kenarı gösterilir. Nesne yapılmış değil sanki kendiliğinden doğmuş gibidir.",
            "Barthes tüketicinin yüzeye dokunarak nesneyi evcilleştirdiğini söyler. Hayranlık sahip olma arzusuna çevrilir.",
            "Ürün lansmanında hangi işçilik, maden ve atığın kadraj dışı kaldığını sormak büyüyü bozup nesneyi toplumsal tarihe geri getirir.",
            "citroen-cathedral", "Pürüzsüz otomobil üretim izlerini silip modern çağın gökten inmiş kutsal nesnesi gibi sergilenir."),
        chapter("Deterjanın derin temizlik tiyatrosu", "BİRİNCİ KISIM · REKLAM",
            "Deterjan reklamları köpüğü kirin içine işleyen, onu ayıran ve temizliği derinden kurtaran canlı güç gibi anlatır. Kimyasal ürün ahlaki arınma tiyatrosu kurar.",
            "Bembeyaz gömlek yalnız temiz değil iyi anne, düzenli ev ve saygın aile göstergesine dönüşür. Leke karakter kusuru gibi kodlanır.",
            "Reklam gerçek işlevi tamamen uydurmaz; ürünü gündelik kaygı ve statü diliyle büyütür. İşlev ile hikâye birbirine eklenir.",
            "Bugün cilt bakımı ve dijital güvenlik reklamlarında da 'derine nüfuz edip görünmez tehdidi temizleme' anlatısı tekrar eder.",
            "detergent-foam", "Köpük yalnız kiri değil düzensizlik ve utanç fikrini de evden uzaklaştıran arınma kahramanı gibi sunulur."),
        chapter("Oyuncak yetişkin dünyanın provası", "BİRİNCİ KISIM · ÇOCUKLUK",
            "Barthes oyuncakların çocuğa hazır yetişkin rollerini küçük ölçekte verdiğini söyler: asker, mutfak, kuaför, araç. Çocuk dünya kurmak yerine var olan dünyayı prova eder.",
            "Minik alışveriş arabası çocuğa tüketici olmayı, oyuncak silah kahramanlığı belirli rol içinde öğretir. Oyun masumken sosyal senaryo taşır.",
            "Çocuk oyuncağı dönüştürebilir; kutuyu uzay gemisi yapar. Barthes'ın eleştirisi çocuğun yaratıcılığını bazen küçümser.",
            "Oyuncak seçerken yalnız eğlenceyi değil hangi rollerin mümkün, hangilerinin görünmez yapıldığını düşünmek faydalıdır.",
            "toy-adult-world", "Hazır rol oyuncakları çocuğa yetişkin toplumunun iş ve cinsiyet düzenini küçük ölçekte prova ettirebilir."),
        chapter("Striptizin çıplaklığı örtmesi", "BİRİNCİ KISIM · BEDEN",
            "Barthes striptizin bedeni özgürleştirmekten çok tüy, ışık, ritüel ve profesyonel hareketle cinselliği evcilleştirdiğini yazar. Çıplaklık gösterilirken güvenli gösteriye dönüştürülür.",
            "Perde açıldıkça sır büyümek yerine koreografiyle kontrol altına alınır. Seyirci gerçek yakınlık değil kodlanmış görüntü alır.",
            "Deneme döneminin erkek bakışını ve kadın öznesini sınırlı ele alır. Feminist analiz güç ve emek boyutunu daha ileri taşır.",
            "Sosyal medyada 'doğal beden' sunumlarının bile ışık, poz ve platform kurallarıyla ne kadar düzenlendiğini aynı araçla görebiliriz.",
            "staged-nudity", "Gösteri bedeni açarken ritüel ve koreografiyle gerçek yakınlığın belirsizliğini örter."),
        chapter("Şarap: ulusal ve ahlaki içecek", "BİRİNCİ KISIM · İÇECEK",
            "Şarap Fransız mitinde yalnız alkol değil sıcaklık, işçi gücü, entelektüel sohbet ve ulusal birlik simgesidir. Sınıflar farklı içse de ortak Fransızlık işareti olur.",
            "Aynı bardak işçiye dayanıklılık, kentliye incelik, ülkeye gelenek anlatabilir. Nesne farklı çevrede farklı rol giyer.",
            "Mit sağlık zararı, bağımlılık ve sömürge üretimini arka plana iter. Ulusal sıcaklık görüntüsü maddi bedeli unutturur.",
            "Kahve ve enerji içeceği kültürlerinde de üretkenlik, aidiyet ve yaşam tarzı içeceğin tadından daha büyük mesaj taşır.",
            "wine-myth", "Şarap tek içecekte emek, sohbet, sıcaklık ve ulusal birlik gibi farklı toplumsal anlamları toplar."),
        chapter("Turistin kör rehberi", "BİRİNCİ KISIM · SEYAHAT",
            "Turistik rehber ülkeyi anıt, pitoresk sokak ve değişmez halk tiplerine indirger. Yaşayan toplum dekor, ziyaretçi ise önceden seçilmiş görüntülerin tüketicisi olur.",
            "Bir şehri yalnız fotoğraf çekilecek beş noktadan görmek, evin yalnız vitrinine bakıp içinde kimlerin yaşadığını bildiğinizi sanmaktır.",
            "Rehber yön bulmak için gereklidir; sorun seçimin tarafsız gerçeklik gibi sunulmasıdır. Kadraj her zaman dışarıda bir şey bırakır.",
            "Seyahatte en az bir kez turistik rotanın dışında gündelik ulaşım, pazar ve mahalle hayatını izlemek miti tarihe ve emeğe bağlar.",
            "tourist-postcard", "Turistik rehber yaşayan toplumu pitoresk anıt ve değişmez tiplerden oluşan kartpostala çevirebilir."),
        chapter("Einstein'ın beyni", "BİRİNCİ KISIM · BİLİM",
            "Popüler kültür Einstein'ın dehasını neredeyse ayrı çalışan mucize beyne dönüştürür. Düşünce, tarihsel bilim ağı ve emekten kopup tek organın büyüsüne bağlanır.",
            "Ampulü yalnız son düğmeye basan kişinin icadı saymak gibi, bilimsel keşfi tek kafanın içinde kapatmak ortak birikimi görünmez yapar.",
            "Bireysel yaratıcılık gerçektir; Barthes'ın hedefi kişiyi silmek değil dehayı doğaüstü nesneye çevirmektir.",
            "Teknoloji girişimlerinde kurucu kültü, kamu araştırması ve ekip emeğini bugün de benzer biçimde gölgeleyebilir.",
            "einstein-brain", "Deha miti bilimsel ağı ve emeği silip keşfi tek mucize beynin doğal ürünü gibi gösterir."),
        chapter("Yeni romana karşı kör eleştirmen", "BİRİNCİ KISIM · KÜLTÜR",
            "Barthes bazı eleştirmenlerin anlamadığı yeniliği hastalık, saçmalık veya insan doğasına aykırılık diye dışladığını gösterir. Alışılmış biçim evrensel sanat ölçüsüne dönüşür.",
            "Yeni müzikte ritmi bulamayan dinleyicinin 'bu müzik değil' demesi, kendi alışkanlığını türün sınırı saymasıdır.",
            "Her yenilik değerli değildir; eleştiri gerekçesiz hayranlık da olmamalıdır. Mesele tanımadığını doğal olmayan diye reddetmemektir.",
            "Dijital sanat ve yapay zekâ tartışmalarında önce eserin hangi yeni kuralı denediğini anlamak, sonra değerini tartmak daha dürüsttür.",
            "critic-old-ruler", "Eleştirmen kendi alıştığı cetveli evrensel sayınca yeni biçimi anlamadan kusurlu ilan eder."),
        chapter("Burjuva kendini insanlık diye sunar", "İKİNCİ KISIM · İDEOLOJİ",
            "Barthes'a göre egemen sınıf kendi tarihsel değerlerini sınıf adıyla değil sağduyu, doğallık ve insanlık adına sunar. Böylece çıkar görünmez, norm kalır.",
            "Belirli aile tipini 'normal aile' diye adlandırınca diğerleri yalnız farklı değil eksik görünür. Sıfat kaybolur, özel biçim genel kural olur.",
            "Burjuva kavramı bugünün parçalı sınıf yapısını tek başına açıklamayabilir. Fakat ayrıcalığın kendini tarafsız norm gibi sunması sürer.",
            "Bir reklam 'herkesin istediği hayat' dediğinde o herkesin gelirini, cinsiyetini ve coğrafyasını sormak miti görünür kılar.",
            "class-as-humanity", "Egemen yaşam biçimi kendi sınıf adını silip kendini insanlığın doğal ve tarafsız normu diye sunabilir."),
        chapter("Mit tarihi boşaltır", "İKİNCİ KISIM · DOĞALLAŞTIRMA",
            "Mit bir nesnenin nasıl oluştuğunu, kimlerin mücadele ettiğini ve kimin kazandığını siler. Sonuç sanki baştan beri öyleymiş gibi görünür; tarih doğaya dönüşür.",
            "Bugünkü şehir meydanına bakıp yıkılan mahalleyi, işçiyi ve siyasi kararı bilmezseniz taşlar kendiliğinden dizilmiş sanılır.",
            "Tarihi geri getirmek her sembolü yok etmez; anlamın seçim ve çatışma ürünü olduğunu gösterir.",
            "Bir kural 'insan doğası' diye savunulduğunda geçmişte ne zaman başladığını araştırmak doğallaştırma büyüsünü bozar.",
            "history-erased", "Mit yapım sürecini silerek tarihsel sonucu sanki doğanın baştan beri değişmez düzeniymiş gibi gösterir."),
        chapter("Mit depolitize edilmiş sözdür", "İKİNCİ KISIM · SİYASET",
            "Mit güç ve çıkar ilişkisini görünmez kılarak tartışılabilir sorunu masum görüntüye çevirir. Yoksulluk kader, iş bölümü doğal yetenek, sömürge egzotik macera olur.",
            "Düşük ücreti 'bu işler zaten böyle' diye anlatmak, sözleşme ve pazarlık gücünü konuşma dışına iter. Siyasi düzen doğa cümlesine saklanır.",
            "Her gündelik tercih doğrudan propaganda değildir. Barthes yöntemi aşırı kullanılırsa insanlar hiçbir şeyden keyif alamayan şüphe makinesine dönüşebilir.",
            "Ama eşitsizliği kaçınılmaz gösteren sözde 'zaten' kelimesini yakalamak, depolitize edilmiş soruyu yeniden tartışmaya açar.",
            "politics-under-cloth", "Mit, tartışılabilir güç ilişkisini doğal görüntünün altına saklayarak siyaseti konuşma dışına iter."),
        chapter("Mit okuru nasıl çalışır?", "İKİNCİ KISIM · OKUMA",
            "Mit çözmek gizli komplocu bulmak değil, işaretin iki katını ayırmaktır. Önce nesnenin ne gösterdiğini, sonra bu görüntünün hangi kavramı doğal hale getirdiğini izlersiniz.",
            "Reklamdaki dağ manzarası önce doğadır; ikinci katta saflık ve ahlaki temizlik ürüne taşınır. Suyun kaynağı ile şirketin karakteri aynı şeymiş gibi birleşir.",
            "Okur kendi konumunu da sorgulamalıdır. Aynı işaret farklı sınıf ve kültürde başka çağrışım yapabilir; anlam tek anahtarla açılmaz.",
            "İyi mit okuması kısa teşhisle yetinmez, dışarıda kalan emek ve tarihi araştırarak ikinci anlamın nasıl kurulduğunu gösterir.",
            "myth-reader-lens", "Mit okuru görüntünün açık nesnesi ile onun sırtında taşınan doğal görünüşlü kültürel kavramı ayırır."),
    ],
    misreading="Mitolojiler her sevilen nesnenin kötü propaganda olduğunu söylemez. Barthes gündelik zevkin nasıl ikinci anlam taşıdığını gösterir. Yöntemi 'her şey aslında gizli mesajdır' paranoyasına çevirmek, tarih ve somut kanıt yerine kolay şüphe üretir.",
    modern="Sosyal medya, influencer estetiği ve marka kimliği Barthes'ın mit makinesini hızlandırdı. Ancak bugünün izleyicisi yalnız pasif alıcı değildir; içeriği yeniden yorumlar ve parodi yapar. Sınıfın yanında ırk, cinsiyet ve platform algoritmaları da analize eklenmelidir.",
    questions="Bu görüntü ilk bakışta ne gösteriyor, ikinci katta neyi doğal saydırıyor? Hangi üretim tarihi ve emek kadraj dışında kalmış? 'Zaten böyledir' denilen şey gerçekten ne zaman ve kimin çıkarıyla böyle oldu?",
    essence="Modern mit, tarihsel olarak kurulmuş sınıf, ulus ve tüketim fikirlerini sıradan görüntünün içine yerleştirip onları tartışılmaz doğa gibi hissettirir.",
))


MORE_BOOKS.append(make_book(
    194, "arac-mesajdir", "Araç Mesajdır", "Marshall McLuhan & Quentin Fiore",
    "Bir iletişim aracının taşıdığı içerikten önce duyularımızı, hızımızı, toplumsal ölçeğimizi ve birlikte yaşama biçimimizi değiştirdiğini; kitabın kendi çarpıcı görsel tasarımıyla okura yaşatan medya klasiği.",
    "#4D5E65", "The Medium is the Massage",
    [
        {"id": 1, "title": "Penguin Random House - The Medium is the Massage", "url": "https://www.penguinrandomhouse.com/books/113070/the-medium-is-the-massage-by-marshall-mcluhan/"},
        {"id": 2, "title": "The Estate of Marshall McLuhan", "url": "https://marshallmcluhan.com/"},
        {"id": 3, "title": "Encyclopaedia Britannica - Marshall McLuhan", "url": "https://www.britannica.com/biography/Marshall-McLuhan"},
    ],
    [
        chapter("Mesaj neden içerikten önce araçtır?", "BAŞLANGIÇ · ANA FİKİR",
            "McLuhan'a göre bir aracın en derin mesajı taşıdığı hikâye değil, insan ilişkilerinin ölçek ve ritmini değiştirmesidir. Elektrik ışığı içerik göstermese bile gece çalışma ve şehir yaşamını dönüştürür.",
            "Telefonda okuduğunuz aynı haber kâğıttakinden daha hızlı paylaşılır, bildirimle bölünür ve yorum kalabalığına girer. Cümle aynı, yaşanan ortam farklıdır.",
            "İçeriği önemsiz saymak aşırıdır; propaganda ile şiir aynı etkiyi yaratmaz. McLuhan dikkati genellikle görünmez kalan taşıyıcı yapıya çeker.",
            "Yeni araçta ilk soru 'ne söylüyor?' kadar 'zamanımı, bedenimi ve başkalarıyla ilişkimi nasıl yeniden kuruyor?' olmalıdır.",
            "medium-message", "Aynı içerik farklı araçta başka hız, dikkat ve toplumsal ilişki biçimi kazanır."),
        chapter("Massage: araç bizi yoğurur", "BAŞLANGIÇ · KELİME OYUNU",
            "Kitabın İngilizce başlığındaki 'massage' bilinçli kelime oyunudur. Araç yalnız mesaj taşımaz; duyularımızı ve alışkanlıklarımızı masaj gibi yoğurur, çağın kitlesel yapısını kurar.",
            "Sürekli dokunmatik ekran kullanan parmak, kısa içerik bekleyen dikkat ve anında cevap isteyen ilişki biçimi aynı teknolojik yoğurmanın parçalarıdır.",
            "İnsan pasif hamur değildir; aracı reddeder, uyarlar ve farklı amaçla kullanır. Yoğurma gücü ile kullanıcı yaratıcılığı birlikte düşünülmelidir.",
            "Kendi medya gününüzü izlemek, aracın beden ritminizde bıraktığı şekli fark etmenin ilk adımıdır.",
            "media-massage", "İletişim aracı yalnız bilgi iletmez, beden ve dikkat alışkanlıklarını sürekli yoğurur."),
        chapter("Her araç bedenin uzantısı", "BİRİNCİ KISIM · UZANTI",
            "Tekerlek ayağın, kitap gözün, kıyafet derinin, elektronik ağ sinir sisteminin uzantısıdır. Teknoloji bir yeteneği dışarı çıkarıp büyütürken duyular arasındaki dengeyi değiştirir.",
            "Navigasyon mekânsal hafızayı uzatır ama yolu kendi başına hatırlama becerisini azaltabilir. Kazanç ile körelme aynı araçta bulunur.",
            "Uzantı benzetmesi teknolojiyi bedene yakınlaştırır; fakat şirket, yasa ve ekonomik çıkarı tek başına açıklamaz. Aracın sahibi de önemlidir.",
            "Yeni cihazı değerlendirirken hangi yeteneği büyüttüğünü ve hangi yeteneği kullanımdan düşürdüğünü beraber sorun.",
            "body-extensions", "Teknoloji bir bedensel yeteneği uzatırken başka duyuların kullanım ağırlığını değiştirebilir."),
        chapter("Basılı sayfanın doğrusal insanı", "İKİNCİ KISIM · MATBAA",
            "Matbaa düzenli satır, standart kopya ve sessiz bireysel okuma alışkanlığı üretti. McLuhan bunun milliyetçilik, uzmanlaşma ve doğrusal düşünceyle birlikte geliştiğini savunur.",
            "Kitap baştan sona aynı sırayla ilerler; sayfa herkese aynı görünür. Bu düzen, düşünceyi basamak ve sınırlarla örgütlemeye yatkındır.",
            "Matbaa tek başına modern bireyi yaratmadı; devlet, din ve ekonomiyle birleşti. Nedensellik iddiaları bazen fazla geniştir.",
            "Uzun metin okuma, parçalı ekran çağında hâlâ düşünceyi yavaşlatan ve bağlantıyı sürdürmeye yarayan özel bir duyusal eğitimdir.",
            "typographic-man", "Basılı satır düşünceyi sıraya, standarda ve uzun süreli görsel dikkate alıştırdı."),
        chapter("Elektrik aynı anda her yerde", "İKİNCİ KISIM · ELEKTRİK ÇAĞI",
            "Elektronik iletişim mesafeyi hızla küçültür; olay uzak yerde olsa da eşzamanlı olarak eve girer. Dünya neden-sonuç sırasından çok karşılıklı tepki ağı gibi hissedilir.",
            "Canlı yayındaki kriz saniyeler içinde telefonunuza düşer, piyasayı ve sokağı aynı anda etkiler. Uzak artık geç demek değildir.",
            "Eşzamanlılık ortak farkındalık yaratırken sürekli aciliyet ve yorgunluk da üretir. Her olay yakında hissedilince öncelik kurmak zorlaşır.",
            "Bildirimleri kapatmak dünyadan kopmak değil, elektrik çağının bütün olayları aynı anda bedeninize sokmasına sınır koymaktır.",
            "electric-simultaneity", "Elektronik ağ uzak olayları gecikmeli haber olmaktan çıkarıp aynı anda bedenimize dokunan çevreye dönüştürür."),
        chapter("Küresel köy yakınlık mı, kavga mı?", "İKİNCİ KISIM · KÜRESEL KÖY",
            "Elektronik ağ dünyayı köy gibi birbirinin işinden haberdar hale getirir. Köy sıcak dayanışma kadar dedikodu, gözetim ve hızlı kavga da demektir.",
            "Mahalle grubunda bir söylenti dakikalar içinde herkese ulaşır; mesafe yoktur ama anlayış garanti değildir. Yakınlık sürtüşmeyi de artırır.",
            "Küresel köy eşit değildir; bazı seslerin vericisi güçlü, bazıları yalnız alıcıdır. Ağ altyapısı ve platform sahipliği görünmez iktidar taşır.",
            "Bağlantı sayısını topluluk kalitesi sanmamak gerekir. Gerçek köy, karşılıklı sorumluluk ve düzeltme yolu da ister.",
            "global-village", "Küresel köy uzaklığı azaltırken dayanışmayla birlikte dedikodu, gözetim ve çatışmayı da büyütebilir."),
        chapter("Sıcak ve soğuk medya", "ÜÇÜNCÜ KISIM · KATILIM",
            "McLuhan yüksek ayrıntı veren aracı sıcak, boşlukları izleyicinin doldurmasını isteyen aracı soğuk diye ayırır. Fotoğraf ayrıntılı, çizgi film daha katılımcı örneğidir.",
            "Net fotoğrafta yüz hazırdır; birkaç çizgilik karikatürde zihin eksik parçayı tamamlar. Daha az veri bazen daha çok katılım ister.",
            "Sınıflandırma her duruma uymaz; kullanım bağlamı ve kişi farkı önemlidir. Televizyon teknolojisi de dönemden beri çok değişti.",
            "Yine de eğitimde hazır cevap ile öğrencinin boşluk doldurduğu etkinlik arasındaki farkı düşünmek için yararlı bir mercektir.",
            "hot-cool-media", "Yüksek ayrıntı bazı boşlukları kapatır, düşük ayrıntı izleyiciyi anlamı tamamlamaya çağırabilir."),
        chapter("Dikiz aynasında geleceğe gitmek", "ÜÇÜNCÜ KISIM · ESKİ İÇERİK",
            "Yeni aracı önce eski aracın içeriğiyle anlamaya çalışırız. İlk filmler tiyatroyu kaydetti, internet gazeteyi taklit etti. McLuhan buna geleceğe dikiz aynasından gitmek der.",
            "İlk otomobile at arabası biçimi vermek rahatlatıcıdır; yeninin kendi imkânı sonra anlaşılır. Eski kalıp geçiş köprüsüdür.",
            "Geçmiş benzetmesi gereksiz değildir; öğrenmeyi kolaylaştırır. Sorun, yeni aracın toplumsal etkisini eski adla görünmez bırakmaktır.",
            "Yapay zekâyı yalnız hızlı daktilo saymak da böyle olabilir. Hangi iş akışını kökten değiştirdiğini ayrıca izlemek gerekir.",
            "rearview-mirror", "Yeni teknolojiye eski aracın biçimini giydirerek geleceğe dikiz aynasından bakarız."),
        chapter("Eğitim ile yeni duyusal çevre", "DÖRDÜNCÜ KISIM · OKUL",
            "Okul basılı kitabın sıralı, tek merkezli düzenini sürdürürken öğrenci elektronik çevrede parçalı ve eşzamanlı bilgiye alışır. İki dikkat rejimi çatışır.",
            "Sınıfta kırk dakika tek ses dinlemesi beklenen çocuk, dışarıda aynı anda video, sohbet ve oyun arasında geçer. Sorun yalnız disiplin değil çevre farkıdır.",
            "Yeni olan her zaman daha iyi değildir. Derin okuma ve sabır kaybedilirse hızlı erişim yüzeysel kalabilir. Eğitim iki rejimin güçlü yanlarını birleştirmelidir.",
            "Ders tasarımında araç seçimi içeriğin süsü değil öğrenme biçiminin parçasıdır. Video, tartışma ve metin farklı zihinsel iş ister.",
            "school-media-gap", "Basılı okulun tek çizgili dikkati, elektronik çevrenin eşzamanlı ve parçalı ritmiyle çatışabilir."),
        chapter("Özel hayatın duvarları incelirken", "DÖRDÜNCÜ KISIM · GÖZETİM",
            "Elektronik uzantı sinir sistemimizi dışarı açar. Başkalarına ulaşma gücü artarken davranış ve tercihler de ölçülebilir hale gelir; uzantı aynı zamanda giriş kapısıdır.",
            "Akıllı saat bedeninizi size gösterir, veriyi şirkete de taşır. Kendi nabzınıza erişim ile başkasının profilinize erişimi aynı cihazda birleşir.",
            "McLuhan bugünkü veri ekonomisini ayrıntısıyla öngörmedi; fakat dışsallaşan sinir sistemi benzetmesi mahremiyet sorununa şaşırtıcı biçimde uyar.",
            "Yeni araçta yalnız ne alabildiğinizi değil, kullanırken ne verdiğinizi ve kimin görebildiğini sorun.",
            "nervous-system-outside", "Elektronik uzantı dünyaya dokunma gücü verirken dünyanın da beden ve davranış verimize dokunmasına kapı açar."),
        chapter("Reklam içeriği değil çevre satar", "DÖRDÜNCÜ KISIM · TÜKETİM",
            "Reklam üründen çok içinde yaşayacağımız duygusal çevreyi sunar. Araba özgürlük, telefon ait olma, deterjan iyi aile mesajı taşır.",
            "Şişedeki içecek yerine sahilde gülen arkadaşlar gösterilir. Satılan sıvı değil o sahnenin parçası olma ihtimalidir.",
            "İzleyici tamamen kandırılan değildir; reklamı mizahla ve kuşkuyla okuyabilir. Yine de tekrar çevrenin normalini biçimlendirir.",
            "Satın alma öncesi ürünün işlevini reklamdaki yaşam sahnesinden ayırmak medya masajını görünür yapar.",
            "advertising-environment", "Reklam nesnenin özelliğinden çok, o nesneyle gireceğimiz arzu edilen yaşam çevresini satar."),
        chapter("İçerik hırsızın taşıdığı et parçası", "DÖRDÜNCÜ KISIM · DİKKAT",
            "McLuhan içeriği, bekçi köpeğinin dikkatini dağıtan et parçasına benzetir. Hikâyeye bakarken aracın toplumsal yapıyı nasıl değiştirdiğini görmeyebiliriz.",
            "Yeni uygulamadaki eğlenceli videoyu tartışırken sonsuz kaydırmanın zamanı nasıl parçaladığını kaçırırız. İçerik konuşulur, mimari çalışır.",
            "İçerik gerçekten önemsiz değildir; nefret söylemi ile eğitim aynı değildir. Benzetme yalnız görünmez tasarımı fark ettirmek için abartıdır.",
            "Medya eleştirisinde tek gönderiyi değil sıralama algoritması, bildirim ve paylaşım teşvikini de incelemek gerekir.",
            "content-meat", "İçerik dikkati çekerken aracın görünmez mimarisi davranış ve ilişki düzenini sessizce değiştirebilir."),
        chapter("Sanatçı yaklaşan çevreyi erken hisseder", "BEŞİNCİ KISIM · SANAT",
            "McLuhan sanatçıyı yeni medyanın duyusal etkisini toplumdan önce fark eden anten gibi görür. Sanat alışkanlığı bozup çevreyi yeniden görünür kılar.",
            "Sürekli duyduğunuz klima sesini ancak durunca fark edersiniz. Sanat biçimi değiştirerek medya çevresinin normalleşmiş uğultusunu duyurur.",
            "Sanatçı her zaman kâhin değildir; teknoloji şirketi ve kullanıcı toplulukları da yeni kullanım keşfeder. Romantik deha miti sınırlandırılmalıdır.",
            "Yine de deneysel sanat ve tasarım, henüz adı konmamış medya etkilerini güvenli alanda hissettirir.",
            "artist-antenna", "Sanatçı normalleşmiş medya çevresinin uğultusunu biçimi bozarak toplumdan erken duyurabilir."),
        chapter("Kitabın tasarımı kitabın savıdır", "BEŞİNCİ KISIM · QUENTIN FIORE",
            "Quentin Fiore'un tipografi, fotoğraf, boşluk ve sayfa dönüşleri metni açıklamaz; fikri bedensel deneyime çevirir. Okur sırayla ders dinlemek yerine medya parçalarının içinde hareket eder.",
            "Bir kelimenin baş aşağı basılması, onu okumadan önce bedeninizi sayfayı çevirmeye zorlar. Biçim doğrudan mesaj olur.",
            "Görsel çarpıcılık bazen savın kanıtını örtebilir. Hatırlanan slogan, tartışmalı nedenselliğin yerini almamalıdır.",
            "Bu özetin görselleri de yalnız süs değil, bölüm fikrini farklı duyusal kanaldan taşıyan küçük medya deneyleri olmalıdır.",
            "book-as-medium", "Sayfanın tipografi ve görüntü düzeni, aracın içeriği yoğurduğu savını okura doğrudan yaşatır."),
        chapter("Teknolojik determinizm tehlikesi", "ELEŞTİRİ · SINIR",
            "McLuhan bazen araç sanki toplumu tek başına değiştiriyormuş gibi konuşur. Oysa mülkiyet, siyaset, cinsiyet, sınıf ve kullanıcı direnci aynı teknolojinin sonucunu değiştirir.",
            "Aynı mesajlaşma uygulaması demokratik örgütlenme, aile dayanışması veya devlet gözetimi için kullanılabilir. Kod aynı, güç düzeni farklıdır.",
            "Araç nötr değildir ama kader de değildir. Tasarım belirli davranışı kolaylaştırır; yasa ve kültür bu imkânı yönlendirir.",
            "En iyi McLuhan okuması teknolojiyi suçlu ilan etmek değil, onunla birleşen çıkar ve kurumları görünür kılmaktır.",
            "same-app-three-worlds", "Aynı araç farklı güç ve kurum ortamlarında dayanışma, ticaret ya da gözetim ağına dönüşebilir."),
        chapter("Dijital çağda araç mesajdır", "GÜNÜMÜZ · PLATFORM",
            "Sosyal platformun mesajı yalnız içerik değildir; beğeni sayısı, kısa video, sürekli akış ve anlık geri bildirim yeni toplumsal ritim kurar.",
            "Herkes aynı meydanda konuşuyor görünür, fakat algoritma bazı seslere megafon, bazılarına duvar verir. Meydanın mimarisi konuşmanın parçasıdır.",
            "Kullanıcılar platformu beklenmedik biçimde dönüştürebilir; mizah, dayanışma ve eğitim alanı açar. Buna rağmen teşvik tasarımı görünürlük yarışını belirler.",
            "Dijital okuryazarlık içerik doğrulamaya ek olarak aracın dikkat ve dağıtım modelini anlamayı gerektirir.",
            "algorithmic-square", "Dijital meydanda içerikten önce görünürlüğü dağıtan algoritmik mimari toplumsal mesajı biçimlendirir."),
    ],
    misreading="'Araç mesajdır' içeriğin hiç önemli olmadığı anlamına gelmez. McLuhan, içerik tartışmasının aracın hız, ölçek ve duyusal düzen etkisini gizlediğini söyler. Teknolojinin toplumu tek başına belirlediğini kabul etmek de eleştirisiz bir teknolojik kadercilik olur.",
    modern="Akıllı telefon, algoritma ve veri ekonomisi McLuhan'ın dışsallaşmış sinir sistemi fikrini aşırı derecede somutlaştırdı. Bugünkü analiz aracın yanında şirket modeli, moderasyon, devlet ve kullanıcı topluluklarını da hesaba katmalıdır.",
    questions="Bu araç hangi yeteneğimi uzatırken hangisini köreltiyor? Taşıdığı içerikten bağımsız olarak zaman ve ilişki ritmimi nasıl değiştiriyor? Görünürlüğü ve veriyi kim kontrol ediyor?",
    essence="İletişim aracının en derin mesajı söylediği sözden önce, duyularımızı, zamanımızı ve birlikte yaşama ölçeğimizi sessizce yeniden biçimlendirmesidir.",
))


MORE_BOOKS.append(make_book(
    214, "teknik-yeniden-uretim-caginda-sanat-eseri", "Teknik Yeniden Üretim Çağında Sanat Eseri", "Walter Benjamin",
    "Fotoğraf ve sinemanın sanat eserini tek ve uzak kutsal nesne olmaktan çıkarıp kitlelerin dolaşımına sokarken aura, otantiklik, siyaset ve algıyı nasıl değiştirdiğini anlatan kısa ama olağanüstü etkili deneme.",
    "#5E535D", "The Work of Art in the Age of Mechanical Reproduction",
    [
        {"id": 1, "title": "Marxists Internet Archive - The Work of Art", "url": "https://www.marxists.org/reference/subject/philosophy/works/ge/benjamin.htm"},
        {"id": 2, "title": "Stanford Encyclopedia of Philosophy - Walter Benjamin", "url": "https://plato.stanford.edu/entries/benjamin/"},
        {"id": 3, "title": "Encyclopaedia Britannica - Walter Benjamin", "url": "https://www.britannica.com/biography/Walter-Benjamin"},
    ],
    [
        chapter("Biricik eserin burada ve şimdisi", "BAŞLANGIÇ · OTANTİKLİK",
            "Geleneksel sanat eseri belirli yerde, belirli tarihte bulunur. Taşıdığı çatlak, sahiplik yolu ve fiziksel varlık onun 'burada ve şimdi'sini kurar.",
            "Müzedeki tablonun önünde durmakla aynı görüntüyü telefonda görmek aynı bilgiye yaklaşabilir, aynı karşılaşma değildir. Ölçek, mekân ve yolculuk deneyime katılır.",
            "Biriciklik her zaman üstün estetik demek değildir; sahte eser de güzel olabilir. Benjamin'in konusu değer yargısından çok toplumsal otorite değişimidir.",
            "Dijital kopya çağında orijinalin neden hâlâ kalabalık çektiğini anlamak için burada ve şimdi fikri güçlüdür.",
            "here-and-now", "Orijinal eser, görüntüsüne ek olarak belirli yerde ve tarihte bulunmuş olmanın eşsiz izini taşır."),
        chapter("Aura nedir?", "BİRİNCİ KISIM · AURA",
            "Aura, bir şey ne kadar yakında olsa da taşıdığı eşsiz uzaklık ve otorite hissidir. Dağın ufuktaki çizgisi veya eski eserin sessiz varlığı kolayca tüketilemeyen mesafe kurar.",
            "Ünlü bir kişinin el yazısı mektubu ile taranmış kopyası aynı kelimeleri taşır; fakat elin ve zamanın izi ilkinde farklı bir yakınlık-uzaklık duygusu yaratır.",
            "Aura mistik sis değil, tarih, ritüel ve biricikliğin toplumsal etkisidir. Her orijinal otomatik değerli, her kopya değersiz değildir.",
            "Sınırlı üretim ve NFT pazarı bugün yapay aura üretmeye çalışır; kıtlık teknik olarak yeniden tasarlanır.",
            "aura-distance", "Aura, eserin fiziksel yakınlığına rağmen tarih ve biriciklikten doğan dokunulmaz mesafe hissidir."),
        chapter("Kopya orijinale ne yapar?", "BİRİNCİ KISIM · YENİDEN ÜRETİM",
            "Teknik kopya eseri bulunduğu yerden çıkarır, farklı boyut ve bağlamlarda çoğaltır. Orijinalin otoritesi azalırken görüntünün erişimi olağanüstü artar.",
            "Katedral freski yalnız oraya gidenin göreceği nesneyken kitap sayfasına ve ekrana gelir. Görüntü yolculuk eder, izleyici artık ona gitmek zorunda değildir.",
            "Kopya ayrıntıyı büyütüp çıplak gözün görmediğini gösterebilir. Yani yalnız kayıp değil yeni bilgi ve algı imkânıdır.",
            "Bugün yüksek çözünürlüklü tarama koruma ve eğitim sağlar; fakat bağlamdan koparılan eser sonsuz içerik akışında sıradanlaşabilir.",
            "copy-travels", "Teknik kopya eseri sabit mekânından çıkarıp milyonlara taşırken orijinalin uzak otoritesini zayıflatır."),
        chapter("Kült değerinden sergileme değerine", "BİRİNCİ KISIM · İŞLEV",
            "Eski sanat ritüelde var olmak için yapılabilir, görülmesi şart değildir. Teknik çağda eserin değeri giderek sergilenme, dolaşma ve çok kişi tarafından görülme kapasitesine bağlanır.",
            "Tapınaktaki kapalı heykel kutsallığını gizlilikten, sosyal medya fotoğrafı değerini görünürlük sayısından alır. İki nesne farklı izleyici mantığına sahiptir.",
            "Kült ve sergileme değeri tamamen ayrı dönemler değildir; müze de ritüel yaratır, dini görüntü de çoğaltılabilir.",
            "Bugünün sanatçısı yalnız eser üretmez, dolaşım ve görünürlük stratejisi de kurar. Platform sergileme değerinin yeni kapısıdır.",
            "cult-to-exhibition", "Gizli kutsal nesnenin değeri ritüelden, çoğaltılan modern görüntünün değeri geniş sergilenmeden doğabilir."),
        chapter("Fotoğraf gözün alışkanlığını kırıyor", "İKİNCİ KISIM · FOTOĞRAF",
            "Fotoğraf anı dondurur, ayrıntıyı büyütür ve insan gözünün hızla geçtiği şeyi incelemeye açar. Benjamin buna optik bilinçdışı fikriyle yaklaşır.",
            "Koşan atın ayaklarını tek karede görmek, çıplak gözün sürekli harekette ayıramadığı düzeni görünür kılar. Kamera yalnız kopyalamaz, keşfeder.",
            "Kamera tarafsız göz değildir; açı, kesme ve zaman seçimi anlam üretir. Görünmeyeni açarken başka şeyi dışarıda bırakır.",
            "Telefon kamerası gündeliğin bilinçdışını arşivliyor, fakat sürekli çekim anı yaşamaktan çok kaydetmeye de yöneltebilir.",
            "optical-unconscious", "Kamera hareketi dondurup ayrıntıyı büyüterek çıplak gözün fark etmediği optik bilinçdışını açar."),
        chapter("Film oyuncusu kime oynar?", "İKİNCİ KISIM · SİNEMA",
            "Tiyatro oyuncusu canlı izleyicinin karşısındadır; film oyuncusu kamera ve montaj için parçalı performans verir. Seyirciyle doğrudan aura ilişkisi teknik aygıt tarafından kesilir.",
            "Oyuncu sahneyi sabah sonundan, öğlen başından çekebilir. Montaj sürekliliği sonra kurar. Performans tek akış değil seçilmiş parçalardır.",
            "Sinema yıldız sistemi kaybolan aurayı kişilik kültüyle yeniden üretebilir. Kopyalanabilir yüz başka türden biriciklik pazarı kurar.",
            "Kısa video çağında herkes kamera önünde kendi oyuncusu ve montajcısı olur; benlik performansı teknik parçalarla yeniden kurulur.",
            "actor-camera", "Film oyuncusu canlı salona değil, performansı parçalayıp yeniden kuracak kamera ve montaj aygıtına oynar."),
        chapter("Montaj yeni düşünce kurar", "İKİNCİ KISIM · SİNEMA",
            "Film farklı görüntüleri yan yana getirerek tek karede bulunmayan anlam yaratır. Montaj yalnız birleştirme değil düşünce yöntemidir.",
            "Boş tabak görüntüsünü ağlayan çocukla yan yana koyunca yoksulluk, lüks sofrayla koyunca israf anlamı doğar. Kare aynı, komşusu değişmiştir.",
            "Montaj propaganda için de kullanılabilir; izleyici bağlantının doğal olay mı kurgu mu olduğunu unutabilir.",
            "Haber ve sosyal medya akışında bir görüntünün öncesi-sonrası kadar hangi görüntüyle yan yana getirildiğini incelemek gerekir.",
            "montage-meaning", "Aynı görüntü farklı komşu karelerle bambaşka siyasi ve duygusal anlam kazanabilir."),
        chapter("Kameranın cerrah bakışı", "İKİNCİ KISIM · AYGIТ",
            "Ressam gerçeklikle sihirbaz gibi mesafe korurken kameraman cerrah gibi görüntünün içine girer, keser ve parçaları yeniden birleştirir. Teknik aygıt dünyayı işlemden geçirir.",
            "Yakın çekim yüzdeki küçük titremeyi dev sahneye çevirir; kamera insanın doğal mesafesini değiştirir. Görmek bedenin olağan konumundan kopar.",
            "Benzetme ressamın da seçtiğini, kameranın da bütün gerçekliği kaydetmediğini unutturmamalıdır. İki araç farklı seçim rejimleridir.",
            "Drone, gözetim kamerası ve tıbbi görüntü bugün cerrah bakışını yeni ölçeklere taşır; erişim gücü etik denetim ister.",
            "camera-surgeon", "Kamera gerçekliğe uzaktan bakmakla kalmaz, içine girip parçalayarak yeni bir görme düzeni kurar."),
        chapter("Şok ve parçalanmış dikkat", "İKİNCİ KISIM · ALGI",
            "Hızlı kesme, yakın çekim ve ani değişim izleyiciyi sürekli küçük şoklarla uyarır. Sinema modern şehrin trafik, reklam ve kalabalık ritmine uygun yeni algı eğitimi sunar.",
            "Sakin odadan yoğun kavşağa çıktığınızda göz sürekli yeni tehlikeye sıçrar. Film montajı bu kentsel sıçramayı salonda yeniden üretir.",
            "Şok uyanıklık yaratabilir, derin düşünceyi de parçalayabilir. Benjamin ikili sonucu açık tutar.",
            "Kısa video akışı şoku sonsuz hale getirir; izleyici şaşırır ama şaşkınlık normalleşince hiçbir görüntü uzun süre kalmaz.",
            "shock-attention", "Modern montaj ve şehir ritmi dikkati sürekli küçük şoklarla bir görüntüden diğerine sıçratır."),
        chapter("Kitle halinde farklı bakmak", "ÜÇÜNCÜ KISIM · KİTLE",
            "Müze eseri tekil yoğunlaşma isterken sinema kitlesi birlikte ve dağınık dikkatle izler. Benjamin dağınıklığı yalnız düşüş değil yeni alışkanlık edinme yolu sayar.",
            "Bir binayı kitap okuyarak değil içinde dolaşıp kapıları kullanarak öğrenirsiniz. Mimari, dikkat etmeden tekrar edilen beden hareketiyle kavranır.",
            "Dağınık dikkat reklam ve propaganda için açık kapıdır. Tekrar edilen görüntü sorgulanmadan normalleşebilir.",
            "Arka planda akan ekran çağında neyi yoğun dikkatle, neyi alışkanlıkla öğrendiğimizi ayırmak medya sağlığı için önemlidir.",
            "mass-viewing", "Kitle, filmi tekil tefekkürden farklı olarak ortak ve parçalı dikkat içinde beden alışkanlığıyla öğrenebilir."),
        chapter("Sanatın siyasallaşması", "ÜÇÜNCÜ KISIM · SİYASET",
            "Aura gerileyince sanat ritüelden kurtulup siyasete açılır. Görüntü daha çok insana ulaşır; işçi ve sıradan yaşam temsil edilebilir, sanat ortak tartışmanın aracı olur.",
            "Duvarın arkasındaki tabloya yalnız seçkinler ulaşırken ucuz baskı mahalleye gelir. Erişim yeni seyirci ve yeni konu yaratır.",
            "Siyasallaşma tek doğru parti çizgisine bağlanırsa sanat propaganda aracına indirgenebilir. Eleştirel çoğulluk korunmalıdır.",
            "Açık lisans, çevrimiçi arşiv ve yurttaş videosu erişimi genişletir; görünürlük algoritması yeni kapı bekçisi haline gelir.",
            "art-to-public", "Çoğaltılan sanat ritüel odasından çıkıp geniş kitlelerin siyasi tartışmasına ve gündelik deneyimine açılır."),
        chapter("Faşizm siyaseti estetikleştirir", "ÜÇÜNCÜ KISIM · FAŞİZM",
            "Benjamin faşizmin kitlelere hak vermeden kendilerini ifade etme gösterisi sunduğunu söyler. Miting, üniforma ve savaş siyaseti büyüleyici estetik sahneye dönüşür.",
            "İnsanlar karar masasına oturamaz ama dev geçitte kendilerini güçlü bütünün parçası hisseder. Görüntü katılımın yerini alır.",
            "Estetik tek başına faşist değildir; sorun güzelliğin eleştiriyi uyuşturup şiddeti yüce deneyim olarak sunmasıdır.",
            "Siyasi videoda biçim bizi büyülerken hangi hak, bütçe ve kararın saklandığını sormak estetikleştirmeye karşı frendir.",
            "aestheticized-politics", "Otoriter gösteri yurttaşa gerçek karar gücü vermeden onu görkemli siyasi sahnenin parçası gibi hissettirebilir."),
        chapter("Savaş sanat eserine dönüşürse", "ÜÇÜNCÜ KISIM · YIKIM",
            "Faşizmin estetik siyasetinin doruğu savaştır: Teknoloji, hız ve kitle seferberliği güzellik olarak sunulur; insanlığın kendi yıkımını seyretmesi mümkün hale gelir.",
            "Gece göğündeki füze görüntüsü teknik olarak etkileyici olabilir, fakat estetik hayranlık yerdeki ölüm ve yıkımı kadraj dışına iter.",
            "Benjamin'in dili keskindir; her savaş görüntüsü şiddeti övmez. Belgesel tanıklık ve suç kanıtı da olabilir.",
            "Görüntünün kimin açısından çekildiği ve insan maliyetini gösterip göstermediği, savaş estetiğini değerlendirmenin temelidir.",
            "war-as-spectacle", "Teknik görkem savaşın insan yıkımını örterse toplum kendi felaketini estetik gösteri gibi seyredebilir."),
        chapter("Demokratik erişim ile değer kaybı", "DÖRDÜNCÜ KISIM · İKİLİ SONUÇ",
            "Çoğaltma seçkin erişimi kırar, eğitim ve eleştiri imkânı verir. Aynı süreç görüntüyü sonsuz akışta sıradanlaştırıp dikkat süresini kısaltabilir.",
            "Dünyanın bütün müzeleri cebinizdeyken daha çok eser görebilir, hiçbirinin önünde iki dakika durmayabilirsiniz. Erişim ve karşılaşma aynı değildir.",
            "Benjamin kayıp auraya yalnız yas tutmaz; demokratik potansiyeli önemser. İki sonucu birlikte görmek gerekir.",
            "Dijital arşiv tasarımı yalnız dosya açmak değil bağlam, yavaş bakış ve kaynak bilgisi de sunmalıdır.",
            "museum-in-pocket", "Müze cebimize girince erişim büyür, fakat sonsuz görüntü akışı tek eserle uzun karşılaşmayı zayıflatabilir."),
        chapter("Dijital kopyada orijinal nerede?", "GÜNÜMÜZ · DİJİTAL",
            "Dijital dosyada kopya ile orijinal bit düzeyinde aynı olabilir. Biriciklik fiziksel nesneden çok kaynak kaydı, imza, platform ve topluluk kararıyla kurulmaya başlar.",
            "Aynı fotoğraf milyon telefonda bulunur; 'ilk dosya' gözle ayırt edilemez. Otantiklik görüntünün içinde değil kayıt zincirindedir.",
            "NFT gibi araçlar kopyalanabilir görüntüye sahiplik kaydı ekler, fakat estetik biricikliği otomatik geri getirmez.",
            "Dijital kültürde kaynak doğrulama, bağlam ve manipülasyon izi yeni burada-şimdi biçimlerini oluşturur.",
            "digital-original", "Dijital eserde biriciklik görüntünün gözle görülür farkından çok kaynak ve kayıt zincirine taşınır."),
        chapter("Yapay zekâ çağında aura", "GÜNÜMÜZ · ÜRETİM",
            "Üretken yapay zekâ saniyeler içinde sayısız benzer görüntü oluşturduğunda ustalık, emek izi ve özgünlük yeniden tartışılır. Görselin nadirliği azalırken seçim ve bağlam önem kazanır.",
            "Bin resim üretebilen makine karşısında değer yalnız üretim zorluğundan değil hangi görüntünün neden seçildiği ve nasıl kullanıldığından doğabilir.",
            "Eğitim verisi, sanatçı emeği ve izin soruları teknik büyünün arkasındaki politik ekonomidir. Yeniden üretim artık mevcut eseri değil üslup olasılığını çoğaltır.",
            "Benjamin'in sorusu güncellenir: Yeni erişim kimi güçlendiriyor, hangi emeği görünmez yapıyor ve eleştirel algıyı nasıl değiştiriyor?",
            "ai-aura", "Sınırsız üretilebilir görüntü çağında değer nadir nesneden seçim, bağlam, kaynak ve görünmez emek tartışmasına kayar."),
    ],
    misreading="Benjamin yalnız 'kopya kötüdür, aura kayboldu' diye nostalji yapmaz. Aura kaybının demokratik erişim ve yeni siyasi sanat imkânı yarattığını da savunur. Teknik üretimin otomatik özgürleştirici olduğunu düşünmek de aynı derecede yanlıştır.",
    modern="Dijital dosya, sosyal medya, NFT ve üretken yapay zekâ biriciklik ile kopya ilişkisini daha da karmaşıklaştırdı. Denemenin film merkezli bazı ayrıntıları eskise de görünürlük, kaynak, dikkat ve siyasetin estetikleştirilmesi kavramları olağanüstü günceldir.",
    questions="Bu görüntünün burada ve şimdi değeri nereden geliyor? Çoğaltma erişimi kimler için büyütürken hangi bağlamı siliyor? Estetik biçim hangi siyasi hak ve insan maliyetini görünmez kılıyor?",
    essence="Teknik çoğaltma sanatın biricik aura ve ritüel otoritesini zayıflatırken onu kitlelere ve siyasete açar; bu açılım hem demokratik imkân hem yeni propaganda gücü taşır.",
))
