#!/usr/bin/env python3
"""Build wave 8, books 168 and 210."""

from eighty_summary_common import topic as t, write_specs
from build_eighty_wave_6a import book


SPECS = [
book(168,"21-yuzyilda-sermaye","21. Yüzyılda Sermaye","Thomas Piketty","Capital in the Twenty-First Century","#5F7B55",
"Servet ve gelirin yüzyıllar boyunca nasıl bölüşüldüğünü vergi kayıtları ve romanlardan izleyip yavaş büyüyen toplumlarda mirasın yeniden belirleyici olabileceğini anlatan büyük eşitsizlik haritası.",
"Bir aile maaşından her ay biraz biriktirir; başka aile büyük bir apartman miras alır. Ekonomi yılda yüzde bir büyürken servet yüzde dört getiri sağlarsa aradaki fark çalışkanlık hikâyesinden daha hızlı açılabilir. Piketty bu basit gerilimi iki yüzyıllık veriye taşır.",
"Kitap Fransa, Britanya, ABD ve başka ülkelerin gelir, vergi ve miras kayıtlarını uzun dönem karşılaştırır. Rehber sermaye-gelir oranı, getiri, büyüme, miras, süper yöneticiler ve vergi önerilerini açar; r>g ifadesini değişmez doğa yasası saymaz.",
"Jane Austen romanında yıllık gelir kişinin toplumsal yerini hemen anlatır. Piketty bu ayrıntıyı süs olarak değil, on dokuzuncu yüzyılda servet stokunun ve miras gelirinin gündelik hayatta ne kadar görünür olduğuna açılan pencere olarak kullanır.",
[{"id":1,"title":"Harvard University Press - Capital Contents","url":"https://www.degruyterbrill.com/document/doi/10.4159/9780674982918-toc/html?lang=en"},{"id":2,"title":"World Inequality Database","url":"https://wid.world/"}],
[
("Eşitsizliği ölçmek neden zor?","BİRİNCİ KISIM · VERİ","Hane anketleri en zenginleri kaçırabilir; uzun dönem vergi ve miras kayıtları tepedeki yoğunlaşmayı daha iyi gösterebilir","Bin kişilik ankette milyarder çıkmaz ama vergi tablosunun en üst diliminde görünür","Vergi kaçırma ve değişen tanımlar veriyi kusursuz yapmaz","Kaynak, kapsam ve ölçüm değişimini açıkça belirtmek gerekir"),
("Gelir ile servet aynı değildir","BİRİNCİ KISIM · AYRIM","Gelir belirli dönemde akan maaş, kâr ve kiradır; servet geçmişten biriken varlıkların stokudur","Aylık maaş musluktan akan su, ev ve hisse depodaki su gibi düşünülebilir","Borç ve kamu serveti hesaba katılmadan stok yanıltır","Akışla birikimi ve brütle net serveti ayırmak gerekir"),
("Sermaye-gelir oranı","BİRİNCİ KISIM · ÖLÇEK","Bir toplumun toplam özel servetinin yıllık gelire oranı ekonomik ağırlığın basit göstergesidir","Servet altı yıllık milli gelire eşitse oran yüzde altı yüzdür","Oran servetin kimde olduğunu tek başına söylemez","Toplam büyüklüğü dağılım ve varlık türüyle birlikte okumak gerekir"),
("Birinci temel yasa: pay = getiri × stok","İKİNCİ KISIM · BAĞ","Sermayenin milli gelirden aldığı pay, sermaye-gelir oranıyla ortalama getiri oranının çarpımına eşit muhasebe ilişkisidir","Servet beş yıllık gelir, getiri yüzde dörtse sermaye payı yaklaşık yüzde yirmi olur","Bu eşitlik davranışın nedeni değil tanımıdır","Muhasebe bağını ekonomik açıklama diye sunmamak gerekir"),
("Uzun dönemde beta = s/g","İKİNCİ KISIM · BİRİKİM","Tasarruf oranı yüksek, büyüme düşük olduğunda geçmiş servetin yıllık gelire oranı zamanla yükselme eğilimindedir","Yüzde on tasarruf ve yüzde iki büyüme kabaca beş yıllık gelir büyüklüğünde stok doğurur","Savaş, fiyat ve değerleme geçişi ilişkiyi bozabilir","Uzun dönem eğilimini kısa yıl tahmini gibi kullanmamak gerekir"),
("U biçimli tarih","İKİNCİ KISIM · TARİH","Avrupa'da servet-gelir oranları on dokuzuncu yüzyılda yüksek, savaşlar ortasında düşük, yirminci yüzyıl sonunda yeniden yükselen yol izledi","Savaş yıkımı, enflasyon ve vergi büyük servetleri küçültür; barışta stok yeniden birikir","Her ülke aynı eğriyi yaşamaz","Ulusal savaş, konut ve emeklilik yapısını ayrı incelemek gerekir"),
("Savaşlar eşitliği nasıl değiştirdi?","İKİNCİ KISIM · ŞOK","1914-1945 dönemi yalnız fiziksel yıkımla değil enflasyon, kamulaştırma, borç ve yüksek vergilerle eski servetleri sarstı","Sabit gelirli tahvil enflasyonda erir, büyük miras yüksek vergiyle bölünür","Felaket eşitlik politikası diye övülemez","Barışçıl kurumların aynı sonucu nasıl sağlayabileceğini düşünmek gerekir"),
("r > g ne anlatır?","ÜÇÜNCÜ KISIM · GERİLİM","Servetin ortalama getirisi ekonominin büyüme hızından uzun süre yüksekse geçmiş birikim yeni gelirden daha hızlı büyüyebilir","Miras portföyü yüzde dört, maaş ekonomisi yüzde bir büyürse servet ağırlığı artar","İfade kaçınılmaz yasa değildir; vergi, risk, tüketim ve siyaset etkiler","Oranların hangi dönem ve dağılım için geçerli olduğunu sormak gerekir"),
("Mirasın geri dönüşü","ÜÇÜNCÜ KISIM · KUŞAK","Düşük büyüme ve büyük servet stoku, yaşam boyu çalışmadan çok doğumla gelen varlığın önemini artırabilir","İki eşit yetenekli gençten biri ev borcu, diğeri kiralık daire mirasıyla başlar","Aile desteğinin tümü haksız veya parasal değildir","Fırsat eşitliğiyle kuşak dayanışmasını dengeli tasarlamak gerekir"),
("Balzac ve Rastignac'ın hesabı","ÜÇÜNCÜ KISIM · ROMAN","Balzac'ın kahramanı küçük maaşlı kariyer ile zengin evlilik arasında seçim yaparken miras toplumunun matematiğini görünür kılar","Yıllarca çalışmak tek evlilikle gelen gelirin yanına yaklaşmaz","Roman istatistik örneklemi değildir","Edebi sahneyi kayıtların gösterdiği yapıyla karşılaştırmak gerekir"),
("ABD neden farklı göründü?","DÖRDÜNCÜ KISIM · ÜCRET","ABD'de yirminci yüzyıl sonu eşitsizliğinin önemli bölümü servetten önce en üst yönetici ücretlerinin sıçramasıyla büyüdü","Şirket yöneticisi ortalama çalışanın yüzlerce katı ücret alır","Yetenek ve küresel piyasa etkisi tümüyle yok değildir","Ücret belirleme gücü, vergi ve performans bağını birlikte ölçmek gerekir"),
("Süper yöneticiler","DÖRDÜNCÜ KISIM · GÜÇ","Üst ücretler yalnız marjinal verimle değil yönetim kurulu, toplumsal norm ve pazarlık gücüyle belirlenebilir","Yönetici kendi ücretini onaylayan çevre üzerinde etki taşır","Her yüksek ücret haksız değildir","Benzer performanslı ülke ve şirketlerle karşılaştırmak gerekir"),
("Kuznets eğrisi neden yetmedi?","DÖRDÜNCÜ KISIM · İYİMSERLİK","Eşitsizliğin kalkınmayla kendiliğinden yükselip sonra düşeceği görüşü savaş sonrası sınırlı dönemi evrenselleştirmiş olabilir","1950'lerin düşüşü kalıcı ekonomik yasa sanılır","Kuznets'in kendi ihtiyatı popüler slogandan daha geniştir","Dönem seçiminin sonucu nasıl değiştirdiğini incelemek gerekir"),
("İlerici gelir ve miras vergisi","BEŞİNCİ KISIM · POLİTİKA","Yüksek ödeme gücüne daha yüksek oran uygulamak yoğunlaşmayı sınırlayıp kamusal yatırım finanse edebilir","Büyük mirasın bir bölümü eğitim ve sağlık altyapısına döner","Aşırı oran kaçınma ve yatırım etkisi yaratabilir","Oranı taban, denetim ve uluslararası uyumla birlikte tasarlamak gerekir"),
("Küresel servet vergisi","BEŞİNCİ KISIM · ÖNERİ","Servetin ülkeler arasında saklandığı dünyada yıllık artan oranlı vergi hem gelir hem şeffaflık aracı olabilir","Varlık kaydı daire, şirket ve fon mülkiyetini görünür kılar","Küresel uygulama siyasi olarak çok zordur","Bölgesel kayıt, bilgi paylaşımı ve kademeli hedefler düşünmek gerekir"),
("Veri devrimi ve açık tartışma","ALTINCI KISIM · MİRAS","Kitabın kalıcı katkısı tek formülden çok eşitsizliği tarihsel veriyle demokratik tartışmanın konusu yapmasıdır","Vergi tabloları uzman çekmecesinden çıkıp herkesin görebileceği grafiklere dönüşür","Veri değer yargısını kendisi vermez","Ölçümün ardından hangi eşitlik anlayışını istediğimizi açıkça tartışmak gerekir"),
],
"Piketty r>g ifadesini her çağda mekanik biçimde çalışan ve devrimi zorunlu kılan yasa olarak sunmaz. Bu bir yoğunlaşma gücüdür; savaş, vergi, kurum, tasarruf ve siyaset yönünü değiştirebilir.",
"Getiri yüzde beş diye her servet sahibi zenginleşmez; tüketim, borç, risk ve vergi vardır. Önemli olan büyük portföylerin ortalama olarak daha iyi çeşitlenip yeniden yatırıma girebilmesidir.",
"Kitap eşitsizlik araştırmasını geniş kamuoyuna taşıdı, tarihsel veriyi büyüttü ve servet yoğunlaşmasını yirmi birinci yüzyıl siyasetinin merkezine yerleştirdi.",
"Sermaye tanımına konutun dahil edilmesi, r>g'nin nedensel gücü, vergi verisindeki düzeltmeler, teknoloji ve kurumlara verilen ağırlık ile politika önerilerinin uygulanabilirliği yoğun biçimde eleştirildi.",
"Akış mı stok mu ölçüyorum? Getiri ve büyüme hangi dönem için karşılaştırılıyor? Dağılımın tepesini veri gerçekten görüyor mu?",
"İki hayali ailenin on yıllık bütçesini kurun: biri yalnız maaş, diğeri maaş ve mirasla başlasın; büyüme ve getiriyi ayrı uygulayıp farkı izleyin.",
"Büyüme yavaşken geçmiş servetin getirisi daha hızlı ilerlerse miras ve birikmiş varlıkların ağırlığı artabilir; bu eğilim doğa kaderi değil vergi ve kurumlarla biçimlenen siyasi tercihtir.",
"orman yeşili, bakır ve gece mavisi tonlarında biri maaş merdiveni, diğeri miras asansörüyle yükselen iki ailenin ardında yüzyıllık servet nehrinin büyüyüp daraldığı tarih sahnesidir"),

book(210,"kultur-ve-emperyalizm","Kültür ve Emperyalizm","Edward Said","Culture and Imperialism","#9B6545",
"Roman, opera ve tarih anlatılarının imparatorluktan uzakta masum dünyalar olmadığını; sömürge coğrafyası, emek ve direnişle aynı kültürel haritanın içinde okunması gerektiğini gösteren büyük eleştiri.",
"İngiliz kır evinde çay içilen sakin bir roman sahnesini düşünün. Masanın, şekerin ve gelirin bir kısmı uzak adalardaki plantasyonlara bağlı olabilir; metin bunu yalnız bir cümleyle geçer. Said o uzaklığı sahnenin kenarından merkeze taşır.",
"Kitap Austen, Dickens, Conrad, Kipling, Verdi ve başka eserleri imparatorluk tarihiyle karşılıklı okur. Rehber kültür, coğrafya, karşıezgisel okuma, direniş, milliyetçilik ve kurtuluşu açar; sevilen bir romanı yalnız propaganda belgesine indirmez.",
"Müzikte iki melodi aynı anda ilerler; biri duyulurken diğeri kaybolmaz. Said'in karşıezgisel okuması da metropol kahramanının hikâyesiyle sömürgeleştirilen yerdeki emek, kayıp ve direnişi aynı anda duymaya çalışır.",
[{"id":1,"title":"Penguin - Culture and Imperialism Sample","url":"https://cdn.penguin.co.uk/dam-assets/books/9781529942125/9781529942125-sample.pdf"},{"id":2,"title":"Penguin - Culture and Imperialism","url":"https://www.penguin.co.uk/books/57467/culture-and-imperialism-by-edward-w-said/9780099967507"}],
[
("Kültür neden siyasetten ayrı değildir?","BİRİNCİ KISIM · BAĞ","Seçkin sanat kendi estetik düzenine sahip olsa da üretildiği toplumun coğrafya, emek ve iktidar ilişkilerinden bütünüyle kopuk değildir","Kır evi romanının geliri uzak plantasyondan gelebilir","Bağ bulmak eseri tek nedene indirmez","Biçimsel güzellikle maddi koşulu aynı anda okumak gerekir"),
("İmparatorluk bir fikir ortamıdır","BİRİNCİ KISIM · HAYAL","Uzak toprakları yönetmenin doğal ve yararlı olduğu inancı askerî işgalden önce kültürel anlatılarda hazırlanabilir","Harita boş alanı keşfedilecek ve düzenlenecek yer gibi gösterir","Her seyahat hikâyesi bilinçli propaganda değildir","Tekrarlanan üstünlük varsayımının eyleme nasıl zemin verdiğini izlemek gerekir"),
("Karşıezgisel okuma","BİRİNCİ KISIM · YÖNTEM","Metni hem metropolün hem sömürgeleştirilen coğrafyanın tarihiyle eşzamanlı okuyarak sessiz bağlantıları duymak gerekir","İngiliz miras hikâyesinin yanında Antigua'daki emeğin ritmi izlenir","Yöntem metinde olmayan her şeyi keyfî ekleme izni vermez","Tarihsel bağ ve metinsel işareti açık göstermek gerekir"),
("Mansfield Park ve Antigua","İKİNCİ KISIM · AUSTEN","Sir Thomas'ın İngiliz malikânesi ile Antigua mülkü arasındaki kısa bağ ev düzeninin sömürge ekonomisinden bağımsız olmadığını açar","Evdeki otoriteyi sağlayan servetin uzak kaynağı birkaç sözle görünür olur","Romanın tamamı kölelik hakkında alegori değildir","Kenar ayrıntısının yapısal işlevini abartmadan izlemek gerekir"),
("Harita çizmek sahip olmak mı?","İKİNCİ KISIM · COĞRAFYA","Adlandırma, ölçme ve haritalama toprağı yönetilebilir nesneye dönüştürerek emperyal denetime eşlik eder","Yerel ad silinir, sınır cetvelle çizilir ve boş bölge hissi yaratılır","Harita aynı zamanda yerel savunma ve bilgi aracı olabilir","Kimin çizdiğini, neyi dışarıda bıraktığını sormak gerekir"),
("Conrad'ın karanlık ikiliği","İKİNCİ KISIM · CONRAD","Conrad imparatorluğun şiddet ve ikiyüzlülüğünü açarken sömürgeleştirilen kişiyi tam konuşan özne yapmaktan da uzak kalabilir","Kurtz'un çöküşü görünür, Afrikalıların dünyası çoğu kez fon olur","Eleştirel eser kendi döneminin sınırlarını taşıyabilir","İtirazı takdir ederken susturduğu sesi de aramak gerekir"),
("Kipling ve hizmet görevi","İKİNCİ KISIM · GÖREV","İmparatorluk kendini kaba çıkar yerine düzen, eğitim ve ağır bir görev diliyle meşrulaştırabilir","Yönetici başkasının iyiliği için hükmettiğini söyler","Gerçek hizmet ve altyapı baskıyı otomatik temizlemez","Yardımın karar hakkını kime bıraktığını sormak gerekir"),
("Aida'nın sahnesi","ÜÇÜNCÜ KISIM · OPERA","Verdi'nin Aida'sı estetik ihtişam, Mısır temsili ve modern Avrupa'nın Doğu ilgisi arasında okunabilir","Sahnedeki egzotik görkem çağdaş imparatorluk sergileriyle yankılanır","Eser tek sipariş ve niyetle açıklanamaz","Müzik biçimi, üretim tarihi ve temsil politikasını ayrı katmanlarda görmek gerekir"),
("Roman neden imparatorluğa uygundu?","ÜÇÜNCÜ KISIM · BİÇİM","Roman geniş zaman, yolculuk ve toplumsal bütün kurma yeteneğiyle uzak coğrafyaları metropol hayatına bağlayabilir","Kahraman denizaşırı yere gider, servetle döner ve ev düzeni tamamlanır","Roman biçimi zorunlu olarak emperyal değildir","Hangi anlatının kimin hareketini merkez yaptığını incelemek gerekir"),
("Örtüşen topraklar, iç içe tarihler","ÜÇÜNCÜ KISIM · BAĞLANTI","Sömürgeci ile sömürgeleştirilen ayrı kapalı kültürler değil, zor eşitsizliği içinde birbirini değiştiren tarihlerin parçasıdır","Dil, yemek ve siyaset iki yönde taşınır ama güç eşit dağılmaz","Karışım sömürge şiddetini önemsizleştirmez","Etkileşimle eşitsizliği aynı cümlede tutmak gerekir"),
("Direniş kültürü","DÖRDÜNCÜ KISIM · KARŞI SES","Sömürgeleştirilen toplumlar yalnız baskının nesnesi değil, kendi tarihini ve coğrafyasını yeniden anlatan etkin öznelerdir","Yasaklanan dil şiir ve okulda geri alınır","Her direniş tek ve saf halk sesi değildir","İç sınıf, cinsiyet ve siyasi ayrılıkları görünür tutmak gerekir"),
("Ulusal kurtuluşun gücü","DÖRDÜNCÜ KISIM · BAĞIMSIZLIK","Milliyetçilik dağınık deneyimleri ortak mücadelede birleştirip sömürge egemenliğine karşı siyasi güç yaratabilir","Farklı bölgeler tek bağımsızlık hedefinde buluşur","Birlik dili azınlık ve muhalifi susturabilir","Kurtuluş hedefiyle çoğul yurttaşlığı birlikte kurmak gerekir"),
("Milliyetçiliğin kapanı","DÖRDÜNCÜ KISIM · SINIR","Bağımsızlık sonrası yönetici elit eski merkezî devlet ve dışlama biçimlerini ulusal adla sürdürebilir","Bayrak değişir ama köylünün söz hakkı ve ekonomik yapı aynı kalır","Sömürge mirası yeni yönetimin sorumluluğunu silmez","Kimin yararlandığını ve kurumun gerçekten değişip değişmediğini sormak gerekir"),
("Fanon ve kurtuluşun ötesi","DÖRDÜNCÜ KISIM · İNSANLIK","Fanon ulusal bağımsızlığın yeni toplumsal insanlık ve eşitlik projesine açılmadığında dar elit düzenine dönebileceğini uyarır","Başkentte yeni sınıf eski sömürge villasına yerleşir","Fanon'un şiddet dili ayrı etik tartışma gerektirir","Kurtuluş aracını sonraki özgür toplum ölçüsüyle sınamak gerekir"),
("Metropole yolculuk","BEŞİNCİ KISIM · İÇERİDEN SES","Sömürge dünyasından gelen yazar ve göçmen imparatorluğun merkezine girip onun kültürünü içeriden dönüştürür","Eski ders kitabının dili yeni romanda ters yönde konuşturulur","Merkezde tanınmak tek başarı ölçüsü olmamalıdır","Yerel okur, dil ve yayın ağlarını da hesaba katmak gerekir"),
("Bugünün kültürel haritası","ALTINCI KISIM · BUGÜN","Küresel dizi, müze ve algoritmik kataloglar eski imparatorluk imgelerini yeni pazar biçimlerinde dolaştırabilir","Müze nesnesi estetik başyapıt diye sergilenir, nasıl alındığı küçük etikette kalır","Her kültürel dolaşım sömürü değildir","Köken, izin, gelir ve anlatma hakkını birlikte sormak gerekir"),
],
"Said büyük romanların değersiz emperyal propaganda olduğunu söylemez. Tam tersine onları ciddiye aldığı için estetik gücün hangi tarih ve sessizliklerle birlikte işlediğini daha geniş okumak ister.",
"Mansfield Park'ta Antigua bağlantısını görmek bütün karakterleri kölelik alegorisine çevirmek değildir. Evin ekonomik zeminini ana hikâyenin yanında duymaktır.",
"Eser postkolonyal eleştirinin en etkili çalışmalarından oldu; edebiyat kanonunu coğrafya, imparatorluk ve direniş tarihiyle yeniden okumayı yaygınlaştırdı.",
"Çok geniş eser ve dönemleri tek emperyal çerçevede topladığı, seçtiği kanonun çoğunlukla Avrupa merkezli kaldığı, estetik özerkliği ve sınıf/cinsiyet ayrımlarını bazen incelttiği eleştirildi.",
"Bu kültürel eserin maddi dünyası nereden geliyor? Kenarda bırakılan coğrafya kim? Karşı sesi hangi kaynakla duyabilirim?",
"Sevdiğiniz bir roman veya filmi seçin. Ana kahramanın dünyasını mümkün kılan uzak emek, kaynak ve susturulmuş bakış için ikinci bir hikâye haritası çizin.",
"Kültür imparatorluğun dışında masum bir oda değildir; karşıezgisel okuma eserin güzelliğini silmeden metropol hikâyesiyle sömürge coğrafyasının emek, şiddet ve direnişini aynı anda duyar.",
"toprak kırmızısı, lacivert ve altın tonlarında bir roman sayfasının iki yanında İngiliz kır eviyle uzak plantasyonun aynı köklerden beslendiği, arada iki karşı melodi gibi yolların dolaştığı sahnedir"),
]


if __name__ == "__main__":
    write_specs(SPECS)
