#!/usr/bin/env python3
"""Build books 152, 156, 189, 194 and 214."""

from summary_batch_second_common import chapter, make_book, write_books


BOOKS = []


BOOKS.append(make_book(
    152, "uluslarin-dususu", "Ulusların Düşüşü", "Daron Acemoğlu & James A. Robinson",
    "Ülkelerin zenginlik farkını iklim, kültür ya da bilgisizlikten çok; geniş kesimlere fırsat veren kapsayıcı kurumlarla servet ve gücü dar çevrede toplayan sömürücü kurumların tarihsel mücadelesinde arayan canlı ekonomi-politik anlatısı.",
    "#526157", "Why Nations Fail",
    [
        {"id": 1, "title": "Why Nations Fail - Authors' book site", "url": "https://whynationsfail.com/"},
        {"id": 2, "title": "MIT Economics - Daron Acemoglu", "url": "https://economics.mit.edu/people/faculty/daron-acemoglu"},
        {"id": 3, "title": "Princeton University Press - Why Nations Fail", "url": "https://press.princeton.edu/books/paperback/9780307719225/why-nations-fail"},
    ],
    [
        chapter("Aynı şehir, iki farklı hayat", "BAŞLANGIÇ · NOGALES",
            "Nogales'in kuzeyi ABD'de, güneyi Meksika'dadır. İklim, coğrafya ve halkın kökeni benzerdir; gelir, sağlık ve güvenlik farkı ise büyüktür. Yazarlar sınırın iki yanındaki kurumlara bakar.",
            "Aynı sokağın ortasına çizgi çekip bir yanda güvenilir okul, mahkeme ve altyapı; diğer yanda keyfî yönetim bırakırsanız yıllar sonra evlerin değeri ayrışır. Toprak değil kural farkı birikir.",
            "Tek örnek bütün dünya teorisini kanıtlamaz. ABD ile Meksika'nın tarihi, dış müdahale ve bölgesel farklılıkları karmaşıktır. Nogales düşünceyi başlatan güçlü karşılaştırmadır.",
            "Bir bölgenin geriliğini insanına bağlamadan önce hak, kamu hizmeti ve karar gücünün nasıl dağıldığını sormak kitabın ilk dersidir.",
            "two-nogales", "Aynı coğrafyanın iki yanında farklı kurumlar zamanla farklı yaşam imkânları üretir."),
        chapter("Kapsayıcı kurum ne demektir?", "BİRİNCİ KISIM · KURUMLAR",
            "Kapsayıcı ekonomik kurumlar mülkiyet güvenliği, eğitim, sözleşme ve yeni işe girme imkânını geniş kesimlere açar. Siyasi kurumlar da gücü çoğul biçimde dağıtıp devleti yeterince merkezî kılar.",
            "Mahalle pazarında yalnız belediye başkanının yakını tezgâh açabiliyorsa yetenek boşa gider. Kurallar herkese açıksa daha çok kişi fikir ve emek yatırır.",
            "Kapsayıcılık kusursuz eşitlik değildir. Tarihte 'kapsayıcı' sayılan ülkeler kadınları, köleleri ve sömürgeleri dışlamıştır. Kavram derece ve mücadele içerir.",
            "Bir kurumu değerlendirirken kâğıttaki hak kadar sıradan kişinin onu gerçekten kullanıp kullanamadığına bakmak gerekir.",
            "open-market-gate", "Kapsayıcı düzen fırsat kapısını yalnız seçkinlere değil, yeni fikir ve emek getiren geniş kesimlere açar."),
        chapter("Sömürücü kurumun pompası", "BİRİNCİ KISIM · KURUMLAR",
            "Sömürücü kurumlar çoğunluğun emeğini ve kaynağını dar bir seçkin gruba taşır. Büyüme kısa süre mümkün olabilir, fakat yenilik ve güven uzun vadede zayıflar.",
            "Köyün ortak kuyusundan çıkan suyun çoğunu tek malikânenin havuzuna pompaladığınızı düşünün. Sistem çalışıyor görünür, ama tarlalar kurur ve köylü yeni kuyu açmak istemez.",
            "Her vergi ya da devlet müdahalesi sömürü değildir; mesele yükün ve karar gücünün kime hizmet ettiğidir. Kamu yatırımı ortak kapasiteyi artırabilir.",
            "Şirket veya devlet analizinde yalnız toplam büyümeye değil, kazancın kimde toplandığına ve yeninin sisteme girebilip giremediğine bakılmalıdır.",
            "extractive-pump", "Sömürücü kurum ortak üretimin suyunu dar bir seçkin havuzuna pompalarken gelecekteki üretim isteğini kurutur."),
        chapter("Merkezî devlet neden yine de gerekir?", "BİRİNCİ KISIM · SİYASİ GÜÇ",
            "Gücü dağıtmak tek başına yetmez; devletin yasa uygulayacak ve kamu hizmeti sunacak kapasitesi de olmalıdır. Aşırı zayıf merkez, yerel silahlı güçlerin ve belirsizliğin alanını açar.",
            "Hakem hiç yoksa oyun güçlü oyuncunun kuralına döner; hakem tek takıma bağlıysa da adalet bozulur. Hem yetkili hem sınırlı hakem gerekir.",
            "Merkezileşme otoriterliği otomatik haklı çıkarmaz. Kitabın dengesi, devleti güçlendirirken onu çoğul siyasi denetime bağlamaktır.",
            "Vergi toplayamayan, afet yönetemeyen ama vatandaşını sıkça cezalandıran devlet güçlü değil seçici kapasiteye sahiptir. Kapasitenin yönü önemlidir.",
            "referee-and-rules", "İşleyen toplum hem kuralı uygulayacak güçlü hakeme hem hakemin taraf tutmasını önleyecek denetime ihtiyaç duyar."),
        chapter("Coğrafya hipotezi neden yetmiyor?", "İKİNCİ KISIM · RAKİP AÇIKLAMALAR",
            "Sıcak iklim, hastalık ve toprak ekonomiyi etkiler; fakat aynı coğrafyanın farklı dönemlerde zenginleşip yoksullaşması coğrafyanın tek açıklama olamayacağını gösterir.",
            "Ev aynı yerde dururken bir yönetim döneminde atölye açılıp diğerinde kapatılıyorsa yalnız duvarlara bakmak yetmez. Kredi, güven ve izin düzeni değişmiştir.",
            "Yazarlar coğrafyanın önemini bazen fazla geri plana iter. Liman, enerji, tarım ve salgın gerçekten uzun iz bırakır. Kurumlar da maddi çevre içinde çalışır.",
            "Doğru soru 'coğrafya mı kurum mu?' değil, coğrafi fırsat ve risklerin hangi kurumlarca nasıl yönetildiğidir.",
            "same-land-new-rules", "Aynı toprak farklı kurum dönemlerinde farklı sonuç veriyorsa harita tek başına kader değildir."),
        chapter("Kültür açıklaması nerede eksik kalır?", "İKİNCİ KISIM · RAKİP AÇIKLAMALAR",
            "Din, güven ve çalışma alışkanlığı ekonomik davranışı etkileyebilir. Fakat kültürü değişmez ulusal karakter saymak, kurumların hangi davranışı ödüllendirdiğini ve kültürün zamanla değiştiğini kaçırır.",
            "Aynı insanlar göç ettikleri ülkede farklı iş kurma ve eğitim sonuçları gösterebilir. İnsan bir gecede kültürünü değiştirmez; karşılaştığı kural ve fırsat değişir.",
            "Kurum da kültürden bağımsız değildir. Güven olmadan kâğıttaki yasa işlemez; alışkanlıklar kuralları destekler veya bozar. Karşılıklı etkiyi tek yöne indirmek zayıftır.",
            "Bir toplumu tembel diye etiketlemek yerine tembelliğin rasyonel hale geldiği teşvik ve güvensizlik düzenini araştırmak daha adildir.",
            "migrant-two-systems", "Aynı kültürel geçmişe sahip insanlar farklı kurumlarda farklı ekonomik davranış ve sonuçlar gösterebilir."),
        chapter("Cehalet hipotezinin rahatlığı", "İKİNCİ KISIM · RAKİP AÇIKLAMALAR",
            "Yoksul ülke yöneticilerinin doğru ekonomi politikasını bilmediği için hata yaptığı düşünülür. Yazarlar çoğu zaman yöneticilerin yanlış politikanın kendi iktidarlarını koruduğunu gayet iyi bildiğini söyler.",
            "Fabrika sahibi verimsiz makineyi değiştirmiyor olabilir; çünkü eski makineye bağlı tedarik şirketi kendisinindir. Sorun bilgi eksikliği değil çıkar düzenidir.",
            "Bazı hatalar gerçekten cehalet, yanlış veri ve kapasite eksikliğinden doğar. Her kötü kararı kötü niyete bağlamak komplo kolaylığıdır.",
            "Politika önerisi verirken yalnız 'ne yapılmalı?' değil, mevcut düzende bunu yapmamak kimin işine geliyor sorusu da sorulmalıdır.",
            "wrong-map-profitable", "Bazen kötü politika bilinmediği için değil, verimsizliğin güçlü kişilere yarar sağladığı için sürer."),
        chapter("Sömürgecilik ve tersine dönen servet", "ÜÇÜNCÜ KISIM · TARİH",
            "Avrupalılar yoğun ve zengin yerli nüfus bulunan bölgelerde emeği sömüren kurumlar kurdu; seyrek yerleşimli bazı kolonilerde göçmenlere daha geniş haklar vermek zorunda kaldı. Eski zenginlik sıralaması zamanla tersine dönebildi.",
            "Hazır dolu depoya gelen fatih kilidi ele geçirir; boş arazide üretim için insanları çalışmaya ikna etmek zorundadır. Başlangıç nüfusu kurum biçimini etkiler.",
            "Tersine dönüş tezi güçlü ama bütün kolonileri aynı kalıba sığdırmaz. Hastalık, yerli direniş, kölelik ve küresel ticaret yolları ayrıntıyı değiştirir.",
            "Bugünkü eşitsizliği yalnız bugünün politikasına bakarak anlamak zor olabilir; mülkiyet ve vergi düzeninin sömürge kökü hâlâ çalışabilir.",
            "reversal-of-fortune", "Sömürgeciler hazır nüfusu sömürebildikleri yerde dar, yerleşim için emek çekmeleri gereken yerde daha geniş haklar kurabildi."),
        chapter("Şanlı Devrim ve pazarlık gücü", "ÜÇÜNCÜ KISIM · İNGİLTERE",
            "1688 Şanlı Devrimi parlamentonun krala karşı gücünü artırdı. Mülkiyet, vergi ve ticaret kuralları daha geniş çıkar koalisyonunun pazarlığına açıldı; yenilik için güven büyüdü.",
            "Şirket kasasının tek patronun cebinden yönetilmesiyle denetim kurulunun bütçe onayı vermesi farklıdır. Güç tek elde değil pazarlık masasında dağılır.",
            "Bu süreç halk egemenliğinin tam zaferi değildi; oy hakkı dar, sömürge ve kölelik sürdü. Kapsayıcılık kademeli ve çelişkiliydi.",
            "Kurum değişiminde kusursuz anayasa anından çok, farklı grupların birbirini sınırlayabildiği kalıcı pazarlık mekanizması önemlidir.",
            "parliament-checks-crown", "Krala karşı güçlenen parlamento, ekonomi kurallarını tek sarayın çıkarından daha geniş pazarlığa açtı."),
        chapter("Yaratıcı yıkımdan kim korkar?", "DÖRDÜNCÜ KISIM · YENİLİK",
            "Yeni teknoloji toplam refahı artırabilir ama eski ayrıcalıkları yıkar. Siyasi seçkinler güç kaybetmekten korkarsa verimli icadı engelleyebilir; ekonomik yenilik siyasi tehdide dönüşür.",
            "Matbaa kitabı ucuzlatır ama bilgiyi denetleyen kâtip ve otoritenin tekelini bozar. Yasak, teknolojinin işe yaramamasından değil fazla işe yaramasından doğabilir.",
            "Her düzenlemeyi yenilik düşmanlığı saymak yanlış olur. Güvenlik, emek ve çevre için sınır gerekebilir. Soru korumanın kamu yararı mı ayrıcalık mı olduğudur.",
            "Yapay zekâ tartışmasında da kazanan ve kaybedenlerin siyasi gücü teknolojinin hangi yönde uygulanacağını belirler.",
            "creative-destruction", "Yeni makine yalnız eski işi değil, o işin çevresindeki siyasi ayrıcalığı da tehdit ettiği için engellenebilir."),
        chapter("Kritik dönemeçte küçük fark", "DÖRDÜNCÜ KISIM · TARİHSEL SAPMA",
            "Savaş, salgın, ticaret yolu ya da teknoloji gibi kritik dönemeçler mevcut kurumları sarsar. Birbirine benzeyen toplumlar bu anda küçük güç farkları yüzünden farklı yollara girebilir.",
            "Aynı yönde giden iki tren makasta birkaç santimetrelik ray farkıyla ayrı kıtalara ulaşır. Başlangıçta küçük olan karar, geri beslemeyle büyür.",
            "Kritik dönemeç her şeyi mümkün kılmaz; geçmiş kurumlar hangi seçeneklerin masada olduğunu belirler. Tarih ne tamamen kader ne boş sayfadır.",
            "Kriz anında geçici düzenlemenin kalıcı güç dengesine dönüşebileceğini bilmek, olağanüstü yetkileri dikkatle tasarlamayı gerektirir.",
            "railway-junction", "Kritik dönemeçte küçük kurumsal fark, geri beslemeyle toplumları çok uzak yollara taşıyabilir."),
        chapter("Erdemli ve kısır döngüler", "DÖRDÜNCÜ KISIM · GERİ BESLEME",
            "Kapsayıcı kurumlar yeni gruplara güç verip daha fazla kapsayıcılık talebi doğurabilir; sömürücü kurumlar ise zenginliği siyasal güce, gücü yeni zenginliğe çevirerek kapanır.",
            "Dönen kapıya bir kez giren ayrıcalıklı kişi hem giriş ücretini alıyor hem kimin gireceğine karar veriyorsa döngü kendini besler.",
            "Döngü kırılmaz yasa değildir. Koalisyon, kriz ve liderlik yön değiştirebilir. Aksi halde reform imkânsız olurdu.",
            "Yolsuzlukla mücadelede tek kişiyi değiştirmek yerine para ile karar gücünü tekrar birbirine bağlayan döngüyü kesmek gerekir.",
            "virtuous-vicious-wheels", "Kurumlar güç ve serveti birbirine geri bağlayarak hem açılan hem kapanan döngüler yaratabilir."),
        chapter("Botsvana neden önemli örnek?", "BEŞİNCİ KISIM · AFRİKA",
            "Yazarlar Botsvana'nın bağımsızlık sonrasında daha çoğul kurumlar, sınırlı seçkin gücü ve elmas gelirini görece düzenli yönetmesiyle bölgesinden ayrıldığını anlatır.",
            "Aynı değerli kaynağa sahip iki kasabadan biri geliri okul ve yola, diğeri yönetici sarayına harcarsa kaynak aynı kalır ama gelecek ayrışır.",
            "Botsvana başarı hikâyesi eşitsizlik, yerli halk hakları ve ekonomik çeşitlenme sorunlarını silmemelidir. Örnek kusursuz model değildir.",
            "Doğal kaynak kader değil kurum sınavıdır. Gelirin kayıt, denetim ve uzun vadeli yatırıma bağlanması belirleyicidir.",
            "diamond-revenue", "Elmasın değeri aynı olabilir; onu yöneten kurum gelirden ortak kapasite ya da dar ayrıcalık üretebilir."),
        chapter("Çin büyümesi teoriyi zorluyor mu?", "BEŞİNCİ KISIM · OTORİTER BÜYÜME",
            "Çin uzun süre siyasi olarak kapsayıcı olmadan büyük ekonomik büyüme gösterdi. Yazarlar sömürücü kurumların kaynakları verimli alana yönlendirerek büyüyebileceğini, fakat yaratıcı yıkım korkusuyla sınır yaşayacağını savunur.",
            "Tek patron fabrikayı hızla modernleştirebilir; çalışanların yeni fikirle patronun yerini tehdit etmesine izin vermeyebilir. Taklit ve yatırım büyür, bağımsız yenilik sınırla karşılaşır.",
            "Çin'in devam eden teknolojik kapasitesi bu öngörüyü canlı tartışma haline getirir. Teori sonucu önceden ilan etmek yerine gelişmeyle sınanmalıdır.",
            "Otoriter verim ile özgürlük arasındaki ilişki tek yıllık büyüme rakamıyla ölçülmez; kriz düzeltme, bilgi açıklığı ve haklar da hesaba katılmalıdır.",
            "china-growth-test", "Merkezî güç hızlı yatırım sağlayabilir; aynı güç kendisini tehdit edecek bağımsız yenilik ve eleştiriyi sınırlayabilir."),
        chapter("Yardım neden bazen duvara çarpar?", "ALTINCI KISIM · POLİTİKA",
            "Dış yardım okul ve sağlık sağlayabilir; fakat yerel seçkinler kaynağı kontrol ediyorsa sömürücü düzeni güçlendirebilir. Teknik para siyasi teşviki tek başına değiştirmez.",
            "Delik kovaya daha çok su dökmek susuzluğu kısa süre azaltır ama deliği kapatmaz. Kovanın kimde olduğu da değişmiyorsa akış eski yere gider.",
            "Bu, yardımı kesmek için kolay mazeret olmamalıdır. Aşı, afet ve doğrudan hizmet hayat kurtarır. Tasarımda yerel hesap verebilirlik ve sonuç ölçümü gerekir.",
            "Reform reçetesi yalnız doğru politikayı yazmak değil, değişimden yarar görecek grupların söz ve örgüt gücünü büyütmektir.",
            "leaking-aid-bucket", "Kaynak akışı, onu yöneten çıkar düzeni değişmezse delik kovada eski ayrıcalıklara sızabilir."),
        chapter("Tek reçete neden yok?", "ALTINCI KISIM · DEĞİŞİM",
            "Kurumlar tarihsel koalisyonlardan doğduğu için başka ülkeden kopyalanan anayasa aynı sonucu vermeyebilir. Değişim, yerel güç dengesini ve kritik dönemeçleri anlamayı ister.",
            "Başka evin anahtarı sizin kapınıza benziyor diye kilidi açmaz. Dişlerin küçük farkı belirleyicidir. Kurum adı aynı, işleyişi farklı olabilir.",
            "Bu tarih vurgusu kaderciliğe dönüşmemelidir. Yurttaş örgütlenmesi, bağımsız bilgi ve kademeli denetim gerçek değişim yollarıdır.",
            "Politika danışmanlığında başarı yalnız yasa çıkarmak değil, yasanın arkasında onu koruyacak çıkar ve kapasite kurmaktır.",
            "borrowed-key", "Başka ülkenin kurumsal anahtarı, adı aynı olsa da yerel güç kilidine doğrudan uymayabilir."),
    ],
    misreading="Kitap 'iyi kurum koy, ülke hemen zenginleşir' şeklinde basit reçete vermez. Kurumlar güç mücadelesi ve tarihsel dönemeçlerden doğar. Kültür ve coğrafyayı tamamen önemsiz saymak da metnin vurgusunu aşırılaştırır; yazarların iddiası bunların tek başına yeterli olmadığıdır.",
    modern="Otoriter Çin'in yenilik kapasitesi, iklim riski ve küresel tedarik zincirleri kurum teorisini yeni sınavlara sokuyor. Kapsayıcılığın yalnız mülkiyet değil sağlık, cinsiyet, dijital erişim ve çevresel adalet boyutlarıyla genişletilmesi gerekiyor.",
    questions="Ekonomik fırsat gerçekten kimlere açık? Bu verimsiz kuralı sürdürmek kimin siyasi çıkarına yarıyor? Kriz anında verilen geçici yetki nasıl kalıcı kurumsal döngüye dönüşebilir?",
    essence="Uzun vadeli refah, insanların yetenek ve fikirlerini kullanmasına izin veren ekonomik fırsatlarla, gücü denetleyen çoğul siyasi kurumların aynı anda var olmasına bağlıdır.",
))


BOOKS.append(make_book(
    156, "buyuk-donusum", "Büyük Dönüşüm", "Karl Polanyi",
    "Piyasanın toplumdan bağımsız doğal bir makine olmadığını; emek, toprak ve parayı satılık mala çevirmeye çalışan on dokuzuncu yüzyıl düzeninin toplumu savunmaya zorladığını anlatan tarih, ekonomi ve siyaset klasiği.",
    "#5C5A4B", "The Great Transformation",
    [
        {"id": 1, "title": "Beacon Press - The Great Transformation", "url": "https://www.beacon.org/The-Great-Transformation-P790.aspx"},
        {"id": 2, "title": "Encyclopaedia Britannica - Karl Polanyi", "url": "https://www.britannica.com/biography/Karl-Polanyi"},
        {"id": 3, "title": "Internet Archive - The Great Transformation", "url": "https://archive.org/details/greattransformat0000pola"},
    ],
    [
        chapter("Piyasa toplumun içine gömülüyken", "BAŞLANGIÇ · GÖMÜLÜ EKONOMİ",
            "Polanyi geçmiş toplumlarda üretim ve değişimin akrabalık, din, siyaset ve karşılıklılık içinde gömülü olduğunu söyler. Ekonomi ayrı ve kendi yasasıyla yöneten bir alan değildi.",
            "Köyde komşuya verilen yemek aynı gün aynı değerle geri dönmez; ilişki, itibar ve gelecekteki yardım hesabın içindedir. Fiyat etiketi bütün değişimi açıklamaz.",
            "Geçmişi saf dayanışma cenneti saymamak gerekir; hiyerarşi ve zor vardı. Polanyi'nin amacı piyasa dışı düzenlerin mümkün olduğunu göstermektir.",
            "Bugün bakım emeği ve açık kaynak yazılım, ekonomik değerin her zaman doğrudan satış biçiminde oluşmadığını hatırlatır.",
            "embedded-market", "Ekonomik değişim uzun süre akrabalık, karşılıklılık ve siyasi düzenin içine gömülü yaşadı."),
        chapter("Kendi kendini düzenleyen piyasa ütopyası", "BİRİNCİ KISIM · PİYASA TOPLUMU",
            "On dokuzuncu yüzyıl ideali üretim ve dağıtımın fiyatlar tarafından dış müdahale olmadan düzenlenmesiydi. Polanyi bunun doğal durum değil, devlet gücüyle kurulmuş radikal proje olduğunu savunur.",
            "Şehrin bütün trafik ışıklarını kaldırıp araçların fiyat sinyaliyle yol bulmasını beklemek gibi, toplumun her alanını tek mekanizmaya teslim etmek büyük deneydir.",
            "Piyasalar çok eskiydi; yeni olan toplumun pazar için yeniden örgütlenmesiydi. İnsanların geçimi ve doğa, fiyat dalgalanmasına doğrudan bağlandı.",
            "'Devlet çekilsin, piyasa doğal çalışsın' cümlesinde piyasayı kuran mülkiyet, para, sözleşme ve polis düzeninin kamusal kökü unutulur.",
            "self-regulating-machine", "Kendi kendini düzenleyen piyasa doğada bulunan makine değil, toplumun devlet eliyle yeniden kurulmasını isteyen projedir."),
        chapter("Emek neden sıradan mal değildir?", "İKİNCİ KISIM · HAYALİ METALAR",
            "Emek satılmak için üretilmiş nesne değil insan yaşam faaliyetidir. Fiyatı düşen bir mal depoda bekleyebilir; işsiz kalan insan kira, sağlık ve onur kaybıyla yaşar.",
            "Fabrika siparişi azalınca makine kapatılabilir, çalışan aile ise kapatılamaz. Emek piyasasının dalgası bütün hayata yayılır.",
            "Polanyi emeğe koruma gerektiğini buradan çıkarır. Fakat koruma iş bulma engeli veya dışlama yaratmayacak biçimde tasarlanmalıdır.",
            "Asgari ücret, işsizlik sigortası ve iş güvenliği piyasayı yok etmek değil insanı fiyat hareketinin çıplak etkisinden korumaktır.",
            "labor-not-box", "Emek rafta bekleyen kutu değil, iş kaybıyla bütün yaşamı etkilenen insanın etkinliğidir."),
        chapter("Toprak neden üretilmiş mal değildir?", "İKİNCİ KISIM · HAYALİ METALAR",
            "Toprak satılmak için üretilmemiş doğadır. Onu yalnız fiyatı olan arsaya indirgemek suyu, ekosistemi, yerel yaşamı ve gelecek kuşakları görünmez yapar.",
            "Ormanı yalnız kesilecek kerestenin bugünkü fiyatıyla ölçerseniz sel koruması, karbon ve yaşam alanı hesap dışında kalır. Etiket bütün değeri taşımaz.",
            "Mülkiyet kullanımı düzenleyebilir; Polanyi bütün özel sahipliği tek cümleyle reddetmez. Sorun doğanın piyasa sinyaline tamamen bırakılmasıdır.",
            "İklim krizi, hayali meta kavramını güncelleştirir: Doğanın kendini yenileme sınırı bilanço döneminden uzundur.",
            "land-not-product", "Toprak üretilmiş bir mal değil, fiyat hesabını aşan ekolojik ve toplumsal yaşam zeminidir."),
        chapter("Para neden yalnız mal değildir?", "İKİNCİ KISIM · HAYALİ METALAR",
            "Para üretimi kolaylaştıran kredi ve ödeme düzenidir; sıradan mal gibi yalnız arz-talebe bırakıldığında faiz ve likidite şokları işletmeleri ve işleri yıkabilir.",
            "Kanın fiyatı yükseldi diye hastaneye kan akışını kesmek bedeni durdurur. Para da ekonominin dolaşımıdır; miktar ve güven toplumsal düzen ister.",
            "Merkez bankası müdahalesi bu nedenle piyasa dışı kaza değil piyasanın yaşama koşuludur. Ancak para desteğinin kime ulaştığı adalet sorusudur.",
            "Finans krizlerinde devletin bankaları kurtarması, 'kendi kendini düzenleyen' sistemin kamu desteğine ne kadar bağımlı olduğunu gösterir.",
            "money-bloodstream", "Para sıradan satılık nesneden çok ekonomik bedenin dolaşımıdır; ani kesinti bütün üretimi durdurabilir."),
        chapter("Çitleme hareketinin kırdığı dünya", "İKİNCİ KISIM · TOPRAK",
            "İngiltere'de ortak arazilerin çitlenmesi köylülerin geçim kaynaklarını özel mülkiyete dönüştürdü. İnsanlar ücretli emek piyasasına daha bağımlı hale geldi.",
            "Mahallenin herkesçe kullanılan bahçesine duvar çekilip giriş bilete bağlanırsa yalnız mekân değil yaşam biçimi değişir. Önceden ihtiyaç karşılayan alan gelir kaynağı olur.",
            "Çitleme tarımsal verim ve üretim artışıyla da ilişkilidir; tarih yalnız kötü niyetli el koyma değildir. Fakat maliyet eşit dağılmadı.",
            "Bugün dijital bilgi, kıyı ve su gibi ortak alanların özelleştirilmesi aynı soruyu taşır: Verim adına hangi ortak yaşam hakkı kayboluyor?",
            "enclosure-fence", "Ortak araziye çekilen çit, toprağı olduğu kadar köylünün geçim ve bağımsızlık düzenini de değiştirdi."),
        chapter("Speenhamland yardımı neden tartışmalı?", "İKİNCİ KISIM · YOKSULLUK",
            "1795 Speenhamland sistemi düşük geliri ekmek fiyatına göre yerel yardımla tamamladı. Polanyi bunun emek piyasasının sert geçişini geciktirdiğini, fakat ücret ve bağımlılık üzerinde karmaşık sonuçlar yarattığını anlatır.",
            "İşveren düşük ücret verirken belediye farkı kapatıyorsa yardım işçiyi korur ama işverene de ucuz emek desteği sağlayabilir. Aynı politika iki yöne çalışır.",
            "Polanyi'nin tarihsel yorumu sonraki araştırmalarda eleştirilmiştir; sistemin ücretleri ne ölçüde düşürdüğü kesin değildir. Bu bölüm tek veri gibi kullanılmamalıdır.",
            "Güncel gelir desteğinde de yardımın işçiye pazarlık gücü mü verdiği, yoksa düşük ücret modelini mi sübvanse ettiği sorulmalıdır.",
            "bread-allowance", "Gelir desteği yoksulu korurken kötü tasarlanırsa düşük ücret düzeninin maliyetini kamuya taşıyabilir."),
        chapter("1834: çıplak emek piyasası", "İKİNCİ KISIM · YOKSUL YASASI",
            "Yeni Yoksul Yasası yardımı caydırıcı çalışma evlerine bağladı. İnsanların geçim için emeklerini piyasada satmaya zorlanması, Polanyi'ye göre piyasa toplumunun sert kuruluş anıdır.",
            "Güvenlik ağını kesip kişiye 'ne ücret verilirse kabul et' demek seçim görüntüsü yaratır; açlık pazarlığın görünmez zorudur.",
            "Eski yardım düzeninin de paternalist ve aşağılayıcı yanları vardı. Seçenek iyi eski ile kötü yeni değildir; insan onurunu koruyan yeni kurum arayışıdır.",
            "Sosyal yardım tartışmasında teşvik kadar pazarlık gücü ve yaşam tabanı görülmelidir. Açlık serbest sözleşme üretmez.",
            "workhouse-gate", "Çalışma evi kapısı, yardımın onur kırıcı koşula bağlanıp emeğin çıplak piyasaya zorlanmasını simgeler."),
        chapter("Altın standardının sert kemeri", "BİRİNCİ KISIM · ULUSLARARASI DÜZEN",
            "Paranın altına sabitlenmesi uluslararası ticarete güven sağladı, fakat kriz anında hükümetlerin para ve istihdam politikasını daralttı. Döviz değerini korumak için toplum işsizlik ve ücret düşüşü taşıdı.",
            "Büyüyen çocuğa eski kemeri hiç gevşetmeden takmak, ölçüyü korur ama bedeni sıkıştırır. Altın standardı da para disiplinini toplumsal esnekliğin önüne koyabilir.",
            "Sabit kur düzeni her zaman aynı sonucu vermez; mali yapı ve siyaset önemlidir. Polanyi onun demokrasiyle gerilimini vurgular.",
            "Bugün bütçe ve para kurallarında benzer soru vardır: Güvenilir sınır gerekir, fakat kriz anında insanları koruyacak hareket payı kalıyor mu?",
            "golden-belt", "Altın standardının sabit kemeri para güveni sağlarken kriz yaşayan toplumsal bedeni sıkıştırdı."),
        chapter("Yüz yıllık barışın görünmeyen ağı", "BİRİNCİ KISIM · BARIŞ",
            "1815 ile 1914 arasındaki Avrupa dengesi yalnız güç siyasetiyle değil, uluslararası finans ve ticaret çıkarlarının barış ihtiyacıyla da desteklendi. Polanyi yüksek finansın beklenmedik barış rolünü gösterir.",
            "Birbirine borç veren rakip dükkânlar kavga ederse ikisi de zarar görür. Ortak çıkar gerilimi tamamen bitirmez ama fren oluşturur.",
            "Ekonomik bağ her zaman barış getirmez; rekabet, milliyetçilik ve eşitsiz bağımlılık savaşı da besleyebilir. 1914 bunun açık sınırıdır.",
            "Küresel tedarik zincirlerini otomatik barış sigortası saymamak gerekir. Ekonomik bağın siyasi kurumla desteklenmesi şarttır.",
            "finance-peace-web", "Uluslararası finans ağı rakip devletleri birbirine bağlayarak savaşa karşı geçici çıkar freni oluşturdu."),
        chapter("Çifte hareket", "ÜÇÜNCÜ KISIM · TOPLUMSAL KORUMA",
            "Piyasa emek, toprak ve parayı daha fazla metalaştırdıkça toplum kendini korumak için sendika, tarife, sosyal yasa ve düzenleme üretir. Polanyi bu karşı tepkiye çifte hareket der.",
            "Yay gerildikçe ters yönde kuvvet birikir. Piyasa genişlemesi karşısında koruma talebi de büyür; iki hareket aynı tarih içinde çatışır.",
            "Koruma her zaman ilerici değildir. Meslek tekeli, yabancı düşmanlığı ve otoriter milliyetçilik de korunma dili kullanabilir.",
            "Bugün küreselleşme karşıtı tepkiyi değerlendirirken kimin neye karşı korunduğunu ve maliyetin kime yüklendiğini sormak gerekir.",
            "double-movement", "Piyasa toplumsal alanı gererken sendika ve düzenleme gibi karşı kuvvetler yayı ters yönde çekmeye başlar."),
        chapter("Piyasayı devlet kurdu", "ÜÇÜNCÜ KISIM · DEVLET",
            "Laissez-faire'in kendiliğinden doğmadığını, mülkiyet, işgücü ve para piyasalarını kurmak için yoğun yasa ve idare gerektiğini savunur. Müdahalesizlik bile müdahaleyle inşa edilmiştir.",
            "Futbol sahasını çizip kaleyi kuran, hakemi atayan ve sonra 'oyun doğal olarak başladı' diyen yönetici gibi. Piyasa önceden kurulmuş kurallara dayanır.",
            "Devletin rolü her müdahaleyi iyi yapmaz; kural seçkin çıkarına hizmet edebilir. Mesele devlet var mı yok mu değil, hangi kuralı kimin için kurduğudur.",
            "Teknoloji platformlarında pazar tasarımının şirket algoritmasıyla yapılması, kural koyucunun görünmezliğini yeniden gösterir.",
            "state-builds-market", "Piyasanın sahası, kalesi ve hakemi yasa ile kurulmadan kendiliğinden oyun başlamaz."),
        chapter("Faşizm neden koruma vaadiyle geldi?", "ÜÇÜNCÜ KISIM · KRİZ",
            "Büyük Buhran piyasa düzenini ve demokrasiyi aynı anda sıkıştırdı. Faşizm toplumu koruma iddiasıyla geldi, fakat korumayı özgürlük ve eşitliği yok eden otoriter birlik içinde kurdu.",
            "Fırtınada gemiyi kurtaracağını söyleyen kaptan bütün yolcuları zincirleyebilir. Güvenlik vaadi yöntemin adaletini garanti etmez.",
            "Polanyi faşizm, sosyalizm ve New Deal'i piyasa krizine farklı toplumsal yanıtlar olarak karşılaştırır. Tarihsel ayrıntılar ülkeden ülkeye değişir.",
            "Ekonomik güvensizliği küçümsemek otoriter koruma vaatlerine alan açar. Demokratik sosyal koruma hem geçim hem hak sunmalıdır.",
            "fascist-lifeboat", "Güvenlik vaat eden otoriter kaptan toplumu kurtarmak bahanesiyle yolcuların özgürlüğünü zincirleyebilir."),
        chapter("Özgürlük planlama ile bitecek mi?", "SONUÇ · ÖZGÜRLÜK",
            "Polanyi her düzenlemenin özgürlüğü yok ettiğini reddeder. Sosyal güvenlik ve haklar bazı ayrıcalıkları sınırlar, fakat daha çok insanın gerçek özgürlüğünü artırabilir.",
            "Trafik ışığı sürücünün anlık hareketini kısıtlar, yayaya sokağı geçme özgürlüğü verir. Hangi özgürlüğü kimin için ölçtüğünüz belirleyicidir.",
            "Planlama da bürokratik baskıya dönüşebilir. Demokratik katılım ve hak güvencesi olmadan koruma paternalist denetime kayar.",
            "İyi toplum piyasa ile devlet arasında basit seçim değil; ikisini insan ve doğa sınırlarına bağlayan denetlenebilir kurum arayışıdır.",
            "traffic-light-freedom", "Bazı ortak kurallar bir kişinin sınırsız hareketini azaltırken birçok kişinin gerçek hareket özgürlüğünü büyütebilir."),
        chapter("Piyasa sinyali neyi duyamaz?", "GÜNÜMÜZ · SINIRLAR",
            "Fiyat kıtlık ve talep hakkında güçlü bilgi taşır, fakat ödeme gücü olmayan ihtiyacı ve gelecek kuşağın sesini zayıf duyar. Piyasa sinyali ahlaki öncelik listesi değildir.",
            "Susuz kişinin parası yoksa su talebi fiyat tablosunda görünmeyebilir; lüks havuzu olanın talebi görünür. İhtiyaç ile efektif talep ayrılır.",
            "Bu eleştiri fiyatı bütünüyle gereksiz saymaz. Fiyatı hak, kamu hizmeti ve ekolojik sınırla tamamlamak gerekir.",
            "Sağlık, konut ve iklim politikasında 'piyasa ne istiyor?' sorusunun yanına 'kim konuşamıyor?' sorusu konmalıdır.",
            "silent-needs", "Fiyat sistemi parası olmayan ihtiyacı ve henüz doğmamış kuşağın talebini kolayca duyamaz."),
        chapter("Neoliberal çağda Polanyi", "GÜNÜMÜZ · YENİ ÇİFTE HAREKET",
            "1980 sonrası özelleştirme, finansallaşma ve küresel rekabet yeni piyasa genişlemesi yarattı. İş güvencesi, konut ve doğa üzerindeki baskı yeni koruma taleplerini büyüttü.",
            "Uygulama üzerinden çalışan kişi özgür girişimci görünürken algoritma ücretini ve erişimini tek taraflı değiştirebilir. Sözleşme bağımsız, güç ilişkisi asimetriktir.",
            "Her güncel sorunu Polanyi'nin şemasına sokmak aşırı olabilir; teknoloji ve hizmet ekonomisi farklı mekanizmalar taşır.",
            "Yine de emek, toprak ve paranın toplumdan koparılamayacağı fikri platform işi, iklim ve finans krizinde güçlü teşhis sunar.",
            "platform-double-movement", "Dijital piyasa genişledikçe güvencesizlik yeni sendika, düzenleme ve sosyal koruma arayışını doğurur."),
    ],
    misreading="Polanyi pazarların hiç olmaması gerektiğini söylemez; pazarın toplumu yöneten tek ilkeye dönüşmesine karşı çıkar. 'Hayali meta' da emek, toprak ve paranın hiçbir zaman alınıp satılmadığı değil, satılmak için üretilmiş sıradan mallar olmadıkları anlamına gelir.",
    modern="İklim krizi toprağın, platform ekonomisi emeğin, finans krizleri paranın toplumdan koparılamadığını yeniden gösterdi. Speenhamland gibi bazı tarihsel yorumlar eleştirilse de piyasayı kuran devlet ve çifte hareket kavramları güncel araştırmada yaşamaktadır.",
    questions="Bu piyasa hangi hukuk ve kamu altyapısıyla kuruldu? Fiyat dalgasının yükünü insan, doğa ve gelecek kuşaklardan hangisi taşıyor? Koruma talebi özgürlüğü genişletiyor mu, yoksa dışlayıcı bir otorite mi kuruyor?",
    essence="Piyasa toplumun dışında doğal bir makine değildir; emek, doğa ve parayı bütünüyle fiyat düzenine teslim etmek toplumu kendini korumaya zorlayan derin bir karşı hareket yaratır.",
))


from build_twenty_more_summaries_batch_3b import MORE_BOOKS  # noqa: E402

BOOKS.extend(MORE_BOOKS)


if __name__ == "__main__":
    write_books(BOOKS)
