#!/usr/bin/env python3
"""Companion definitions for books 103, 122 and 124."""

from summary_batch_second_common import chapter, make_book


MORE_BOOKS = []


MORE_BOOKS.append(make_book(
    103, "protestan-ahlaki-ve-kapitalizmin-ruhu", "Protestan Ahlakı ve Kapitalizmin Ruhu", "Max Weber",
    "Kapitalizmin yalnız para hırsından doğmadığını; çalışmayı kutsal görev, zamanı sorumluluk ve kazancı kişisel tüketimden çok yeniden yatırım sayan belirli bir hayat disiplininin modern ekonomiye nasıl uyduğunu araştıran sosyoloji klasiği.",
    "#655747", "The Protestant Ethic and the Spirit of Capitalism",
    [
        {"id": 1, "title": "Project Gutenberg - The Protestant Ethic", "url": "https://www.gutenberg.org/ebooks/67193"},
        {"id": 2, "title": "Marxists Internet Archive - Weber, Protestant Ethic", "url": "https://www.marxists.org/reference/archive/weber/protestant-ethic/"},
        {"id": 3, "title": "Encyclopaedia Britannica - Max Weber", "url": "https://www.britannica.com/biography/Max-Weber-German-sociologist"},
    ],
    [
        chapter("Para hırsı kapitalizm değildir", "BAŞLANGIÇ · SORU",
            "Weber para kazanma arzusunun her çağda bulunduğunu söyler. Korsan, saray görevlisi ve tefeci de zenginlik isterdi. Modern kapitalizmin ayırt edici yanı, düzenli hesap, sürekli işletme ve kârın yeniden yatırıma bağlanmasıdır.",
            "Piyangodan zengin olmakla her gün kayıt tutup üretimi büyütmek aynı para ilişkisi değildir. İlkinde tek vuruş, ikincisinde sistemli yaşam biçimi vardır.",
            "Kitap kapitalizmin tek nedenini din ilan etmez. Hukuk, şehir, teknoloji ve pazar gerekir. Weber belirli bir ahlakın bu makineyle neden iyi uyuştuğunu araştırır.",
            "Bugün girişimcilik konuşurken yalnız kazanç miktarına değil, zaman, kayıt, yatırım ve meslek fikrinin nasıl ahlaki değer kazandığına bakabiliriz.",
            "greed-vs-ledger", "Tek seferlik zenginlik arzusu ile sürekli hesap ve yeniden yatırıma dayanan kapitalist düzen aynı şey değildir."),
        chapter("Kapitalizmin ruhu Benjamin Franklin'de", "BİRİNCİ KISIM · RUH",
            "Weber 'vakit nakittir' ve güvenilir borçlunun değerli olduğu yönündeki Franklin öğütlerini örnek verir. Burada kazanç yalnız araç değil, insanın görevini iyi yaptığının ölçüsü gibi görünür.",
            "Dakik çalışan, hesabını tutan ve kazancını savurmayan esnaf yalnız başarılı değil 'iyi karakterli' sayılır. Ekonomik davranış ahlaki övgüye bağlanır.",
            "Bu ruh hazcı değildir. Daha çok para, daha çok eğlence için değil işi büyütmek ve görevi sürdürmek için kazanılır. Birikim tüketimden kopar.",
            "Modern özgeçmiş kültüründe de üretkenlik karakter ölçüsüne dönüşebilir. İnsan ne yaptığıyla değil ne kadar verimli olduğu ile değer görmeye başlar.",
            "franklin-clock", "Zaman ve kredi disiplininin ekonomik değerleri, çalışkanlığı ahlaki karakter işaretine dönüştürür."),
        chapter("Meslek aynı zamanda çağrı olunca", "BİRİNCİ KISIM · MESLEK",
            "Almanca Beruf sözcüğü hem meslek hem çağrı anlamı taşır. Reform düşüncesinde dünyevi iş, manastır dışındaki sıradan hayatın Tanrı'ya karşı görevi haline gelir.",
            "Ekmek yapan kişi yalnız ücret kazanmıyor, işini dikkatle yaparak kutsal sorumluluğunu yerine getiriyorsa tezgâh ibadet alanına yaklaşır.",
            "Luther dünyevi görevi yüceltir ama Weber'in aradığı sistemli kapitalist disiplin özellikle sonraki Kalvinist ve Püriten çevrelerde keskinleşir.",
            "Bugün 'işini tutkuyla yap' sözü dinsel dilini kaybetmiş çağrı fikridir. İşin anlam vermesi güzel olabilir; bütün benliği işe teslim etmek tükenmişlik getirir.",
            "calling-workbench", "Meslek kutsal çağrı sayıldığında gündelik çalışma yalnız geçim değil ahlaki görev haline gelir."),
        chapter("Kaderin bilinmediği korku", "İKİNCİ KISIM · KALVİNİZM",
            "Kalvinist kader öğretisinde kimin kurtulacağı önceden belirlenmiştir ve insan bunu kesin bilemez. Bu belirsizlik yoğun iç kaygı doğurabilir; kişi seçilmişliğin işaretlerini düzenli hayatında arar.",
            "Sonucu açıklanmayan büyük sınavda olduğunuzu, tekrar girme şansınız bulunmadığını düşünün. Doğrudan cevap alamayınca her davranışı dolaylı işaret gibi okumaya başlayabilirsiniz.",
            "Weber herkesin aynı psikolojiyi yaşadığını söylemez; dini fikir ile toplumsal davranış arasında olası bir yakınlık kurar. Öğreti tek başına otomatik sonuç üretmez.",
            "Belirsizlik bugün performans puanı ve algoritmik değerlendirmede de benzer disiplin yaratabilir: Ölçüyü tam bilmeyen kişi kendini sürekli kanıtlamaya çalışır.",
            "predestination-anxiety", "Kurtuluşun bilinmezliği, insanı düzenli yaşamında seçilmişliğin işaretlerini aramaya itebilir."),
        chapter("Dünya içinde çilecilik", "İKİNCİ KISIM · DİSİPLİN",
            "Manastır çilecisi dünyadan çekilir; Püriten çileci dünya içinde çalışır. Hazdan kaçınır, zamanı boşa harcamaz ve hayatını düzenli özdenetim altında tutar.",
            "Gösterişli tatil yerine dükkânını büyüten, kazancını yeni alete yatıran ve gününü saatle bölen kişi bu dünyasal çileciliğin ekonomik görüntüsüdür.",
            "Çilecilik tüketimi kısarken üretimi düşürmez; tam tersine artırır. Kazanç harcanmayınca sermaye olarak birikir. Ahlaki disiplin ekonomik büyüme davranışıyla buluşur.",
            "Bugün sade yaşam ile yatırım kültürü benzer görünse de amaçlar farklı olabilir. Aynı davranışın dini, çevreci ya da finansal anlamı bağlama göre değişir.",
            "worldly-ascetic", "Dünya içindeki çileci çok çalışır ama kazancı haz için tüketmeyip yeniden işe bağlar."),
        chapter("Boşa geçen dakikanın günaha dönüşmesi", "İKİNCİ KISIM · ZAMAN",
            "Püriten ahlakında boş zaman yalnız ekonomik kayıp değil ahlaki tehlikedir. Düzenli çalışma, kişinin kendini dağınık arzulardan koruma yolu sayılır.",
            "Dinlenirken bile saatin tik takını borç gibi hissetmek, zamanın tarafsız akıştan performans hesabına dönüşmesidir. Takvim vicdanın dışarıdaki sesi olur.",
            "Bu disiplin üretkenlik sağlar fakat dinlenmeyi suçluluğa çevirebilir. İnsan bedeni makine değildir; boşluk yaratıcılık, bakım ve ilişki için gereklidir.",
            "Telefon uygulamalarının her dakikayı ölçtüğü çağda Weber'in zaman ahlakı yeni araçlarla geri döner. Ölçü, hayatın amacının yerini almamalıdır.",
            "moral-clock", "Saat ekonomik planın ötesine geçip her boş dakikayı ahlaki eksik gibi yargılayan vicdana dönüşebilir."),
        chapter("Defterin sessiz devrimi", "İKİNCİ KISIM · HESAP",
            "Rasyonel kapitalist işletme gelir, gider, borç ve verimi düzenli kayda bağlar. Defter yalnız olanı yazmaz; hangi işin sürmesi gerektiğine karar veren göz olur.",
            "Ev bütçesini ilk kez kalem kalem çıkarınca kahve harcamasının toplamını görürsünüz. Kayıt davranışı görünür kılar ve gelecekteki davranışı değiştirir.",
            "Ölçülemeyen şeyin değersiz sayılması tehlikesi vardır. Bakım emeği, güven ve doğa kaybı bilançoda görünmezse karar bunları yokmuş gibi kullanabilir.",
            "Modern veri yönetiminde soru yalnız doğru ölçmek değil, neyi dışarıda bıraktığını bilmektir. Defter gerçekliğin aynası değil seçilmiş haritasıdır.",
            "double-entry-book", "Hesap defteri işletmeyi yalnız kaydetmez; görünür kıldığı değerlerle gelecekteki davranışı da yönetir."),
        chapter("Kazanç tüketilmeyince sermaye olur", "İKİNCİ KISIM · BİRİKİM",
            "Çalışma kutsal görev, lüks ise kuşkulu olduğunda kazanç kişisel hazza akmaz. Yeni araç, stok ve işletme için yeniden yatırılır; sermaye düzenli biçimde büyür.",
            "Fırıncı kârıyla şölen vermek yerine ikinci fırını alırsa ertesi yıl daha çok ekmek üretir. Tek karar tekrarlandığında küçük disiplin ekonomik yapıya dönüşür.",
            "Birikimin kaynağını yalnız ahlaka bağlamak yetersizdir; sömürge ticareti, emek ilişkileri ve mülkiyet düzeni de belirleyicidir. Weber ilişkinin bir parçasını seçer.",
            "Bugün yatırım övgüsünün yanında kârın hangi emekten ve hangi çevresel maliyetten geldiğini sormak gerekir. Büyüme tarafsız sayı değildir.",
            "profit-to-capital", "Tüketilmeyen kazanç tekrar üretime bağlandığında ahlaki tutumluluk sermaye birikimine dönüşebilir."),
        chapter("Güvenilir insanın kredi değeri", "İKİNCİ KISIM · GÜVEN",
            "Dakiklik, sözünde durma ve ölçülü yaşam yalnız erdem değil kredi piyasasında ekonomik avantaja dönüşür. İnsan karakteri gelecekte ödeme yapacağına dair teminat gibi okunur.",
            "Komşusuna borcunu hep gününde ödeyen esnaf, yazılı belgeden önce bile daha kolay mal alır. İtibar görünmez sermayedir.",
            "Bu düzen ahlaki görünüşü dışlama aracına çevirebilir. Farklı giyinen, başka inanca sahip veya yoksul kişi güvenilmez damgası yiyebilir; erdem ölçüsü sınıf önyargısıyla karışır.",
            "Kredi puanı çağında karakter yargısı algoritmaya taşındı. Verinin geçmiş eşitsizliği yeniden üretip üretmediği Weberci güven sorusunun yeni biçimidir.",
            "credit-reputation", "Güvenilirlik ahlaki övgüden ekonomik krediye dönüşürken görünmez sermaye ve dışlama ölçüsü olabilir."),
        chapter("Geleneksel işçi neden daha az çalışabilir?", "BİRİNCİ KISIM · EMEK",
            "Weber, ücret artınca daha çok çalışmak yerine aynı ihtiyacı daha kısa sürede karşılayıp dinlenen geleneksel işçi örneğini verir. Modern ekonomik aklın 'daha çok kazanç her zaman daha iyidir' varsayımı evrensel değildir.",
            "Günde yüz lira ihtiyacı olan kişi saat ücreti iki katına çıkınca yarım gün çalışabilir. İşveren daha çok emek beklerken çalışan daha çok zaman kazanır.",
            "Örnek işçiyi tembel gösterme riski taşır; çalışma tercihleri güç, zorunluluk ve yaşam amacıyla ilgilidir. Verimlilik kimin açısından ölçüldüğüne göre değişir.",
            "Dört günlük çalışma haftası tartışması aynı soruyu canlandırır: Teknolojik kazanç daha çok üretime mi, daha çok serbest zamana mı dönüşmeli?",
            "wage-time-choice", "Daha yüksek ücret her zaman daha çok emek değil, aynı ihtiyacı karşılayıp daha fazla boş zaman seçimi doğurabilir."),
        chapter("Ruh makineyi kurdu mu?", "TARTIŞMA · NEDENSELLİK",
            "Weber dini ahlakın kapitalizmi tek başına icat ettiğini söylemez. Belirli fikirler ile ekonomik kurumlar arasında 'seçici yakınlık' arar: İki düzen birbirini güçlendirebilir.",
            "Rüzgâr değirmeni rüzgârı yaratmaz; ama kanatları uygun açıdaysa var olan rüzgârı üretime çevirir. Ahlak da pazar ve hukuk koşullarını belirli davranışa yöneltebilir.",
            "Neden okunu tek yönde çizmek hatadır. Ekonomik değişim dini yorumu da etkiler; sınıf çıkarı, şehirleşme ve siyaset aynı anda çalışır.",
            "Kültür ile ekonomi tartışmasında 'ya fikir ya madde' ikiliğinden çıkmak Weber'in en değerli yöntem dersidir.",
            "windmill-affinity", "Dini ahlak kapitalist rüzgârı tek başına yaratmaz; fakat uygun kanatlar gibi onu belirli yönde güçlendirebilir."),
        chapter("Demir kafes nasıl kuruldu?", "SONUÇ · KURUM",
            "Dini anlam zamanla zayıflasa bile onun kurduğu disiplin kurumlarda yaşamaya devam eder. İnsan artık kurtuluş için değil işini kaybetmemek için saat, bürokrasi ve piyasa kuralına uyar. İnanç ceketi demir kafese dönüşür.",
            "Başlangıçta isteyerek kullanılan üretkenlik uygulamasının sonra yöneticinin zorunlu performans aracına dönüştüğünü düşünün. Araç, onu seçen kişiden bağımsız baskı kazanır.",
            "Kafes benzetmesi modernliğin kaçınılmaz sonu olmak zorunda değildir. Kurumlar insan yapımıdır ve çalışma süresi, sosyal güvence, ortak mülkiyet gibi düzenlemelerle değişebilir.",
            "Bugün algoritmik vardiya ve sürekli çevrimiçi olma, kafesin yeni çubuklarıdır. Verimlilik sisteminin kime hizmet ettiğini yeniden sormak gerekir.",
            "iron-cage", "Bir zamanlar seçilmiş ahlaki disiplin, anlamı unutulunca herkesi zorlayan kurumsal demir kafese dönüşebilir."),
        chapter("Avrupa dışındaki yollar", "ELEŞTİRİ · DÜNYA",
            "Weber Batı kapitalizminin özel yolunu araştırırken Çin, Hindistan ve başka toplumları karşılaştırır. Bazı tasvirleri döneminin Avrupamerkezci genellemelerini taşır ve yerel çeşitliliği küçültür.",
            "Başka mutfakları yalnız kendi tarifinizde eksik olan malzemelerle değerlendirmek, onların neden farklı yemek yaptığını kaçırır. Karşılaştırma tarafsız cetvel ister.",
            "Kapitalist ticaretin Avrupa dışındaki uzun geçmişi ve sömürge bağlantıları, Protestanlık merkezli anlatıyı sınırlar. Küresel sistem tek kültürel kaynaktan doğmadı.",
            "Bugün Weber'i kullanırken soruyu koruyup hiyerarşiyi bırakmak gerekir: Fikirler ekonomik davranışı farklı coğrafyalarda hangi yollarla etkiliyor?",
            "many-economic-roads", "Dünya ekonomileri tek Batı yolunun eksik kopyaları değil, farklı tarihsel birleşimlerin ürünüdür."),
        chapter("Sömürge ve zorun görünmeyen payı", "ELEŞTİRİ · GÜÇ",
            "Kitap özdisiplin ve hesap kültürünü aydınlatırken kölelik, sömürge kaynakları ve toprak gasbının sermaye birikimindeki rolünü merkezde işlemez. Kapitalizmin ruhu kadar zor gücü de vardır.",
            "Fabrikanın temiz ofisindeki defter, hammaddenin hangi koşullarda çıkarıldığını göstermeyebilir. Düzenli muhasebe tedarik zincirindeki şiddeti görünmez bırakabilir.",
            "Bu eksik Weber'in bütün analizini geçersiz kılmaz; kültürel motivasyon ile maddi zorun aynı sistemde birlikte incelenmesini gerektirir.",
            "Güncel şirket değerlendirmesinde yalnız kârlılık ve çalışma kültürü değil emek hakkı, çevre ve tedarik zinciri de bilançoya girmelidir.",
            "ledger-and-colony", "Düzenli kapitalist defter, hammaddenin arkasındaki sömürge şiddetini ve zorunlu emeği görünmez bırakabilir."),
        chapter("Çalışkanlık ne zaman karakter ölçüsü olur?", "GÜNÜMÜZ · İŞ KÜLTÜRÜ",
            "Weber'in anlattığı ahlak bugün dinsel dil olmadan sürer. Çok çalışan kişi yalnız başarılı değil değerli, işsiz kalan ise yapısal koşullar ne olursa olsun kişisel olarak eksik görülebilir.",
            "Toplantıda gece yarısına kadar çevrimiçi kalan çalışanın alkışlanması, yorgunluğun bağlılık kanıtına dönüşmesidir. Sonuçtan çok fedakârlık gösterisi ödüllenir.",
            "Çalışma anlam, ustalık ve toplumsal katkı sağlayabilir. Sorun insan değerinin yalnız üretime bağlanması ve bakım, dinlenme, hastalık gibi hayat parçalarının ahlaki kusur sayılmasıdır.",
            "İyi iş kültürü çabayı tanır ama sınır, izin ve insanın iş dışındaki değerini de korur. Kafesin kapısı böyle aralanır.",
            "hustle-halo", "Çalışkanlık üretim alışkanlığından çıkıp insanın bütün ahlaki değerini ölçen bir hale dönüşebilir."),
        chapter("Weber'in yöntemi: anlamı ciddiye almak", "YÖNTEM · SOSYOLOJİ",
            "İnsan davranışını yalnız dış koşulla açıklamak yetmez; insanlar yaptıkları işe hangi anlamı veriyor? Aynı tasarruf, korku, inanç, aile sorumluluğu ya da yatırım hesabından doğabilir.",
            "İki kişi aynı saatte dükkân açar. Biri borçtan korktuğu, diğeri mesleği kutsal görev saydığı için. Dış hareket aynı, iç anlam farklıdır ve uzun vadeli davranışı değiştirir.",
            "Anlamı sormak öznel hikâyeyi sorgusuz kabul etmek değildir. Söylenen değer ile gerçek uygulama, kurum ve sonuç karşılaştırılmalıdır.",
            "Gündelik gözlemde davranışa hemen kişilik etiketi yapıştırmadan, kişinin dünyasında o davranışın ne anlama geldiğini sormak daha derin açıklama sağlar.",
            "same-action-two-meanings", "Aynı ekonomik hareket, insanların ona verdiği farklı anlamlar yüzünden farklı toplumsal yollara bağlanabilir."),
    ],
    misreading="Weber 'Protestanlık kapitalizmi yarattı' diye tek nedenli bir denklem kurmaz ve Protestanların doğal olarak daha çalışkan olduğunu söylemez. Belirli inanç yorumlarıyla disiplinli işletme davranışı arasındaki tarihsel yakınlığı araştırır.",
    modern="Kapitalizmin sömürge, teknoloji ve hukuk kaynakları üzerine araştırmalar Weber'in çerçevesini genişletti. Buna rağmen üretkenliğin ahlaki karaktere dönüşmesi, zamanın ölçülmesi ve anlamını kaybeden disiplinin kurumsal baskı haline gelmesi son derece günceldir.",
    questions="Çalışmayı yalnız geçim mi, ahlaki değer ölçüsü mü sayıyorum? Ölçtüğüm verim hangi görünmez emeği dışarıda bırakıyor? Başlangıçta seçilmiş bir alışkanlık ne zaman beni zorlayan kuruma dönüştü?",
    essence="Belirli bir dini çalışma ahlakı modern kapitalizmi tek başına yaratmadı; fakat zamanı, kazancı ve mesleği disiplinli görev sayarak onun kurumlarıyla güçlü biçimde birleşti.",
))


MORE_BOOKS.append(make_book(
    122, "etika", "Etika", "Baruch Spinoza",
    "Tanrı ile doğayı iki ayrı dünya olmaktan çıkaran; insanı evrensel neden zincirinin içine yerleştirip tutkuların kölesi olmaktan özgürlüğe, zorunluluğu anlayarak geçebileceğimizi savunan geometrik felsefe yapısı.",
    "#4F625D", "Ethica, ordine geometrico demonstrata",
    [
        {"id": 1, "title": "Project Gutenberg - Ethics", "url": "https://www.gutenberg.org/ebooks/3800"},
        {"id": 2, "title": "Stanford Encyclopedia of Philosophy - Spinoza", "url": "https://plato.stanford.edu/entries/spinoza/"},
        {"id": 3, "title": "Internet Encyclopedia of Philosophy - Spinoza", "url": "https://iep.utm.edu/spinoza/"},
    ],
    [
        chapter("Felsefeyi geometri gibi kurmak", "BAŞLANGIÇ · YÖNTEM",
            "Etika tanım, aksiyom, önerme ve kanıtlarla yazılmıştır. Spinoza duygular ve Tanrı hakkında bile geometrinin açıklığıyla ilerlemek, keyfî inanç yerine neden zinciri kurmak ister.",
            "Bir binanın her katını alttaki kolonlara dayandırmak gibi, sonraki fikir önceki tanımlardan çıkmalıdır. Okur sonuca katılmasa da hangi basamakta ayrıldığını görebilir.",
            "İnsan hayatı üçgen kadar temiz değildir; tanımlar tartışmalıysa kusursuz çıkarım da sorunlu olur. Geometrik biçim kesinlik hissini bazen gereğinden fazla büyütür.",
            "Yine de tartışmada 'bence' demek yerine kavramı tanımlayıp gerekçeyi adım adım göstermek güçlü bir düşünme disiplinidir.",
            "geometric-ladder", "Spinoza düşünce binasını tanım ve aksiyomlardan başlayıp önermelere yükselen geometrik merdivenle kurar."),
        chapter("Tek töz: Tanrı ya da Doğa", "BİRİNCİ KISIM · TANRI",
            "Spinoza'ya göre kendi başına var olan sonsuz tek töz vardır: Tanrı ya da Doğa. Dünya Tanrı'nın dışında yaptığı bir nesne değil, sonsuz gerçekliğin zorunlu ifadesidir.",
            "Okyanus ile dalgaları düşünün. Dalga okyanustan ayrı ikinci madde değildir; okyanusun belirli biçimde görünmesidir. Tek tek varlıklar da doğanın kipleridir.",
            "Bu görüş geleneksel kişisel Tanrı anlayışından ayrılır. Dua ile karar değiştiren, ödül ve ceza veren hükümdar yerine doğanın kendisi kutsal gerçeklik olur.",
            "İnsan kendini evrenin merkezi değil bütünün geçici biçimi saydığında hem yalnızlık hem ayrıcalık duygusu değişebilir.",
            "ocean-and-waves", "Tek tek varlıklar okyanustan ayrı olmayan dalgalar gibi, tek sonsuz doğanın geçici biçimleridir."),
        chapter("Sıfatlar ve kipler", "BİRİNCİ KISIM · VARLIK",
            "Sonsuz töz sonsuz sıfatla ifade edilir; insan bunlardan düşünce ve uzamı bilir. Zihin ve beden iki ayrı madde değil, aynı gerçekliğin iki farklı anlatımıdır.",
            "Aynı şarkıyı nota kâğıdında desen, hoparlörde ses olarak görürsünüz. İki görüntü birbirine çarpmadan aynı düzeni farklı biçimde ifade eder.",
            "Bu paralellik zihnin bedeni nasıl ittiği sorununu ortadan kaldırır; fakat düşünce ile fiziksel olayın tam ilişkisini yorumlamak kolay değildir.",
            "Modern zihin-beden tartışmasında Spinoza, ruhu bedenden koparmadan deneyimin önemini korumaya çalışan erken bir alternatif sunar.",
            "score-and-sound", "Zihin ile beden iki ayrı dünya değil, aynı düzenin düşünce ve uzam diliyle iki ifadesidir."),
        chapter("Doğada tesadüf değil bilmediğimiz neden", "BİRİNCİ KISIM · ZORUNLULUK",
            "Her şey doğanın zorunlu düzeninden çıkar. Bir olayı tesadüf saymamız onun nedensiz olduğunu değil, neden zincirini bilmediğimizi gösterir.",
            "Masadaki bilyenin aniden yön değiştirdiğini görüp rastlantı diyebilirsiniz; görünmeyen eğimi ve önceki çarpışmayı keşfedince olay anlaşılır olur.",
            "Bu sıkı belirlenim özgür irade sezgisini zorlar. Spinoza'ya göre insanlar arzularının farkında, onları doğuran nedenlerin farkında olmadığı için kendini bağımsız sanır.",
            "Neden aramak mazeret üretmek değil, davranışı değiştirecek gerçek noktayı bulmaktır. Yine de hukuk ve sorumluluk dilinin nasıl kurulacağı açık bir tartışmadır.",
            "hidden-causes", "Tesadüf çoğu zaman olayın nedensizliği değil, onu doğuran eğim ve çarpışmaları göremememizdir."),
        chapter("Conatus: varlığını sürdürme çabası", "ÜÇÜNCÜ KISIM · DUYGULAR",
            "Her şey kendi varlığını sürdürmeye çabalar; insandaki bu temel yönelime conatus denir. Arzu, insanın özü olarak bu sürdürme gücünün bilinçli görünümüdür.",
            "Bitkinin ışığa dönmesi, bedenin yarayı kapatması ve insanın tehditten kaçması farklı düzeylerde devam etme eğilimi gösterir. Ortada bilinçli karar olmak zorunda değildir.",
            "Conatus yalnız bencil hayatta kalma değildir. Başkalarıyla işbirliği gücümüzü artırıyorsa onların iyiliğini istemek kendi varlık kapasitemizle birleşir.",
            "Gündelik kararda 'bu istek gerçekten yaşam gücümü artırıyor mu, yoksa kısa hazla beni daha bağımlı mı yapıyor?' sorusu conatusu pratik hale getirir.",
            "plant-to-light", "Canlı varlık ışığa dönen bitki gibi, kendi varlığını sürdürme ve etki gücünü artırma yönelimi taşır."),
        chapter("Sevinç ve keder birer hareket", "ÜÇÜNCÜ KISIM · DUYGULAR",
            "Sevinç daha büyük etkinlik gücüne geçiş, keder ise bu gücün azalmasıdır. Duygu yalnız iç renk değil, yapabilme kapasitesindeki değişimdir.",
            "Sizi anlayan dostla konuşunca dünya genişler, aşağılayan ortamdan çıkınca beden daralmış hisseder. Duygunun ölçüsü yalnız hoşluk değil hangi eylemleri mümkün kıldığıdır.",
            "Kısa haz her zaman gerçek güç artışı değildir. Bağımlılık anlık sevinç verirken uzun vadede seçenekleri daraltabilir. Spinoza geçişin bütün yönüne bakmayı ister.",
            "Duygu günlüğünde yalnız 'iyi/kötü hissettim' değil, 'bu durum hangi kapasitemi açtı veya kapattı?' sorusu daha açıklayıcı olabilir.",
            "joy-expansion", "Sevinç insanın etki alanını genişleten, keder ise yapabilme gücünü daraltan geçiştir."),
        chapter("Tutkuların ipinde yaşamak", "DÖRDÜNCÜ KISIM · KÖLELİK",
            "Bir duygunun nedeni dışarıdaysa ve onu yeterince anlamıyorsak edilgin tutku bizi sürükler. Özgür olduğunu sanan kişi aslında övgü, korku ve kıskançlık ipleriyle hareket edebilir.",
            "Telefon bildirimine her ses geldiğinde uzanmak küçük bir dış yönetimdir. Parmağınız sizin, fakat hareketin zamanı başkasının tasarladığı işarete bağlıdır.",
            "Duyguyu bastırmak çözüm değildir. Daha güçlü bir karşı duygu ve daha yeterli fikir gerekir. İnsan yalnız mantık cümlesiyle yoğun korkuyu susturamaz.",
            "Ortamı değiştirmek, tetikleyiciyi tanımak ve yeni alışkanlık kurmak Spinoza'nın nedenleri anlama özgürlüğüne güncel karşılık verir.",
            "puppet-strings", "Nedeni anlaşılmayan tutku, insanı kendi seçimi sanılan dış iplerle hareket ettirebilir."),
        chapter("İyi ve kötü doğanın etiketleri değil", "DÖRDÜNCÜ KISIM · DEĞER",
            "Doğada kendiliğinden iyi ya da kötü damgası yoktur. Bir şey bizim varlık gücümüzü artırdığı ölçüde iyi, azalttığı ölçüde kötü diye adlandırılır.",
            "Yağmur pikniği bozar, çiftçinin ürününü kurtarır. Aynı olay evrensel kötü değil, farklı ilişkilerde farklı etkidir.",
            "Bu görecelilik her davranış eşittir demek değildir. İnsanların ortak doğası ve birlikte güçlenme ihtiyacı, daha genel yarar ölçüleri kurmamıza izin verir.",
            "Bir kararı değerlendirirken etiketi olayın üstünde hazır bulmak yerine kimin gücünü nasıl etkilediğini ve uzun vadeli ilişkiyi sormak gerekir.",
            "rain-picnic-field", "Aynı yağmur piknikçi için kötü, çiftçi için iyi olabilir; değer ilişkideki etkiye göre doğar."),
        chapter("Aklın ortak kavramları", "İKİNCİ VE DÖRDÜNCÜ KISIM · BİLGİ",
            "Yetersiz fikir olayı parçalı ve rastlantısal gösterir; yeterli fikir neden bağını kavrar. Ortak kavramlar, bedenlerin paylaştığı özelliklerden daha sağlam bilgi kurar.",
            "Tek bir gölgenin hareketinden korkmak yerine ışık kaynağı, nesne ve duvar ilişkisini anlayınca farklı gölgeleri de açıklarsınız. Bilgi tek olayı genel düzene bağlar.",
            "Spinoza deneyimi küçümsemez ama yalnız duyulan hikâyeye güvenmez. Akıl farklı durumlarda ortak olan bağlantıyı arar.",
            "Haber okurken tek dramatik vaka yerine oran, karşılaştırma ve mekanizma aramak ortak kavramlara yaklaşan bir zihinsel alışkanlıktır.",
            "shadow-mechanism", "Yeterli fikir tek gölgeye bakmak yerine ışık, nesne ve duvar arasındaki ortak düzeni kavrar."),
        chapter("Özgürlük zorunluluğu anlamaksa", "DÖRDÜNCÜ KISIM · ÖZGÜRLÜK",
            "Spinoza için özgürlük nedensiz seçim yapmak değildir. Kendi doğamızın nedenlerini daha yeterli anlayıp iç zorunluluğumuzla eylemektir; taş havaya atıldığında uçmayı seçtiğini sansa özgür olmazdı.",
            "Öfkenin hangi korku ve beklentiden doğduğunu anlayan kişi, öfkesiz olmasa bile ona farklı yanıt verebilir. Neden bilgisi seçenek alanını büyütür.",
            "Bu özgürlük anlayışı 'başka türlü yapabilirdim' sezgisinden ayrılır. Eleştirmenler gerçek sorumluluğu fazla zayıflattığını düşünür.",
            "Pratikte özgürlük kontrol edemediğimiz nedeni inkâr etmek değil, anlayabildiğimiz bağlantı üzerinden etkili müdahale kurmaktır.",
            "thrown-stone", "Havaya atılan taş uçmayı seçtiğini sansa da özgür değildir; özgürlük hareketin gerçek nedenini kavramakla başlar."),
        chapter("Erdem güçtür", "DÖRDÜNCÜ KISIM · ERDEM",
            "Erdem dışarıdan dayatılan fedakârlık değil, insanın kendi doğasına göre etkin yaşama gücüdür. Akıl, kalıcı yararı görerek bizi daha bağımsız ve tutarlı yapar.",
            "Kas gücü yalnız ağır yük kaldırmak değil bedeni dengeli kullanmaktır. Ahlaki güç de başkasını yenmekten çok tutkuların rastgele çekişinde kaybolmamaktır.",
            "Kendi yararını aramak Spinoza'da dar egoizm değildir. İnsan başkalarıyla güven ve bilgi içinde yaşadığında daha çok şey yapabilir.",
            "Kişisel gelişim dilinde güç sözü baskınlıkla karışır. Spinoza'nın ölçüsü başkasını küçültmek değil ortak yapabilme alanını büyütmektir.",
            "virtue-strength", "Erdem başkasına hükmetmek değil, kendi doğasının nedenlerini anlayarak daha etkin ve tutarlı yaşayabilme gücüdür."),
        chapter("İnsan insana en yararlı varlık", "DÖRDÜNCÜ KISIM · TOPLUM",
            "Akılla yaşayan insanlar birbirine düşman değil en büyük yardımcıdır. Bilgi, güvenlik ve üretim tek başına kurulamaz; ortak düzen herkesin etkinlik gücünü artırır.",
            "Bir kişinin tek başına yapamayacağı köprü, farklı ustaların bilgisiyle yükselir. İşbirliği bireyi eritmez, kapasitesini genişletir.",
            "Gerçek toplum yalnız çıkar sözleşmesi değil ortak duygular ve kurumlar ister. Korkuya dayalı birlik kırılgandır; umut ve adalet daha kalıcı bağ kurar.",
            "Sosyal politikayı yardım alan zayıflarla veren güçlüler olarak değil, herkesin yaşama kapasitesini büyüten ortak altyapı olarak görmek Spinozacı bakıştır.",
            "people-build-bridge", "İnsan başkalarıyla birleştiğinde tek bedenin yapamayacağı bilgi ve eylem kapasitesine ulaşır."),
        chapter("Duyguyu duyguyla dönüştürmek", "DÖRDÜNCÜ KISIM · DUYGUSAL AKIL",
            "Bir tutku yalnız doğru cümle duyduğu için kaybolmaz. Onu aşacak daha güçlü bir sevinç, umut veya anlama deneyimi gerekir. Akıl bedenden ayrı soğuk komutan değildir.",
            "Sigaranın zararlı olduğunu bilmek isteği otomatik silmez; sağlıklı yaşamdan alınan gerçek haz, destek grubu ve yeni rutin karşı güç oluşturabilir.",
            "Bu yaklaşım ahlaki kınamayı azaltır. İnsan zayıf olduğu için değil, belirli nedenler daha güçlü olduğu için davranır; dönüşüm yeni nedenler kurmayı ister.",
            "Eğitimde korkuyla ezberletmek yerine merak ve ustalık sevinci üretmek, bilgiye eşlik eden duyguyu değiştirir.",
            "emotion-counterforce", "Yoğun tutku yalnız kuru bilgiyle değil, ondan daha güçlü ve özgürleştirici bir duygusal düzenle dönüşür."),
        chapter("Tanrı'nın zihinsel sevgisi", "BEŞİNCİ KISIM · ÖZGÜRLÜK",
            "Doğanın zorunlu düzenini yeterli biçimde kavramak, Spinoza'nın Tanrı'nın zihinsel sevgisi dediği sevinci doğurur. İnsan olayları kişisel hakaret gibi değil bütünün bağlantıları içinde görür.",
            "Denizde dalga kendini okyanustan ayrı sanırsa her çarpışmayı düşmanlık yaşar; okyanusun hareketi olduğunu kavradığında kaybolmaz ama bakışı genişler.",
            "Bu sevgi dua eden kişisel Tanrı'ya yönelmez. Doğanın düzenini anlamanın kendisi huzur ve hayranlık kaynağıdır.",
            "Bilimsel merak ve doğa deneyimi bugün benzer bir bütünlük duygusu verebilir; fakat felsefi huzur gerçek acının toplumsal nedenlerini görmezden gelmemelidir.",
            "wave-knows-ocean", "Dalga kendini okyanusun hareketi olarak kavradığında her çarpışmayı kişisel düşmanlık gibi yaşamaz."),
        chapter("Sonsuzluk bakışı", "BEŞİNCİ KISIM · ZAMAN",
            "Şeyleri sonsuzluk açısından görmek, onları belirli anda bize yararlı ya da zararlı oluşunun ötesinde zorunlu ilişkiler içinde kavramaktır. Bu, kişisel ölümsüzlük vaadiyle aynı değildir.",
            "Bir günlük trafik sıkışıklığı yerden bakınca bütün dünya, şehir haritasından bakınca küçük akıştır. Ölçek büyüdükçe olay yok olmaz ama duygudaki yeri değişir.",
            "Spinoza zihnin bir yönünün ebediliği hakkında zor ve tartışmalı cümleler kurar. Bunları geleneksel ruhun sonsuza kadar sürmesi diye okumak yanıltıcıdır.",
            "Gündelik kaygıda daha geniş zaman ve neden ölçeğine çıkmak, sorunu inkâr etmeden onun tek gerçeklik olmasını önleyebilir.",
            "view-from-eternity", "Sonsuzluk bakışı günlük sıkışıklığı silmez, onu daha geniş neden ve zaman haritasında yerine koyar."),
        chapter("İnsan doğanın imparatorluğu değildir", "ÜÇÜNCÜ KISIM · DOĞALLAŞTIRMA",
            "Spinoza insanların doğa içinde ayrı bir imparatorluk olmadığını söyler. Öfke, kıskançlık ve arzu doğa yasalarının dışında günah lekeleri değil, nedenleri araştırılabilir olaylardır.",
            "Fırtınaya ahlaksız demediğimiz gibi öfkeye de yalnız kınama ile yaklaşmak açıklama vermez. Fakat fırtınadan korunur, öfkenin zararını da sınırlarız.",
            "Doğallaştırma onaylama değildir. Bir davranışın nedeni olması onu iyi yapmaz; yalnız etkili değişimin gerçek neden üzerinden kurulmasını sağlar.",
            "Ruh sağlığına damga yerine merakla yaklaşmak bu çizginin güncel gücüdür. İnsan anlaşılabilir olduğu için daha iyi desteklenebilir.",
            "not-empire-in-nature", "İnsan duyguları doğa yasalarının dışında günah lekeleri değil, nedenleri araştırılabilir olaylardır."),
    ],
    misreading="Spinoza'nın 'her şey zorunludur' sözü hiçbir şey yapmaya gerek yok demek değildir. Biz de neden zincirinin parçasıyız; bilgi, eğitim ve kurumlar sonuçları değiştiren gerçek nedenlerdir. Tanrı ya da Doğa sözü de geleneksel kişisel Tanrı anlayışıyla aynı değildir.",
    modern="Sinirbilim, psikoloji ve ekoloji Spinoza'nın zihin-beden birliği ve insanın doğa içindeki yeri üzerine ilgiyi artırdı. Geometrik kanıtların tümü kabul edilmese de duyguları kınamadan nedenleriyle anlama ve özgürlüğü kapasite artışı sayma yaklaşımı günceldir.",
    questions="Bu duygu hangi neden zincirinden doğdu? Bana kısa haz veren şey uzun vadeli yapabilme gücümü artırıyor mu? Özgürlüğü nedensiz seçim gibi mi, nedenleri anlayıp etkili hareket etme kapasitesi gibi mi düşünüyorum?",
    essence="İnsan doğadan ayrı özgür bir krallık değildir; tutkuların nedenini daha yeterli anladıkça dış etkilerle sürüklenmekten çıkar ve başkalarıyla birlikte daha etkin yaşama gücü kazanır.",
))


MORE_BOOKS.append(make_book(
    124, "dusunceler-pascal", "Düşünceler", "Blaise Pascal",
    "İnsanın hem evren karşısında kırılgan hem kendi kırılganlığını bilecek kadar büyük olduğunu; can sıkıntısından eğlenceye kaçışımızı, aklın sınırlarını, kalbin sezgisini ve inanç bahsini tamamlanmamış parçalarla araştıran çarpıcı iç konuşma.",
    "#665A58", "Pensées",
    [
        {"id": 1, "title": "Project Gutenberg - Pascal's Pensées", "url": "https://www.gutenberg.org/ebooks/18269"},
        {"id": 2, "title": "Stanford Encyclopedia of Philosophy - Blaise Pascal", "url": "https://plato.stanford.edu/entries/pascal/"},
        {"id": 3, "title": "Internet Encyclopedia of Philosophy - Pascal", "url": "https://iep.utm.edu/pascal-b/"},
    ],
    [
        chapter("Tamamlanmamış kitabın açık masası", "BAŞLANGIÇ · PARÇALAR",
            "Düşünceler bitmiş bir eser değil, Pascal'ın Hristiyanlık savunusu için tuttuğu notların ölümünden sonra düzenlenmiş halidir. Bu yüzden aynı fikir farklı yerde döner, sıralama baskıdan baskıya değişir.",
            "Bir yazarın masasındaki kartları, kenar notlarını ve yarım cümleleri bulduğunuzu düşünün. Okur yalnız kitabı değil düşüncenin hazırlanışını da görür.",
            "Parçalı yapı zayıflık ve güçtür. Sistem eksiktir ama ani gözlemler doğrudan vurur. Pascal bazen kanıtlamadan sezdirir.",
            "Metni roman sırası beklemeden, birbirini aydınlatan temalar arasında dolaşarak okumak daha verimlidir.",
            "fragment-table", "Düşünceler tamamlanmış bina değil, Pascal'ın ölümünden sonra bir araya getirilen açık çalışma masasıdır."),
        chapter("İnsan hem sefil hem büyük", "BİRİNCİ KISIM · ÇELİŞKİ",
            "İnsan yanılır, ölür ve küçük çıkarların peşinde sürüklenir; fakat kendi yanılgısını ve ölümünü düşünebilir. Sefaletin farkında olmak bile bir büyüklük işaretidir.",
            "Taş ezildiğini bilmez, insan ise bir kamış kadar kolay kırılırken onu kıran evreni düşünebilir. Beden zayıf, düşünce ufku geniştir.",
            "Pascal insanı yalnız yüceltmenin gurur, yalnız küçültmenin umutsuzluk doğurduğunu söyler. İki gerçeği aynı anda tutmak ister.",
            "Kişisel hatada 'ben değersizim' ile 'ben yanılmam' arasında üçüncü yol açılır: Kırılganım ve bunu anlayıp düzeltebilirim.",
            "wretched-great", "İnsan kırılganlığını bilecek kadar büyük, büyüklüğüne rağmen sürekli yanılacak kadar kırılgandır."),
        chapter("Düşünen kamış", "BİRİNCİ KISIM · İNSAN",
            "Evren insanı bir damla suyla yok edebilir; yine de insan öldüğünü bilir, evren bilmez. Pascal değeri fiziksel güçten bilinç ve düşünmeye taşır.",
            "Rüzgârda eğilen ince kamış ile onu ezen dev bulutu düşünün. Kamış kırılır ama bulutun ve kendi sonunun anlamını sorabilen odur.",
            "Düşünceyi yüceltmek bedensel ve toplumsal koşulları küçümsememelidir. Açlık ve hastalık zihnin özgürlüğünü daraltır; insan yalnız bilinç değildir.",
            "Yine de güç takıntılı kültürde önemli düzeltmedir: Büyük olmak daha çok yer kaplamak değil, durumunu dürüstçe kavrayabilmektir.",
            "thinking-reed", "Kırılgan kamış evrenden güçsüzdür, fakat kendi kırılganlığını düşünebildiği için benzersiz bir büyüklük taşır."),
        chapter("Bir odada sakin kalamamak", "İKİNCİ KISIM · EĞLENCE",
            "Pascal insanların mutsuzluğunun büyük bölümünü odasında sakin kalamamaya bağlar. Sessizlikte ölüm, boşluk ve kendimizle karşılaşırız; bu yüzden av, oyun, iş ve dedikoduya kaçarız.",
            "Telefon olmadan on dakika beklerken elinizin cebe gitmesi, kaçışın modern görüntüsüdür. İçerik önemli değildir; asıl işlev sessizliği doldurmaktır.",
            "Her eğlence kaçış değildir. Oyun, sanat ve dostluk gerçek değer taşır. Pascal'ın hedefi etkinliğin kendisi değil, onsuz kaldığımızda duyduğumuz dayanılmaz boşluktur.",
            "Gündelik deney olarak kısa sessizlik, hangi arzunun gerçek hangi hareketin yalnız oyalanma olduğunu gösteren ayna olabilir.",
            "room-without-phone", "Sessiz odada kalamayan insan, dış gürültüyle ölüm ve iç boşluk düşüncesinden kaçabilir."),
        chapter("Avdan çok kovalamacayı sevmek", "İKİNCİ KISIM · EĞLENCE",
            "İnsan çoğu zaman hedefe ulaştığında değil peşinden koşarken canlı hisseder. Avın kendisinden çok hazırlık, risk ve beklenti bizi meşgul eder; sonuç gelince yeni hedef gerekir.",
            "Aylarca beklenen terfi ilk hafta sevindirir, sonra normalleşir. Zihin yeniden sonraki unvana döner. Kovalamaca durduğunda boşluk geri gelir.",
            "Bu gözlem bütün hedefleri değersiz kılmaz. Sorun amacı elde edilince hayatın bütünüyle tamamlanacağını sanmaktır.",
            "Başarı planında 'ulaştıktan sonra hangi yaşamı sürdüreceğim?' sorusu, sonsuz koşu bandını fark etmeye yardım eder.",
            "hunt-without-prey", "İnsan çoğu zaman avı değil, kendini sessizlikten uzak tutan kovalamacanın hareketini arzular."),
        chapter("Can sıkıntısının açtığı boşluk", "İKİNCİ KISIM · BOŞLUK",
            "Can sıkıntısı Pascal için küçük rahatsızlık değil insanın kendi sonluluğuyla karşılaşmasıdır. Dış görev çekilince iç huzursuzluk görünür olur.",
            "Tatilin ilk günlerinde özgür hissedip sonra ne yapacağını bilememek, yoğun programın yalnız iş değil kimlik desteği olduğunu gösterir.",
            "Modern psikoloji can sıkıntısını dikkat, anlam ve uyarılma düzeyiyle daha çeşitli açıklar. Pascal onu fazla tek bir dinsel sonuca bağlar.",
            "Yine de sıkıntıyı hemen içerikle uyuşturmak yerine hangi anlam eksikliğini haber verdiğini dinlemek verimli olabilir.",
            "boredom-empty-chair", "Boş sandalye gibi can sıkıntısı, sürekli faaliyet çekildiğinde geride kalan anlam eksikliğini görünür kılar."),
        chapter("Hayal gücü dünyanın kraliçesi", "ÜÇÜNCÜ KISIM · YANILGI",
            "İnsan kanıttan çok görünüş, unvan, kıyafet ve ses tonuna kapılabilir. Pascal hayal gücünü bizi yöneten aldatıcı kraliçe diye anlatır.",
            "Aynı cümle beyaz önlük giyen kişiden gelince daha doğru sanılabilir. Giysi kanıt değildir ama zihnin güven hesabını değiştirir.",
            "Hayal gücü yalnız hata kaynağı değildir; bilim, sanat ve empati için gereklidir. Pascal'ın eleştirisi onun kanıt yerine tahta oturmasınadır.",
            "Bir iddiayı değerlendirirken sunanın statüsünü geçici olarak kapatıp gerekçeyi tek başına okumak bu kraliçeye küçük sınır koyar.",
            "imagination-queen", "Unvan ve görünüş hayal gücünün tacıyla kanıtın önüne geçebilir."),
        chapter("Alışkanlığın görünmez anayasası", "ÜÇÜNCÜ KISIM · GELENEK",
            "Birçok kural bize doğal gelir çünkü çocukluktan beri ona alışmışızdır. Başka ülkede farklı olan şey, kendi düzenimizin zorunlu değil tarihsel olduğunu gösterir.",
            "Yemekte çatalı hangi elle tuttuğunuz size doğru görünür; farklı kültürde aynı hareket kabalık sayılabilir. Beden, toplumsal kuralı düşünmeden uygular.",
            "Pascal geleneksel hukukun rastlantısını gösterirken ortak düzen ihtiyacını da kabul eder. Her kuralın kökeni keyfî diye onu bir gecede yıkmak kaos doğurabilir.",
            "Gelenek sorgusunda iki soru gerekir: Bu kural neden başlamıştı ve bugün kimi koruyup kimi zorluyor? Alışkanlık gerekçe yerine geçmemelidir.",
            "custom-constitution", "Alışkanlık, tarihsel kuralları doğanın kendisi gibi hissettiren görünmez anayasa yazar."),
        chapter("Adalet ile kuvvetin zor evliliği", "ÜÇÜNCÜ KISIM · SİYASET",
            "Adalet güçsüz kalırsa uygulanamaz, güç adaletsiz kalırsa zorbalık olur. Pascal insanların çoğu zaman güçlü olanı adil ilan ederek bu gerilimi gizlediğini söyler.",
            "Haklı ama uygulanmayan mahkeme kararı kâğıtta kalır; çok güçlü ama taraflı karar korku yaratır. Kurum hem meşru hem etkili olmalıdır.",
            "Pascal siyasi istikrar uğruna mevcut düzene fazla boyun eğebilir. Düzenin bozulma riski, adaletsizliğe sürekli teslimiyet gerekçesi olmamalıdır.",
            "Modern hukukta güçler ayrılığı ve bağımsız yargı, adalet ile kuvveti tek elde eritmeden bir araya getirmeye çalışır.",
            "justice-and-force", "Adalet uygulama gücüne, güç ise meşruiyet için adalet ölçüsüne ihtiyaç duyar."),
        chapter("Aklın son sınırı", "DÖRDÜNCÜ KISIM · BİLGİ",
            "Pascal büyük matematikçiydi; aklı küçümsemez. Fakat ilk ilkeleri ve hayatın bütün anlamını yalnız çıkarımla kanıtlayamayacağımızı düşünür. Akıl kendi sınırını tanıdığında daha akıllıdır.",
            "Cetvel masanın uzunluğunu ölçer ama sofranın neden değerli olduğunu söylemez. Araç kusurlu değildir; yalnız görevi farklıdır.",
            "Aklın sınırı kolayca kanıtsız inancı koruyan duvara dönüşebilir. Hangi sorunun gerçekten akıl dışı, hangisinin yalnız zor olduğunu ayırmak gerekir.",
            "Bilimde belirsizliği kabul etmek araştırmayı bitirmez; tam tersine nerede yeni kanıt gerektiğini gösterir. Sınır, teslimiyet değil yön işareti olabilir.",
            "ruler-and-table", "Cetvel uzunluğu ölçebilir ama sofranın hayatımızdaki değerini tek başına belirleyemez."),
        chapter("Kalbin bildiği ilkeler", "DÖRDÜNCÜ KISIM · KALP",
            "Pascal 'kalbin aklın bilmediği nedenleri vardır' derken yalnız romantik duygudan söz etmez. Zaman, uzam ve ilk ilkeler gibi bazı temelleri doğrudan sezdiğimizi düşünür.",
            "Bir arkadaşın acısını anlamak için önce mantıksal kanıt istemezsiniz. Deneyim, güven ve sezgi bazı bilgileri hesaptan önce taşır.",
            "Kalp yanılmaz değildir; önyargı ve korku da içten kesinlik hissi verebilir. Sezgi kanıtla ve başkalarının deneyimiyle sınanmalıdır.",
            "Kararda yalnız tabloya bakmak kadar yalnız iç sese güvenmek de eksiktir. Pascal iki bilgi biçiminin sınırını düşündürür.",
            "heart-and-reason", "Kalp bazı ilkeleri ve ilişkileri doğrudan hisseder, fakat bu iç kesinlik de eleştiri ve sınama ister."),
        chapter("İki sonsuz arasında insan", "BEŞİNCİ KISIM · EVREN",
            "İnsan sonsuz büyüklük ile sonsuz küçüklük arasında ortadadır. Evrenin yanında nokta, mikroskobik dünyanın yanında büyük bir dünyadır; ne bütünü kavrar ne bütünüyle bilgisizdir.",
            "Gece gökyüzüne bakıp küçülür, hücrenin içindeki düzeni düşününce büyürsünüz. Ölçek değiştikçe merkez duygusu çözülür.",
            "Pascal'ın bilimsel ayrıntıları bugün değişmiştir ama ölçek şoku sürer. İnsan gözle görülen orta dünyaya göre evrilmiş sezgilerle uçları anlamaya çalışır.",
            "Bu konum hem alçakgönüllülük hem merak üretir: Bilmediğimiz çoktur, fakat aradaki yerimiz soru sormaya yeter.",
            "between-infinities", "İnsan yıldızlara göre nokta, mikro dünyaya göre devdir; iki sonsuz arasında düşünür."),
        chapter("Gizlenen Tanrı", "BEŞİNCİ KISIM · İNANÇ",
            "Pascal'a göre Tanrı kendini ne zorlayıcı biçimde açık eder ne bütünüyle saklar. Arayan için işaret, kaçan için belirsizlik vardır; inanç mekanik kanıt değil varoluşsal yöneliştir.",
            "Çok parlak ışık bakışı kör eder, tam karanlık hiçbir şey göstermez. Pascal dini kanıtları yarı ışıkta görür.",
            "Bu düzen kuşkuyu her durumda suçlu çıkarma riski taşır: Görürsen kanıt, görmezsen saklanma. Yanlış çıkma ihtimali olmayan savı eleştirmek zordur.",
            "İnanç tartışmasında kişisel deneyime saygı ile kamusal iddianın kanıt yükünü ayırmak gerekir.",
            "hidden-light", "Pascal'ın Tanrısı zorlayıcı gün ışığında değil, arayışa alan bırakan yarı aydınlıkta görünür."),
        chapter("Pascal'ın bahsi", "BEŞİNCİ KISIM · BAHİS",
            "Tanrı'nın varlığı teorik olarak kesinleşmiyorsa Pascal kararı bahis gibi ele alır. Sonsuz kazanç ihtimali karşısında sınırlı dünyevi maliyet, inancı seçmeyi akılcı gösterebilir.",
            "Küçük primle çok büyük zarara karşı sigorta almak gibi, düşük olasılıklı ama sonsuz sonuç hesabı beklenen değeri değiştirir.",
            "Bahis birçok itiraz doğurur: Hangi dinin Tanrısı, zorla inanmak mümkün mü, samimiyetsiz inanç değerli mi? Sonsuz ödül her seçeneği hesap dışı büyütebilir.",
            "Kalıcı ders inanç sonucundan çok belirsizlik altında karar sorusudur. Kanıt tamamlanmadan da yaşamak ve seçim yapmak zorundayız.",
            "wager-table", "Kesin bilgi yokken Pascal sonsuz sonuç ihtimalini karar masasındaki bahis hesabına sokar."),
        chapter("Benlik neden sevilmek ister?", "ALTINCI KISIM · BENLİK",
            "Pascal insanın gerçek haliyle değil, başkalarının gözünde kurduğu görüntüyle sevilmek istediğini söyler. Kusurumuzu saklar, başarıyı büyütür ve alkışın aynasında kimlik ararız.",
            "Sosyal medyada yalnız en iyi anları paylaşırken hayatın tamamını değil beğenilecek sürümü gösteririz. Sonra başkalarının seçilmiş görüntüsüyle kendi dağınık günümüzü kıyaslarız.",
            "Kendini gösterme bütünüyle sahtekârlık değildir; insanlar toplumsal varlıktır. Sorun görüntü ile gerçek arasındaki fark büyüdükçe benliğin sürekli savunma istemesidir.",
            "Daha özgür ilişki, övgü toplamak kadar kusurla görülmeye ve başkasını da tek performansa indirmemeye dayanır.",
            "mirror-of-approval", "Benlik başkalarının aynasında kusursuz görüntü aradıkça gerçek haliyle görülmekten korkabilir."),
        chapter("Düzenler: akıl, beden ve kalp", "YEDİNCİ KISIM · DÜZEN",
            "Pascal farklı büyüklük düzenlerini ayırır: Bedensel güç, zihinsel deha ve sevgi-kutsallık aynı cetvelle ölçülemez. Bir kral matematikçiden siyasi, matematikçi kraldan zihinsel bakımdan üstün olabilir.",
            "Hızlı koşucuya iyi bir dosttan daha değerli demek, kilogramla müzik ölçmeye benzer. Başarı alanları birbirine çevrilemez.",
            "Toplum para ve görünürlüğü tek ölçü yaptığında bakım, bilgelik ve karakter görünmezleşir. Pascal değer çoğulluğuna alan açar.",
            "Kendinizi başkasıyla kıyaslarken önce aynı oyunda olup olmadığınızı sorun. Yanlış cetvel gereksiz aşağılık ve üstünlük üretir.",
            "three-orders", "Beden, zihin ve kalp başarıları farklı cetveller ister; birinin üstünlüğü diğerine otomatik çevrilemez."),
    ],
    misreading="Pascal aklı bütünüyle reddeden karanlık bir inanç savunucusu değildir; matematiksel aklın gücünü çok iyi bilir ve tam da bu yüzden sınırlarını çizer. Bahis de Tanrı'nın varlığını kanıtlamaz, belirsizlik altında pratik karar önerir.",
    modern="Psikoloji eğlence, dikkat, öz sunum ve can sıkıntısını Pascal'dan daha çeşitli açıklıyor. Yine de telefona kaçış, bitmeyen hedef kovalamacası ve performans benliği onun gözlemlerini şaşırtıcı biçimde güncel kılıyor. Dini çözüm herkes için ikna edici olmasa da insan teşhisi güçlüdür.",
    questions="Şu an yaptığım şey gerçek değer taşıdığı için mi, sessizlikten kaçmak için mi? Kendimi hangi yanlış cetvelle ölçüyorum? Aklın çözemediği yerde dürüst belirsizlik mi taşıyorum, yoksa istediğim cevabı kalbin kesinliği diye mi adlandırıyorum?",
    essence="İnsan evren karşısında kırılgan, kendi kırılganlığını bilecek kadar büyük ve sessizlikten kaçacak kadar huzursuzdur; akıl ile kalbin sınırını tanımak daha dürüst bir hayatın başlangıcı olabilir.",
))
