import json
import os

def create_hawking_summary():
    os.makedirs("data/summaries", exist_ok=True)
    
    summary = {
        "bookNo": 1,
        "title": "Zamanın Kısa Tarihi",
        "author": "Stephen Hawking",
        "subtitle": "Gençler ve Meraklı Zihinler İçin Popüler Bilim Kitapçığı",
        "meta": {
            "originalTitle": "A Brief History of Time",
            "compiler": "Yapay Zeka Asistanı",
            "date": "Haziran 2026",
            "language": "Türkçe"
        },
        "intro": "Stephen Hawking'in yazdığı \"Zamanın Kısa Tarihi\", insanlığın binlerce yıldır sorduğu en büyük soruları ele alır: Evren nasıl başladı? Zaman nereye akıyor? Kara deliklerin içinde ne var? Biz nereden geldik? Bu sorular ilk bakışta çok karmaşık ve sadece çılgın profesörlerin anlayabileceği şeyler gibi görünebilir. Ancak Hawking, bu devasa kitabı yazarken herkesin, hatta bir ortaokul öğrencisinin bile bu büyük gizemleri anlayabileceğini kanıtlamak istemiştir. Hawking, tüm kitabı boyunca tek bir matematiksel formül kullanmıştır: Einstein'ın meşhur E = mc² formülü. Çünkü ona göre, her formül kitabı okuyacak kişilerin yarısını kaçırır! Bu özet kitapçıkta, Stephen Hawking'in o büyüleyici anlatım tarzını koruyarak, evrenin en derin sırlarını günlük hayattan örnekler, eğlenceli benzetmeler ve sade açıklamalarla özetledik. Kitabın ilk sayfasında yer alan içindekiler dizinini takip ederek, Dünya'nın yuvarlak olduğunu keşfettiğimiz ilk günlerden, kara deliklerin buharlaşmasına, solucan deliklerinden zaman yolculuğuna ve fiziğin o büyük birleştirilme hayaline kadar heyecan dolu bir yolculuğa çıkacaksınız. Kemerlerinizi bağlayın, uzay ve zaman bükülmek üzere!",
        "chapters": [
            {
                "id": "intro_text",
                "title": "Giriş: Kozmosun Büyüleyici Arayışı",
                "image": "/images/hawking_portrait_sketch.png",
                "imageCaption": "Stephen Hawking: Tekerlekli sandalyesinden zihniyle kozmosun sınırlarını aşan deha.",
                "paragraphs": [
                    "Evrenin Gizemi: Hawking'in en büyük başarısı, tekerlekli sandalyeden kafasını kaldırıp sonsuz evreni zihinsel olarak keşfetmesidir. Onun popüler bilim dili, zor fizik terimlerini herkesin anlayabileceği birer masala dönüştürür. Bu kitapçıkta evrenin en heyecanlı konularını keşfedeceksiniz."
                ]
            },
            {
                "id": "chapter1",
                "title": "BÖLÜM 1: Evren Resmimiz (Dünyanın Şeklinden Başlayan Yolculuk)",
                "paragraphs": [
                    "**Düz Dünya İnancı ve Küresel Gerçeklik**\n\nÇok eski zamanlarda yaşayan insanlar, Dünya'yı devasa bir tepsi gibi düz zannederlerdi. Onlara göre eğer yeterince uzağa yürürseniz, Dünya'nın kenarından aşağıya, dipsiz bir boşluğa düşerdiniz! Hatta ünlü bir hikayeye göre, yaşlı bir kadın Dünya'nın dev bir kaplumbağanın sırtında durduğunu söylemişti. Biri ona 'Peki o kaplumbağa neyin üzerinde duruyor?' diye sorduğunda ise kadın gururla 'Onun altında da başka bir kaplumbağa var, aşağıya kadar hep kaplumbağa!' diye cevap vermişti. Ancak Aristoteles gibi eski Yunan filozofları gökyüzünü izleyerek bu teorinin yanlış olduğunu anladılar. Ay tutulması sırasında Dünya'nın Ay üzerindeki gölgesinin her zaman yuvarlak olduğunu fark ettiler. Eğer Dünya düz olsaydı gölgesi de ince uzun bir çizgi gibi olurdu. Ayrıca kutup yıldızının kuzeye gittikçe gökyüzünde daha yükseğe çıktığını gördüler. Sonunda anlaşıldı ki, üzerinde yaşadığımız evimiz dev bir küreydi.",
                    "**Dünya Evrenin Merkezinde mi? (Kopernik ve Galileo)**\n\nDünya'nın yuvarlak olduğunu anladıktan sonra insanlar bu kez de kendilerini evrenin en önemli şeyi zannedip Dünya'yı tam merkeze koydular. Batlamyus adındaki bilim insanı, Dünya'nın hiç kımıldamadan ortada durduğunu, Güneş'in, Ay'ın ve tüm yıldızların bizim etrafımızda döndüğünü iddia etti. Bu model kilise tarafından da çok sevildi çünkü insanoğlunun evrenin merkezinde olması dini inançlara uygun görünüyordu. Fakat 1514 yılında Mikolaj Kopernik adında cesur bir Polonyalı gökbilimci ortaya çıktı ve 'Hayır, biz merkezde değiliz! Dünya ve diğer tüm gezegenler aslında Güneş'in etrafında dönüyor' dedi. Kiliseden korktuğu için bu fikrini uzun süre gizlice paylaştı. Yıllar sonra Galileo Galilei kendi yaptığı teleskopla gökyüzüne bakıp Kopernik'in haklı olduğunu kanıtladı. Galileo, Jüpiter'in etrafında dönen küçük uyduları keşfetti; bu da her şeyin Dünya etrafında dönmek zorunda olmadığını gösteren ilk büyük kanıttı.",
                    "**Newton ve Sonsuz Evren Çelişkisi**\n\nIsaac Newton, kütleçekim yasasını bulduğunda kafası karıştı. Çünkü kütleçekim kuramına göre evrendeki her şey birbirini çeker. Eğer evren sınırlı olsaydı ve içinde belirli sayıda yıldız bulunsaydı, bu yıldızlar birbirini çekerek eninde sonunda tek bir noktada birleşir ve üst üste çökerdi. Bu çökmeyi engellemek için Newton ve dönemin bilim insanları, evrenin sonsuz olması gerektiğini düşündüler. Eğer evren sonsuzsa ve her yönde sonsuz sayıda yıldız varsa, her yıldız her yöne eşit çekileceğinden yerinde sabit kalabilirdi. Ancak bu fikir de başka bir çelişki doğurdu: Olbers Paradoksu. Eğer evren sonsuz ve yıldızlarla doluysa, geceleri gökyüzüne baktığımızda her noktada bir yıldız görmemiz gerekirdi. Bu da gece gökyüzünün kapkaranlık değil, Güneş kadar parlak olması gerektiği anlamına gelirdi! Bu durum, evrenin durağan ve sonsuz olamayacağının en büyük kanıtıydı.\n\n*\"Eğer evren sonsuz ve durağan olsaydı, geceleri gökyüzüne baktığımızda her yerin Güneş gibi parlaması gerekirdi. Ama gece karanlıktır.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter2",
                "title": "BÖLÜM 2: Uzay ve Zaman (Zaman Aslında Nedir ve Nasıl Bükülür?)",
                "paragraphs": [
                    "**Mutlak Uzay ve Zamanın Sonu**\n\nIsaac Newton'a göre uzay sabit bir sahne, zaman ise her yerde aynı hızla akan gizemli bir nehir gibiydi. Dünyadaki bir saat ile uzay boşluğundaki bir saat her zaman aynı zamanı göstermeliydi. Buna 'mutlak zaman' deniyordu. Ancak Albert Einstein, zamanın herkes için aynı olmadığını söyleyerek bu fikri tamamen yerle bir etti. Einstein, zamanın hareket hızımıza bağlı olarak değiştiğini fark etti. Yani siz çok hızlı hareket ediyorsanız, sizin için zaman duran birine göre daha yavaş akar! Bu ilk başta kulağa inanılmaz gelebilir ama modern uçaklarda ve uydularda hassas atom saatleriyle yapılan deneyler bunu defalarca kanıtlamıştır. Zaman sabit değil, kişiye özel ve esnektir.",
                    "**Işığın Hızı ve Esrarengiz Yolculuk**\n\nZamanın esnemesinin arkasında yatan büyük sır ışık hızıdır. Işık, saniyede tam 300.000 kilometre hızla koşar. Evrendeki en hızlı şey ışık hızıdır ve bu hız asla ama asla değişmez. Örneğin, siz bir trenin üstünde ışık hızına yakın bir hızla gitseniz ve elinizdeki feneri yaksanız, dışarıdan bakan biri fenerin ışığını trenin hızı artı ışık hızı olarak değil, yine sadece ışık hızı olarak ölçer. Işık hızının herkes için aynı kalabilmesi için doğa ilginç bir hile yapar: Zamanı yavaşlatır ve uzayı kısaltır! Hızlandıkça zaman sizin için daha yavaş akmaya başlar ki ışık hızını aşamayın. Eğer ışık hızına ulaşabilseydiniz, sizin için zaman tamamen dururdu!",
                    "**Einstein'ın Özel Görelilik Kuramı**\n\nEinstein'ın 1905 yılında yayınladığı Özel Görelilik Kuramı, uzay ve zamanın birbirinden bağımsız olmadığını, ikisinin birleşerek 'uzay-zaman' adında dört boyutlu bir örtü oluşturduğunu söyler (üç boyutlu uzay artı dördüncü boyut olan zaman). Bunu anlamak için ünlü İkizler Paradoksu'nu düşünebiliriz. İki ikiz kardeşten biri Dünya'da kalsın, diğeri ise ışık hızına yakın bir uzay gemisiyle uzayda seyahate çıksın. Uzaydaki kardeş birkaç yıl gezip Dünya'ya geri döndüğünde, Dünya'daki kardeşinin çoktan yaşlandığını, kendisinin ise hala çok genç kaldığını görür. Çünkü hızlı hareket eden uzay gemisinde zaman çok daha yavaş akmıştır.",
                    "**Genel Görelilik ve Uzay-Zaman Çarşafı**\n\nEinstein, 1915 yılında Genel Görelilik Kuramı'nı geliştirerek kütleçekimini yeniden tanımladı. Kütleçekimi, cisimlerin birbirini görünmez iplerle çekmesi değildir. Uzay-zamanı gerilmiş esnek bir çarşaf veya trambolin gibi düşünün. Eğer bu trambolinin ortasına ağır bir gülle (örneğin Güneş) koyarsanız, trambolin aşağıya doğru bükülür. Şimdi bu tramboline küçük bir bilye (örneğin Dünya) fırlatırsanız, bilye düz gitmek yerine Güneş'in yarattığı bu çukura doğru eğilir ve onun etrafında dönmeye başlar. İşte gezegenlerin Güneş etrafında dönme sebebi budur! Kütleçekim, büyük kütleli cisimlerin uzay-zaman çarşafını bükmesinden başka bir şey değildir.\n\n*\"Zaman, sabit bir nehir değildir; büyük kütlelerin ve yüksek hızların yakınında yavaşlayan esnek bir örtüdür.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter3",
                "title": "BÖLÜM 3: Genişleyen Evren (Şişen Bir Balonun Üzerindeyiz!)",
                "image": "/images/expanding_universe_sketch.png",
                "imageCaption": "Şişen balon benzetmesi: Evren genişledikçe tüm galaksiler birbirinden hızla uzaklaşmaktadır.",
                "paragraphs": [
                    "**Yıldızların Uzaklığını Ölçmek**\n\nEvrenin ne kadar büyük olduğunu anlamak için önce yıldızların bize ne kadar uzak olduğunu ölçmemiz gerekir. Peki, elimizde devasa bir mezura olmadığına göre bunu nasıl yaparız? Gökbilimciler iki yöntem kullanır. Birincisi 'parallaks' denilen yöntemdir. Parmağınızı gözünüzün önüne koyup sırayla sol ve sağ gözünüzü kapatırsanız parmağınızın arka plana göre hareket ettiğini görürsünüz. Dünya Güneş etrafında dönerken, yakın yıldızlar da uzak yıldızlara göre hafifçe yer değiştirir. Bu açı farkından yıldızın uzaklığı hesaplanır. İkinci yöntem ise 'Sefe Değişkenleri' denilen özel yıldızlardır. Bu yıldızlar tıpkı deniz fenerleri gibi belirli aralıklarla parlayıp sönerler. Parlama hızlarından onların gerçek parlaklıklarını anlarız. Gerçek parlaklığını bildiğimiz bir yıldızın Dünya'dan ne kadar sönük göründüğüne bakarak uzaklığını kolayca bulabiliriz.",
                    "**Hubble ve Kırmızıya Kayma**\n\n1929 yılında Edwin Hubble, insanlık tarihinin en büyük keşiflerinden birini yaptı. Hubble, uzak galaksilerden gelen ışıkları incelediğinde şaşırtıcı bir şey fark etti. Bu galaksilerin yaydığı ışık spektrumu kırmızı renge doğru kayıyordu. Işığın kırmızıya kayması ne demektir? Bunu ses dalgalarındaki Doppler Etkisi ile anlayabiliriz. Bir ambulans size doğru gelirken sesi tizleşir, sizden uzaklaşırken ise sesi pesleşir (yani dalga boyu uzar). Işıkta da benzer bir durum vardır. Eğer bir galaksi bizden uzaklaşıyorsa, ışık dalgaları boyuna esner ve rengi kırmızıya kayar. Hubble, neredeyse tüm galaksilerin bizden hızla uzaklaştığını ve en uzaktaki galaksilerin en hızlı uzaklaşanlar olduğunu gördü. Bu, evrenin sürekli genişlediği anlamına geliyordu!",
                    "**Friedman Modelleri ve Evrenin Kaderi**\n\nAlexander Friedman adındaki Rus matematikçi, Einstein'ın denklemlerini kullanarak genişleyen bir evrenin nasıl davranacağını gösteren modeller geliştirdi. Friedman'a göre evrenin geleceği, içindeki madde miktarına (yani kütleçekim gücüne) bağlıdır. Üç olasılık vardır:\n1. **Kapalı Evren:** Evrendeki madde miktarı çok fazladır. Genişleme bir süre sonra durur ve kütleçekim evreni geri çekerek dev bir büzüşmeyle yok eder (Büyük Çöküş).\n2. **Açık Evren:** Madde miktarı azdır. Kütleçekim genişlemeyi durduramaz ve evren sonsuza kadar genişleyip soğur.\n3. **Düz Evren:** Genişleme hızı ile kütleçekim tam dengededir. Evren sonsuza kadar genişler ama genişleme hızı giderek sıfıra yaklaşır.",
                    "**Büyük Patlama (Big Bang) Tekilliği**\n\nEvrenin genişlediğini biliyorsak, zaman filmini geriye doğru sardığımızda ne görürüz? Galaksilerin birbirine giderek yaklaştığını ve sonunda her şeyin tek bir noktada birleştiğini! Yaklaşık 13.8 milyar yıl önce, evrendeki tüm madde, enerji, uzay ve zaman sıfır hacimli, sonsuz yoğunlukta tek bir noktaya sıkışmıştı. Bu noktaya 'tekillik' diyoruz. İşte bu tekillik anında yaşanan devasa patlamaya Büyük Patlama (Big Bang) adı verilir. Büyük Patlama'dan önce ne vardı sorusu anlamsızdır çünkü zamanın kendisi de bu patlamayla başlamıştır. Zamanın sıfır noktası burasıdır.\n\n*\"Evren durağan değildir. O, şişen bir balon gibidir ve üzerindeki galaksiler sürekli olarak birbirinden uzaklaşmaktadır.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter4",
                "title": "BÖLÜM 4: Belirsizlik İlkesi (Kuantum Dünyasının Tuhaf Kuralları)",
                "paragraphs": [
                    "**Laplace'ın Şeytanı ve Determinizm**\n\n19. yüzyılda bilim insanları evrenin tıpkı devasa bir saat gibi tıkır tıkır işleyen kuralları olduğuna inanıyorlardı. Fransız bilim insanı Pierre-Simon Laplace, eğer evrendeki tüm atomların yerini ve hızını bilirsek, fizik kurallarını kullanarak gelecekte ne olacağını yüzde yüz kesinlikle tahmin edebileceğimizi söyledi. Bu fikre 'determinizm' deniyordu. Yani her şey önceden belirlenmişti ve evren bir robot gibi çalışıyordu. Ancak atomların dünyası keşfedildiğinde, bu fikrin tamamen bir rüya olduğu anlaşıldı.",
                    "**Planck and Işık Paketleri**\n\nAlman fizikçi Max Planck, sıcak cisimlerin yaydığı radyasyonu incelerken ışığın sürekli bir akış halinde değil, 'kuantum' adını verdiği minik enerji paketçikleri halinde yayıldığını keşfetti. Bunu şuna benzetebiliriz: Işık musluktan akan sürekli bir su gibi değil, tek tek düşen su damlaları gibidir. Bu keşif, fiziğin en çılgın dalı olan Kuantum Mekaniği'nin doğuşuna yol açtı. Artık doğayı anlamak için mikroskobik ölçekteki bu paketçiklerin dilini öğrenmek gerekiyordu.",
                    "**Heisenberg'in Belirsizlik İlkesi**\n\n1927 yılında Werner Heisenberg, bilim dünyasını sarsan Belirsizlik İlkesi'ni ortaya koydu. Bu ilkeye göre, bir parçacığın (örneğin bir elektronun) nerede olduğunu ve nereye doğru gittiğini (hızını) aynı anda asla tam bir kesinlikle ölçemeyiz. Bunu anlamak için karanlık bir odadaki hızlı bir kuşu fotoğraflamaya çalıştığınızı hayal edin. Kuşu görmek için flaş patlatırsınız. Ancak kuantum dünyasında flaşın yaydığı ışık paketçikleri o kadar güçlüdür ki elektrona çarptığı anda onu fırlatıp hızını değiştirir! Yani yerini tam görmek istediğinizde hızını bozarsınız; hızını ölçmek istediğinizde ise yerini kaçırırsınız. Doğa, bize mikro dünyada tam kesinliği yasaklar; geriye sadece ihtimaller kalır.",
                    "**Dalga-Parçacık İkililiği**\n\nKuantum dünyasının en tuhaf özelliklerinden biri de parçacıkların bazen bir bilye (parçacık), bazen de su yüzeyindeki dalgalar gibi davranmasıdır. Örneğin, tek tek fırlatılan elektronlar iki yarıktan geçtiklerinde arkadaki ekranda dalgaların oluşturduğu gibi girişim desenleri oluştururlar. Bu durum, kuantum nesnelerinin biz onlara bakmadığımız sürece birer 'olasılık dalgası' olarak yayıldığını, ancak onları ölçmeye veya gözlemlemeye kalktığımız anda tek bir noktada parçacık olarak belirdiğini gösterir. Einstein bu fikirden hiç hoşlanmamış ve 'Tanrı zar atmaz!' diyerek kuantumun şansa dayalı yapısını reddetmiştir. Ancak Hawking'in de belirttiği gibi, Einstein yanılıyordu; Tanrı sadece zar atmakla kalmıyor, bazen zarları göremediğimiz yerlere fırlatıyor!\n\n*\"Doğa bize mikro dünyada tam bir kesinliği yasaklar. Bir parçacığın yerini ne kadar iyi bilirsek, hızını o kadar az bilebiliriz.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter5",
                "title": "BÖLÜM 5: Temel Parçacıklar ve Doğanın Kuvvetleri (Evrenin Lego Parçaları)",
                "paragraphs": [
                    "**Maddenin En Derin Sırrı (Kuarklar)**\n\nÇok uzun süre boyunca atomun, maddenin bölünemez en küçük yapı taşı olduğu düşünüldü. Sonra atomun içinde proton, nötron ve elektronlar keşfedildi. Ama macera burada bitmedi! Bilim insanları proton ve nötronların da içinde daha küçük parçacıklar olduğunu buldular: Kuarklar. Kuarklar evrenin en temel Lego parçalarından bazılarıdır. Protonların içinde üç adet kuark bulunur. Kuarklar asla tek başlarına doğada bulunamazlar; birbirlerine o kadar sıkı bağlanmışlardır ki onları ayırmaya çalışmak lastik bir bandı germek gibidir. Bandı ne kadar çekerseniz çekme kuvveti o kadar artar, en sonunda bant koptuğunda ise yeni kuark çiftleri oluşur.",
                    "**Spin Nedir? (Fermiyonlar ve Bozonlar)**\n\nKuantum dünyasındaki parçacıkların 'spin' denilen garip bir özelliği vardır. Spin, parçacığın kendi etrafında dönmesine benzer ama tam olarak öyle değildir. Bir parçacığın spini, onun farklı açılardan bakıldığında nasıl göründüğünü belirler. Örneğin, spini 1 olan bir parçacık, kendi etrafında tam bir tur (360 derece) döndüğünde ilk haline döner. Spini 2 olan bir parçacık yarım turda ilk haline döner. Spini 1/2 (yarım) olan parçacıklar ise ancak iki tam tur döndüklerinde eski hallerine dönebilirler! Evrendeki parçacıklar ikiye ayrılır: Spinleri yarım olan **Fermiyonlar** (maddeyi oluşturan kuark ve elektronlar) ve spinleri tam sayı olan **Bozonlar** (kuvvetleri taşıyan parçacıklar).",
                    "**Evreni Yöneten Dört Temel Kuvvet**\n\nEvrendeki her türlü etkileşim ve hareket, doğadaki dört temel kuvvet sayesinde gerçekleşir:\n1. **Kütleçekim:** En zayıf kuvvettir ama devasa mesafelerde etkilidir. Gezegenleri ve yıldızları bir arada tutar.\n2. **Elektromanyetik Kuvvet:** Mıknatısların çekimini, elektriği ve atomların etrafındaki elektronları bir arada tutan kuvvettir. Kütleçekimden çok daha güçlüdür.\n3. **Zayıf Nükleer Kuvvet:** Radyoaktif maddelerin bozulmasına ve Güneş'in parlamasını sağlayan nükleer tepkimelere yol açar.\n4. **Güçlü Nükleer Kuvvet:** En güçlü kuvvettir. Atom çekirdeğindeki proton ve nötronları (ve onların içindeki kuarkları) bir arada sımsıkı tutar.",
                    "**Sanal Parçacıklar ve Kuvvet Taşıyıcıları**\n\nKuantum fiziğinde kuvvetler uzaktan uzağa büyüyle iletilmez. Kuvvetlerin iletilmesi, parçacıkların birbirine 'kuvvet taşıyıcı' parçacıklar atıp tutmasıyla olur. Bunu su üstündeki iki kayıkta duran insanların birbirlerine ağır toplar fırlatmasına benzetebiliriz. Biri topu fırlattığında geriye doğru itilir, diğeri topu yakaladığında o da geriye doğru itilir. Dışarıdan bakan biri iki kayığın birbirini ittiğini görür. Bu alışveriş sırasında kullanılan parçacıklara 'sanal parçacıklar' denir çünkü bunlar doğrudan gözlemlenemezler, ancak yarattıkları kuvvet etkileri ölçülebilir. Örneğin elektromanyetik kuvveti taşıyan parçacık fotondur (ışık).\n\n*\"Evren, görünmeyen sanal parçacıkların birbirine attığı mesajlarla ayakta duran devasa bir Lego yapısıdır.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter6",
                "title": "BÖLÜM 6: Kara Delikler (Uzaydaki Dipsiz Kozmik Kuyular)",
                "paragraphs": [
                    "**Kara Delik Fikrinin Doğuşu**\n\nKara delik fikri sanıldığı kadar yeni değildir. 1783 yılında John Michell adında bir İngiliz rahip ve bilim insanı ilginç bir şey düşündü: Eğer bir cismin kütleesi çok büyük, boyutları ise çok küçük olursa, yerçekimi o kadar güçlü olur ki saniyede 300.000 km hızla giden ışık bile onun çekiminden kaçamaz. Işık kaçamadığı için bu cisim uzayda tamamen karanlık görünecektir. Michell bunlara 'karanlık yıldızlar' adını verdi. Yıllar sonra Laplace da benzer bir hesaplama yaptı. Ancak o dönem ışığın bir dalga olduğu düşünüldüğünden, yerçekiminin ışıktan nasıl etkileneceği anlaşılamadı ve bu fikir unutuldu. Ta ki Einstein'ın Genel Görelilik kuramına kadar.",
                    "**Bir Yıldız Nasıl Ölür? (Chandrasekhar Limiti)**\n\nBir yıldız, yaşamı boyunca merkezindeki nükleer yakıtı yakarak dışarıya doğru devasa bir basınç (ısı ve ışık) üretir. Bu dış basınç, yıldızın kendi içine çökmek isteyen yerçekimini dengeler. Yıldız böylece milyarlarca yıl parlar. Ancak yakıt bittiğinde dış basınç durur ve kütleçekim savaşı kazanır. Yıldız kendi içine doğru çökmeye başlar. Hintli fizikçi Subrahmanyan Chandrasekhar, çöken yıldızın kaderinin kütlesine bağlı olduğunu hesapladı. Eğer yıldız Güneş'ten en fazla 1.4 kat daha büyükse, çöküş bir yerde durur ve yıldız soğuk bir 'Beyaz Cüce'ye veya 'Nötron Yıldızı'na dönüşür. Bu sınıra Chandrasekhar Limiti denir. Ancak bu limitten daha ağır olan dev yıldızların çöküşünü hiçbir şey durduramaz. Yıldız sonsuza kadar çökmeye devam eder ve bir kara delik oluşturur.",
                    "**Olay Ufku ve Tekillik**\n\nKara deliğin etrafında, geri dönüşü olmayan hayali bir sınır vardır. Bu sınıra **Olay Ufku** denir. Bunu dev bir şelalenin döküldüğü kenara benzetebiliriz. Şelalenin kenarına yaklaşan bir kayıkçı, akıntı çok güçlü değilse geri kürek çekebilir. Ancak o kritik sınırı geçtiği an, ne kadar güçlü kürek çekerse çeksin şelaleden aşağı düşmekten kurtulamaz. Olay ufku da böyledir; bu sınırı geçen hiçbir şey, hatta ışık bile geri dönemez. Olay ufkunun tam merkezinde ise yıldızın tüm kütlesinin sıkıştığı, hacmi sıfır, yoğunluğu ve uzay-zaman eğriliği sonsuz olan **Tekillik** noktası bulunur. Tekillikte bildiğimiz tüm fizik kuralları ve zaman kavramı çöker.",
                    "**Kara Deliklerin Gözlemlenmesi**\n\nMadem kara delikler tamamen karanlıktır ve ışık bile saçmazlar, o halde gökbilimciler uzayda onları nasıl buluyorlar? Cevap basit: Onların etraflarındaki maddelere yaptığı etkilere bakarak! Bir kara deliğin yakınında dolanan normal bir yıldız varsa, kara delik o yıldızın gazlarını güçlü çekimiyle kendine doğru çeker. Bu gazlar kara deliğin etrafında dönerken sürtünmeden dolayı milyonlarca derece ısınır ve uzaya çok güçlü X-ışınları saçar. Dünya'daki teleskoplar bu X-ışınlarını görebilir. Örneğin, Cygnus X-1 adı verilen bölgede gökbilimciler, görünmeyen çok ağır bir cismin etrafında çılgınca dönen mavi bir dev yıldız keşfettiler. Bu, gözlemlenen ilk kara delik adayıydı.\n\n*\"Kara deliklerin olay ufku, evrenin geri dönüşü olmayan tek yönlü kapısıdır. Oraya giren her şey geleceğini kaybeder.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter7",
                "title": "BÖLÜM 7: Kara Delikler O Kadar da Kara Değil (Buharlaşan Devler)",
                "paragraphs": [
                    "**Kara Delikler ve Termodinamik**\n\nFizikte çok önemli bir kural vardır: Termodinamiğin İkinci Yasası. Bu yasa, evrendeki düzensizliğin (entropinin) her zaman artması gerektiğini söyler. Eğer bir kara deliğe sıcak bir fincan çay atarsanız, o çay ve içindeki düzensizlik kara deliğin içinde kaybolur. Dışarıdaki evrenin entropisi azalmış gibi görünür. Bu durum fizik yasalarına aykırıdır! Genç fizikçi Jacob Bekenstein, kara deliğin olay ufkunun büyüklüğünün aslında onun entropisini temsil ettiğini öne sürdü. Kara deliğe bir şey attığınızda olay ufku büyür, yani entropi yine artmış olur. Ancak eğer bir cismin entropisi (düzensizliği) varsa, onun bir sıcaklığı da olmalıdır. Sıcaklığı olan her cisim ise dışarıya ısı (radyasyon) yaymalıdır! Ama kara delikler tamamen karanlık değil miydi? Bu büyük bir çelişkiydi.",
                    "**Sanal Parçacıkların Dansı ve Hawking Işıması**\n\nStephen Hawking, kuantum mekaniğini kara deliklerin olay ufkuna uygulayarak bu bilmeceyi çözdü. Kuantum fiziğine göre boş uzay aslında boş değildir. Boşlukta sürekli olarak sanal parçacık çiftleri (biri madde, diğeri zıt-madde) var olur, birbirlerine çarpıp yok olurlar. Bu olay her an, her yerde yaşanmaktadır. Hawking, bu sanal parçacık çiftlerinin tam bir kara deliğin olay ufkunun sınırında oluştuklarında ne olacağını düşündü. Bazen, parçacıklardan biri olay ufkunun içine düşer, diğeri ise dışarıda kalır. İçeri düşen parçacık zıt-madde özelliğindeyse kara deliğin kütlesini azaltır. Dışarıda kalan diğer kardeş ise eşini kaybedince uzay boşluğuna doğru fırlatılır. Dışarıdan bakan bir gözlemci için kara delik dışarıya parçacık (yani radyasyon) saçıyor gibi görünür! İşte buna **Hawking Radyasyonu** (veya Işıması) denir.",
                    "**Kara Deliklerin Buharlaşması ve Kaderi**\n\nMadem kara delikler sürekli olarak dışarıya radyasyon yayıyor ve bu sırada kütle kaybediyorlar, o halde zamanla ne olur? Buharlaşırlar! Evet, kara delikler sonsuza kadar yaşamazlar. Dışarıya enerji verdikçe kütleleri azalır, kütleleri azaldıkça sıcaklıkları daha da artar ve daha hızlı radyasyon yaymaya başlarlar. Ömürlerinin en sonunda, artık küçücük kaldıklarında, milyonlarca hidrojen bombası gücünde devasa bir patlamayla evrenden tamamen silinirler. Ancak büyük kara deliklerin buharlaşması çok uzun sürer (evrenin yaşından bile daha uzun!). Sadece Büyük Patlama sırasında oluşmuş olabilecek mikro kara delikler günümüzde bu patlamayla yok oluyor olabilir.\n\n*\"Kara delikler sanıldığı kadar kara değildir. Kuantum sızıntıları yüzünden yavaşça radyasyon yayarlar ve sonunda patlayarak buharlaşırlar.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter8",
                "title": "BÖLÜM 8: Evrenin Kökeni ve Kaderi (Büyük Patlama Nasıl Başladı?)",
                "paragraphs": [
                    "**Sıcak Büyük Patlama ve Şişme (Enflasyon)**\n\nBüyük Patlama'dan hemen sonraki ilk saniyelerde evren inanılmaz derecede sıcak ve yoğundu. O kadar sıcaktı ki atomlar bile oluşamıyordu; her yer kuarklar ve elektronlardan oluşan kozmik bir çorba gibiydi. Evren genişledikçe soğudu ve parçacıklar birleşerek ilk atomları oluşturdu. Bilim insanları evrenin neden her yönde bu kadar pürüzsüz ve eşit sıcaklıkta olduğunu açıklamak için 'Şişme' (Enflasyon) teorisini geliştirdiler. Bu teoriye göre, Büyük Patlama'nın hemen ardından evren, saniyenin trilyonda birinden çok daha kısa bir sürede, ışık hızından kat kat daha hızlı bir şekilde genişledi. Tıpkı buruşuk bir balonun şişirildiğinde pürüzsüz hale gelmesi gibi, evren de bu ani şişmeyle düzleşti ve pürüzsüzleşti.",
                    "**İnsancı İlke (Anthropic Principle)**\n\nEvrendeki fizik kuralları ve sabitler (örneğin kütleçekim gücü, elektronun yükü) tam da bizim yaşayabileceğimiz kadar hassas ayarlara sahiptir. Eğer kütleçekim birazcık daha güçlü olsaydı, evren hemen geri çökerdi. Birazcık daha zayıf olsaydı, yıldızlar ve gezegenler asla oluşamazdı. Neden evren tam bizim istediğimiz gibidir? Bunu açıklamak için İnsancı İlke öne sürülür. İki versiyonu vardır. **Zayıf İnsancı İlke:** Çok sayıda farklı evren veya bölgeler vardır ve biz sadece yaşamın oluşabileceği, koşulların uygun olduğu bu özel bölgede yaşayıp bu soruyu sorabiliyoruz. **Güçlü İnsancı İlke:** Evrenin amacı zaten eninde sonunda zeki yaşamı (bizi) yaratmaktır. Hawking, zayıf insancı ilkeyi daha bilimsel bulmaktadır.",
                    "**Sınırların Olmaması Önerisi (No-Boundary Proposal)**\n\nEğer evrenin Büyük Patlama ile bir başlangıcı varsa, o başlangıç anındaki 'tekillik' noktasında tüm fizik kuralları çöker. Bu da bilimin evrenin nasıl başladığını asla tam olarak açıklayamayacağı anlamına gelir. Stephen Hawking ve ortağı Jim Hartle bu sorunu çözmek için harika bir fikir ortaya attılar: **Sınırsızlık Önerisi**. Bu öneride Hawking, 'sanal zaman' denilen matematiksel bir kavram kullanır. Sanal zamanda geçmiş, gelecek veya başlangıç/bitiş gibi sınırlar yoktur; zaman tıpkı Dünya'nın yüzeyi gibidir. Dünya'nın yüzeyinde yürüdüğünüzde 'Dünya'nın başladığı yer' veya 'Dünya'nın bittiği kenar' diye bir yer bulamazsınız. Dünya yuvarlaktır ve sınırı yoktur. Hawking'e göre uzay-zaman da sanal zamanda dört boyutlu kapalı bir küre gibidir; başlangıcı veya sonu olan bir sınırı yoktur. Evren tamamen kendi içine kapalıdır ve yaratılış anı gibi bir tekillik barındırmaz.\n\n*\"Evrenin başlangıcını araştırmak, Dünya'nın kenarını aramaya benzer. Yuvarlak bir Dünya'nın kenarı yoktur; sınırları olmayan bir evrenin de başlangıç sınırı olmayabilir.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter9",
                "title": "BÖLÜM 9: Zamanın Oku (Zaman Neden Hep İleriye Doğru Akar?)",
                "image": "/images/time_bending_sketch.png",
                "imageCaption": "Zamanın Oku: Entropi yasası gereği, zaman her zaman düzensizliğin arttığı yöne doğru (ileriye) akar.",
                "paragraphs": [
                    "**Entropi ve Düzensizlik Kanunu**\n\nMasadan düşüp kırılan bir porselen bardağı hayal edin. Bardak tuz buz olur ve parçaları yere dağılır. Peki, yerdeki parçaların kendiliğinden havaya fırlayıp masanın üzerinde sapasağlam bir bardak olarak birleştiğini hiç gördünüz mü? Tabii ki hayır! Peki ama neden? Fizik yasalarına göre bu teorik olarak mümkündür fakat pratikte asla gerçekleşmez. Bunun sebebi Termodinamiğin İkinci Yasası, yani **Entropi**dir. Entropi, düzensizlik miktarıdır. Doğadaki her şey kendiliğinden düzensizliğe doğru akar. Düzenli bir bardağın kırılıp düzensiz parçalara ayrılması çok kolaydır çünkü düzensiz olmanın milyonlarca farklı yolu varken, düzenli (sapasağlam) olmanın tek bir yolu vardır. Zaman, düzensizliğin arttığı yöne doğru akar.",
                    "**Zamanın Üç Farklı Oku**\n\nStephen Hawking, zamanın hep ileriye doğru akmasını açıklayan üç farklı 'zaman oku' tanımlar:\n1. **Termodinamik Zaman Oku:** Evrendeki düzensizliğin (entropinin) sürekli arttığı yöndür. Bardakların kırıldığı yöndür.\n2. **Psikolojik Zaman Oku:** Bizim zamanı hissetme şeklimizdir. Geçmişi hatırlarız ama geleceği hatırlayamayız. Beynimiz bilgileri kaydederken entropiyi artırdığı için psikolojik ok, termodinamik ok ile aynı yöne bakar.\n3. **Kozmolojik Zaman Oku:** Evrenin büzülmek yerine genişlediği yöndür.",
                    "**Evren Büzülürse Zaman Geriye Akar mı?**\n\nStephen Hawking, kariyerinin ilk yıllarında ilginç bir hata yaptı. Evrenin genişlemesi durup içine doğru büzülmeye (Büyük Çöküş'e doğru gitmeye) başladığında kozmolojik zaman okunun tersine döneceğini ve böylece diğer okların da tersine döneceğini düşündü! Yani evren büzülürken kırık bardaklar birleşecek, insanlar gençleşecek ve zaman geriye akacaktı. Fakat daha sonra yaptığı detaylı hesaplamalarla bunun yanlış olduğunu anladı ve hatasını cesurca kabul etti. Evren büzülürken bile termodinamik zaman oku tersine dönmez; yani entropi artmaya devam eder ve zaman yine ileriye akar. Kırık bardaklar yine birleşmez. Zamanı geri döndürmek evren büzülse bile imkansızdır.\n\n*\"Zamanın oku, düzensizliğin arttığı yöndür. Odamızın kendiliğinden dağılması gibi, evren de sürekli düzensizliğe doğru akar.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter10",
                "title": "BÖLÜM 10: Solucan Delikleri ve Zaman Yolculuğu (Geleceğe Gitmek Kolay, Peki Ya Geçmişe?)",
                "paragraphs": [
                    "**Uzay-Zamanı Kestirmeden Geçmek (Solucan Delikleri)**\n\nUzayda iki nokta arasındaki mesafe milyonlarca ışık yılı olabilir. Işık hızıyla bile gitsek oraya ulaşmamız milyonlarca yıl sürer. Ancak Genel Görelilik kuramı, uzay-zamanın bükülebileceğini söyler. Eğer uzay-zamanı iki ucundan büküp birbirine yaklaştırırsak ve aralarında bir tünel açarsak ne olur? İşte bu tünele **Solucan Deliği** (wormhole) denir. Bunu anlamak için iki ucunda elmalar olan düz bir kağıt hayal edin. Bir karınca kağıdın bir ucundan diğer ucuna yürümek zorunda kalırsa tüm kağıdı geçmelidir. Ama kağıdı ikiye katlayıp üst üste getirir ve arasından bir delik açarsak, karınca tüm kağıdı yürümek yerine o delikten doğrudan karşı tarafa geçebilir. Solucan delikleri uzaydaki devasa kestirme yollardır.",
                    "**Zaman Makinesi Yapılabilir mi?**\n\nSolucan delikleri sadece uzayda değil, zamanda da kestirme yollar oluşturabilir. Eğer bir solucan deliğinin bir ucunu alıp ışık hızına yakın bir hızla hareket ettirir ve sonra eski yerine getirirsek, zaman genişlemesi yüzünden tünelin iki ucu arasında bir zaman farkı oluşur. Bu tünelden geçen biri, tünele girdiği andan daha önceki bir zamana çıkabilir! Yani geçmişe yolculuk teorik olarak mümkün hale gelir. Ancak pratikte bir solucan deliğini açık tutmak için 'negatif enerji' denilen ve uzay-zamanı tersine büken çok garip bir enerji türüne ihtiyaç vardır.",
                    "**Zaman Paradoksları (Büyükbaba Paradoksu)**\n\nGeçmişe yolculuk yapıldığında çok büyük mantık hataları, yani paradokslar ortaya çıkar. Bunlardan en meşhuru **Büyükbaba Paradoksu**dur. Geçmişe gidip, henüz babanız doğmadan önce büyükbabanızı kazayla vurduğunuzu hayal edin. Bu durumda babanız doğamaz. Babanız doğamazsa siz de doğamazsınız. Eğer siz doğmadıysanız, geçmişe gidip büyükbabanızı vuran kişi kimdir? Bu paradoksu çözmek için fizikçiler iki teori üretirler:\n- **Çoklu Evrenler Teorisi:** Geçmişe gittiğinizde aslında kendi evreninize değil, paralel başka bir evrene gidersiniz. Orada büyükbabanızı vursanız bile kendi evreniniz bundan etkilenmez.\n- **Tutarlı Geçmişler Teorisi:** Geçmişe gitseniz bile geçmişi değiştiremezsiniz. Fizik kuralları büyükbabanızı vurmanızı bir şekilde engeller (örneğin silah tutukluk yapar).",
                    "**Kronoloji Koruma Varsayımı**\n\nHawking, geçmişe yolculuk fikirlerine karşı oldukça şüpheci yaklaşmıştır. Hawking, **Kronoloji Koruma Varsayımı** adını verdiği bir teori ortaya attı. Buna göre doğa (fizik yasaları), zaman yolculuğuna ve paradoksların oluşmasına asla izin vermez. Solucan delikleri oluşsa bile, kuantum etkileri yüzünden tünelden geçmeye çalıştığımız anda tünel aşırı yüklenip havaya uçar ve kapanır. Hawking bu fikrini eğlenceli bir kanıtla desteklemiştir: 'Eğer geçmişe yolculuk mümkün olsaydı, etrafımız gelecekten gelen turistlerle dolu olurdu! Nerede bu turistler?' Hatta Hawking, gelecekten gelen yolcular için özel bir parti düzenlemiş ama davetiyeyi parti bittikten sonra yayınlamıştır. Partiye kimse gelmemiştir!\n\n*\"Eğer zaman yolculuğu mümkün olsaydı, gelecekten gelen turistlerin istilasına uğramış olmalıydık. Ama ortalıkta kimse yok.\"* — Stephen Hawking, Zamanın Kısa Tarihi"
                ]
            },
            {
                "id": "chapter11",
                "title": "BÖLÜM 11: Fiziğin Birleştirilmesi (Büyük Rüya: Her Şeyin Teorisi)",
                "paragraphs": [
                    "**İki Büyük Kuramın Savaşı**\n\nModern fizik şu anda iki ayrı hükümdar tarafından yönetilmektedir. Bir yanda devasa yıldızları, galaksileri ve kütleçekimini mükemmel açıklayan Einstein'ın **Genel Görelilik** kuramı vardır. Diğer yanda ise atomları, elektronları ve mikro dünyayı harika açıklayan **Kuantum Mekaniği** bulunur. Sorun şu ki, bu iki büyük teori bir araya geldiğinde birbirleriyle adeta savaşırlar ve matematiksel olarak anlamsız, sonsuz sonuçlar verirler. Evrenin tek bir anayasası olmalıdır; bu yüzden fizikçiler ikisini birleştirmek isterler.",
                    "**Kuantum Kütleçekimi Arayışı**\n\nİki kuramı birleştirmek için geliştirilecek yeni teoriye \"Kuantum Kütleçekimi\" veya her şeyi açıklayacağı için **Her Şeyin Teorisi** (Theory of Everything) denir. Bu teoriyi bulduğumuzda, Büyük Patlama'nın ilk saniyesinde kütleçekimin ve kuantum parçacıklarının nasıl davrandığını tam olarak anlayabileceğiz. Çünkü Büyük Patlama anında kütle devasa boyuttaydı (genel görelilik alanı) ama boyut sıfıra yakındı (kuantum alanı).",
                    "**Sicim Kuramı ve Ek Boyutlar (M-Teorisi)**\n\nBu birleşme için günümüzdeki en güçlü adaylardan biri **Sicim Kuramı**dır. Bu kurama göre, evrendeki temel parçacıklar (elektronlar, kuarklar) aslında minik noktacıklar değil, çılgınca titreşen minik sicimler (teller) gibidir. Tellerin farklı notalarda titreşmesi gibi, bu sicimler de farklı titreşerek farklı parçacıkları oluştururlar. Ancak bu teorinin çalışması için evrenin bildiğimiz 4 boyutlu (3 uzay + 1 zaman) yapısı yetmez; evrenin 10 hatta 11 boyutlu olması gerekir! Kalan boyutlar bizim göremeyeceğimiz kadar minik şekilde kıvrılmıştır."
                ]
            },
            {
                "id": "chapter12",
                "title": "BÖLÜM 12: Sonuç (İnsanlığın En Büyük Arayışı ve Felsefe)",
                "paragraphs": [
                    "**Felsefeden Bilime Yolculuk**\n\nEski zamanlarda evrenin neden var olduğunu, nereden geldiğimizi felsefe ve dinler sorgulardı. Filozoflar hayatın anlamını ararlardı. Ancak modern çağda bilim o kadar karmaşık ve matematiksel hale geldi ki, filozoflar denklemleri takip edemez oldular ve sorgulama fizikçilere kaldı. Fakat fizikçiler de genellikle 'nasıl' sorusuna odaklanırlar (evren nasıl çalışır?), 'neden' sorusunu (evren neden var?) arka plana atarlar.",
                    "**Tanrı'nın Aklını Okumak**\n\nHawking, eğer bir gün Her Şeyin Teorisi'ni keşfedebilirsek, bunu sadece birkaç dahi bilim insanının değil, tüm insanlığın anlayabileceği sadelikte tartışabileceğimizi söyler. İşte o gün geldiğinde, insanlık olarak evrenin neden var olduğunu tam olarak anlayacağız. Hawking'in kitabını bitirdiği o ünlü ve şiirsel cümleyle söylersek: *\"İşte o zaman Tanrı'nın aklını okuyabilirdik.\"*"
                ]
            },
            {
                "id": "chapter13",
                "title": "BÖLÜM 13: Bilim Dünyasını Değiştiren Üç Dev Portre",
                "paragraphs": [
                    "**Albert Einstein: Göreliliğin ve Barışın Babası**\n\n20. yüzyılın en büyük dehası olan Einstein, uzay ve zaman algımızı Genel ve Özel Görelilik kuramlarıyla kökten değiştirdi. Kütleçekimin uzay-zamanın bükülmesi olduğunu gösterdi. Hayatı boyunca nükleer silahlara karşı çıkmış ve dünya barışını savunmuştur. Onun E=mc² formülü modern nükleer çağın kapısını açmıştır.",
                    "**Galileo Galilei: Modern Bilimin Cesur Kurucusu**\n\nGalileo, kendi geliştirdiği teleskopla gökyüzünü gözlemleyen ve modern bilimsel yöntemi kuran İtalyan gökbilimcidir. Jüpiter'in uydularını keşfederek Dünya'nın evrenin merkezinde olmadığını kanıtladı. Kilisenin engizisyon mahkemesi tarafından yargılandı ve ömür boyu ev hapsine mahkum edildi, ancak bilimin gerçeğini savunmaktan asla vazgeçmedi.",
                    "**Isaac Newton: Kütleçekimin Yalnız Dehası**\n\nNewton, elmanın düşüşünden ilham alarak kütleçekim yasasını formüle döken ve modern mekaniğin temellerini atan İngiliz bilim insanıdır. Aynı zamanda diferansiyel matematiği (kalkülüs) keşfetmiştir. Yıldızların ve gezegenlerin hareketini tek bir çekim yasasıyla açıklayarak bilim dünyasında devrim yapmıştır."
                ]
            }
        ]
    }
    
    with open("data/summaries/1.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=4, ensure_ascii=False)
        
    print("Successfully wrote Hawking summary to data/summaries/1.json!")

if __name__ == "__main__":
    create_hawking_summary()
